Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-12, with the labels that each got.

#906 ES: Minis Updates
  UI/ui_item.csv
Labels: size/XS

#907 Fixes and stuff
  Dialogue/Mid-Mission/heatup.csv
  Quests/Phantom God/quest_00050660.csv
  Quests/Phantom God/quest_00050690.csv
  Quests/Phantom God/quest_00170200.csv
  Quests/Seasonal/Xmas 2019/quest_00051110.csv
  Quests/Seasonal/Xmas 2019/quest_00170700.csv
Labels: size/M

#908 English translation for Ep6 Ch 3-2 + substories
  Files/st_063070.csv
  Files/st_063075.csv
  Files/st_063080.csv
  Files/st_063090.csv
  Files/st_063097.csv
  Files/st_063100.csv
  Files/st_063107.csv
  Files/st_063110.csv
  Files/st_063115.csv
  Files/st_063120.csv
  Files/un_061050.csv
  Files/un_061120.csv
  Files/un_062020.csv
  Files/un_062030.csv
  Files/un_062060.csv
  Files/un_063010.csv
  Files/un_063100.csv
  Files/un_063150.csv
  Files/un_065020.csv
  Story/Episode 6/st_063070.csv
  Story/Episode 6/st_063075.csv
  Story/Episode 6/st_063080.csv
  Story/Episode 6/st_063090.csv
  Story/Episode 6/st_063097.csv
  Story/Episode 6/st_063100.csv
  Story/Episode 6/st_063107.csv
  Story/Episode 6/st_063110.csv
  Story/Episode 6/st_063115.csv
  Story/Episode 6/st_063120.csv
  Story/Episode 6/un_061050.csv
  Story/Episode 6/un_061120.csv
  Story/Episode 6/un_062020.csv
  Story/Episode 6/un_062030.csv
  Story/Episode 6/un_062060.csv
  Story/Episode 6/un_063010.csv
  Story/Episode 6/un_063100.csv
  Story/Episode 6/un_063150.csv
  Story/Episode 6/un_065020.csv
Labels: size/XL

#909 English translation of un_063190.csv
  Files/un_063190.csv
  Story/Episode 6/un_063190.csv
Labels: size/S

#913 ES:ep6 cap3 full
  Files/un_062020.csv
  Files/un_062030.csv
  Files/un_062080.csv
  Files/un_062090.csv
  Story/Episode 6/Kyokuya/un_061050.csv
  Story/Episode 6/Kyokuya/un_062020.csv
  Story/Episode 6/Kyokuya/un_062030.csv
  Story/Episode 6/Kyokuya/un_062080.csv
  Story/Episode 6/Kyokuya/un_062090.csv
  Story/Episode 6/Ludmilla/un_062060.csv
  Story/Episode 6/cap3/un_062070.csv
  Story/Episode 6/cap3/un_063150.csv
  Story/Episode 6/cap3/un_065020.csv
Labels: size/L

#917 ES: ui mainmode ET
  Misc/actor_name.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/M

#920 ES: Lucotte
  Files/un_063020.csv
  Story/Episode 6/Lucotte/un_063020.csv
Labels: size/M

#923 Es
  Dialogue/np_npc_00cmn.csv
  Misc/actor_name.csv
  UI/ui_mainmode.csv
Labels: size/S

#921 EN: super sm0l fixes
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/XS

#924 EN: A few small things
  Files/co_061050.csv
  Files/co_061051.csv
  Files/co_061052.csv
  Files/co_061053.csv
  Files/co_061054.csv
  Files/co_061055.csv
  Files/co_061056.csv
  Misc/actor_name.csv
  Quests/Training Quests/AIS Vega/co_061050.csv
  Quests/Training Quests/AIS Vega/co_061051.csv
  Quests/Training Quests/AIS Vega/co_061052.csv
  Quests/Training Quests/AIS Vega/co_061053.csv
  Quests/Training Quests/AIS Vega/co_061054.csv
  Quests/Training Quests/AIS Vega/co_061055.csv
  Quests/Training Quests/AIS Vega/co_061056.csv
  UI/item_element_expl.csv
  UI/ui_item.csv
Labels: size/L

#925 English translation of un_063020
  Files/un_063020.csv
  Story/Episode 6/un_063020.csv
Labels: size/M

#927 EN: Partner chat
  Dialogue/_Partner chat/apc_chat_1.csv
  UI/apc_name.csv
  UI/item_element_expl.csv
Labels: size/XXL

#928 EN: Shorten S5s
  UI/item_element_expl.csv
Labels: size/S

#929 EN: message about feeding re-egged pets to things
  UI/ui_pet.csv
Labels: size/XS
