Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-05, with the labels that each got.

#801 es: Varios Cambios
  Misc/actor_name.csv
  Orders/Azanami/co02038700.csv
  UI/quest_counter.csv
  UI/ui_guild.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_symbol.csv
Labels: size/M

#804 Es: ya me dio peresa seguir traduciendo el resto :v
  Dialogue/Mid-Mission/heatup.csv
  Dialogue/Xiera/tr_120020.csv
  Orders/Kyokuya/co06010002.csv
  Orders/Kyokuya/co06010003.csv
  UI/ui_group_chat.csv
  UI/ui_missionboard.csv
  UI/ui_tutorial.csv
Labels: size/M

#805 Update ui_craft.csv
  UI/ui_craft.csv
Labels: size/XS

#807 es: mini cambios
  UI/common.csv
  UI/ui_selectmenu_text.csv
Labels: size/M

#810 ES: UI item_element_expl
  UI/item_element_expl.csv
Labels: size/L

#811 ES: Ui item
  UI/item_element_expl.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/XL

#813 Adding some Event Chronicle translations!
  Misc/actor_name.csv
  UI/ui_eventchronicle.csv
Labels: size/S

#812 WIP: UI fixes
  UI/ui_guild.csv
  UI/ui_mainmode.csv
  UI/ui_myroom.csv
Labels: size/S

#816 ES: Ui correccion
  UI/ui_mainmode.csv
Labels: size/XS

#817 EN: Various small things
  Misc/actor_name.csv
  Quests/Descriptions/quest_00080200.csv
  Quests/Limited Quests/quest_00080140.csv
  UI/common.csv
  UI/quest_common.csv
  UI/quest_counter.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  _aspell/PSO2.en_Names.dict
Labels: size/M

#815 EN: Misc translations
  Dialogue/Mid-Mission/heatup.csv
  Dialogue/Mid-Mission/ii_boss_ahl_nyau.csv
  Dialogue/Mid-Mission/ii_boss_ahl_remaining_buff.csv
  Files/ii_boss_ahl_remaining_buff.csv
  UI/quest_counter.csv
  UI/ui_eventchronicle.csv
Labels: size/M

#820 EN: Fix "have have"
  UI/ui_item.csv
Labels: size/XS

#822 Fixing string escapes/punctuation + misc order translation
  Dialogue/Afin/np_012100.csv
  Dialogue/Mid-Mission/ii_2ev_boss.csv
  Dialogue/Mid-Mission/ii_waker_bit_ahl_2ev_boss.csv
  Dialogue/Mid-Mission/ii_waker_bit_ahl_ev_boss.csv
  Dialogue/Xiera/co_040039.csv
  Dialogue/Xiera/co_040109.csv
  Dialogue/_Partner chat/apc_chat_3.csv
  Dialogue/np_npc_160.csv
  Misc/Concert/bd_010010.csv
  Misc/actor_name.csv
  Orders/_ARKS Missions/ac06040109.csv
  Quests/Story EP1-3 names/quest_00701180.csv
  Quests/Story EP1-3 names/quest_00701610.csv
  Quests/Story EP1-3 names/quest_00702860.csv
  Story/Episode 4/st_047105.csv
  Story/Episode 5/st_053090.csv
  Story/Matterboard/mb00000012.csv
  Tutorial/Quest/co_012006.csv
  UI/quest_common.csv
  UI/ui_eventchronicle.csv
  UI/ui_supportpartoner.csv
Labels: size/M

#823 EN: small mid-mission armada translations
  Files/co_063001.csv
  Files/co_063011.csv
  Files/co_063021.csv
  Files/co_063031.csv
  Files/co_063041.csv
  Quests/Armada/co_063001.csv
  Quests/Armada/co_063011.csv
  Quests/Armada/co_063021.csv
  Quests/Armada/co_063031.csv
  Quests/Armada/co_063041.csv
Labels: size/M

#825 EN: More of the update
  Files/quest_00020220.csv
  Files/quest_00020230.csv
  Files/quest_00020240.csv
  Quests/Armada/quest_00051000.csv
  Quests/Armada/quest_00051010.csv
  Quests/Armada/quest_00051020.csv
  Quests/Armada/quest_00051030.csv
  Quests/Armada/quest_00051040.csv
  Quests/Armada/quest_00051060.csv
  Quests/Armada/quest_00170600.csv
  Quests/Armada/quest_00170620.csv
  Quests/Ultra Exploration/quest_00020180.csv
  Quests/Ultra Exploration/quest_00020200.csv
  Quests/Ultra Exploration/quest_00020210.csv
  Quests/Ultra Exploration/quest_00020220.csv
  Quests/Ultra Exploration/quest_00020230.csv
  Quests/Ultra Exploration/quest_00020240.csv
  UI/ui_craft_name.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_missionboard.csv
  UI/ui_quest.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/L

#826 EN: Update stuff
  Dialogue/Astarte/co_060502.csv
  Dialogue/Mid-Mission/ii_j_s_ssn_apc_revival.csv
  Files/cm_063000.csv
  Files/cm_063001.csv
  Files/cm_063002.csv
  Files/cm_063003.csv
  Files/cm_063011.csv
  Files/cm_063012.csv
  Files/cm_063013.csv
  Files/cm_063020.csv
  Files/cm_063021.csv
  Files/cm_063022.csv
  Files/cm_063023.csv
  Files/cm_063030.csv
  Files/cm_063031.csv
  Files/cm_063032.csv
  Files/cm_063033.csv
  Files/cm_063034.csv
  Files/cm_063035.csv
  Files/cm_063036.csv
  Files/cm_063040.csv
  Files/cm_063041.csv
  Files/cm_063042.csv
  Files/cm_063043.csv
  Files/cm_063044.csv
  Files/cm_063045.csv
  Files/cm_063046.csv
  Files/cm_063047.csv
  Quests/Armada/cm_063000.csv
  Quests/Armada/cm_063001.csv
  Quests/Armada/cm_063002.csv
  Quests/Armada/cm_063003.csv
  Quests/Armada/cm_063011.csv
  Quests/Armada/cm_063012.csv
  Quests/Armada/cm_063013.csv
  Quests/Armada/cm_063020.csv
  Quests/Armada/cm_063021.csv
  Quests/Armada/cm_063022.csv
  Quests/Armada/cm_063023.csv
  Quests/Armada/cm_063030.csv
  Quests/Armada/cm_063031.csv
  Quests/Armada/cm_063032.csv
  Quests/Armada/cm_063033.csv
  Quests/Armada/cm_063034.csv
  Quests/Armada/cm_063035.csv
  Quests/Armada/cm_063036.csv
  Quests/Armada/cm_063040.csv
  Quests/Armada/cm_063041.csv
  Quests/Armada/cm_063042.csv
  Quests/Armada/cm_063043.csv
  Quests/Armada/cm_063044.csv
  Quests/Armada/cm_063045.csv
  Quests/Armada/cm_063046.csv
  Quests/Armada/cm_063047.csv
  Quests/Armada/co_063011.csv
  Quests/Training Quests/AIS Vega/co_063051.csv
  Quests/Training Quests/AIS Vega/quest_00080390.csv
  Quests/Training Quests/AIS Vega/quest_00161300.csv
  _aspell/PSO2.en_Enemies_EP6.dict
Labels: size/L

#828 Fixing encoding ’->' SJIS->UTF8 and double punc(.。etc)
  Dialogue/Afin/od_010200401.csv
  Dialogue/Mid-Mission/cm_042430.csv
  Dialogue/Mid-Mission/cm_042807_02.csv
  Dialogue/Mid-Mission/cm_042819_02.csv
  Misc/Concert/bd_010010.csv
  Misc/Concert/bd_010030.csv
  Misc/Concert/bd_010040.csv
  Misc/Concert/ls_010060.csv
  Orders/_Bingo/bo00001637.csv
  Orders/_Bingo/bo00001808.csv
  Quests/Story EP5 names/Chapter 3/quest_00300710.csv
  Story/Episode 1/st_010375_om.csv
  Story/Episode 1/st_012010.csv
  Story/Episode 2/co_022505.csv
  Story/Episode 2/un_025120.csv
  Story/Episode 2/un_025150.csv
  Story/Episode 3/cm_032840.csv
  Story/Episode 4/st_043120.csv
  Story/Episode 4/st_044075.csv
  Story/Episode 4/st_044080.csv
  Story/Episode 4/st_044090.csv
  Story/Episode 4/st_044100.csv
  Story/Episode 4/st_044110.csv
  Translated/Dialogue/od_000018991.csv
  Translated/Dialogue/od_010403073.csv
  Translated/Dialogue/od_020302002.csv
  Translated/Dialogue/od_020302022.csv
  Translated/Dialogue/od_020318041.csv
  Translated/Story/Episode 1/co_012713.csv
  Translated/Story/Episode 1/co_012716.csv
  Translated/Story/Episode 2/co_022417.csv
  Tutorial/Window Help/wh_charamake.csv
  UI/ui_charamake_parts.csv
  UI/ui_mainmode.csv
Labels: size/L

#827 es: Probando Traduccio de nuevas cosas
  UI/ui_item.csv
Labels: size/XS

#829 EN: Story and other things
  Misc/actor_name.csv
  Quests/Armada/cm_063032.csv
  Quests/Armada/cm_063033.csv
  Story/Episode 1/un_010540.csv
  Story/Episode 1/un_011250.csv
  Story/Episode 2/ra_020010.csv
  Story/Episode 2/ra_020010_om.csv
  Story/Episode 2/st_020660.csv
  Story/Episode 2/st_020665.csv
  UI/item_element_expl.csv
  _aspell/PSO2.en_Enemies_EP6.dict
Labels: size/M

#830 EN: Couple of Armada things
  Dialogue/Mid-Mission/ii_areaboss_ab.csv
  Files/ii_areaboss_ab.csv
  Orders/_ARKS Missions/3 Event/ac06030211.csv
  Orders/_ARKS Missions/3 Event/ac06030221.csv
  Orders/_ARKS Missions/3 Event/ac06030231.csv
  Orders/_ARKS Missions/3 Event/ac06030232.csv
  Orders/_ARKS Missions/3 Event/ac06030233.csv
  Orders/_ARKS Missions/3 Event/ac06030234.csv
  Tutorial/Tutorial List/wh_tl_co_060014.csv
  Tutorial/Window/co_060014.csv
Labels: size/M
