Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-10, with the labels that each got.

#880 EN: Translated some more greetings
  Dialogue/Mid-Mission/ii_session_apc_5445.csv
  Files/ii_session_apc_5445.csv
  Misc/My Room/sp_greeting.csv
Labels: size/M

#885 English translation of Ep6 Ch2 story/substories
  Files/st_062010.csv
  Files/st_062040.csv
  Files/st_062045.csv
  Files/st_062050.csv
  Files/st_062060.csv
  Files/st_062070.csv
  Files/st_062080.csv
  Files/st_062085.csv
  Files/st_062087.csv
  Files/st_062090.csv
  Files/st_062100.csv
  Files/un_061140.csv
  Files/un_062120.csv
  Story/Episode 6/st_062010.csv
  Story/Episode 6/st_062040.csv
  Story/Episode 6/st_062045.csv
  Story/Episode 6/st_062050.csv
  Story/Episode 6/st_062060.csv
  Story/Episode 6/st_062070.csv
  Story/Episode 6/st_062080.csv
  Story/Episode 6/st_062085.csv
  Story/Episode 6/st_062087.csv
  Story/Episode 6/st_062090.csv
  Story/Episode 6/st_062100.csv
  Story/Episode 6/un_061140.csv
  Story/Episode 6/un_062120.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/XL

#887 Forde Luz to Fordruss
  Misc/actor_name.csv
  _aspell/PSO2.en_Enemies_EP6.dict
Labels: size/XS

#888 Es: config
  Files/st_062010.csv
  Files/st_062040.csv
  Files/st_062045.csv
  Files/st_062050.csv
  Files/st_062060.csv
  Files/st_062070.csv
  Files/st_062080.csv
  Files/st_062085.csv
  Files/st_062087.csv
  Files/st_062090.csv
  Files/st_062100.csv
  Files/st_063010.csv
  Files/st_063020.csv
  Files/st_063030.csv
  Files/st_063035.csv
  Files/st_063050.csv
  Files/st_063055.csv
  Files/un_061140.csv
  Files/un_062010.csv
  Files/un_062120.csv
  Story/Episode 6/st_062010.csv
  Story/Episode 6/st_062040.csv
  Story/Episode 6/st_062045.csv
  Story/Episode 6/st_062050.csv
  Story/Episode 6/st_062060.csv
  Story/Episode 6/st_062070.csv
  Story/Episode 6/st_062080.csv
  Story/Episode 6/st_062085.csv
  Story/Episode 6/st_062087.csv
  Story/Episode 6/st_062090.csv
  Story/Episode 6/st_062100.csv
  Story/Episode 6/st_063010.csv
  Story/Episode 6/st_063020.csv
  Story/Episode 6/st_063030.csv
  Story/Episode 6/st_063035.csv
  Story/Episode 6/st_063050.csv
  Story/Episode 6/st_063055.csv
  Story/Episode 6/st_063060.csv
  Story/Episode 6/un_061140.csv
  Story/Episode 6/un_062010.csv
  Story/Episode 6/un_062120.csv
  UI/config.csv
Labels: size/L

#892 ES No me acuerdo como actualizar
  UI/quest_counter.csv
  UI/ui_item.csv
Labels: size/XS
