Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-08, with the labels that each got.

#861 ES: EP6 al dia
  Files/pr_062010.csv
  Misc/actor_name.csv
  Story/Episode 6/pr_062010.csv
  Story/Episode 6/un_061030.csv
  Story/Episode 6/un_061080.csv
  Story/Episode 6/un_061090.csv
  Story/Episode 6/un_061130.csv
  Story/Episode 6/un_061160.csv
  Story/Episode 6/un_061170.csv
  Story/Episode 6/un_061200.csv
  Story/Episode 6/un_065010.csv
  UI/ui_tips.csv
Labels: size/L

#859 EN: Some tutorial popups and story fixes
  Dialogue/_Partner Cards/co_050061.csv
  Dialogue/_Partner chat/apc_chat_1.csv
  Files/co_050005.csv
  Files/co_050006.csv
  Files/co_050007.csv
  Files/co_050010.csv
  Files/co_050061.csv
  Quests/Story EP1-3 names/quest_00700130.csv
  Quests/Story EP1-3 names/quest_00700250.csv
  Quests/Story EP1-3 names/quest_00700390.csv
  Story/Episode 1/ra_010080.csv
  Story/Episode 1/ra_010280.csv
  Story/Episode 1/st_010370.csv
  Story/Episode 1/st_010375.csv
  Story/Episode 1/st_010375_om.csv
  Story/Episode 1/un_010550.csv
  Story/Episode 1/un_011260.csv
  Story/Episode 6/un_061030.csv
  Story/Episode 6/un_061080.csv
  Tutorial/Client Order notices/co_050010.csv
  Tutorial/Dialogue/co_050006.csv
  Tutorial/Dialogue/co_050007.csv
  Tutorial/Window/co_050005.csv
  Tutorial/Window/co_058003.csv
  UI/ui_eventchronicle.csv
Labels: size/S

#864 EN: Story stuff
  Misc/actor_name.csv
  Story/Episode 1/ra_010110.csv
  Story/Episode 1/ra_010240.csv
  Story/Episode 1/ra_010310.csv
  Story/Episode 1/ra_010470.csv
  Story/Episode 1/ra_010510.csv
  Story/Episode 1/ra_010600.csv
  Story/Episode 3/ra_037010.csv
  Story/Episode 3/ra_037010_om.csv
  UI/ui_eventchronicle.csv
Labels: size/M

#867 EN: Update stuff
  Dialogue/Mid-Mission/ii_defense_from_mge.csv
  Dialogue/_Partner chat/apc_chat_1.csv
  Files/ac06030511.csv
  Files/ac06030521.csv
  Files/ac06030531.csv
  Files/ac06030541.csv
  Files/ac06030542.csv
  Files/ac06030543.csv
  Files/ac06030544.csv
  Files/ac06030551.csv
  Files/ac06030552.csv
  Files/ac06030553.csv
  Files/ac06030611.csv
  Files/ac06030621.csv
  Files/ac06041019.csv
  Files/ac06041601.csv
  Files/ac06041602.csv
  Files/co_060017.csv
  Files/wh_te_pg_004007.csv
  Files/wh_te_pg_004008.csv
  Files/wh_tl_co_060017.csv
  Orders/_ARKS Missions/3 Event/ac06030511.csv
  Orders/_ARKS Missions/3 Event/ac06030521.csv
  Orders/_ARKS Missions/3 Event/ac06030531.csv
  Orders/_ARKS Missions/3 Event/ac06030541.csv
  Orders/_ARKS Missions/3 Event/ac06030542.csv
  Orders/_ARKS Missions/3 Event/ac06030543.csv
  Orders/_ARKS Missions/3 Event/ac06030544.csv
  Orders/_ARKS Missions/3 Event/ac06030551.csv
  Orders/_ARKS Missions/3 Event/ac06030552.csv
  Orders/_ARKS Missions/3 Event/ac06030553.csv
  Orders/_ARKS Missions/3 Event/ac06030611.csv
  Orders/_ARKS Missions/3 Event/ac06030621.csv
  Orders/_ARKS Missions/ac06041019.csv
  Orders/_ARKS Missions/ac06041601.csv
  Orders/_ARKS Missions/ac06041602.csv
  Tutorial/ARKS Handbook/wh_te_pg_004007.csv
  Tutorial/ARKS Handbook/wh_te_pg_004008.csv
  Tutorial/Tutorial List/wh_tl_co_060017.csv
  Tutorial/Window/co_060017.csv
  UI/quest_counter.csv
  UI/ui_craft.csv
  UI/ui_craft_name.csv
  UI/ui_item.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
  UI/ui_tutorial.csv
Labels: size/L

#868 EN: More update stuff
  Dialogue/Alis/np_011250.csv
  Files/co_060018.csv
  Files/mp_000556.csv
  Files/mp_000557.csv
  Quests/Limited Quests/quest_00080100.csv
  Tutorial/Message Pack/mp_000556.csv
  Tutorial/Message Pack/mp_000557.csv
  Tutorial/Window/co_060018.csv
  UI/quest_common.csv
  UI/ui_mainmode.csv
Labels: size/M

#866 EN: we need to spellcheck
  Quests/Buster Quests/co_052104_01.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/XS

#871 EN: Beach trigger and XQ rewards
  Files/quest_00170640.csv
  Quests/Extreme Quests/co_017003.csv
  Quests/Extreme Quests/co_017006.csv
  Quests/Seasonal/Beach 2019/quest_00170640.csv
Labels: size/M
