Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-04, with the labels that each got.

#766 WIP EN: Translations/fixes/grammar etc.
  Dialogue/Mid-Mission/cm_052410_05.csv
  Files/cm_052410_05.csv
  Quests/Omega Apprentice/pr_056010.csv
  Story/Episode 5/cm_052406_05.csv
  Story/Episode 5/pr_054020.csv
  Story/Episode 5/st_056140.csv
  Story/Episode 5/st_058025.csv
  Story/Episode 5/st_058110.csv
  Story/Episode 5/st_058115.csv
  Story/Episode 5/st_058117.csv
  Story/Episode 5/st_058120.csv
  Story/Episode 5/st_058125.csv
  Story/Episode 5/st_058130.csv
  Story/Episode 5/st_058140.csv
  Story/Episode 5/st_058145.csv
  Story/Episode 5/st_058150.csv
  Story/Episode 5/st_058155.csv
  Story/Episode 5/st_058160.csv
  Story/Episode 5/st_058165.csv
  Story/Episode 5/st_058180.csv
  Story/Episode 5/st_058185.csv
  Story/Episode 5/st_058187.csv
  Story/Episode 5/un_050070.csv
  Story/Episode 5/un_050090.csv
  Story/Episode 5/un_055020.csv
  Story/Episode 5/un_055200.csv
  Story/Episode 5/un_055210.csv
  Story/Episode 5/un_056030.csv
  Story/Episode 5/un_057010.csv
  Story/Episode 5/un_057040.csv
  Story/Episode 5/un_057050.csv
  Story/Episode 5/un_057060.csv
  Story/Episode 5/un_057070.csv
  Story/Episode 5/un_059050.csv
  Story/Episode 5/un_059070.csv
  Story/Episode 5/un_059080.csv
Labels: size/S

#767 English translation - cleanup for Ep5 EQ scenes
  Files/pr_057010.csv
  Files/pr_059010.csv
  Files/pr_059020.csv
  Quests/Buster Quests/pr_057010.csv
  Quests/Omega Persona/pr_059010.csv
  Quests/Omega Persona/pr_059020.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/M

#770 EN: Minor scratch UI fixes, potential and personality updates, one CO description
  Orders/Afin/co01020023.csv
  UI/ui_gacha.csv
  UI/ui_item.csv
  _aspell/PSO2.en_Weapons_Potentials.dict
Labels: size/XL

#777 ES: CO Kyokuya
  Files/co06033203.csv
  Files/co06033204.csv
  Files/co06033205.csv
  Files/co06033206.csv
  Files/co06033211.csv
  Orders/Kyokuya/co06010001.csv
  Orders/Kyokuya/co06010002.csv
  Orders/Kyokuya/co06010003.csv
  Orders/Kyokuya/co06010004.csv
  Orders/Kyokuya/co06010005.csv
  Orders/Kyokuya/co06010006.csv
  Orders/Kyokuya/co06010007.csv
  Orders/Kyokuya/co06033201.csv
  Orders/Kyokuya/co06033202.csv
  Orders/Kyokuya/co06033203.csv
  Orders/Kyokuya/co06033204.csv
  Orders/Kyokuya/co06033205.csv
  Orders/Kyokuya/co06033206.csv
  Orders/Kyokuya/co06033211.csv
Labels: size/M

#778 ES: Ui Chat Group
  UI/ui_group_chat.csv
Labels: size/L

#782 Es PH
  Orders/Kyokuya/co06010001.csv
  Orders/Kyokuya/co06010002.csv
  Orders/Kyokuya/co06010003.csv
  Orders/Kyokuya/co06010004.csv
  Orders/Kyokuya/co06010005.csv
  Orders/Kyokuya/co06010006.csv
  Orders/Kyokuya/co06033201.csv
  UI/ui_mainmode.csv
  UI/ui_missionboard.csv
  UI/ui_pet.csv
Labels: size/L

#783 ES: Ui PH skill tree
  UI/ui_mainmode.csv
Labels: size/XS

#788 'The End' to 'Demise'
  Quests/Story EP6 names/Chapter 1/quest_00301410.csv
  Quests/Story EP6 names/Chapter 1/quest_00301500.csv
Labels: size/XS

#787 EN: English translation of Ep6 Ch0~Ch1(+substories)
  Files/st_061010.csv
  Files/st_061015.csv
  Files/st_061020.csv
  Files/st_061030.csv
  Files/st_061035.csv
  Files/st_061040.csv
  Files/st_061050.csv
  Files/st_061070.csv
  Files/st_061080.csv
  Files/st_061090.csv
  Files/st_061100.csv
  Files/st_061110.csv
  Files/st_061120.csv
  Files/st_061130.csv
  Files/st_061135.csv
  Files/st_061136.csv
  Files/st_061137.csv
  Files/st_061140.csv
  Files/un_061020.csv
  Files/un_061040.csv
  Story/Episode 6/st_061010.csv
  Story/Episode 6/st_061015.csv
  Story/Episode 6/st_061020.csv
  Story/Episode 6/st_061030.csv
  Story/Episode 6/st_061035.csv
  Story/Episode 6/st_061040.csv
  Story/Episode 6/st_061050.csv
  Story/Episode 6/st_061070.csv
  Story/Episode 6/st_061080.csv
  Story/Episode 6/st_061090.csv
  Story/Episode 6/st_061100.csv
  Story/Episode 6/st_061110.csv
  Story/Episode 6/st_061120.csv
  Story/Episode 6/st_061130.csv
  Story/Episode 6/st_061135.csv
  Story/Episode 6/st_061136.csv
  Story/Episode 6/st_061137.csv
  Story/Episode 6/st_061140.csv
  Story/Episode 6/un_061020.csv
  Story/Episode 6/un_061040.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/XL

#789 WIP: EPISODE 6 Story stuff
  Dialogue/Brigitta/cm_060400.csv
  Dialogue/Brigitta/cm_060402.csv
  Dialogue/Mid-Mission/cm_060200.csv
  Dialogue/Mid-Mission/cm_060201.csv
  Dialogue/Mid-Mission/cm_060202.csv
  Dialogue/Mid-Mission/cm_060203.csv
  Dialogue/Mid-Mission/cm_060205.csv
  Dialogue/Mid-Mission/cm_060206.csv
  Dialogue/Mid-Mission/cm_060207.csv
  Dialogue/Mid-Mission/cm_060208.csv
  Dialogue/Mid-Mission/cm_060211.csv
  Dialogue/Mid-Mission/cm_060212.csv
  Dialogue/Mid-Mission/cm_060213.csv
  Dialogue/Mid-Mission/cm_060214.csv
  Files/cm_060200.csv
  Files/cm_060201.csv
  Files/cm_060202.csv
  Files/cm_060203.csv
  Files/cm_060205.csv
  Files/cm_060206.csv
  Files/cm_060207.csv
  Files/cm_060208.csv
  Files/cm_060211.csv
  Files/cm_060212.csv
  Files/cm_060213.csv
  Files/cm_060214.csv
  Story/Episode 6/st_061010.csv
  Story/Episode 6/st_061015.csv
  Story/Episode 6/st_061020.csv
  Story/Episode 6/st_061030.csv
  Story/Episode 6/st_061035.csv
  Story/Episode 6/st_061050.csv
  Story/Episode 6/st_061070.csv
  Story/Episode 6/st_061080.csv
  Story/Episode 6/st_061090.csv
  Story/Episode 6/st_061100.csv
  Story/Episode 6/st_061110.csv
  Story/Episode 6/st_061120.csv
  Story/Episode 6/st_061130.csv
  Story/Episode 6/st_061135.csv
  Story/Episode 6/st_061136.csv
  Story/Episode 6/st_061137.csv
  Story/Episode 6/st_061140.csv
  Story/Episode 6/un_061020.csv
  Story/Episode 6/un_061040.csv
  UI/quest_common.csv
  UI/quest_counter.csv
Labels: size/XS

#786 EN: Misspell for VillainKatanaPA03#0?
  Misc/actor_name.csv
  _aspell/PSO2.en_PhotonArts.dict
Labels: size/XS

#791 ES: Cambios Menores del Daily Boost
  Misc/clientorder_name.csv
Labels: size/XS

#795 Fix wrong quest name in Arks Mission
  Orders/_ARKS Missions/ac06040413.csv
Labels: size/XS

#799 EN: Update config.csv
  UI/common.csv
  UI/config.csv
Labels: size/XS

#796 Es: Update ui_mainmode.csv
  UI/ui_mainmode.csv
Labels: size/XS

#797 ES:ep6
  Files/cm_060200.csv
  Files/cm_060201.csv
  Files/cm_060202.csv
  Files/cm_060203.csv
  Files/cm_060204.csv
  Files/cm_060205.csv
  Files/cm_060206.csv
  Files/cm_060207.csv
  Files/cm_060208.csv
  Files/cm_060209.csv
  Files/un_061020.csv
  Files/un_061040.csv
  Story/Episode 6/cm_060200.csv
  Story/Episode 6/cm_060201.csv
  Story/Episode 6/cm_060202.csv
  Story/Episode 6/cm_060203.csv
  Story/Episode 6/cm_060204.csv
  Story/Episode 6/cm_060205.csv
  Story/Episode 6/cm_060206.csv
  Story/Episode 6/cm_060207.csv
  Story/Episode 6/cm_060208.csv
  Story/Episode 6/cm_060209.csv
  Story/Episode 6/st_061020.csv
  Story/Episode 6/st_061030.csv
  Story/Episode 6/st_061035.csv
  Story/Episode 6/st_061040.csv
  Story/Episode 6/st_061050.csv
  Story/Episode 6/st_061070.csv
  Story/Episode 6/st_061080.csv
  Story/Episode 6/st_061090.csv
  Story/Episode 6/st_061100.csv
  Story/Episode 6/st_061110.csv
  Story/Episode 6/st_061120.csv
  Story/Episode 6/st_061130.csv
  Story/Episode 6/st_061135.csv
  Story/Episode 6/st_061136.csv
  Story/Episode 6/st_061137.csv
  Story/Episode 6/st_061140.csv
  Story/Episode 6/un_061020.csv
  Story/Episode 6/un_061040.csv
Labels: size/M
