Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-07, with the labels that each got.

#843 EN: Couple of LA changes
  UI/common.csv
Labels: size/XS

#844 EN: Review names of status potentials
  UI/ui_item.csv
Labels: size/M

#845 EN: Minor fixes to story stuff
  Files/un_036030.csv
  Misc/actor_name.csv
  Orders/Emilia & Vivienne/co04063604.csv
  Orders/_ARKS Missions/ac06040802.csv
  Quests/Story EP1-3 names/quest_00700310.csv
  Quests/Story EP1-3 names/quest_00700410.csv
  Quests/Story EP1-3 names/quest_00700810.csv
  Quests/Story EP1-3 names/quest_00701010.csv
  Quests/Story EP1-3 names/quest_00701030.csv
  Quests/Story EP1-3 names/quest_00701070.csv
  Quests/Story EP1-3 names/quest_00701220.csv
  Quests/Story EP1-3 names/quest_00701290.csv
  Quests/Story EP1-3 names/quest_00702850.csv
  Quests/Story EP1-3 names/quest_00703050.csv
  Story/Episode 1/ra_010120.csv
  Story/Episode 1/ra_010380.csv
  Story/Episode 1/ra_010390.csv
  Story/Episode 1/st_010230.csv
  Story/Episode 1/st_010230_om.csv
  Story/Episode 1/st_010310.csv
  Story/Episode 1/st_010310_om.csv
  Story/Episode 1/st_010395.csv
  Story/Episode 1/st_010420.csv
  Story/Episode 1/st_010430.csv
  Story/Episode 1/st_010460.csv
  Story/Episode 1/st_010460_om.csv
  Story/Episode 1/un_010390.csv
  Story/Episode 1/un_010800.csv
  Story/Episode 1/un_010880.csv
  Story/Episode 1/un_011250.csv
  Story/Episode 3/un_036030.csv
  UI/ui_eventchronicle.csv
  UI/ui_outline.csv
  _aspell/PSO2.en_Names.dict
Labels: size/L

#849 EN: More update
  Orders/_ARKS Missions/3 Event/ac06030441.csv
  Orders/_ARKS Missions/3 Event/ac06030442.csv
  Orders/_ARKS Missions/3 Event/ac06030443.csv
  Orders/_ARKS Missions/3 Event/ac06030444.csv
  Orders/_Daily/do01020515.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060220.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060221.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060223.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060225.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060227.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060228.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060229.csv
  Quests/Limited Quests/Episode 5 LQ/cm_060232.csv
  Tutorial/Window Help/wh_missionboard.csv
  Tutorial/Window Help/wh_qu_eternal_floorinfo.csv
  UI/ui_item.csv
  UI/ui_tips.csv
Labels: size/L

#852 EN: Fixing Flopped Trigger Names
  Quests/Omega Persona/quest_00170490.csv
  Quests/Omega Persona/quest_00170530.csv
Labels: size/XS

#854 EN: Remaining shipwreck helpers
  Dialogue/Xie (Anniversary)/od_060501047.csv
  Files/ii_session_apc_5057.csv
  Files/ii_session_apc_5059.csv
  Files/ii_session_apc_5083.csv
  Files/ii_session_apc_5210.csv
  Files/ii_session_apc_5437.csv
  Files/ii_session_apc_5566.csv
  Quests/Armada/ii_session_apc_5057.csv
  Quests/Armada/ii_session_apc_5059.csv
  Quests/Armada/ii_session_apc_5083.csv
  Quests/Armada/ii_session_apc_5210.csv
  Quests/Armada/ii_session_apc_5437.csv
  Quests/Armada/ii_session_apc_5566.csv
  UI/ui_petlabo.csv
Labels: size/L

#856 English translations of July Substories for Ep6
  Files/pr_062010.csv
  Files/st_062020.csv
  Files/un_061030.csv
  Files/un_061080.csv
  Files/un_061090.csv
  Files/un_061130.csv
  Files/un_061160.csv
  Files/un_061170.csv
  Files/un_061200.csv
  Files/un_065010.csv
  Quests/Armada/pr_062010.csv
  Story/Episode 6/st_062020.csv
  Story/Episode 6/un_061030.csv
  Story/Episode 6/un_061080.csv
  Story/Episode 6/un_061090.csv
  Story/Episode 6/un_061130.csv
  Story/Episode 6/un_061160.csv
  Story/Episode 6/un_061170.csv
  Story/Episode 6/un_061200.csv
  Story/Episode 6/un_065010.csv
Labels: size/L

#857 EN: Angry visbolt + ep6 substory proofreading
  Dialogue/Mid-Mission/ii_escape_boost_v.csv
  Dialogue/Mid-Mission/ii_escape_boost_v_ev_rare.csv
  Files/ii_escape_boost_v.csv
  Files/ii_escape_boost_v_ev_rare.csv
  Orders/Xie 7th Anniversary/co06050107.csv
  Orders/_Daily/do04020400.csv
  Quests/Story EP6 names/Chapter 1/quest_00301550.csv
  Story/Episode 6/st_062020.csv
  Story/Episode 6/un_061030.csv
  Story/Episode 6/un_061080.csv
  Story/Episode 6/un_061090.csv
  Story/Episode 6/un_061130.csv
  Story/Episode 6/un_061160.csv
  Story/Episode 6/un_061170.csv
  Story/Episode 6/un_061200.csv
  Story/Episode 6/un_065010.csv
Labels: size/L

#858 EN: Phantom TQ dialogue + a couple other fixes
  Misc/actor_name.csv
  Tutorial/Training Quests/12 Phantom/tr_120020.csv
  Tutorial/Training Quests/12 Phantom/tr_120030.csv
  Tutorial/Training Quests/12 Phantom/tr_120040.csv
  Tutorial/Training Quests/12 Phantom/tr_120045.csv
  Tutorial/Training Quests/12 Phantom/tr_120046.csv
  Tutorial/Training Quests/12 Phantom/tr_120047.csv
  Tutorial/Training Quests/12 Phantom/tr_120050.csv
  Tutorial/Training Quests/12 Phantom/tr_120060.csv
  Tutorial/Training Quests/12 Phantom/tr_120065.csv
  Tutorial/Training Quests/12 Phantom/tr_120070.csv
  Tutorial/Training Quests/12 Phantom/tr_120080.csv
  Tutorial/Training Quests/12 Phantom/tr_120085.csv
  Tutorial/Training Quests/12 Phantom/tr_120086.csv
  Tutorial/Training Quests/12 Phantom/tr_120090.csv
  Tutorial/Training Quests/12 Phantom/tr_120100.csv
  Tutorial/Training Quests/12 Phantom/tr_120105.csv
  Tutorial/Training Quests/12 Phantom/tr_120106.csv
  Tutorial/Training Quests/12 Phantom/tr_120110.csv
  Tutorial/Training Quests/12 Phantom/tr_120120.csv
  Tutorial/Training Quests/12 Phantom/tr_120125.csv
  Tutorial/Training Quests/12 Phantom/tr_120130.csv
  Tutorial/Training Quests/12 Phantom/tr_120140.csv
  Tutorial/Training Quests/12 Phantom/tr_120160.csv
  Tutorial/Training Quests/12 Phantom/tr_120165.csv
  Tutorial/Training Quests/12 Phantom/tr_120170.csv
  Tutorial/Training Quests/12 Phantom/tr_120180.csv
  Tutorial/Training Quests/12 Phantom/tr_120190.csv
  Tutorial/Training Quests/12 Phantom/tr_120210.csv
  Tutorial/Training Quests/12 Phantom/tr_120220.csv
  Tutorial/Training Quests/12 Phantom/tr_120230.csv
  UI/item_element_expl.csv
Labels: size/L
