Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-06, with the labels that each got.

#832 EN: Lightshade to Luminecho
  UI/ui_item.csv
  _aspell/PSO2.en_Weapons_Potentials.dict
Labels: size/M

#831 EN: Cabracan talking like a pirate
  Story/Episode 2/ra_020070.csv
  Story/Episode 2/ra_020070_om.csv
  Story/Episode 2/st_020010.csv
  Story/Episode 2/st_020010_om.csv
  Story/Episode 2/st_020040.csv
  Story/Episode 2/st_020045.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/L

#835 EN: Fixing Regular EQ Trigger Name
  Quests/Omega Persona/quest_00170490.csv
Labels: size/XS

#836 Es: mini cambios :P
  UI/config.csv
  UI/quest_counter.csv
  UI/ui_item.csv
  UI/ui_quest.csv
Labels: size/S

#838 EN: Toro & Kuro CO descriptions
  Orders/_ARKS Missions/3 Event/ac06030211.csv
  Translated/Orders/Client/Toro & Kuro/co01060000.csv
  Translated/Orders/Client/Toro & Kuro/co01060001.csv
  Translated/Orders/Client/Toro & Kuro/co01060002.csv
  Translated/Orders/Client/Toro & Kuro/co01061001.csv
  Translated/Orders/Client/Toro & Kuro/co01061002.csv
  Translated/Orders/Client/Toro & Kuro/co02060002.csv
  UI/ui_craft.csv
Labels: size/S

#839 EN: Story fixes
  Files/quest_00301520.csv
  Misc/actor_name.csv
  Quests/Story EP1-3 names/quest_00700340.csv
  Quests/Story EP1-3 names/quest_00700500.csv
  Quests/Story EP1-3 names/quest_00700560.csv
  Quests/Story EP6 names/Chapter 1/quest_00301520.csv
  Story/Episode 1/ra_012020.csv
  Story/Episode 1/ra_012020_om.csv
  Story/Episode 1/st_010555.csv
  Story/Episode 1/st_010555_om.csv
  Story/Episode 1/st_010560_om.csv
  Story/Episode 1/un_010570.csv
  Story/Episode 1/un_010860.csv
  Tutorial/Tutorial List/wh_tl_co_050063.csv
  Tutorial/Window/co_050063.csv
  UI/common.csv
  UI/ui_eventchronicle.csv
  UI/ui_title_text.csv
Labels: size/M

#837 EN: Fixed typo
  Translated/Tutorial/Dialogue/co_011224.csv
Labels: size/XS

#841 EN: Change a pot name
  UI/ui_item.csv
Labels: size/S
