Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2019-09, with the labels that each got.

#875 EN: Various
  Dialogue/Afin/np_010030.csv
  Dialogue/Afin/np_012100.csv
  Dialogue/Annette (Summer)/np_015900.csv
  Dialogue/Bluesy Requiem (Summer)/np_015910.csv
  Dialogue/Jean/od_010200257.csv
  Dialogue/Kyokuya/np_015660.csv
  Dialogue/Puso ni/od_060642067.csv
  Dialogue/Puso ni/om_060642063.csv
  Files/od_060642067.csv
  Files/om_060642063.csv
  Misc/actor_name.csv
  Orders/Kressida/co01041543.csv
  Orders/Pusoni Comic/co06064202.csv
  Orders/Pusoni Comic/co06064203.csv
  Orders/Pusoni Comic/co06064206.csv
  Orders/_Bingo/bo00001870.csv
  Orders/_Bingo/bo00002151.csv
  Orders/_Daily/do04905501.csv
  Translated/Story/Episode 1/co_011108.csv
  Tutorial/Message Pack/mp_000028.csv
  Tutorial/Message Pack/mp_000032.csv
  Tutorial/Message Pack/mp_000091.csv
  Tutorial/Message Pack/mp_000099.csv
  Tutorial/Message Pack/mp_000157.csv
  Tutorial/Message Pack/mp_000239.csv
  Tutorial/Message Pack/mp_000245.csv
  Tutorial/Message Pack/mp_000312.csv
  Tutorial/Message Pack/mp_000313.csv
  Tutorial/Message Pack/mp_000314.csv
  Tutorial/Message Pack/mp_000315.csv
  Tutorial/Message Pack/mp_000316.csv
  Tutorial/Message Pack/mp_000318.csv
  Tutorial/Message Pack/mp_000319.csv
  Tutorial/Message Pack/mp_000320.csv
  Tutorial/Message Pack/mp_000321.csv
  Tutorial/Message Pack/mp_000322.csv
  Tutorial/Message Pack/mp_000323.csv
  Tutorial/Message Pack/mp_000324.csv
  Tutorial/Message Pack/mp_000325.csv
  Tutorial/Message Pack/mp_000326.csv
  Tutorial/Message Pack/mp_000327.csv
  Tutorial/Message Pack/mp_000328.csv
  Tutorial/Message Pack/mp_000329.csv
  Tutorial/Message Pack/mp_000330.csv
  Tutorial/Message Pack/mp_000331.csv
  Tutorial/Message Pack/mp_000376.csv
  Tutorial/Message Pack/mp_000377.csv
  Tutorial/Tutorial List/wh_tl_mp_000239.csv
  Tutorial/Window/co_011108.csv
  UI/common.csv
  UI/item_element_expl.csv
  UI/ui_gat.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
  _aspell/PSO2.en_Chat.dict
  _aspell/PSO2.en_Enemies.dict
  _aspell/PSO2.en_Enemies_Darkers.dict
  _aspell/PSO2.en_Items.dict
  _aspell/PSO2.en_Makeup.dict
  _aspell/PSO2.en_Names.dict
Labels: size/L

#869 EN: Translate Episode 3 "Tricking and Deceiving Katori"
  Files/un_035010.csv
  Story/Episode 3/un_035010.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/M

#876 EN: Regiment of the Wicked 2019
  Files/co_063100.csv
  Files/ii_session_apc_5580.csv
  Files/ii_session_apc_5584.csv
  Files/ii_session_apc_5597.csv
  Files/ii_session_apc_5598.csv
  Files/ii_session_apc_5608.csv
  Files/ii_session_apc_5609.csv
  Files/ii_session_apc_5618.csv
  Files/ii_session_apc_5619.csv
  Files/quest_00051080.csv
  Files/quest_00161500.csv
  Files/quest_00170650.csv
  Quests/Damage Tally/co_063100.csv
  Quests/Damage Tally/quest_00161500.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5580.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5584.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5597.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5598.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5608.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5609.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5618.csv
  Quests/Seasonal/Regiment 2019/ii_session_apc_5619.csv
  Quests/Seasonal/Regiment 2019/quest_00051080.csv
  Quests/Seasonal/Regiment 2019/quest_00170650.csv
Labels: size/M

#879 Support partner quotes translation
  Misc/My Room/sp_greeting.csv
Labels: size/S

#881 EN: Potentials and Phantom level cap COs
  Orders/Koffie/co06010002.csv
  Orders/Koffie/co06010003.csv
  Orders/Koffie/co06010004.csv
  Orders/Koffie/co06010005.csv
  Orders/Koffie/co06010006.csv
  UI/ui_item.csv
  _aspell/PSO2.en_Items.dict
Labels: size/M

#884 EN: Some small stuff
  Quests/Loser/quest_00050810.csv
  Quests/Loser/quest_00170380.csv
  UI/common.csv
  UI/ui_mainmode.csv
  _aspell/PSO2.en_Names.dict
Labels: size/M
