Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-03, with the labels that each got.

#974 EN: Afin CO fixes
  Orders/Afin/Retired/co01020039.csv
  Orders/Afin/co01020020.csv
  Orders/Afin/co01020039.csv
  Orders/Afin/co01030304.csv
  Orders/Afin/co01030306.csv
  Orders/Afin/co01030307.csv
  Orders/Afin/co01030308.csv
  Orders/Afin/co01030309.csv
Labels: size/S

#971 WIP: [RU] Preparation
  translated files/Dialogue/Mid-Mission/incident_common.csv
  translated files/Misc/actor_name.csv
  translated files/Misc/clientorder_name.csv
  translated files/Orders/Daily/do00001032.csv
  translated files/Orders/Daily/do01020111.csv
  translated files/Story/Episode 6/st_061010.csv
  translated files/Story/Episode 6/st_061015.csv
  translated files/Story/Episode 6/st_061080.csv
  translated files/Story/Episode 6/st_061110.csv
  translated files/Story/Episode 6/st_062020.csv
  translated files/Tutorial/Arks Road/Lessons/kn_010200.csv
  translated files/Tutorial/Arks Road/Lessons/kn_010400.csv
  translated files/UI/common.csv
  translated files/UI/config.csv
  translated files/UI/forced_move.csv
  translated files/UI/quest_common.csv
  translated files/UI/quest_counter.csv
  translated files/UI/ui_apc.csv
  translated files/UI/ui_charamake_text.csv
  translated files/UI/ui_craft.csv
  translated files/UI/ui_item.csv
  translated files/UI/ui_mainmode.csv
  translated files/UI/ui_quest.csv
  translated files/UI/ui_title_text.csv
Labels: size/L

#975 EN: Black Nyack & Rappy Slot explanation, misc. Casino Area stuff
  Dialogue/Claudia/np_011620.csv
  Dialogue/Claudia/np_npc_162.csv
  Dialogue/Hearty/np_011600.csv
  Dialogue/Hearty/np_npc_160.csv
  Dialogue/Naris/np_020340.csv
  Files/np_011600.csv
  Files/np_011620.csv
  Files/np_020340.csv
  UI/ui_amusement.csv
  _aspell/PSO2.en_Casino.dict
Labels: size/M

#980 ES: Correcion Fracaso
  Quests/Divide Quest/quest_00220000.csv
  Quests/Divide Quest/quest_00220010.csv
  Quests/Divide Quest/quest_00220015.csv
  Quests/Divide Quest/quest_00220020.csv
  Quests/Divide Quest/quest_00220025.csv
  Quests/Divide Quest/quest_00220030.csv
  Quests/Divide Quest/quest_00220035.csv
  Quests/Divide Quest/quest_00220040.csv
  Quests/Divide Quest/quest_00220045.csv
  Quests/Divide Quest/quest_00220050.csv
  Quests/Divide Quest/quest_00220055.csv
  Quests/Divide Quest/quest_00220060.csv
  Quests/Divide Quest/quest_00220065.csv
  Quests/Divide Quest/quest_00220070.csv
  Quests/Divide Quest/quest_00220075.csv
  Quests/Divide Quest/quest_00220080.csv
  Quests/Divide Quest/quest_00220085.csv
  Quests/Divide Quest/quest_00220090.csv
  Quests/Divide Quest/quest_00220095.csv
  Quests/Divide Quest/quest_00220100.csv
  Quests/Divide Quest/quest_00220105.csv
  Quests/Divide Quest/quest_00220110.csv
  Quests/Divide Quest/quest_00220115.csv
  Quests/Divide Quest/quest_00220120.csv
  Quests/Divide Quest/quest_00220125.csv
  Quests/Divide Quest/quest_00220130.csv
  Quests/Divide Quest/quest_00220135.csv
  Quests/Divide Quest/quest_00220140.csv
  Quests/Divide Quest/quest_00220145.csv
  Quests/Divide Quest/quest_00220150.csv
  Quests/Divide Quest/quest_00220155.csv
  Quests/Divide Quest/quest_00220160.csv
  Quests/Divide Quest/quest_00220165.csv
  Quests/Divide Quest/quest_00220170.csv
  Quests/Divide Quest/quest_00220175.csv
  Quests/Divide Quest/quest_00220180.csv
  Quests/Divide Quest/quest_00220185.csv
  Quests/Divide Quest/quest_00220190.csv
  Quests/Divide Quest/quest_00220195.csv
  Quests/Divide Quest/quest_00220200.csv
  Quests/Divide Quest/quest_00220201.csv
  Quests/Divide Quest/quest_00220202.csv
  Quests/Divide Quest/quest_00220205.csv
  Quests/Divide Quest/quest_00220206.csv
  Quests/Divide Quest/quest_00220207.csv
  Quests/Divide Quest/quest_00220210.csv
  Quests/Divide Quest/quest_00220220.csv
  Quests/Divide Quest/quest_00220230.csv
  Quests/Divide Quest/quest_00220240.csv
  Quests/Divide Quest/quest_00220250.csv
  Quests/Divide Quest/quest_00220260.csv
Labels: size/L
