Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-06, with the labels that each got.

#1022 Fix Lets typo in Revelle's CO and Receive League Rewards.
  Dialogue/np_npc_00cmn.csv
  Orders/Revelle/co01042120.csv
Labels: size/XS

#1023 [RU] group chat hot fix
  translated files/UI/ui_group_chat.csv
Labels: size/M

#1024 KO: Additional Translation
  Files/quest_00100060.csv
  Files/st_010005.csv
  Files/st_010020.csv
  Files/st_010050.csv
  Quests/Base Defense/quest_00100060.csv
  Story/Episode 1/st_010005.csv
  Story/Episode 1/st_010010.csv
  Story/Episode 1/st_010020.csv
  Story/Episode 1/st_010030.csv
  Story/Episode 1/st_010030_fs.csv
  Story/Episode 1/st_010040.csv
  Story/Episode 1/st_010050.csv
  Story/Episode 1/st_010060.csv
  Story/Episode 1/st_010060_fs.csv
  Story/Episode 1/st_010070.csv
  Story/Episode 1/st_010080.csv
  Story/Episode 1/st_010080_fs.csv
  Story/Episode 1/st_010090.csv
  Story/Episode 1/st_010100.csv
  Story/Episode 1/st_010100_fs.csv
  Story/Episode 1/st_010110.csv
  UI/ui_charamake_text.csv
  UI/ui_esthetic_text.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1025 KO: fix / add translation
  UI/ui_title_text.csv
Labels: size/S

#1027 KO: Translation and fix
  Files/date.csv
  Files/ui_quest.csv
  UI/config.csv
  UI/date.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
  UI/ui_title_text.csv
Labels: size/S

#1029 KO: Additional work
  Misc/actor_name.csv
  UI/date.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
Labels: size/L

#1032 KO: examination work
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_quest.csv
  UI/ui_title_text.csv
Labels: size/M

#1034 KO: Additional Translation
  Dialogue/E-Trial/ii_abd_clone_boss.csv
  Dialogue/E-Trial/ii_anh_fantasy_mob.csv
  Dialogue/E-Trial/ii_anh_phantom_ship.csv
  Dialogue/E-Trial/ii_anh_rd.csv
  Dialogue/E-Trial/ii_anh_thunder_hell.csv
  Dialogue/E-Trial/ii_annihilation_aold.csv
  Dialogue/E-Trial/ii_areaboss.csv
  Dialogue/E-Trial/ii_boss_ahl_ranking.csv
  Dialogue/E-Trial/ii_enemy_ranking.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1035 KO: 번역 추가 및 검수
  Dialogue/E-Trial/ii_pamper_jack_box.csv
  UI/common.csv
  UI/config.csv
  UI/ui_charamake_text.csv
Labels: size/XL

#1038 KO: Additional Translation
  UI/config.csv
  UI/ui_charamake_text.csv
  UI/ui_item.csv
Labels: size/L

#1040 KO: 오메가 팔스 루서 번역
  Files/quest_00050800.csv
  Files/quest_00050810.csv
  Files/quest_00170370.csv
  Files/quest_00170380.csv
  Misc/actor_name.csv
  Quests/Dark Falz/Loser/quest_00050800.csv
  Quests/Dark Falz/Loser/quest_00050810.csv
  Quests/Dark Falz/Loser/quest_00170370.csv
  Quests/Dark Falz/Loser/quest_00170380.csv
  UI/ui_quest.csv
Labels: size/M

#1045 Standardize the rest of the key namings to match current item patch.
  Orders/Pusoni Comic/co06064204.csv
  Orders/Pusoni Comic/co06065004.csv
  Quests/Bonus Quests/Magatsu G/quest_00150040.csv
  Quests/Bonus Quests/Magatsu S/quest_00150030.csv
  Quests/Bonus Quests/Tokyo G/quest_00150000.csv
  Quests/Bonus Quests/Tokyo R/quest_00150080.csv
  Quests/Bonus Quests/Tokyo S/quest_00150010.csv
Labels: size/S

#1047 KO: 검수 작업
  Misc/actor_name.csv
  Orders/Koffie/co01019200.csv
  Orders/Koffie/co01019202.csv
  Orders/Koffie/co02010040.csv
  Orders/Koffie/co04010042.csv
  Orders/Koffie/co05010233.csv
  Orders/Koffie/co05010911.csv
  Orders/Koffie/co06010008.csv
  Orders/Koffie/co06010009.csv
  Quests/quest_common.csv
  UI/config.csv
  UI/refer.csv
  UI/ui_charamake_text.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/L

#1048 KO: 추가 번역 및 검수작업
  Orders/Koffie/co06010009.csv
  UI/ui_item.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1050 KO: some fix type error
  Orders/Koffie/co01010020.csv
  Orders/Koffie/co01010090.csv
  Orders/Koffie/co01010220.csv
  Orders/Koffie/co01019200.csv
  Orders/Koffie/co01019201.csv
  Orders/Koffie/co01019202.csv
  Orders/Koffie/co05010234.csv
  Orders/Koffie/co05010235.csv
  Orders/Koffie/co06010004.csv
  Orders/Koffie/co06010005.csv
  Orders/Koffie/co06010008.csv
  Quests/quest_counter.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/L

#1051 KO:Additional inspection work
  Misc/actor_name.csv
  Orders/Koffie/co01010020.csv
  Quests/Dark Falz/Loser/quest_00050800.csv
  Quests/quest_common.csv
  UI/common.csv
Labels: size/L

#1053 st_048020_0060#0 > case fix
  Story/Episode 4/Chapter 8/st_048020.csv
Labels: size/XS

#1055 [RU] hot fix + Nekonomia apc (test)
  translated files/Dialogue/Makino/np_npc_635.csv
  translated files/Dialogue/Makino/np_npc_640.csv
  translated files/Dialogue/PuSo Ni/od_060650031.csv
  translated files/Dialogue/PuSo Ni/om_060650032.csv
  translated files/Dialogue/PuSo Ni/om_060650033.csv
  translated files/Dialogue/Zect/np_npc_634.csv
  translated files/Misc/_Partner chat/apc_chat_4.csv
  translated files/Misc/actor_name.csv
  translated files/Orders/Koffie/co01010000.csv
  translated files/Orders/Koffie/co01010001.csv
  translated files/Orders/Koffie/co01010020.csv
  translated files/Orders/Koffie/co01010030.csv
  translated files/Orders/Koffie/co01010090.csv
  translated files/Orders/Koffie/co01010200.csv
  translated files/Orders/Koffie/co01010201.csv
  translated files/Orders/Koffie/co01010220.csv
  translated files/Orders/Koffie/co01019200.csv
  translated files/Orders/Koffie/co01019201.csv
  translated files/Orders/Koffie/co01019202.csv
  translated files/Orders/Koffie/co01019203.csv
  translated files/Orders/Koffie/co01019204.csv
  translated files/Orders/Koffie/co01019205.csv
  translated files/Orders/Koffie/co01019206.csv
  translated files/Orders/Koffie/co01019207.csv
  translated files/Orders/Koffie/co01019208.csv
  translated files/Orders/Koffie/co01019209.csv
  translated files/Orders/Koffie/co01019210.csv
  translated files/Orders/Koffie/co02010040.csv
  translated files/Orders/Koffie/co04010000.csv
  translated files/Orders/Koffie/co04010002.csv
  translated files/Orders/Koffie/co04010042.csv
  translated files/Orders/Koffie/co05010231.csv
  translated files/Orders/Koffie/co05010232.csv
  translated files/Orders/Koffie/co05010233.csv
  translated files/Orders/Koffie/co05010234.csv
  translated files/Orders/Koffie/co05010235.csv
  translated files/Orders/Koffie/co05010911.csv
  translated files/Orders/Koffie/co06010001.csv
  translated files/Orders/Koffie/co06010002.csv
  translated files/Orders/Koffie/co06010003.csv
  translated files/Orders/Koffie/co06010004.csv
  translated files/Orders/Koffie/co06010005.csv
  translated files/Orders/Koffie/co06010008.csv
  translated files/Orders/Koffie/co06010009.csv
  translated files/Orders/Koffie/co06010010.csv
  translated files/Orders/Koffie/co06010011.csv
  translated files/Orders/Koffie/co06010012.csv
  translated files/Orders/Koffie/co06010013.csv
  translated files/Orders/Koffie/co06010014.csv
  translated files/Orders/Koffie/co06010015.csv
  translated files/Orders/Koffie/co06010016.csv
  translated files/Orders/Koffie/co06010017.csv
  translated files/Orders/PuSo Ni Comi/co06065003.csv
  translated files/Orders/PuSo Ni Comi/co06065004.csv
  translated files/Orders/PuSo Ni Comi/co06065005.csv
  translated files/UI/ui_mainmode.csv
Labels: size/L

#1059 KO: NPC text fix
  NPC/Lisa/Order/co01011200.csv
  NPC/Lisa/Order/co01011201.csv
  NPC/Lisa/Order/co01011300.csv
  NPC/Lisa/Order/co01011301.csv
  NPC/Lisa/Order/co01020008.csv
  NPC/Lisa/Order/co01020009.csv
  NPC/Lisa/Order/co02032603.csv
  NPC/Lisa/Order/co03032602.csv
  NPC/Lisa/Order/co03032603.csv
  NPC/Lisa/Order/co03032604.csv
  NPC/Ohza/Order/co01011000.csv
  NPC/Ohza/Order/co01011001.csv
  NPC/Ohza/Order/co01011100.csv
  NPC/Ohza/Order/co01011101.csv
  NPC/Ohza/Order/co01012000.csv
  NPC/Ohza/Order/co01020000.csv
  NPC/Ohza/Order/co01020001.csv
  NPC/Ohza/Order/co01020002.csv
  NPC/Ohza/Order/co01020003.csv
  NPC/Ohza/Order/co01020005.csv
  NPC/Ohza/Order/co01020006.csv
  NPC/Ohza/Order/co01020007.csv
  NPC/Ohza/Order/co01032000.csv
  NPC/Ohza/Order/co01032001.csv
  NPC/Ohza/Order/co01032002.csv
  NPC/Ohza/Order/co01032003.csv
  NPC/Ohza/Order/co01032004.csv
  NPC/Ohza/Order/co01032005.csv
  NPC/Ohza/Order/co01032006.csv
  NPC/Ohza/Order/co01032007.csv
  NPC/Ohza/Order/co01032008.csv
  NPC/Ohza/Order/co02032000.csv
  NPC/Ohza/Order/co02032001.csv
  NPC/Ohza/Order/co02032002.csv
  NPC/Ohza/Order/co02032003.csv
  NPC/Ohza/Order/co03032000.csv
  NPC/Ohza/Order/co03032001.csv
  NPC/Ohza/Order/co03032002.csv
  NPC/Ohza/Order/co03032003.csv
  NPC/Ohza/Order/co03032004.csv
  NPC/Ohza/Order/co03032005.csv
  NPC/Ohza/Order/co03032006.csv
  NPC/Ohza/Order/co03032007.csv
  NPC/Ohza/Order/co03032008.csv
  NPC/Ohza/Order/co03032009.csv
  NPC/Ohza/Order/co03032010.csv
Labels: size/L

#1060 KO: Additional Translation
  Files/clientorder_name.csv
  Misc/actor_name.csv
  Misc/clientorder_name.csv
  NPC/Lisa/Order/co01020009.csv
  NPC/Lisa/Order/co01020011.csv
  NPC/Lisa/Order/co01020013.csv
  NPC/Ohza/Order/co01012000.csv
  NPC/Ohza/Order/co01020000.csv
  NPC/Ohza/Order/co01020006.csv
  NPC/Ohza/Order/co01020007.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1061 KO: Additional translation
  Files/co_060518.csv
  Files/np_npc_607.csv
  Files/np_npc_634.csv
  Files/np_npc_636.csv
  Files/od_060650011.csv
  Files/od_060650017.csv
  Files/od_060650021.csv
  Files/od_060650027.csv
  Files/od_060650031.csv
  Files/od_060650037.csv
  Files/od_060650041.csv
  Files/od_060650047.csv
  Misc/actor_name.csv
  Misc/clientorder_name.csv
  NPC/Dolce/Dialogue/np_016360.csv
  NPC/Dolce/Dialogue/np_npc_636.csv
  NPC/Dolce/Order/od_060650021.csv
  NPC/Dolce/Order/od_060650027.csv
  NPC/Lisa/Order/co01011200.csv
  NPC/Lisa/Order/co01011300.csv
  NPC/Magical Robo/Dialogue/np_016340.csv
  NPC/Magical Robo/Dialogue/np_npc_634.csv
  NPC/Magical Robo/Order/od_060650011.csv
  NPC/Magical Robo/Order/od_060650017.csv
  NPC/Magical Robo/Order/od_060650041.csv
  NPC/Magical Robo/Order/od_060650047.csv
  NPC/Nekonomiya/Dialogue/np_016070.csv
  NPC/Nekonomiya/Dialogue/np_npc_607.csv
  NPC/Nekonomiya/Order/co06065003.csv
  NPC/Nekonomiya/Order/od_060650031.csv
  NPC/Nekonomiya/Order/od_060650037.csv
  NPC/Ohza/Order/co01012000.csv
  NPC/Ohza/Order/co01020002.csv
  NPC/Ohza/Order/co01020003.csv
  NPC/Ohza/Order/co01020006.csv
  NPC/Ohza/Order/co01020007.csv
  NPC/Ohza/Order/co03032000.csv
  NPC/Ohza/Order/co03032001.csv
  NPC/Puso ni/co_060518.csv
  Quests/quest_counter.csv
  UI/config.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1052 st_047010 > spelling fixes
  Story/Episode 4/Chapter 6/st_047010.csv
Labels: size/XS

#1064 EN: New PAs and tweaks to crafted Techs
  Misc/actor_name.csv
  UI/ui_item.csv
Labels: size/S

#1066 EN: Tokyo Team Order descriptions
  Orders/_Team/go04000000.csv
  Orders/_Team/go04000001.csv
  Orders/_Team/go04000002.csv
  Orders/_Team/go04000003.csv
  Orders/_Team/go04000004.csv
  Orders/_Team/go04000005.csv
  Orders/_Team/go04000006.csv
  Orders/_Team/go04000007.csv
  Orders/_Team/go04000008.csv
  Orders/_Team/go04000009.csv
  Orders/_Team/go04000010.csv
Labels: size/S

#1068 KO: Additional work
  Files/quest_00051180.csv
  Files/quest_00170820.csv
  NPC/Lisa/Order/co01011200.csv
  Quests/Seasonal/Rain 2020/quest_00051180.csv
  Quests/Seasonal/Rain 2020/quest_00170820.csv
  UI/ui_item.csv
Labels: size/XL

#1069 KO: hotfix stuff
  NPC/Magical Robo/Order/np_016380.csv
  NPC/Magical Robo/Order/np_016440.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_quest.csv
Labels: size/M

#1071 KO: Additional work
  Files/item_element_expl.csv
  Misc/actor_name.csv
  UI/common.csv
  UI/config.csv
  UI/item_element_expl.csv
  UI/item_element_name.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1073 KO: Additional Work
  UI/item_element_expl.csv
Labels: size/L

#1074 KO: Additional Translation
  Files/co03073000.csv
  Files/co03073001.csv
  Files/co03073002.csv
  Files/co03074132.csv
  Files/co03074133.csv
  Files/co05033131.csv
  Files/co05033132.csv
  Files/co05033133.csv
  Files/co05033134.csv
  Files/co05033135.csv
  Files/co05033136.csv
  Files/co05033151.csv
  NPC/Claris Claes/Order/co03073000.csv
  NPC/Claris Claes/Order/co03073001.csv
  NPC/Claris Claes/Order/co03073002.csv
  NPC/Stratos/Order/co05033131.csv
  NPC/Stratos/Order/co05033132.csv
  NPC/Stratos/Order/co05033133.csv
  NPC/Stratos/Order/co05033134.csv
  NPC/Stratos/Order/co05033135.csv
  NPC/Stratos/Order/co05033136.csv
  NPC/Stratos/Order/co05033151.csv
  NPC/Zieg/co03074132.csv
  NPC/Zieg/co03074133.csv
Labels: size/M

#1075 Fix colon type/missing spacing in Dark Blast alert.
  Misc/actor_name.csv
Labels: size/XS

#1077 Es: Update
  Files/ii_session_apc_5527.csv
  Misc/My Room/mikiri.csv
  Misc/ii_session_apc_5527.csv
Labels: size/S
