Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-07, with the labels that each got.

#1076 EN: Fix spacing in room goods size
  UI/ui_item.csv
Labels: size/XS

#1079 EN: English Translation of Episode 6 Chapter 5
  Files/st_064050.csv
  Files/st_064060.csv
  Files/st_064070.csv
  Files/st_064075.csv
  Files/st_064078.csv
  Files/st_064080.csv
  Files/st_064100.csv
  Files/st_064110.csv
  Files/st_064120.csv
  Files/un_063070.csv
  Files/un_064060.csv
  Files/un_064100.csv
  Files/un_064110.csv
  Files/un_064160.csv
  Files/un_065040.csv
  Files/un_065240.csv
  Story/Episode 6/st_064050.csv
  Story/Episode 6/st_064060.csv
  Story/Episode 6/st_064070.csv
  Story/Episode 6/st_064075.csv
  Story/Episode 6/st_064078.csv
  Story/Episode 6/st_064080.csv
  Story/Episode 6/st_064100.csv
  Story/Episode 6/st_064110.csv
  Story/Episode 6/st_064120.csv
  Story/Episode 6/un_063070.csv
  Story/Episode 6/un_064060.csv
  Story/Episode 6/un_064100.csv
  Story/Episode 6/un_064110.csv
  Story/Episode 6/un_064160.csv
  Story/Episode 6/un_065040.csv
  Story/Episode 6/un_065240.csv
  _aspell/PSO2.en_Chat.dict
  _aspell/PSO2.en_Misc.dict
Labels: size/XL

#1081 EN: Missed one
  Dialogue/Quna/np_013130.csv
Labels: size/XS

#1082 KO: S class ability name translation
  NPC/Kyokuya/co06033204.csv
  UI/item_element_name.csv
Labels: size/XL

#1085 Update ui_item.csv
  UI/ui_item.csv
Labels: size/XS

#1083 EN: Anniversary stuff and 6-2 story area names
  Dialogue/Xie/Anniversary/8th/od_060505011.csv
  Dialogue/Xie/Anniversary/8th/od_060505017.csv
  Dialogue/Xie/Anniversary/8th/od_060505021.csv
  Dialogue/Xie/Anniversary/8th/od_060505027.csv
  Dialogue/Xie/Anniversary/8th/od_060505031.csv
  Dialogue/Xie/Anniversary/8th/od_060505037.csv
  Dialogue/Xie/Anniversary/8th/od_060505041.csv
  Dialogue/Xie/Anniversary/8th/od_060505047.csv
  Dialogue/Xie/Anniversary/np_010970.csv
  Files/od_060505011.csv
  Files/od_060505017.csv
  Files/od_060505021.csv
  Files/od_060505027.csv
  Files/od_060505031.csv
  Files/od_060505037.csv
  Files/od_060505041.csv
  Files/od_060505047.csv
  Orders/Xie/Anniversary/8th/co06050501.csv
  Orders/Xie/Anniversary/8th/co06050502.csv
  Orders/Xie/Anniversary/8th/co06050503.csv
  Orders/Xie/Anniversary/8th/co06050504.csv
  Quests/Limited Quests/Episode 6 LQ/quest_00080440.csv
  Quests/Story EP6 names/Chapter 1/quest_00301500.csv
  Quests/Story EP6 names/Chapter 2/quest_00301620.csv
  Quests/Story EP6 names/Chapter 3/quest_00301770.csv
  Quests/Story EP6 names/Chapter 3/quest_00301850.csv
  Quests/Story EP6 names/Chapter 4/quest_00302070.csv
Labels: size/L

#1088 KO: NPC menu translation
  Files/np_npc_00cmn.csv
  UI/np_npc_00cmn.csv
Labels: size/L

#1089 EN: LQ dialogue
  Dialogue/Io/od_020391011.csv
  Dialogue/Io/od_020391017.csv
  Dialogue/Zieg/np_010110.csv
  Files/cm_069000.csv
  Files/cm_069001.csv
  Files/cm_069002.csv
  Files/cm_069003.csv
  Files/cm_069004.csv
  Files/cm_069005.csv
  Files/cm_069006.csv
  Files/cm_069007.csv
  Files/cm_069008.csv
  Files/cm_069009.csv
  Files/cm_069010.csv
  Files/cm_069011.csv
  Files/cm_069012.csv
  Files/cm_069013.csv
  Files/cm_069014.csv
  Files/cm_069015.csv
  Files/cm_069016.csv
  Files/cm_069017.csv
  Files/cm_069018.csv
  Files/od_020391011.csv
  Files/od_020391017.csv
  Orders/Io/co02039101.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069000.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069001.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069002.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069003.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069004.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069005.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069006.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069007.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069008.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069009.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069010.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069011.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069012.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069013.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069014.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069015.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069016.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069017.csv
  Quests/Limited Quests/Episode 6 LQ/cm_069018.csv
  Quests/Limited Quests/Episode 6 LQ/quest_00080440.csv
  Quests/Limited Quests/Episode 6 LQ/quest_00170800.csv
Labels: size/L

#1091 KO: fix xie and LQ's text
  Files/np_010970.csv
  Files/quest_00170800.csv
  Misc/actor_name.csv
  NPC/Xie/Anniversary/8th/co09050004.csv
  NPC/Xie/Anniversary/8th/np_010970.csv
  NPC/Xie/Anniversary/8th/od_060505021.csv
  NPC/Xie/Anniversary/8th/od_060505031.csv
  NPC/Xie/Anniversary/8th/od_060505037.csv
  NPC/Xie/Anniversary/8th/od_060505041.csv
  NPC/Xie/Anniversary/8th/od_060505047.csv
  Quests/Base Defense/quest_00100060.csv
  Quests/Limited Quest/Anniversary/8th/cm_069013.csv
  Quests/Limited Quest/Anniversary/8th/quest_00080440.csv
  Quests/Limited Quest/Anniversary/8th/quest_00170800.csv
  UI/ui_item.csv
  UI/ui_quest.csv
Labels: size/L

#1094 Add EP3 The Reason You Were Born checkpoint.
  Files/oc_030130.csv
  Story/Episode 3/oc_030130.csv
Labels: size/S

#1095 KO: fix typing error stuff
  NPC/Xie/Anniversary/8th/od_060505037.csv
  NPC/Xie/Anniversary/8th/od_060505041.csv
  UI/ui_mainmode.csv
Labels: size/L

#1096 KO: UI's Translation
  Files/quest_00160100.csv
  Files/tr_010000.csv
  Files/ui_beginner_guide.csv
  Misc/actor_name.csv
  Quests/Limited Quest/Anniversary/8th/quest_00080440.csv
  Quests/quest_common.csv
  Quests/quest_counter.csv
  Tutorial/Training Quests/01 Hunter/quest_00160100.csv
  Tutorial/Training Quests/01 Hunter/tr_010000.csv
  UI/item_element_expl.csv
  UI/ui_beginner_guide.csv
  UI/ui_mainmode.csv
  UI/ui_myroom.csv
  UI/ui_quest.csv
Labels: size/XL

#1097 Vehicle-based Devil's Trailer
  Story/Episode 4/Chapter 4/cm_042415.csv
Labels: size/XS

#1098 KO: Additional Work
  Files/ui_missionboard.csv
  Quests/quest_counter.csv
  Tutorial/Training Quests/01 Hunter/quest_00160100.csv
  UI/ui_mainmode.csv
  UI/ui_missionboard.csv
  UI/ui_ship_battle.csv
Labels: size/L

#1099 KO: change date
  Misc/actor_name.csv
Labels: size/XS

#1101 KO: Quest Translation
  Files/quest_00030010.csv
  Files/quest_00030015.csv
  Files/quest_00030020.csv
  Files/quest_00030030.csv
  Files/quest_00030040.csv
  Files/quest_00030050.csv
  Files/quest_00030060.csv
  Files/quest_00030070.csv
  Misc/actor_name.csv
  Quests/Arks Quest/quest_00030010.csv
  Quests/Arks Quest/quest_00030015.csv
  Quests/Arks Quest/quest_00030020.csv
  Quests/Arks Quest/quest_00030030.csv
  Quests/Arks Quest/quest_00030040.csv
  Quests/Arks Quest/quest_00030050.csv
  Quests/Arks Quest/quest_00030060.csv
  Quests/Arks Quest/quest_00030070.csv
  UI/date.csv
  UI/ui_mainmode.csv
  UI/ui_missionboard.csv
Labels: size/L

#1102 KO: Free fields translation
  Files/quest_00020010.csv
  Files/quest_00020020.csv
  Files/quest_00020030.csv
  Files/quest_00020040.csv
  Files/quest_00020050.csv
  Files/quest_00020060.csv
  Files/quest_00020070.csv
  Files/quest_00020080.csv
  Files/quest_00020090.csv
  Files/quest_00020100.csv
  Files/quest_00020110.csv
  Files/quest_00020120.csv
  Files/quest_00020130.csv
  Files/quest_00020140.csv
  Files/quest_00020150.csv
  Files/quest_00020160.csv
  Files/quest_00020170.csv
  NPC/Puso ni/co_060518.csv
  Quests/Arks Quest/quest_00030010.csv
  Quests/Arks Quest/quest_00030015.csv
  Quests/Arks Quest/quest_00030020.csv
  Quests/Arks Quest/quest_00030030.csv
  Quests/Arks Quest/quest_00030040.csv
  Quests/Arks Quest/quest_00030050.csv
  Quests/Arks Quest/quest_00030060.csv
  Quests/Arks Quest/quest_00030070.csv
  Quests/Free Fields/UH/quest_00020180.csv
  Quests/Free Fields/UH/quest_00020200.csv
  Quests/Free Fields/UH/quest_00020210.csv
  Quests/Free Fields/UH/quest_00020220.csv
  Quests/Free Fields/UH/quest_00020230.csv
  Quests/Free Fields/UH/quest_00020240.csv
  Quests/Free Fields/UH/quest_00020250.csv
  Quests/Free Fields/UH/quest_00020260.csv
  Quests/Free Fields/UH/quest_00020270.csv
  Quests/Free Fields/UH/quest_00020280.csv
  Quests/Free Fields/UH/quest_00020290.csv
  Quests/Free Fields/quest_00020010.csv
  Quests/Free Fields/quest_00020020.csv
  Quests/Free Fields/quest_00020030.csv
  Quests/Free Fields/quest_00020040.csv
  Quests/Free Fields/quest_00020050.csv
  Quests/Free Fields/quest_00020060.csv
  Quests/Free Fields/quest_00020070.csv
  Quests/Free Fields/quest_00020080.csv
  Quests/Free Fields/quest_00020090.csv
  Quests/Free Fields/quest_00020100.csv
  Quests/Free Fields/quest_00020110.csv
  Quests/Free Fields/quest_00020120.csv
  Quests/Free Fields/quest_00020130.csv
  Quests/Free Fields/quest_00020140.csv
  Quests/Free Fields/quest_00020150.csv
  Quests/Free Fields/quest_00020160.csv
  Quests/Free Fields/quest_00020170.csv
  Quests/quest_counter.csv
Labels: size/L

#1106 EN: Update ui_mainmode.csv
  UI/ui_mainmode.csv
Labels: size/XS

#1107 Fix story typo.
  Story/Episode 1/un_012220.csv
Labels: size/XS

#1103 EN: Fix names to Reaper's Axe Labrys/Imperial Cannon Quantum.
  Story/Episode 3/st_039030.csv
Labels: size/XS

#1036 ES: update quest commom
  UI/quest_common.csv
Labels: size/XS

#1090 EN: Io COs
  Dialogue/Io/od_020391021.csv
  Dialogue/Io/od_020391027.csv
  Dialogue/Io/od_020391031.csv
  Dialogue/Io/od_020391037.csv
  Dialogue/Io/od_020391041.csv
  Dialogue/Io/od_020391047.csv
  Dialogue/Io/od_020391051.csv
  Dialogue/Io/od_020391057.csv
  Dialogue/Xiera/pr_047900.csv
  Dialogue/Xiera/pr_056020.csv
  Files/od_020391021.csv
  Files/od_020391027.csv
  Files/od_020391031.csv
  Files/od_020391037.csv
  Files/od_020391041.csv
  Files/od_020391047.csv
  Files/od_020391051.csv
  Files/od_020391057.csv
  Files/pr_047900.csv
  Files/pr_056020.csv
  Orders/Io/co02039102.csv
  Orders/Io/co02039103.csv
  Orders/Io/co02039104.csv
  Orders/Io/co02039105.csv
Labels: size/M

#1108 KO : Additional Work
  Dialogue/E-Trial/ii_mack_defense.csv
  Dialogue/E-Trial/incident_common.csv
  Misc/actor_name.csv
  Quests/quest_common.csv
  UI/ui_missionboard.csv
  UI/ui_myroom.csv
Labels: size/XXL

#1111 KO: examine work
  Dialogue/E-Trial/ii_areaboss_db.csv
  Dialogue/E-Trial/ii_areaboss_df.csv
  Quests/Dark Falz/Persona/cm_0511114.csv
  Quests/Dark Falz/Persona/ii_areaboss_med.csv
  Quests/Limited Quest/Anniversary/8th/2nd/cm_069102.csv
  Quests/Limited Quest/Anniversary/8th/2nd/cm_069104.csv
  Quests/Limited Quest/Anniversary/8th/2nd/cm_069106.csv
  Quests/Limited Quest/Anniversary/8th/2nd/cm_069108.csv
  Quests/Limited Quest/Anniversary/8th/2nd/cm_069110.csv
  Quests/Limited Quest/Anniversary/8th/2nd/cm_069111.csv
  Quests/Limited Quest/Anniversary/8th/2nd/quest_00080450.csv
  Quests/Limited Quest/Anniversary/8th/2nd/quest_00170840.csv
Labels: size/M

#1112 EN: Update stuff
  Dialogue/Mid-Mission/heatup.csv
  Dialogue/Xie/Anniversary/8th/od_060505051.csv
  Dialogue/Xie/Anniversary/8th/od_060505057.csv
  Dialogue/Xie/Anniversary/8th/od_060505061.csv
  Dialogue/Xie/Anniversary/8th/od_060505067.csv
  Dialogue/Yerkes/np_013090.csv
  Files/cm_069101.csv
  Files/cm_069102.csv
  Files/cm_069103.csv
  Files/cm_069104.csv
  Files/cm_069105.csv
  Files/cm_069106.csv
  Files/cm_069107.csv
  Files/cm_069108.csv
  Files/cm_069109.csv
  Files/cm_069110.csv
  Files/cm_069111.csv
  Files/cm_069112.csv
  Files/co06050505.csv
  Files/co06050506.csv
  Files/od_060505051.csv
  Files/od_060505057.csv
  Files/od_060505061.csv
  Files/od_060505067.csv
  Files/quest_00170790.csv
  Misc/actor_name.csv
  Orders/Io/co02039108.csv
  Orders/Xie/Anniversary/8th/co06050505.csv
  Orders/Xie/Anniversary/8th/co06050506.csv
  Quests/Limited Quests/Enhancer/cm_069101.csv
  Quests/Limited Quests/Enhancer/cm_069102.csv
  Quests/Limited Quests/Enhancer/cm_069103.csv
  Quests/Limited Quests/Enhancer/cm_069104.csv
  Quests/Limited Quests/Enhancer/cm_069105.csv
  Quests/Limited Quests/Enhancer/cm_069106.csv
  Quests/Limited Quests/Enhancer/cm_069107.csv
  Quests/Limited Quests/Enhancer/cm_069108.csv
  Quests/Limited Quests/Enhancer/cm_069109.csv
  Quests/Limited Quests/Enhancer/cm_069110.csv
  Quests/Limited Quests/Enhancer/cm_069111.csv
  Quests/Limited Quests/Enhancer/cm_069112.csv
  Quests/Limited Quests/Enhancer/quest_00080450.csv
  Quests/Limited Quests/Enhancer/quest_00170840.csv
  Quests/Primordial Darkness/quest_00051160.csv
  Quests/Primordial Darkness/quest_00170830.csv
  Quests/Seasonal/Beach 2020/quest_00051170.csv
  Quests/Seasonal/Beach 2020/quest_00170810.csv
  Quests/VR Planet/quest_00170790.csv
  UI/item_element_expl.csv
  UI/item_element_name.csv
  UI/ui_item.csv
  UI/ui_tips.csv
Labels: size/XXL

#1113 KO: Xie's client order
  Files/co06050505.csv
  Files/co06050506.csv
  Files/od_060505051.csv
  Files/od_060505057.csv
  Files/od_060505061.csv
  Files/od_060505067.csv
  NPC/Xie/Anniversary/8th/co06050505.csv
  NPC/Xie/Anniversary/8th/co06050506.csv
  NPC/Xie/Anniversary/8th/od_060505051.csv
  NPC/Xie/Anniversary/8th/od_060505057.csv
  NPC/Xie/Anniversary/8th/od_060505061.csv
  NPC/Xie/Anniversary/8th/od_060505067.csv
  Quests/Limited Quest/Anniversary/8th/2nd/quest_00080450.csv
  Quests/Limited Quest/Anniversary/8th/2nd/quest_00170840.csv
Labels: size/M

#1115 KO: fix Xie's orders
  NPC/Xie/Anniversary/8th/co06050505.csv
  NPC/Xie/Anniversary/8th/co06050506.csv
Labels: size/XS

#1117 Shorten description so Guardians isn't cut off.
  Quests/Story EP6 names/Chapter 3/quest_00301850.csv
Labels: size/XS

#1119 KO: EP6 Prologue and TA quest
  Files/quest_00040010.csv
  Files/quest_00040020.csv
  Files/quest_00040030.csv
  Files/quest_00040040.csv
  Files/quest_00040050.csv
  Files/quest_00040060.csv
  Files/quest_00040070.csv
  Quests/Time Attack/quest_00040010.csv
  Quests/Time Attack/quest_00040020.csv
  Quests/Time Attack/quest_00040030.csv
  Quests/Time Attack/quest_00040040.csv
  Quests/Time Attack/quest_00040050.csv
  Quests/Time Attack/quest_00040060.csv
  Quests/Time Attack/quest_00040070.csv
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/st_061010.csv
Labels: size/L

#1120 KO: EP6 Prologue stuff
  Files/quest_00301400.csv
  Quests/Story EP6 names/Chapter 0/quest_00301400.csv
  Story/Episode 6/Chapter 0/st_061010.csv
Labels: size/M

#1118 Various fixes.
  Misc/actor_name.csv
  Orders/Koffie/co06010001.csv
  Story/Episode 2/st_025060.csv
  Translated/Dialogue/Klotho/od_010318091.csv
  Tutorial/Arks Road/Talk/ar_talk_or011401.csv
  Tutorial/Window Help/wh_recommend.csv
  UI/quest_counter.csv
  UI/ui_craft.csv
  UI/ui_gat.csv
  UI/ui_item.csv
Labels: size/M

#1121 Fix missed s.
  UI/ui_item.csv
Labels: size/XS

#1122 Fix EP1 Ch3 typo.
  Story/Episode 1/Chapter 4/ra_010330.csv
Labels: size/XS

#1123 KO: EP6 Chapter 0 Translation
  Files/st_061015.csv
  NPC/Saga/co03071004.csv
  Quests/Story EP6 names/Chapter 0/quest_00301400.csv
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/Chapter 0/st_061015.csv
Labels: size/M

#1124 KO: EP6 Story translation
  Files/st_061020.csv
  Quests/Story EP6 names/Chapter 0/quest_00301400.csv
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/Chapter 0/st_061020.csv
  Story/Episode 6/Chapter 0/st_061030.csv
  Story/Episode 6/Chapter 0/st_061040.csv
Labels: size/M

#1125 KO: EP6 Story translation
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/Chapter 0/st_061020.csv
  Story/Episode 6/Chapter 0/st_061030.csv
  Story/Episode 6/Chapter 0/st_061040.csv
Labels: size/M

#1126 Fix typo with LQ 2.
  Quests/Limited Quests/Enhancer/cm_069102.csv
  Quests/Limited Quests/Enhancer/cm_069104.csv
  Quests/Limited Quests/Enhancer/cm_069106.csv
  Quests/Limited Quests/Enhancer/cm_069108.csv
  Quests/Limited Quests/Enhancer/cm_069111.csv
Labels: size/S

#1127 Fix Salon Pass and Color Change Pass.
  UI/ui_billing_direct.csv
  UI/ui_esthetic_text.csv
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/M

#1128 Fix Dark Falz Persona mentions.
  UI/ui_quest.csv
Labels: size/XS
