Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-12, with the labels that each got.

#1279 KO: minor updates
  Arks Mission/Event/Limited Mission/ac06032141.csv
  Arks Mission/Event/Limited Mission/ac06032142.csv
  Arks Mission/Event/Limited Mission/ac06032152.csv
  Dialogue/E-Trial/ii_ssn_apc_ev_nyau_5150.csv
  Dialogue/E-Trial/ii_ssn_apc_ev_rare_5150.csv
  Files/np_012130.csv
  NPC/Koffie/Order/co01010001.csv
  NPC/Koffie/Order/co05010235.csv
  NPC/Koffie/Order/co06010005.csv
  NPC/Koffie/Order/co06010015.csv
  NPC/Koffie/Order/co06010024.csv
  NPC/Marlu/Order/co01020014.csv
  NPC/Master nezumi/E trial/ii_session_apc_5376.csv
  NPC/Matoi/Dialogue/np_012130.csv
  NPC/RINA/E trial/ii_session_apc_5314.csv
  NPC/RINA/E trial/ii_session_apc_5327.csv
  NPC/SORO/E trial/ii_session_apc_5386.csv
  NPC/Xie/Anniversary/8th/co06050505.csv
  NPC/Xie/Anniversary/8th/np_010970.csv
  NPC/Xie/Anniversary/8th/od_060505037.csv
  NPC/Xie/Anniversary/8th/od_060505061.csv
  Story/Episode 3/Chapter 1/un_031100.csv
  Story/Episode 6/Chapter 0/st_061030.csv
  Story/Episode 6/Chapter 6/st_065070.csv
  UI/ui_mainmode.csv
Labels: size/L

#1280 KO: additional translation
  Quests/Limited Quest/Anniversary/8th/2nd/quest_00170840.csv
  Quests/Seasonal/Xmas 2020/quest_00051230.csv
  Quests/quest_counter.csv
  UI/common.csv
  UI/item_element_expl.csv
  UI/item_element_name.csv
  UI/ui_item.csv
  UI/ui_lobbymap.csv
Labels: size/XXL

#1281 KO: fix typo
  Dialogue/E-Trial/heatup.csv
  Files/cm_038001_120020.csv
  Files/quest_00120020.csv
  Misc/actor_name.csv
  NPC/Koffie/Dialogue/Talk/np_010500.csv
  NPC/Magical Robo/Order/od_060650017.csv
  Quests/Challenge Quests/3 Cataclysm/cm_038001_120020.csv
  Quests/Challenge Quests/3 Cataclysm/quest_00120020.csv
  Quests/quest_common.csv
  Quests/quest_counter.csv
  Story/Episode 1/st_010150.csv
  Story/Episode 1/st_010150_fs.csv
  Story/Episode 3/Chapter 1/ra_031020.csv
  Story/Episode 3/Chapter 1/ra_031040.csv
  Story/Episode 3/Chapter 1/st_030100.csv
  Story/Episode 3/Chapter 1/st_030100_om.csv
  Story/Episode 3/Chapter 1/st_031010.csv
  Story/Episode 3/Chapter 1/un_031010.csv
  Story/Episode 3/Chapter 1/un_031040.csv
  Story/Episode 3/Chapter 1/un_031060.csv
  Story/Episode 3/Chapter 1/un_031070.csv
  Story/Episode 3/Chapter 1/un_031070_om.csv
  UI/ui_mainmode.csv
Labels: size/L

#1282 KO: Fix Story
  NPC/Kyokuya/co06033203.csv
  NPC/Kyokuya/co06033205.csv
  NPC/Kyokuya/co06033211.csv
  NPC/Marlu/Order/co01020016.csv
  NPC/Saga/co03071000.csv
  NPC/Saga/co03071002.csv
  NPC/Saga/co03071005.csv
  NPC/Saga/co03071010.csv
  Quests/Challenge Quests/3 Cataclysm/quest_00120020.csv
  Story/Episode 0/st_010030.csv
  Story/Episode 0/st_010030_fs.csv
  Story/Episode 0/st_010040.csv
  Story/Episode 0/st_010090.csv
  Story/Episode 0/st_010100.csv
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/Chapter 0/st_061015.csv
Labels: size/L

#1283 KO: fix typo
  UI/ui_item.csv
Labels: size/XS

#1284 KO: Fix typo
  Arks Mission/Star Mission/ac06050503.csv
  Arks Mission/Weekly/ac06020110.csv
  Quests/Mourning/cm_069411.csv
  Quests/Seasonal/viva lasVegas/quest_00051190.csv
  Quests/Seasonal/viva lasVegas/quest_00170870.csv
  Quests/quest_common.csv
  Quests/quest_counter.csv
  Tutorial/Window Help/wh_tl_co_011020.csv
  Tutorial/Window Help/wh_tl_co_031385.csv
  UI/item_element_expl.csv
  UI/ui_craft.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
  UI/ui_quest.csv
Labels: size/L

#1286 KO: fix typo
  Files/co06065704.csv
  Files/np_npc_664.csv
  Files/np_npc_665.csv
  NPC/Kirito&Asuna/co06065701.csv
  NPC/Kirito&Asuna/co06065702.csv
  NPC/Kirito&Asuna/co06065703.csv
  NPC/Kirito&Asuna/co06065704.csv
  NPC/Kirito&Asuna/co06065705.csv
  NPC/Kirito&Asuna/np_016640.csv
  NPC/Kirito&Asuna/np_016650.csv
  NPC/Kirito&Asuna/np_npc_664.csv
  NPC/Kirito&Asuna/np_npc_665.csv
  NPC/Kirito&Asuna/od_060657011.csv
  NPC/Kirito&Asuna/od_060657017.csv
  NPC/Kirito&Asuna/od_060657021.csv
  NPC/Kirito&Asuna/od_060657027.csv
  NPC/Kirito&Asuna/od_060657031.csv
  NPC/Kirito&Asuna/od_060657037.csv
  NPC/Kirito&Asuna/od_060657041.csv
  NPC/Kirito&Asuna/od_060657047.csv
  NPC/Kirito&Asuna/od_060657057.csv
  NPC/Kirito&Asuna/od_060657061.csv
  NPC/Kirito&Asuna/od_060657067.csv
  NPC/Kirito&Asuna/od_060657081.csv
  NPC/Kirito&Asuna/om_060657053.csv
  Quests/quest_counter.csv
  UI/apc_name.csv
  UI/item_element_name.csv
  UI/ui_amusement.csv
  UI/ui_item.csv
Labels: size/XL

#1287 KO fix typo
  Files/co06065706.csv
  NPC/Kirito&Asuna/co06065704.csv
  NPC/Kirito&Asuna/co06065706.csv
  NPC/Kirito&Asuna/np_016650.csv
  NPC/Kirito&Asuna/od_060657047.csv
  NPC/Kirito&Asuna/od_060657051.csv
  NPC/Kirito&Asuna/od_060657057.csv
  UI/item_element_expl.csv
Labels: size/S

#1288 ES: Corrected translation
  Story/Episode 6/cap5/st_064060.csv
Labels: size/S

#1289 KO: translation SAO
  Dialogue/E-Trial/ii_areaboss_df.csv
  Dialogue/Kyokuya/np_015660.csv
  Dialogue/Lucotte/np_015700.csv
  Dialogue/Stratos/np_014370.csv
  Files/co06065707.csv
  Files/co06065708.csv
  NPC/Kirito&Asuna/co06065706.csv
  NPC/Kirito&Asuna/co06065707.csv
  NPC/Kirito&Asuna/co06065708.csv
  NPC/Kirito&Asuna/np_016640.csv
  NPC/Kirito&Asuna/np_016650.csv
  NPC/Kirito&Asuna/np_npc_665.csv
  NPC/Kirito&Asuna/od_060657061.csv
  NPC/Kirito&Asuna/od_060657067.csv
  NPC/Kirito&Asuna/od_060657071.csv
  NPC/Kirito&Asuna/od_060657077.csv
  NPC/Kirito&Asuna/od_060657081.csv
  NPC/Kirito&Asuna/od_060657087.csv
  NPC/Kirito&Asuna/om_060657073.csv
  NPC/Kirito&Asuna/pr_068020.csv
  NPC/Kirito&Asuna/pr_068030.csv
  NPC/Kirito&Asuna/pr_068040.csv
Labels: size/L

#1290 KO: Fix typo
  NPC/Kirito&Asuna/co06065708.csv
  NPC/Kirito&Asuna/np_016640.csv
  NPC/Kirito&Asuna/np_016650.csv
  NPC/Kirito&Asuna/od_060657021.csv
  NPC/Kirito&Asuna/od_060657027.csv
  Quests/Divide Quest/quest_00220570.csv
Labels: size/S

#1291 KO: fix typo
  UI/ui_item.csv
Labels: size/XS

#1292 KO: fix typo
  Files/cm_069200.csv
  Files/cm_069606.csv
  Files/cm_069607.csv
  Files/cm_069608.csv
  Files/cm_069609.csv
  Files/cm_069617.csv
  Files/cm_069618.csv
  Files/cm_069619.csv
  Files/cm_069624.csv
  Files/cm_069625.csv
  Files/cm_069626.csv
  Files/cm_069627.csv
  Files/cm_069628.csv
  Files/co_060072.csv
  Files/mp_000572.csv
  NPC/Kirito&Asuna/co06065705.csv
  NPC/Kirito&Asuna/co06065708.csv
  NPC/Kirito&Asuna/np_016650.csv
  NPC/Kirito&Asuna/od_060657067.csv
  NPC/Kirito&Asuna/pr_068040.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069200.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069606.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069607.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069608.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069609.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069617.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069618.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069619.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069624.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069625.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069626.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069627.csv
  Quests/Challenge Quests/3 Cataclysm/cm_069628.csv
  Quests/Challenge Quests/3 Cataclysm/co_060072.csv
  Quests/Challenge Quests/3 Cataclysm/mp_000572.csv
  Quests/Challenge Quests/3 Cataclysm/quest_00120020.csv
  Quests/quest_common.csv
  UI/ui_challenge.csv
Labels: size/M

#1293 KO: fix typo
  Misc/Concert/ls_010025.csv
  Misc/Concert/ls_010080.csv
  Quests/Challenge Quests/3 Cataclysm/co_060072.csv
  Quests/Challenge Quests/3 Cataclysm/mp_000572.csv
Labels: size/M

#1294 KO: fix typo
  Quests/Challenge Quests/3 Cataclysm/co_060072.csv
  Quests/Challenge Quests/3 Cataclysm/mp_000572.csv
  Quests/Challenge Quests/3 Cataclysm/quest_00120020.csv
  UI/ui_charamake_parts.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
Labels: size/XL

#1295 KO: fix typo
  Dialogue/E-Trial/ii_cleanup_shell_flower.csv
  Misc/actor_name.csv
  UI/ui_mainmode.csv
Labels: size/XS
