Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-02, with the labels that each got.

#946 EN: Variety pack
  Files/cm_065000.csv
  Files/cm_065001.csv
  Files/cm_065002.csv
  Files/cm_065003.csv
  Files/cm_065004.csv
  Files/un_036040.csv
  Misc/actor_name.csv
  Orders/_Bingo/bo00002267.csv
  Quests/Damage Tally/cm_065000.csv
  Quests/Damage Tally/cm_065001.csv
  Quests/Damage Tally/cm_065002.csv
  Quests/Damage Tally/cm_065003.csv
  Quests/Damage Tally/cm_065004.csv
  Quests/Damage Tally/co_063100.csv
  Quests/Endless Quest/2 Eternal Rondo/cm_057056.csv
  Quests/Endless Quest/2 Eternal Rondo/cm_057057.csv
  Quests/Limited Quests/Revelry of Darkness/cm_0511100.csv
  Quests/Limited Quests/Revelry of Darkness/cm_0511103.csv
  Quests/Limited Quests/Revelry of Darkness/cm_0511120.csv
  Quests/Story EP3 names/Chapter 4/quest_00703270.csv
  Quests/Story EP5 names/Chapter 4/quest_00300940.csv
  Story/Episode 3/un_036040.csv
  UI/item_element_name.csv
  UI/quest_common.csv
  UI/ui_item.csv
  _aspell/PSO2.en_Enemies_Darkers.dict
Labels: size/M

#947 EN: a few fixes for the buildbot
  Dialogue/Mid-Mission/ii_js_apc_boss_5032.csv
Labels: size/XS

#948 ES: a few things to fix the buildbot
  Dialogue/Mid-Mission/ii_js_apc_boss_5032.csv
Labels: size/XS

#950 EN: Valentine's cleanup
  Dialogue/Stratos/np_014370.csv
  Dialogue/Xiera/co_060513.csv
  Files/co_060513.csv
  Orders/Koffie/co01010001.csv
  Orders/Kyokuya (White Day)/co06064803.csv
  Orders/Stratos (V-day)/co06064701.csv
  Orders/Stratos (V-day)/co06064703.csv
  Orders/Stratos (V-day)/co06064704.csv
  Quests/Seasonal/Choco 2020/cm_065157.csv
  UI/common.csv
  _aspell/PSO2.en_Enemies_Dragonkin.dict
  _aspell/PSO2.en_Items.dict
  _aspell/PSO2.en_Misc.dict
  _aspell/PSO2.en_Names.dict
Labels: size/M

#951 EN: Added missing comma for Rarity Evolution hint.
  Quests/Seasonal/Choco 2020/cm_065158.csv
  UI/ui_pet.csv
Labels: size/XS

#952 Es: Camara
  UI/ui_selectmenu_text.csv
Labels: size/M

#953 Manually wrap text for Video Sound Volume for Vita
  UI/config.csv
Labels: size/XS

#954 Fix missing punctuation inconsistencies in some menu titles.
  UI/ui_title_text.csv
Labels: size/XS

#955 EN: Couple of tiny fixes
  Misc/actor_name.csv
  UI/common.csv
Labels: size/XS

#956 EN: translation of Lucotte stuff
  Files/un_063030.csv
  Files/un_063040.csv
  Files/un_063050.csv
  Files/un_063060.csv
  Files/un_063090.csv
  Files/un_064070.csv
  Files/un_064080.csv
  Files/un_064090.csv
  Story/Episode 6/un_063030.csv
  Story/Episode 6/un_063040.csv
  Story/Episode 6/un_063050.csv
  Story/Episode 6/un_063060.csv
  Story/Episode 6/un_063090.csv
  Story/Episode 6/un_064070.csv
  Story/Episode 6/un_064080.csv
  Story/Episode 6/un_064090.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/XL

#961 EN: CO stuff
  Dialogue/Hans/np_npc_52.csv
  Dialogue/Hans/od_010403041.csv
  Dialogue/Hans/od_010403043.csv
  Dialogue/Hans/od_010403047.csv
  Dialogue/Hans/od_010403321.csv
  Dialogue/Hans/od_010403323.csv
  Dialogue/Hans/od_010403324.csv
  Dialogue/Hans/od_010403327.csv
  Dialogue/Hans/od_020403201.csv
  Dialogue/Hans/od_020403207.csv
  Dialogue/Hans/od_050403911.csv
  Dialogue/Hans/od_050403917.csv
  Dialogue/Hans/od_060403011.csv
  Dialogue/Hans/od_060403017.csv
  Dialogue/Theodore/np_010270.csv
  Dialogue/Xion/np_010050.csv
  Files/od_020403201.csv
  Files/od_020403207.csv
  Files/od_050403911.csv
  Files/od_050403917.csv
  Files/od_060403011.csv
  Files/od_060403017.csv
  Orders/Hans/co01040300.csv
  Orders/Hans/co01040301.csv
  Orders/Hans/co01040302.csv
  Orders/Hans/co01040303.csv
  Orders/Hans/co01040304.csv
  Orders/Hans/co01040305.csv
  Orders/Hans/co01040306.csv
  Orders/Hans/co01040307.csv
  Orders/Hans/co01040310.csv
  Orders/Hans/co01040311.csv
  Orders/Hans/co01040312.csv
  Orders/Hans/co01040313.csv
  Orders/Hans/co01040314.csv
  Orders/Hans/co01040315.csv
  Orders/Hans/co01040316.csv
  Orders/Hans/co01040332.csv
  Orders/Hans/co02040320.csv
  Orders/Hans/co05040391.csv
  Orders/Hans/co05040392.csv
  Orders/_Bingo/bo00002312.csv
  Translated/Dialogue/Hans/od_010403041.csv
  Translated/Dialogue/Hans/od_010403043.csv
  Translated/Dialogue/Hans/od_010403047.csv
  Translated/Dialogue/Hans/od_010403321.csv
  Translated/Dialogue/Hans/od_010403327.csv
  Translated/Dialogue/Xion/np_010050.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/L

#962 EN: New LQ
  Dialogue/Mid-Mission/ii_areaboss.csv
  Dialogue/Mid-Mission/ii_areaboss_dk.csv
  Files/cm_067000.csv
  Files/cm_067001.csv
  Files/cm_067003.csv
  Files/cm_067004.csv
  Files/cm_067005.csv
  Files/cm_067006.csv
  Files/cm_067007.csv
  Files/cm_067009.csv
  Files/cm_067010.csv
  Files/cm_067011.csv
  Files/cm_067012.csv
  Files/cm_067013.csv
  Files/cm_067014.csv
  Files/cm_067015.csv
  Files/cm_067016.csv
  Files/cm_067017.csv
  Files/cm_067018.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067000.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067001.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067002.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067003.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067004.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067005.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067006.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067007.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067008.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067009.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067010.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067011.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067012.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067013.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067014.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067015.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067016.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067017.csv
  Quests/Limited Quests/Piper of Disharmony/cm_067018.csv
Labels: size/L

#964 EN: Probably White Day 2020 dialogue
  Files/cm_065160.csv
  Files/cm_065161.csv
  Files/cm_065162.csv
  Files/cm_065163.csv
  Files/cm_065164.csv
  Files/cm_065165.csv
  Files/cm_065166.csv
  Quests/Seasonal/White Day 2020/cm_065160.csv
  Quests/Seasonal/White Day 2020/cm_065161.csv
  Quests/Seasonal/White Day 2020/cm_065162.csv
  Quests/Seasonal/White Day 2020/cm_065163.csv
  Quests/Seasonal/White Day 2020/cm_065164.csv
  Quests/Seasonal/White Day 2020/cm_065165.csv
  Quests/Seasonal/White Day 2020/cm_065166.csv
  UI/ui_mainmode.csv
Labels: size/M

#965 Minor optional dialogue for Hitsugi in Ep. 4
  Dialogue/Hitsugi/np_012970.csv
Labels: size/XS

#966 EN: Lobby Action fixes
  UI/common.csv
Labels: size/S

#968 EN: DO capitalisation consistency
  Orders/_Daily/do01030000.csv
  Orders/_Daily/do01030002.csv
  Orders/_Daily/do01030004.csv
  Orders/_Daily/do01030006.csv
  Orders/_Daily/do01030102.csv
  Orders/_Daily/do04030101.csv
  Orders/_Daily/do04030200.csv
  Orders/_Daily/do04030201.csv
  Orders/_Daily/do04030202.csv
  Orders/_Daily/do04030203.csv
  Orders/_Daily/do04030204.csv
  Orders/_Daily/do06301001.csv
  Orders/_Daily/do06301002.csv
Labels: size/S

#969 EN: Hans Caves COs
  Dialogue/Hans/od_010403081.csv
  Dialogue/Hans/od_010403083.csv
  Dialogue/Hans/od_010403087.csv
  Dialogue/Hans/od_010403091.csv
  Dialogue/Hans/od_010403093.csv
  Dialogue/Hans/od_010403097.csv
  Dialogue/Hans/od_010403211.csv
  Dialogue/Hans/od_010403213.csv
  Dialogue/Hans/od_010403217.csv
  Dialogue/Hans/od_050403921.csv
  Dialogue/Hans/od_050403927.csv
  Files/od_050403921.csv
  Files/od_050403927.csv
  Orders/Hans/co01040308.csv
  Orders/Hans/co01040309.csv
  Orders/Hans/co02040321.csv
  Orders/Hans/co05040392.csv
  Translated/Dialogue/Hans/od_010403081.csv
  Translated/Dialogue/Hans/od_010403083.csv
  Translated/Dialogue/Hans/od_010403087.csv
  Translated/Dialogue/Hans/od_010403091.csv
  Translated/Dialogue/Hans/od_010403097.csv
  Translated/Dialogue/Hans/od_010403211.csv
  Translated/Dialogue/Hans/od_010403213.csv
  Translated/Dialogue/Hans/od_010403217.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/M

#970 EN: Couple of small things
  Dialogue/Barbara/od_010424401.csv
  Dialogue/Barbara/od_010424407.csv
  Orders/Barbara/co01042440.csv
  Orders/Hans/co02040321.csv
  Orders/Hans/co05040392.csv
  Translated/Dialogue/Barbara/od_010424401.csv
  Translated/Dialogue/Barbara/od_010424407.csv
Labels: size/S

#972 EN: Minor CO fixes
  Orders/Hans/co01040309.csv
  Orders/_Daily/do01020101.csv
  Orders/_Daily/do01020103.csv
  Orders/_Daily/do01020105.csv
  Orders/_Daily/do01020107.csv
  Orders/_Daily/do01020201.csv
  Orders/_Daily/do01020203.csv
  Orders/_Daily/do01020205.csv
  Orders/_Daily/do01020207.csv
  Orders/_Daily/do01020301.csv
  Orders/_Daily/do01020303.csv
  Orders/_Daily/do01020305.csv
  Orders/_Daily/do01020307.csv
  Orders/_Daily/do01020309.csv
  Orders/_Daily/do01020311.csv
  Orders/_Daily/do01020313.csv
  Orders/_Daily/do01020315.csv
  Orders/_Daily/do01020316.csv
  Orders/_Daily/do01020317.csv
  Orders/_Daily/do01020319.csv
  Orders/_Daily/do01020400.csv
  Orders/_Daily/do01020401.csv
  Orders/_Daily/do01020402.csv
  Orders/_Daily/do01020403.csv
  Orders/_Daily/do01020404.csv
  Orders/_Daily/do01020405.csv
  Orders/_Daily/do01020406.csv
  Orders/_Daily/do01020407.csv
  Orders/_Daily/do01020408.csv
  Orders/_Daily/do01020409.csv
  Orders/_Daily/do01020410.csv
  Orders/_Daily/do01020411.csv
  Orders/_Daily/do01020412.csv
  Orders/_Daily/do01020413.csv
  Orders/_Daily/do01020500.csv
  Orders/_Daily/do01020501.csv
  Orders/_Daily/do01020502.csv
  Orders/_Daily/do01020503.csv
  Orders/_Daily/do01020504.csv
  Orders/_Daily/do01020505.csv
  Orders/_Daily/do01020506.csv
  Orders/_Daily/do01020507.csv
  Orders/_Daily/do01020508.csv
  Orders/_Daily/do01020509.csv
  Orders/_Daily/do01020510.csv
  Orders/_Daily/do01020511.csv
  Orders/_Daily/do01020512.csv
  Orders/_Daily/do01020513.csv
  Orders/_Daily/do01020514.csv
Labels: size/M
