Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-10, with the labels that each got.

#1246 KO: Additional Translation
  Dialogue/E-Trial/ii_mep_annihilation.csv
  Files/co06065201.csv
  Files/co06065202.csv
  Files/co06065203.csv
  Files/co06065204.csv
  Files/co06065205.csv
  Files/co06065206.csv
  Files/co06065207.csv
  Misc/Concert/ls_010020.csv
  Misc/actor_name.csv
  NPC/Weaponoids/co06065201.csv
  NPC/Weaponoids/co06065202.csv
  NPC/Weaponoids/co06065203.csv
  NPC/Weaponoids/co06065204.csv
  NPC/Weaponoids/co06065205.csv
  NPC/Weaponoids/co06065206.csv
  NPC/Weaponoids/co06065207.csv
  Quests/Seasonal/viva lasVegas/cm_060506.csv
  Quests/Seasonal/viva lasVegas/cm_060507.csv
  Quests/Seasonal/viva lasVegas/cm_060508.csv
  Quests/Seasonal/viva lasVegas/cm_060509.csv
  Quests/Seasonal/viva lasVegas/cm_060510.csv
  Quests/Seasonal/viva lasVegas/cm_060511.csv
  Quests/Seasonal/viva lasVegas/cm_060512.csv
  Quests/Seasonal/viva lasVegas/cm_060513.csv
  Quests/Seasonal/viva lasVegas/co_060043.csv
  Quests/Seasonal/viva lasVegas/mp_000564.csv
  Quests/Seasonal/viva lasVegas/quest_00051190.csv
  Quests/Seasonal/viva lasVegas/quest_00170870.csv
  UI/ui_charamake_parts.csv
Labels: size/M

#1248 KO:fix typo
  NPC/Weaponoids/co06065202.csv
  NPC/Weaponoids/co06065205.csv
  Quests/Buster Quests/quest_00050750.csv
  Quests/Seasonal/viva lasVegas/quest_00051190.csv
  Quests/quest_common.csv
  Story/Episode 6/Chapter 2/cm_062221_01.csv
  Story/Episode 6/Chapter 2/cm_062233_01.csv
  Story/Episode 6/Chapter 3/cm_064100.csv
  Story/Episode 6/Chapter 3/cm_064103.csv
  Story/Episode 6/Chapter 3/cm_064107.csv
  Story/Episode 6/Chapter 3/cm_064201.csv
  Story/Episode 6/Chapter 4/cm_064400.csv
  Story/Episode 6/Chapter 4/cm_064421.csv
  Story/Episode 6/Chapter 4/cm_064422.csv
  Story/Episode 6/Chapter 4/cm_064423.csv
  Story/Episode 6/Chapter 4/cm_064424.csv
  Story/Episode 6/Chapter 5/cm_062507.csv
Labels: size/M

#1250 KO: fix typo
  Dialogue/E-Trial/ii_anh_phantom_ship.csv
  Dialogue/E-Trial/ii_areaboss.csv
  Dialogue/E-Trial/ii_areaboss_db.csv
  Dialogue/E-Trial/ii_areaboss_dk.csv
  Dialogue/E-Trial/ii_areaboss_dp.csv
  Dialogue/E-Trial/ii_areaboss_dp2.csv
  Dialogue/E-Trial/ii_areaboss_dp_toy.csv
  Dialogue/E-Trial/ii_areaboss_neo.csv
  Dialogue/E-Trial/ii_defense_from_mge.csv
  Misc/actor_name.csv
  NPC/Weaponoids/co06065202.csv
  Story/Episode 6/Chapter 6/Quest Message/cm_062613.csv
  UI/ui_mainmode.csv
Labels: size/L

#1252 KO: fix ex order
  Dialogue/E-Trial/incident_common.csv
  Misc/Concert/ls_010020.csv
  Quests/Dark Falz/Elder/quest_00050170.csv
  UI/ui_pet.csv
  UI/ui_petlabo.csv
Labels: size/L

#1254 KO: new EQ translation
  Dialogue/E-Trial/ii_areaboss_ap.csv
  Files/quest_00051200.csv
  Files/quest_00100010.csv
  Files/quest_00170000.csv
  Files/quest_00170010.csv
  Files/quest_00170880.csv
  Misc/Concert/ls_010010.csv
  Misc/Concert/ls_010020.csv
  NPC/SORO/E trial/ii_session_apc_5315.csv
  Quests/Base Defense/quest_00100010.csv
  Quests/Base Defense/quest_00100060.csv
  Quests/Base Defense/quest_00170010.csv
  Quests/Dark Falz/Elder/quest_00170000.csv
  Quests/Divide Quest/cm_068003.csv
  Quests/Mourning/quest_00051200.csv
  Quests/Mourning/quest_00170880.csv
Labels: size/L

#1253 Episode 3 mid-mission dialogue
  Dialogue/Mid-Mission/ii_session_apc_5019.csv
  Dialogue/Mid-Mission/ii_session_apc_5020.csv
  Dialogue/Mid-Mission/ii_session_apc_5026.csv
  Files/ii_session_apc_5026.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/M

#1255 KO: translate CO
  Files/co06065301.csv
  Files/co06065302.csv
  Files/quest_00051140.csv
  Files/quest_00170760.csv
  Misc/actor_name.csv
  NPC/Sighx & Ecru/co06065301.csv
  NPC/Sighx & Ecru/co06065302.csv
  Quests/Seasonal/Easter 2020/quest_00051140.csv
  Quests/Seasonal/Easter 2020/quest_00170760.csv
Labels: size/M

#1257 untranslated lisa CO
  Orders/Lisa/co01011201.csv
Labels: size/XS

#1259 more lisa COs
  Dialogue/Lisa/od_030326021.csv
  Dialogue/Lisa/od_030326027.csv
  Dialogue/Lisa/od_030326031.csv
  Dialogue/Lisa/od_030326037.csv
  Dialogue/Lisa/od_030326041.csv
  Dialogue/Lisa/od_030326047.csv
  Dialogue/Lisa/od_030326051.csv
  Dialogue/Lisa/od_030326057.csv
  Dialogue/Lisa/od_030326061.csv
  Dialogue/Lisa/od_030326067.csv
  Dialogue/Lisa/od_030326071.csv
  Dialogue/Lisa/od_030326077.csv
  Dialogue/Lisa/od_030326081.csv
  Dialogue/Lisa/od_030326087.csv
  Dialogue/Lisa/od_030326091.csv
  Dialogue/Lisa/od_030326097.csv
  Files/od_030326021.csv
  Files/od_030326027.csv
  Files/od_030326031.csv
  Files/od_030326037.csv
  Files/od_030326041.csv
  Files/od_030326047.csv
  Files/od_030326051.csv
  Files/od_030326057.csv
  Files/od_030326061.csv
  Files/od_030326067.csv
  Files/od_030326071.csv
  Files/od_030326077.csv
  Files/od_030326081.csv
  Files/od_030326087.csv
  Files/od_030326091.csv
  Files/od_030326097.csv
  Orders/Lisa/co03032602.csv
  Orders/Lisa/co03032603.csv
  Orders/Lisa/co03032604.csv
  Orders/Lisa/co03032605.csv
  Orders/Lisa/co03032606.csv
  Orders/Lisa/co03032607.csv
  Orders/Lisa/co03032608.csv
  Orders/Lisa/co03032609.csv
Labels: size/L

#1258 KO: fix typo
  Files/cm_056016.csv
  Files/cm_065160.csv
  Files/cm_065161.csv
  Files/cm_065162.csv
  Files/cm_065163.csv
  Files/cm_065164.csv
  Files/cm_065165.csv
  Files/cm_065166.csv
  Files/ii_session_apc_5629.csv
  Files/ii_session_apc_5630.csv
  Files/quest_00051130.csv
  Files/quest_00170740.csv
  Misc/Concert/bd_010010.csv
  NPC/Lisa/E trial/ii_session_apc_5026.csv
  NPC/Sighx & Ecru/co06065301.csv
  Quests/Mourning/cm_069402.csv
  Quests/Mourning/cm_069405.csv
  Quests/Mourning/cm_069407.csv
  Quests/Mourning/cm_069408.csv
  Quests/Mourning/cm_069409.csv
  Quests/Mourning/cm_069410.csv
  Quests/Mourning/quest_00051200.csv
  Quests/Mourning/quest_00170880.csv
  Quests/Seasonal/Easter 2020/cm_056016.csv
  Quests/Seasonal/Rain 2020/cm_064500.csv
  Quests/Seasonal/Rain 2020/cm_064501.csv
  Quests/Seasonal/White Day 2020/cm_065160.csv
  Quests/Seasonal/White Day 2020/cm_065161.csv
  Quests/Seasonal/White Day 2020/cm_065162.csv
  Quests/Seasonal/White Day 2020/cm_065163.csv
  Quests/Seasonal/White Day 2020/cm_065164.csv
  Quests/Seasonal/White Day 2020/cm_065165.csv
  Quests/Seasonal/White Day 2020/cm_065166.csv
  Quests/Seasonal/White Day 2020/ii_session_apc_5629.csv
  Quests/Seasonal/White Day 2020/ii_session_apc_5630.csv
  Quests/Seasonal/White Day 2020/quest_00051130.csv
  Quests/Seasonal/White Day 2020/quest_00170740.csv
  Quests/quest_common.csv
  UI/item_element_expl.csv
  UI/ui_item.csv
Labels: size/M

#1261 Fix weapon library and title categories.
  Misc/actor_name.csv
  Quests/Mother/co_040107.csv
  Tutorial/Dialogue/co_031439.csv
  Tutorial/Tutorial List/wh_tl_co_031439.csv
  Tutorial/Tutorial List/wh_tl_co_040107.csv
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/S

#1264 KO: Fix Co
  Files/co03071005.csv
  Files/co03071006.csv
  Files/co03071007.csv
  Files/co03071008.csv
  Files/co03071009.csv
  Files/co03071010.csv
  Files/co03071011.csv
  Files/co03071012.csv
  Files/co03071013.csv
  Files/co03071014.csv
  Files/co03071019.csv
  Files/ls_010045.csv
  Files/ls_010050.csv
  Files/ls_010060.csv
  Files/quest_00051220.csv
  Files/quest_00170900.csv
  Misc/Concert/bd_010040.csv
  Misc/Concert/ls_010045.csv
  Misc/Concert/ls_010050.csv
  Misc/Concert/ls_010060.csv
  Misc/actor_name.csv
  NPC/Saga/co03071005.csv
  NPC/Saga/co03071006.csv
  NPC/Saga/co03071007.csv
  NPC/Saga/co03071008.csv
  NPC/Saga/co03071009.csv
  NPC/Saga/co03071010.csv
  NPC/Saga/co03071011.csv
  NPC/Saga/co03071012.csv
  NPC/Saga/co03071013.csv
  NPC/Saga/co03071014.csv
  NPC/Saga/co03071019.csv
  NPC/Sarah/E trial/ii_session_apc_5293.csv
  NPC/Sighx & Ecru/co06065301.csv
  Quests/Seasonal/toritori 2020/quest_00051220.csv
  Quests/Seasonal/toritori 2020/quest_00170900.csv
  Story/Episode 3/Chapter 1/un_031040.csv
  UI/ui_charamake_parts.csv
  UI/ui_mainmode.csv
  _py/Fonts.py
Labels: size/L

#1265 Fix used terms and Buster Quest description.
  Misc/actor_name.csv
  Quests/Time Attack/Traces/quest_00040110.csv
  Story/Episode 1/un_012661.csv
  UI/quest_common.csv
  UI/quest_counter.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/S

#1266 extreme quest tutorial window and unrelated koffie dialogue
  Dialogue/Koffie/od_060100097.csv
  Dialogue/Koffie/od_060100107.csv
  Files/co_060070.csv
  Files/od_060100097.csv
  Files/od_060100107.csv
  Tutorial/Window/co_060070.csv
Labels: size/S

#1268 worlds beyond clear Karin dialogue
  Files/co_066300.csv
  Quests/Extreme Quests/co_066300.csv
Labels: size/S

#1269 KO: fix live boost
  Arks Mission/Daily/ac06010101.csv
  Arks Mission/Daily/ac06010102.csv
  Arks Mission/Daily/ac06010103.csv
  Arks Mission/Event/Limited Mission/ac06032131.csv
  Dialogue/E-Trial/ii_boss_ahl_ranking.csv
  Files/cm_069500.csv
  Files/cm_069501.csv
  Files/cm_069502.csv
  Files/cm_069503.csv
  Files/cm_069504.csv
  Files/cm_069505.csv
  Files/cm_069506.csv
  Files/cm_069507.csv
  Files/cm_069508.csv
  Files/cm_069509.csv
  Files/cm_069510.csv
  Files/cm_069511.csv
  Files/cm_069512.csv
  Files/co_011257.csv
  Misc/actor_name.csv
  NPC/Xie/트릭 오어 트릿 2020/co06050601.csv
  NPC/Xie/트릭 오어 트릿 2020/co06050602.csv
  Quests/Extreme Quests/co_011257.csv
  Quests/Seasonal/toritori 2020/cm_069500.csv
  Quests/Seasonal/toritori 2020/cm_069501.csv
  Quests/Seasonal/toritori 2020/cm_069502.csv
  Quests/Seasonal/toritori 2020/cm_069503.csv
  Quests/Seasonal/toritori 2020/cm_069504.csv
  Quests/Seasonal/toritori 2020/cm_069505.csv
  Quests/Seasonal/toritori 2020/cm_069506.csv
  Quests/Seasonal/toritori 2020/cm_069507.csv
  Quests/Seasonal/toritori 2020/cm_069508.csv
  Quests/Seasonal/toritori 2020/cm_069509.csv
  Quests/Seasonal/toritori 2020/cm_069510.csv
  Quests/Seasonal/toritori 2020/cm_069511.csv
  Quests/Seasonal/toritori 2020/cm_069512.csv
  Quests/Seasonal/toritori 2020/quest_00051220.csv
  Quests/Seasonal/toritori 2020/quest_00170900.csv
  Quests/quest_common.csv
  UI/ui_quest.csv
Labels: size/L
