Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-08, with the labels that each got.

#1129 KO: fix some words
  Quests/Free Fields/UH/quest_00020240.csv
  Quests/Limited Quest/Anniversary/8th/2nd/quest_00170840.csv
  Story/Episode 6/Chapter 0/st_061015.csv
  Story/Episode 6/Chapter 0/st_061030.csv
Labels: size/M

#1130 EN: Finish Io COs
  Dialogue/Io/od_020391081.csv
  Dialogue/Io/od_020391091.csv
  Dialogue/Io/od_020391097.csv
  Dialogue/Io/od_020391101.csv
  Dialogue/Io/od_020391107.csv
  Dialogue/Io/od_020391111.csv
  Dialogue/Io/od_020391117.csv
  Dialogue/Io/od_030391001.csv
  Dialogue/Io/od_030391007.csv
  Dialogue/Io/od_030391011.csv
  Dialogue/Io/od_030391017.csv
  Dialogue/Io/od_030391021.csv
  Dialogue/Io/od_030391027.csv
  Dialogue/Io/od_040391011.csv
  Dialogue/Io/od_040391017.csv
  Dialogue/Io/od_040391021.csv
  Dialogue/Io/od_040391027.csv
  Dialogue/_Featured rewards/cm_040000_03.csv
  Files/od_020391091.csv
  Files/od_020391097.csv
  Files/od_020391101.csv
  Files/od_020391107.csv
  Files/od_020391111.csv
  Files/od_020391117.csv
  Files/od_030391001.csv
  Files/od_030391007.csv
  Files/od_030391011.csv
  Files/od_030391017.csv
  Files/od_030391021.csv
  Files/od_030391027.csv
  Files/od_040391011.csv
  Files/od_040391017.csv
  Files/od_040391021.csv
  Files/od_040391027.csv
  Orders/Io/co02039109.csv
  Orders/Io/co02039110.csv
  Orders/Io/co02039111.csv
  Orders/Io/co03039100.csv
  Orders/Io/co03039101.csv
  Orders/Io/co03039102.csv
  Orders/Io/co04039101.csv
  Orders/Io/co04039102.csv
Labels: size/L

#1133 KO: EP6 Story Translation
  Files/st_061050.csv
  Files/st_061070.csv
  Story/Episode 6/Chapter 0/st_061020.csv
  Story/Episode 6/Chapter 0/st_061030.csv
  Story/Episode 6/Chapter 0/st_061050.csv
  Story/Episode 6/Chapter 0/st_061070.csv
Labels: size/L

#1134 KO: Story quest name & beach wars 2020
  Dialogue/E-Trial/ii_areaboss_neo.csv
  Dialogue/E-Trial/ii_boss_ahl_m_oarfish.csv
  Dialogue/E-Trial/ii_ev_different_sp_boss_ahl.csv
  Dialogue/E-Trial/ii_ev_double_sp_ahl.csv
  Files/co_060519.csv
  Files/co_060520.csv
  Files/co_060521.csv
  Files/quest_00301410.csv
  Files/quest_00301420.csv
  Files/quest_00301440.csv
  Files/quest_00301460.csv
  Files/quest_00301480.csv
  Quests/Seasonal/beach wars 2020/co_060519.csv
  Quests/Seasonal/beach wars 2020/co_060520.csv
  Quests/Seasonal/beach wars 2020/co_060521.csv
  Quests/Seasonal/beach wars 2020/quest_00051170.csv
  Quests/Seasonal/beach wars 2020/quest_00170810.csv
  Quests/Story EP6 names/Chapter 0/quest_00301410.csv
  Quests/Story EP6 names/Chapter 0/quest_00301420.csv
  Quests/Story EP6 names/Chapter 0/quest_00301440.csv
  Quests/Story EP6 names/Chapter 0/quest_00301460.csv
  Quests/Story EP6 names/Chapter 0/quest_00301470.csv
  Quests/Story EP6 names/Chapter 0/quest_00301480.csv
Labels: size/L

#1137 KO: fix ep6 ch6 fix typo
  Misc/actor_name.csv
  Story/Episode 6/Chapter 6/Quest Message/cm_062601.csv
  Story/Episode 6/Chapter 6/st_065010.csv
  Story/Episode 6/Chapter 6/st_065020.csv
  Story/Episode 6/Chapter 6/st_065030.csv
  Story/Episode 6/Chapter 6/st_065050.csv
  Story/Episode 6/Chapter 6/st_065060.csv
  Story/Episode 6/Chapter 6/st_065073.csv
  Story/Episode 6/Chapter 6/st_065083.csv
  Story/Episode 6/Chapter 6/st_065087.csv
  Story/Episode 6/Chapter 6/st_065090.csv
  Story/Episode 6/Chapter 6/st_065100.csv
  Story/Episode 6/Chapter 6/st_065119.csv
Labels: size/M

#1138 KO: fix serious typ
  Files/un_065200.csv
  NPC/Koffie/Dialogue/Talk/np_010500.csv
  Quests/Arks Quest/quest_00030290.csv
  Story/Episode 6/Chapter 6/Sub Story/un_065110.csv
  Story/Episode 6/Chapter 6/Sub Story/un_065150.csv
  Story/Episode 6/Chapter 6/Sub Story/un_065180.csv
  Story/Episode 6/Chapter 6/Sub Story/un_065190.csv
  Story/Episode 6/Chapter 6/Sub Story/un_065200.csv
Labels: size/M

#1143 KO: Additional translation
  Files/quest_00040110.csv
  Files/quest_00040120.csv
  Files/quest_00050010.csv
  Files/quest_00050020.csv
  Files/quest_00050030.csv
  Files/quest_00050035.csv
  Files/quest_00050040.csv
  Files/quest_00050050.csv
  Files/quest_00050070.csv
  Files/quest_00050130.csv
  Files/quest_00050170.csv
  Files/quest_00050180.csv
  Files/quest_00050190.csv
  Files/quest_00050200.csv
  Files/quest_00050230.csv
  Files/quest_00050270.csv
  Files/quest_00050280.csv
  Files/quest_00050290.csv
  Files/quest_00050310.csv
  Files/quest_00050330.csv
  Files/un_010400.csv
  Files/un_010400_fs.csv
  Files/un_010470.csv
  Files/un_010470_fs.csv
  Files/un_010470_om.csv
  Files/un_010540.csv
  Files/un_011250.csv
  NPC/Koffie/Dialogue/Talk/np_010500.csv
  Quests/Dark Falz/Elder/quest_00050170.csv
  Quests/Dark Falz/Elder/quest_00050180.csv
  Quests/Dark Falz/Loser/quest_00050270.csv
  Quests/Dark Falz/Loser/quest_00050280.csv
  Quests/Dark Falz/Loser/quest_00050290.csv
  Quests/Descriptions/quest_00050010.csv
  Quests/Descriptions/quest_00050020.csv
  Quests/Descriptions/quest_00050030.csv
  Quests/Descriptions/quest_00050035.csv
  Quests/Descriptions/quest_00050040.csv
  Quests/Descriptions/quest_00050050.csv
  Quests/Descriptions/quest_00050070.csv
  Quests/Descriptions/quest_00050130.csv
  Quests/Descriptions/quest_00050190.csv
  Quests/Descriptions/quest_00050200.csv
  Quests/Descriptions/quest_00050230.csv
  Quests/Descriptions/quest_00050310.csv
  Quests/Descriptions/quest_00050330.csv
  Quests/Time Attack/quest_00040110.csv
  Quests/Time Attack/quest_00040120.csv
  Story/Episode 1/un_010400.csv
  Story/Episode 1/un_010400_fs.csv
  Story/Episode 1/un_010470.csv
  Story/Episode 1/un_010470_fs.csv
  Story/Episode 1/un_010470_om.csv
  Story/Episode 1/un_010540.csv
  Story/Episode 1/un_011250.csv
  Story/Episode 6/Chapter 1/st_061090.csv
  Story/Episode 6/Chapter 6/st_065020.csv
  Story/Episode 6/Chapter 6/st_065030.csv
Labels: size/L

#1144 KO: EP6 Chapter 1 Translation
  Files/st_062020.csv
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/Chapter 1/st_061100.csv
  Story/Episode 6/Chapter 1/st_062020.csv
Labels: size/M

#1142 Misc grammer etc fixes
  README.md
  Story/Episode 6/Lucotte/un_063070.csv
  Story/Episode 6/Lucotte/un_064060.csv
  Story/Episode 6/Lucotte/un_065240.csv
  Story/Episode 6/Ludmilla/un_064110.csv
Labels: size/M

#1114 Misc story fixes
  Story/Episode 4/Chapter 8/un_048010.csv
  Story/Episode 6/Chapter 1/un_061030.csv
  Story/Episode 6/Chapter 1/un_061160.csv
  Story/Episode 6/Chapter 1/un_061200.csv
  Story/Episode 6/Chapter 3/cm_064202.csv
  Story/Episode 6/Chapter 3/st_063075.csv
  Story/Episode 6/Chapter 3/st_063100.csv
  Story/Episode 6/Chapter 3/un_062070.csv
  Story/Episode 6/Chapter 4/st_064020.csv
  Story/Episode 6/Chapter 5/st_064050.csv
  Story/Episode 6/Chapter 5/st_064075.csv
  Story/Episode 6/Chapter 5/st_064080.csv
  Story/Episode 6/Kyokuya/un_061080.csv
  Story/Episode 6/Kyokuya/un_061170.csv
  Story/Episode 6/Kyokuya/un_062030.csv
  Story/Episode 6/Kyokuya/un_062080.csv
  Story/Episode 6/Kyokuya/un_062090.csv
  Story/Episode 6/Lucotte/un_063020.csv
  Story/Episode 6/Lucotte/un_063060.csv
  Story/Episode 6/Lucotte/un_064080.csv
  Story/Episode 6/Lucotte/un_064090.csv
  Story/Episode 6/Ludmilla/un_062060.csv
  Story/Episode 6/Ludmilla/un_063170.csv
  Story/Episode 6/Other/un_062050.csv
  Story/Episode 6/Other/un_063010.csv
  Story/Episode 6/Other/un_063100.csv
  Story/Episode 6/Other/un_065025.csv
Labels: size/M

#1147 KO: Fix Typo + Episode 6 Translation
  Files/un_061170.csv
  Misc/actor_name.csv
  Quests/Seasonal/beach wars 2020/co06065105.csv
  Story/Episode 6/Chapter 0/st_061010.csv
  Story/Episode 6/Chapter 0/st_061015.csv
  Story/Episode 6/Chapter 1/st_061100.csv
  Story/Episode 6/Chapter 1/st_062020.csv
  Story/Episode 6/Chapter 6/st_065119.csv
  Story/Episode 6/Kyokuya/un_061170.csv
  UI/ui_quest.csv
Labels: size/L

#1146 EN: Old potential names
  UI/ui_item.csv
Labels: size/XL

#1148 Es EP6 cap6 correccion
  Files/st_065075.csv
  Files/st_065077.csv
  Files/st_065080.csv
  Story/Episode 5/cap 6/st_058187.csv
  Story/Episode 6/cap6/st_065070.csv
  Story/Episode 6/cap6/st_065075.csv
  Story/Episode 6/cap6/st_065077.csv
  Story/Episode 6/cap6/st_065080.csv
Labels: size/L

#1149 Es: Fixing
  Story/Episode 6/cap4/cm_064409.csv
  Story/Episode 6/cap5/st_064070.csv
  Story/Episode 6/cap5/st_064075.csv
  Story/Episode 6/cap5/st_064078.csv
  Story/Episode 6/cap6/st_065075.csv
  Story/Episode 6/cap6/st_065077.csv
  Story/Episode 6/cap6/st_065080.csv
Labels: size/M

#1150 ES: a bit more?
  Dialogue/Lucotte/np_npc_570.csv
  Story/Episode 6/Kyokuya/un_062020.csv
  Story/Episode 6/Kyokuya/un_062030.csv
  Story/Episode 6/Lucotte/un_063020.csv
  Story/Episode 6/cap1/un_061160.csv
  Story/Episode 6/cap2/un_062120.csv
  Story/Episode 6/cap3/st_063100.csv
  Story/Episode 6/cap3/un_062140.csv
  Story/Episode 6/cap4/st_064010.csv
  Story/Episode 6/cap4/st_064025.csv
  Story/Episode 6/cap4/st_064028.csv
  Story/Episode 6/cap4/st_064030.csv
  Story/Episode 6/cap5/st_064070.csv
  Story/Episode 6/cap5/st_064075.csv
  Story/Episode 6/cap5/st_064078.csv
  Story/Episode 6/cap5/st_064080.csv
  Story/Episode 6/cap5/un_064160.csv
  Story/Episode 6/cap6/ii_session_apc_5008.csv
  Story/Episode 6/cap6/ii_session_apc_5659.csv
  Story/Episode 6/cap6/st_065070.csv
  Story/Episode 6/otros/un_061120.csv
  Story/Episode 6/otros/un_061180.csv
  Story/Episode 6/otros/un_063100.csv
Labels: size/L

#1153 Es: A little more
  Files/quest_00301760.csv
  Files/quest_00301780.csv
  Story/Episode 3/quest_00301760.csv
  Story/Episode 6/cap3/quest_00301780.csv
  Story/Episode 6/cap3/st_063060.csv
  Story/Episode 6/cap3/st_063075.csv
Labels: size/M

#1154 Es: One more
  Story/Episode 6/cap3/st_063080.csv
  Story/Episode 6/cap3/st_063090.csv
  Story/Episode 6/cap3/st_063107.csv
  Story/Episode 6/cap3/st_063110.csv
  Story/Episode 6/cap3/st_063120.csv
  Story/Episode 6/cap3/un_063150.csv
  Story/Episode 6/cap3/un_065020.csv
  Story/Episode 6/cap4/st_064010.csv
  Story/Episode 6/otros/un_063100.csv
  Story/Episode 6/otros/un_063190.csv
Labels: size/L

#1155 Es: ¡One more!
  Dialogue/np_npc_counterteam4.csv
  Files/un_063060.csv
  Story/Episode 1/un_011160.csv
  Story/Episode 2/ra_020510.csv
  Story/Episode 2/st_020760.csv
  Story/Episode 2/st_020764.csv
  Story/Episode 3/st_031030.csv
  Story/Episode 3/st_037150.csv
  Story/Episode 3/un_036020.csv
  Story/Episode 4/st_042082.csv
  Story/Episode 4/st_042130.csv
  Story/Episode 4/st_043060.csv
  Story/Episode 4/st_044060.csv
  Story/Episode 4/st_044100.csv
  Story/Episode 4/st_045070.csv
  Story/Episode 4/st_045090.csv
  Story/Episode 4/st_046070.csv
  Story/Episode 4/st_046100.csv
  Story/Episode 4/st_047090.csv
  Story/Episode 4/st_048010.csv
  Story/Episode 4/st_048133.csv
  Story/Episode 6/Kyokuya/un_062080.csv
  Story/Episode 6/Lucotte/un_063060.csv
  Story/Episode 6/cap4/cm_064404.csv
  Story/Episode 6/cap4/cm_064405.csv
  Story/Episode 6/cap4/st_064020.csv
  Story/Episode 6/cap5/st_064070.csv
  Story/Episode 6/cap5/st_064100.csv
  Story/Episode 6/otros/un_063010.csv
Labels: size/L

#1156 Es: da...
  Dialogue/Lottie/np_npc_288.csv
  Dialogue/Lottie/np_npc_62.csv
  Dialogue/np_npc_363.csv
  Misc/np_npc_443.csv
  Misc/un_057020.csv
  Quests/Divide Quest/cm_068000.csv
  Quests/Divide Quest/ii_mep_annihilation_mack.csv
  Story/Episode 4/st_043100.csv
  Story/Episode 4/st_045020.csv
  Story/Episode 4/st_048160.csv
  Story/Episode 5/st_052080.csv
  Story/Episode 5/un_050050.csv
  Story/Episode 6/Kyokuya/un_061040.csv
  Story/Episode 6/Kyokuya/un_061050.csv
  Story/Episode 6/Kyokuya/un_061080.csv
  Story/Episode 6/Kyokuya/un_061170.csv
  Story/Episode 6/Kyokuya/un_062020.csv
  Story/Episode 6/Kyokuya/un_062030.csv
  Story/Episode 6/Kyokuya/un_062080.csv
  Story/Episode 6/Kyokuya/un_062090.csv
  Story/Episode 6/Ludmilla/un_063200.csv
  Story/Episode 6/Ludmilla/un_064110.csv
  Story/Episode 6/cap1/st_061010.csv
  Story/Episode 6/cap1/st_061015.csv
  Story/Episode 6/cap1/un_061130.csv
  Story/Episode 6/cap1/un_061160.csv
  Story/Episode 6/cap2/st_062045.csv
  Story/Episode 6/cap2/st_062070.csv
  Story/Episode 6/cap2/st_062085.csv
  Story/Episode 6/cap3/st_063107.csv
  Story/Episode 6/cap3/st_063115.csv
  Story/Episode 6/cap4/st_064028.csv
  Story/Episode 6/cap4/st_064030.csv
  Story/Episode 6/cap4/st_064040.csv
  Story/Episode 6/cap5/st_064050.csv
  Story/Episode 6/cap5/st_064060.csv
  Story/Episode 6/cap5/st_064070.csv
  Story/Episode 6/cap5/st_064075.csv
  Story/Episode 6/cap5/st_064100.csv
  Story/Episode 6/cap5/st_064110.csv
  Story/Episode 6/cap5/un_064160.csv
  Story/Episode 6/cap5/un_065040.csv
  Story/Episode 6/cap6/ii_session_apc_5008.csv
  Story/Episode 6/cap6/ii_session_apc_5658.csv
  Story/Episode 6/cap6/ii_session_apc_5659.csv
  Story/Episode 6/cap6/st_065040.csv
  Story/Episode 6/otros/un_063010.csv
  UI/quest_common.csv
  UI/ui_guild.csv
Labels: size/L

#1158 Merge pull request #87 from Arks-Layer/ES
  Files/st_065020.csv
  Files/un_064100.csv
  Files/un_065110.csv
  Story/Episode 4/st_043100.csv
  Story/Episode 6/Kyokuya/un_061050.csv
  Story/Episode 6/Kyokuya/un_061170.csv
  Story/Episode 6/cap3/un_062070.csv
  Story/Episode 6/cap5/st_064080.csv
  Story/Episode 6/cap5/st_064100.csv
  Story/Episode 6/cap5/st_064110.csv
  Story/Episode 6/cap5/st_064120.csv
  Story/Episode 6/cap6/st_065010.csv
  Story/Episode 6/cap6/st_065020.csv
  Story/Episode 6/cap6/un_065110.csv
  Story/Episode 6/otros/un_064100.csv
Labels: size/L

#1160 Es: patty
  Dialogue/Patty/np_010130.csv
  Story/Episode 6/cap6/st_065080.csv
Labels: size/S

#1164 Es: ultimate for this days
  Story/Episode 6/cap6/un_065110.csv
  UI/quest_counter.csv
Labels: size/S

#1165 English Translation of Episode 6 Chapter 6
  Files/st_065010.csv
  Files/st_065020.csv
  Files/st_065030.csv
  Files/st_065040.csv
  Files/st_065073.csv
  Files/st_065075.csv
  Files/st_065077.csv
  Files/st_065079.csv
  Files/st_065080.csv
  Files/st_065083.csv
  Files/st_065085.csv
  Files/st_065086.csv
  Files/st_065087.csv
  Files/st_065090.csv
  Files/st_065092.csv
  Files/st_065093.csv
  Files/st_065100.csv
  Files/st_065101.csv
  Files/st_065102.csv
  Files/st_065110.csv
  Files/st_065115.csv
  Files/st_065117.csv
  Files/st_065120.csv
  Files/st_065125.csv
  Files/st_065127.csv
  Story/Episode 6/Chapter 6/st_065050.csv
  Story/Episode 6/Chapter 6/st_065060.csv
  Story/Episode 6/Chapter 6/st_065070.csv
  Story/Episode 6/Chapter 6/st_065119.csv
  Story/Episode 6/st_065010.csv
  Story/Episode 6/st_065020.csv
  Story/Episode 6/st_065030.csv
  Story/Episode 6/st_065040.csv
  Story/Episode 6/st_065073.csv
  Story/Episode 6/st_065075.csv
  Story/Episode 6/st_065077.csv
  Story/Episode 6/st_065079.csv
  Story/Episode 6/st_065080.csv
  Story/Episode 6/st_065083.csv
  Story/Episode 6/st_065085.csv
  Story/Episode 6/st_065086.csv
  Story/Episode 6/st_065087.csv
  Story/Episode 6/st_065090.csv
  Story/Episode 6/st_065092.csv
  Story/Episode 6/st_065093.csv
  Story/Episode 6/st_065100.csv
  Story/Episode 6/st_065101.csv
  Story/Episode 6/st_065102.csv
  Story/Episode 6/st_065110.csv
  Story/Episode 6/st_065115.csv
  Story/Episode 6/st_065117.csv
  Story/Episode 6/st_065120.csv
  Story/Episode 6/st_065125.csv
  Story/Episode 6/st_065127.csv
Labels: size/XL

#1166 EN: 6-6 checks
  Dialogue/Hans/np_010520.csv
  Quests/Primordial Darkness/ii_areaboss_db.csv
  Quests/Primordial Darkness/ii_areaboss_df.csv
  Quests/Story EP6 names/Chapter 6/quest_00302210.csv
  Quests/Story EP6 names/Chapter 6/quest_00302220.csv
  Story/Episode 6/Chapter 6/cm_062609.csv
  Story/Episode 6/Chapter 6/ii_session_apc_5666.csv
  Story/Episode 6/Chapter 6/st_065010.csv
  Story/Episode 6/Chapter 6/st_065020.csv
  Story/Episode 6/Chapter 6/st_065030.csv
  Story/Episode 6/Chapter 6/st_065040.csv
  Story/Episode 6/Chapter 6/st_065050.csv
  Story/Episode 6/Chapter 6/st_065060.csv
  Story/Episode 6/Chapter 6/st_065070.csv
  Story/Episode 6/Chapter 6/st_065079.csv
  Story/Episode 6/Chapter 6/st_065080.csv
  Story/Episode 6/Chapter 6/st_065083.csv
  Story/Episode 6/Chapter 6/st_065085.csv
  Story/Episode 6/Chapter 6/st_065086.csv
  Story/Episode 6/Chapter 6/st_065087.csv
  Story/Episode 6/Chapter 6/st_065090.csv
  Story/Episode 6/Chapter 6/st_065093.csv
  Story/Episode 6/Chapter 6/st_065100.csv
  Story/Episode 6/Chapter 6/st_065110.csv
  Story/Episode 6/Chapter 6/st_065115.csv
  Story/Episode 6/Chapter 6/st_065117.csv
  Story/Episode 6/Chapter 6/st_065119.csv
  Story/Episode 6/Chapter 6/st_065120.csv
  Story/Episode 6/Chapter 6/st_065125.csv
  Story/Episode 6/Chapter 6/st_065127.csv
  UI/ui_mainmode.csv
Labels: size/L

#1167 [WIP] Misc EP6 story fixes
  Dialogue/Afin/od_010303012.csv
  Dialogue/Kyokuya/np_015660.csv
  Dialogue/Lucotte/od_060333061.csv
  Misc/Concert/ls_010060.csv
  Orders/Kressida/co01041500.csv
  Orders/Lucotte/co06033306.csv
  Quests/Primordial Darkness/ii_areaboss_db.csv
  Quests/Primordial Darkness/quest_00051160.csv
  Quests/Primordial Darkness/quest_00170830.csv
  Quests/Story EP6 names/Chapter 6/quest_00302295.csv
  Story/Episode 2/ra_025020_om.csv
  Story/Episode 2/ra_025030.csv
  Story/Episode 3/Chapter 1/un_031070.csv
  Story/Episode 3/Chapter 1/un_031070_om.csv
  Story/Episode 5/st_053080.csv
  Story/Episode 5/st_054070.csv
  Story/Episode 6/Chapter 6/ii_session_apc_5062.csv
  Story/Episode 6/Chapter 6/st_065020.csv
  Story/Episode 6/Chapter 6/st_065040.csv
  Story/Episode 6/Chapter 6/st_065060.csv
  Story/Episode 6/Chapter 6/st_065075.csv
  Story/Episode 6/Chapter 6/st_065079.csv
  Story/Episode 6/Chapter 6/st_065086.csv
  Story/Episode 6/Chapter 6/st_065087.csv
  Story/Episode 6/Chapter 6/st_065115.csv
Labels: size/M

#1163 Fix story typos and PVP.
  Quests/Primordial Darkness/ii_areaboss_df.csv
  Story/Episode 2/st_025080_om.csv
  Story/Episode 2/un_020140.csv
  Story/Episode 3/cm_032920.csv
  Story/Episode 3/ra_039050.csv
  Story/Episode 3/un_039140.csv
  Story/Episode 4/Chapter 2/ra_043030.csv
  Translated/Story/Episode 1/co_012711.csv
  Translated/Story/Episode 2/co_022409.csv
  Translated/Story/Episode 2/co_022423.csv
  UI/ui_poka_text.csv
Labels: size/S

#1168 Fix the rest of the A24 voices.
  UI/ui_charamake_parts.csv
Labels: size/XS

#1170 Fix Dark Falz Persona tip.
  UI/ui_tips.csv
Labels: size/XS

#1171 KO: Azanami's text and EP6 Ch.1 translation
  Files/cm_060205.csv
  Files/cm_060213.csv
  Files/cm_060214.csv
  Files/np_npc_87.csv
  Files/od_020387061.csv
  Files/st_061130.csv
  Files/st_061135.csv
  Files/st_061136.csv
  NPC/Azanami/np_010870.csv
  NPC/Azanami/np_npc_87.csv
  NPC/Azanami/od_020387001.csv
  NPC/Azanami/od_020387061.csv
  Story/Episode 6/Chapter 1/cm_060205.csv
  Story/Episode 6/Chapter 1/cm_060206.csv
  Story/Episode 6/Chapter 1/cm_060212.csv
  Story/Episode 6/Chapter 1/cm_060213.csv
  Story/Episode 6/Chapter 1/cm_060214.csv
  Story/Episode 6/Chapter 1/st_061110.csv
  Story/Episode 6/Chapter 1/st_061120.csv
  Story/Episode 6/Chapter 1/st_061130.csv
  Story/Episode 6/Chapter 1/st_061135.csv
  Story/Episode 6/Chapter 1/st_061136.csv
  Story/Episode 6/Chapter 6/st_065119.csv
Labels: size/L

#1172 EN: Lobby dialogue
  Dialogue/Afin/np_012100.csv
  Dialogue/Aika/np_012540.csv
  Dialogue/Henri/np_010440.csv
  Dialogue/Jean/np_010210.csv
  Dialogue/Klotho/np_010180.csv
  Dialogue/Lisa/np_010260.csv
  Dialogue/Marlu/np_010190.csv
  Dialogue/Ohza/np_010200.csv
  Dialogue/Philia/np_010170.csv
  Dialogue/Quna/np_013130.csv
  Dialogue/Reda/np_010220.csv
  Translated/Dialogue/Koffie/np_010500.csv
Labels: size/L

#1174 EN: Summer fixes
  Dialogue/Summer Heroines/od_060651017.csv
  Files/ii_session_apc_5424.csv
  Files/ii_session_apc_5646.csv
  Files/ii_session_apc_5647.csv
  Files/ii_session_apc_5648.csv
  Orders/Summer Heroines/co06065101.csv
  Orders/Summer Heroines/co06065104.csv
  Quests/Seasonal/Beach 2020/ii_session_apc_5424.csv
  Quests/Seasonal/Beach 2020/ii_session_apc_5646.csv
  Quests/Seasonal/Beach 2020/ii_session_apc_5647.csv
  Quests/Seasonal/Beach 2020/ii_session_apc_5648.csv
  Quests/Seasonal/Beach 2020/quest_00051170.csv
  Quests/Seasonal/Beach 2020/quest_00170810.csv
Labels: size/M

#1175 EN: Hitsugi and Marlu partner dialogue
  Dialogue/_Partner chat/apc_chat_1.csv
  Dialogue/_Partner chat/apc_chat_3.csv
  Dialogue/_Partner chat/apc_chat_4.csv
  UI/apc_name.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/XXL

#1178 EN: Riding Quests and organization
  Dialogue/Mimi/np_013442.csv
  Dialogue/Pietro/np_012422.csv
  Dialogue/Pudding/np_010822.csv
  Dialogue/Sophia/np_013082.csv
  Files/cm_040200.csv
  Files/cm_040201.csv
  Files/co_040052.csv
  Files/co_060058.csv
  Files/mp_000486.csv
  Files/mp_000487.csv
  Files/mp_000563.csv
  Files/wh_tl_co_040051.csv
  Files/wh_tl_co_040052.csv
  Quests/Damage Tally/co_060018.csv
  Quests/Damage Tally/mp_000556.csv
  Quests/Damage Tally/mp_000557.csv
  Quests/Divide Quest/co_060048.csv
  Quests/Divide Quest/co_066100.csv
  Quests/Divide Quest/mp_000561.csv
  Quests/Divide Quest/mp_000562.csv
  Quests/Riding/cm_040200.csv
  Quests/Riding/cm_040201.csv
  Quests/Riding/co_040052.csv
  Quests/Riding/mp_000486.csv
  Quests/Riding/mp_000487.csv
  Quests/Seasonal/Beach 2019/co_061769.csv
  Quests/Seasonal/Beach 2019/mp_000558.csv
  Quests/Seasonal/Beach 2020/co_060058.csv
  Quests/Seasonal/Beach 2020/mp_000563.csv
  Quests/Seasonal/Easter 2019/mp_000553.csv
  Quests/Seasonal/Halloween 2019/co_060022.csv
  Quests/Seasonal/Halloween 2019/mp_000559.csv
  Quests/Seasonal/Xmas 2019/co_060034.csv
  Quests/Seasonal/Xmas 2019/mp_000560.csv
  Tutorial/Tutorial List/wh_tl_co_040051.csv
  Tutorial/Tutorial List/wh_tl_co_040052.csv
  UI/quest_common.csv
Labels: size/M

#1179 KO: fix typo
  Misc/Concert/bd_010010.csv
  Misc/Concert/bd_010020.csv
  Quests/quest_counter.csv
  UI/item_element_expl.csv
  UI/item_element_name.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/L

#1181 KO: Limited Mission Translation
  Arks Mission/Event/Road To Luster/ac06031711.csv
  Arks Mission/Event/Road To Luster/ac06031721.csv
  Arks Mission/Event/Road To Luster/ac06031731.csv
  Arks Mission/Event/Road To Luster/ac06031741.csv
  Arks Mission/Event/Road To Luster/ac06031811.csv
  Arks Mission/Event/Road To Luster/ac06031821.csv
  Arks Mission/Event/Road To Luster/ac06031831.csv
  Arks Mission/Event/Road To Luster/ac06031911.csv
  Arks Mission/Event/Road To Luster/ac06031921.csv
  Arks Mission/Event/ac06031611.csv
  Arks Mission/Event/ac06031612.csv
  Arks Mission/Event/ac06031613.csv
  Arks Mission/Event/ac06031614.csv
  Arks Mission/Event/ac06031615.csv
  Arks Mission/Event/ac06031616.csv
  Arks Mission/Event/ac06031621.csv
  Files/ac06031611.csv
  Files/ac06031612.csv
  Files/ac06031613.csv
  Files/ac06031614.csv
  Files/ac06031615.csv
  Files/ac06031616.csv
  Files/ac06031621.csv
  Files/ac06031711.csv
  Files/ac06031721.csv
  Files/ac06031731.csv
  Files/ac06031741.csv
  Files/ac06031811.csv
  Files/ac06031821.csv
  Files/ac06031831.csv
  Files/ac06031911.csv
  Files/ac06031921.csv
  Misc/Concert/bd_010010.csv
  Misc/Concert/bd_010020.csv
  Quests/Story EP3 names/quest_00703270.csv
  Quests/quest_counter.csv
  Story/Episode 6/Chapter 1/cm_060200.csv
  Story/Episode 6/Chapter 1/cm_060212.csv
  Story/Episode 6/Chapter 1/st_061110.csv
  Story/Episode 6/Chapter 1/st_061136.csv
  Story/Episode 6/Chapter 1/st_061137.csv
  UI/item_element_expl.csv
Labels: size/L

#1182 Fix untranslated limited arks mission.
  Orders/_ARKS Missions/3 Event/ac06031921.csv
Labels: size/XS

#1180 Fix Cabracan dialogue.
  Story/Episode 2/ra_020080.csv
  Story/Episode 2/st_020020.csv
  Story/Episode 2/st_020030.csv
  Story/Episode 2/st_020040.csv
  Story/Episode 2/st_020045.csv
Labels: size/M

#1185 Fix rest of limited arks missions.
  Orders/_ARKS Missions/3 Event/ac06031741.csv
  Orders/_ARKS Missions/3 Event/ac06031922.csv
  Orders/_ARKS Missions/3 Event/ac06031923.csv
Labels: size/S

#1186 KO: Casino Translation
  Arks Mission/Event/Road To Luster/ac06031721.csv
  Arks Mission/Event/Road To Luster/ac06031731.csv
  Arks Mission/Event/Road To Luster/ac06031831.csv
  Arks Mission/Event/Road To Luster/ac06031911.csv
  Arks Mission/Event/Road To Luster/ac06031931.csv
  Dialogue/E-Trial/ii_areaboss_db.csv
  Dialogue/E-Trial/ii_areaboss_de_duel.csv
  Dialogue/E-Trial/ii_areaboss_raid.csv
  Dialogue/E-Trial/ii_areaboss_volcano.csv
  Dialogue/E-Trial/ii_boss_ahl.csv
  Dialogue/E-Trial/ii_boss_ahl_3boss.csv
  Dialogue/E-Trial/ii_boss_ahl_dk.csv
  Dialogue/E-Trial/ii_boss_ahl_remaining_buff.csv
  Dialogue/E-Trial/ii_boss_ahl_timelimit.csv
  Dialogue/E-Trial/ii_enemy_fever_ahl.csv
  Dialogue/E-Trial/ii_escape_boost_v.csv
  Dialogue/E-Trial/ii_escape_from_neo_burufu.csv
  Dialogue/E-Trial/ii_waker_bit_ahl_2ev_boss.csv
  Files/ac06031931.csv
  Files/cm_060504.csv
  Files/cm_060505.csv
  Files/pr_058010.csv
  Misc/Concert/bd_010010.csv
  Misc/actor_name.csv
  NPC/Koffie/Dialogue/Talk/np_010500.csv
  Quests/Arks Quest/quest_00030080.csv
  Quests/Dark Falz/Loser/quest_00050280.csv
  Quests/Dark Falz/Loser/quest_00050290.csv
  Quests/Divide Quest/quest_00220000.csv
  Quests/Free Fields/quest_00020060.csv
  Quests/Limited Quest/Anniversary/8th/1st/quest_00080440.csv
  Quests/Profound Darkness/cm_036213.csv
  Quests/Seasonal/beach wars 2020/cm_060504.csv
  Quests/Seasonal/beach wars 2020/cm_060505.csv
  Quests/Seasonal/beach wars 2020/co_060519.csv
  Quests/Seasonal/beach wars 2020/co_060520.csv
  Quests/Seasonal/beach wars 2020/co_060521.csv
  Quests/Seasonal/beach wars 2020/ii_session_apc_5424.csv
  Quests/Seasonal/beach wars 2020/pr_058010.csv
  Quests/Seasonal/beach wars 2020/quest_00051170.csv
  Quests/Seasonal/beach wars 2020/quest_00170810.csv
  Quests/Story EP3 names/quest_00703270.csv
  Quests/Story EP6 names/Chapter 6/quest_00302295.csv
  Quests/quest_common.csv
  Quests/quest_counter.csv
  Story/Episode 6/Chapter 6/st_065090.csv
  Story/Episode 6/Chapter 6/st_065092.csv
  Story/Episode 6/Chapter 6/st_065100.csv
  Story/Episode 6/Chapter 6/st_065110.csv
  UI/common.csv
  UI/ui_amusement.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
Labels: size/XL

#1191 KO: Additional work
  Arks Mission/Daily/ac06010101.csv
  Arks Mission/Daily/ac06010102.csv
  Arks Mission/Daily/ac06010103.csv
  Arks Mission/Daily/ac06010201.csv
  Arks Mission/Daily/ac06010202.csv
  Arks Mission/Daily/ac06010203.csv
  Arks Mission/Daily/ac06010301.csv
  Arks Mission/Daily/ac06010302.csv
  Arks Mission/Daily/ac06010303.csv
  Arks Mission/Daily/ac06010304.csv
  Arks Mission/Daily/ac06010305.csv
  Arks Mission/Daily/ac06010306.csv
  Arks Mission/Daily/ac06010307.csv
  Arks Mission/Daily/ac06010308.csv
  Arks Mission/Daily/ac06010401.csv
  Arks Mission/Daily/ac06010402.csv
  Arks Mission/Daily/ac06010403.csv
  Arks Mission/Daily/ac06010404.csv
  Arks Mission/Daily/ac06010405.csv
  Arks Mission/Daily/ac06010406.csv
  Arks Mission/Daily/ac06010407.csv
  Arks Mission/Daily/ac06010408.csv
  Arks Mission/Daily/ac06010409.csv
  Arks Mission/Daily/ac06010501.csv
  Arks Mission/Daily/ac06010502.csv
  Arks Mission/Daily/ac06010503.csv
  Dialogue/E-Trial/ii_umincyu_kiki1patu.csv
  Dialogue/E-Trial/ii_waker_ahl.csv
  Dialogue/E-Trial/ii_waker_bit_ahl.csv
  Dialogue/E-Trial/ii_waker_bit_ahl_2ev_boss.csv
  Dialogue/E-Trial/ii_waker_bit_ahl_ev_boss.csv
  Dialogue/E-Trial/ii_waker_bit_ahl_ev_waker.csv
  Dialogue/E-Trial/incident_common.csv
  UI/ui_amusement.csv
Labels: size/XL
