Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-01, with the labels that each got.

#930 EN: Partner dialogue
  Dialogue/_Partner chat/apc_chat_1.csv
  Misc/actor_name.csv
  Quests/Evangelion/ii_areaboss_prism.csv
  Quests/Limited Quests/quest_00080100.csv
  Story/Episode 2/un_020450.csv
  UI/apc_name.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/L

#931 EN: More stuff
  Dialogue/_Partner chat/apc_chat_1.csv
  Dialogue/_Partner chat/apc_chat_4.csv
  Quests/Free Fields/quest_00020140.csv
  UI/apc_name.csv
  UI/ui_item.csv
Labels: size/L

#934 EN: NY Xie COs
  Dialogue/Harriet & Luther (Xmas)/np_016210.csv
  Dialogue/Harriet & Luther (Xmas)/od_060646011.csv
  Dialogue/Harriet & Luther (Xmas)/od_060646017.csv
  Dialogue/Xie (New Year)/np_011210.csv
  Dialogue/Xie (New Year)/np_npc_121.csv
  Dialogue/Xie (New Year)/od_060503011.csv
  Dialogue/Xie (New Year)/od_060503017.csv
  Dialogue/_Partner chat/apc_chat_1.csv
  Dialogue/np_npc_121.csv
  Files/co06050301.csv
  Files/co06050302.csv
  Files/co06050303.csv
  Files/co06050304.csv
  Files/co06050305.csv
  Files/np_011210.csv
  Files/od_060503011.csv
  Files/od_060503017.csv
  Orders/Xie (New Year)/co06050301.csv
  Orders/Xie (New Year)/co06050302.csv
  Orders/Xie (New Year)/co06050303.csv
  Orders/Xie (New Year)/co06050304.csv
  Orders/Xie (New Year)/co06050305.csv
  Orders/_Bingo/bo00002545.csv
  Quests/Story EP6 names/Chapter 3/quest_00301850.csv
  Quests/Story EP6 names/Chapter 3/quest_00301870.csv
  Story/Episode 6/Chapter 3/st_063107.csv
  Story/Episode 6/Kyokuya/un_061050.csv
  Story/Episode 6/Kyokuya/un_062020.csv
  Story/Episode 6/Other/un_063010.csv
  UI/ui_mainmode.csv
  _aspell/PSO2.en_Chat.dict
  _aspell/PSO2.en_Class.dict
  _aspell/PSO2.en_Items.dict
  _aspell/PSO2.en_Misc.dict
  _aspell/PSO2.en_NPC.dict
  _aspell/PSO2.en_Names.dict
  _aspell/PSO2.en_Noun.dict
Labels: size/M

#935 EN: Space Magatsu and config stuff
  Dialogue/Mid-Mission/incident_common.csv
  Dialogue/Xie (New Year)/od_060503021.csv
  Dialogue/Xie (New Year)/od_060503027.csv
  Dialogue/Xie (New Year)/od_060503031.csv
  Dialogue/Xie (New Year)/od_060503037.csv
  Dialogue/Xie (New Year)/od_060503041.csv
  Dialogue/Xie (New Year)/od_060503047.csv
  Dialogue/Xie (New Year)/od_060503051.csv
  Dialogue/Xie (New Year)/od_060503057.csv
  Files/cm_060204.csv
  Files/cm_060209.csv
  Files/cm_060210.csv
  Files/cm_060301.csv
  Files/cm_060303.csv
  Files/cm_060306.csv
  Files/cm_060307.csv
  Files/cm_060309.csv
  Files/cm_060310.csv
  Files/cm_060311.csv
  Files/co_060038.csv
  Files/ii_areaboss_bh.csv
  Files/od_060503021.csv
  Files/od_060503027.csv
  Files/od_060503031.csv
  Files/od_060503037.csv
  Files/od_060503041.csv
  Files/od_060503047.csv
  Files/od_060503051.csv
  Files/od_060503057.csv
  Files/wh_tl_co_060038.csv
  Orders/Xie (New Year)/co06050302.csv
  Quests/Space Magatsu/cm_060301.csv
  Quests/Space Magatsu/cm_060302.csv
  Quests/Space Magatsu/cm_060303.csv
  Quests/Space Magatsu/cm_060304.csv
  Quests/Space Magatsu/cm_060305.csv
  Quests/Space Magatsu/cm_060306.csv
  Quests/Space Magatsu/cm_060307.csv
  Quests/Space Magatsu/cm_060309.csv
  Quests/Space Magatsu/cm_060310.csv
  Quests/Space Magatsu/cm_060311.csv
  Quests/Space Magatsu/ii_areaboss_bh.csv
  Quests/Space Magatsu/quest_00080410.csv
  Quests/Space Magatsu/quest_00170670.csv
  Story/Episode 6/Chapter 1/cm_060204.csv
  Story/Episode 6/Chapter 1/cm_060209.csv
  Story/Episode 6/Chapter 1/cm_060210.csv
  Tutorial/Tutorial List/wh_tl_co_060020.csv
  Tutorial/Tutorial List/wh_tl_co_060038.csv
  Tutorial/Window/co_060020.csv
  Tutorial/Window/co_060038.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_selectmenu_text.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/L

#936 EN: Jozsef CO descriptions + other stuff
  Orders/Jozsef/co06040901.csv
  Orders/Jozsef/co06040902.csv
  Orders/Jozsef/co06040903.csv
  Orders/Jozsef/co06040904.csv
  Orders/Jozsef/co06040905.csv
  Orders/Jozsef/co06040906.csv
  Orders/Jozsef/co06040907.csv
  Orders/Jozsef/co06040908.csv
  Orders/Jozsef/co06040909.csv
  Quests/Elder/quest_00170710.csv
  UI/quest_counter.csv
  UI/ui_item.csv
Labels: size/M

#938 Es: Mas ediciónes
  Tutorial/Training Quests/14 Etoile/tr_140000.csv
  Tutorial/Training Quests/14 Etoile/tr_140015.csv
  Tutorial/Training Quests/14 Etoile/tr_140025.csv
  Tutorial/Training Quests/14 Etoile/tr_140100.csv
Labels: size/S

#940 Es: Mas Correcciónes
  Dialogue/Koffie/co_060511.csv
  Files/co_060511.csv
  Tutorial/Training Quests/14 Etoile/tr_140040.csv
  Tutorial/Training Quests/14 Etoile/tr_140046.csv
Labels: size/S

#943 ES: a bit
  Dialogue/Mid-Mission/ii_boss_ahl_m_oarfish.csv
  Story/Evangelion/pr_064950.csv
  UI/quest_common.csv
  UI/ui_mainmode.csv
Labels: size/S

#944 Es: little
  Dialogue/Mid-Mission/ii_session_apc_5407.csv
  Dialogue/Popona/np_016130.csv
  Dialogue/Popona/od_060645031.csv
  Dialogue/Popona/od_060645037.csv
  Orders/Kyokuya/co06033206.csv
  Story/Episode 4/st_045010.csv
  Story/Episode 4/st_047020.csv
  Story/Episode 4/st_048110.csv
  Story/Episode 4/un_042030.csv
  Story/Episode 6/Kyokuya/un_062010.csv
  Story/Episode 6/Lucotte/un_063020.csv
  Story/Episode 6/cap1/st_061130.csv
  Story/Episode 6/cap1/un_061030.csv
  Story/Episode 6/cap1/un_061200.csv
  Story/Episode 6/cap2/st_062070.csv
  Story/Episode 6/cap2/st_062085.csv
  Story/Episode 6/cap2/un_062120.csv
  Story/Episode 6/cap3/cm_064140.csv
  Story/Episode 6/cap3/st_063107.csv
  Story/Episode 6/otros/un_063010.csv
  Story/Evangelion/pr_064950.csv
Labels: size/XS

#945 Merge pull request #73 from Arks-Layer/ES
  Orders/_Daily/do00001002.csv
Labels: size/XS
