Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-05, with the labels that each got.

#1001 Es: Actualizacion mini
  Misc/actor_name.csv
  Quests/Divide Quest/quest_00220000.csv
  UI/quest_counter.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
  UI/ui_tips.csv
Labels: size/M

#1002 EN: Some more E-trial dialogue
  Dialogue/Mid-Mission/darker_trap.csv
  Dialogue/Mid-Mission/darker_trap_cage.csv
  Dialogue/Mid-Mission/dwarf_message.csv
  Dialogue/Mid-Mission/enebomb.csv
  Dialogue/Mid-Mission/ii_annihilation_aold.csv
  Dialogue/Mid-Mission/ii_annihilation_bomb_wave.csv
  Dialogue/Mid-Mission/ii_boss_ahl_nyau.csv
  Dialogue/Mid-Mission/ii_boss_ahl_nyau_ev_boss.csv
  Dialogue/Mid-Mission/ii_boss_ahl_nyau_ev_rare.csv
  Dialogue/Mid-Mission/ii_boss_ahl_nyau_ev_two.csv
  Dialogue/Mid-Mission/ii_boss_ahl_remaining_buff.csv
  Dialogue/Mid-Mission/ii_bss_chase.csv
  Dialogue/Mid-Mission/ii_castle_town_terror.csv
  Dialogue/Mid-Mission/ii_collect_goods_a.csv
  Dialogue/Mid-Mission/ii_collect_goods_b.csv
  Dialogue/Mid-Mission/ii_collect_goods_c.csv
  Dialogue/Mid-Mission/ii_collect_sample.csv
  Dialogue/Mid-Mission/ii_darkercore.csv
  Dialogue/Mid-Mission/ii_defense_from_mge.csv
  Dialogue/Mid-Mission/ii_destroy_neo_burufu.csv
  Dialogue/Mid-Mission/ii_destroy_pirate_ship.csv
  Dialogue/Mid-Mission/ii_dwarf_defense.csv
  Dialogue/Mid-Mission/ii_dwarf_msg.csv
  Dialogue/Mid-Mission/ii_escape_enemy_ahl.csv
  Dialogue/Mid-Mission/ii_escape_from_neo_burufu.csv
  Dialogue/Mid-Mission/ii_escape_rare_enemy_ahl.csv
  Dialogue/Mid-Mission/ii_ev_boss_rematch.csv
  Dialogue/Mid-Mission/ii_ev_different_sp_boss_ahl.csv
  Dialogue/Mid-Mission/ii_ev_enemybomb_boss.csv
  Dialogue/Mid-Mission/ii_ev_js_apc.csv
  Dialogue/Mid-Mission/ii_ev_partner_boss.csv
  Dialogue/Mid-Mission/ii_ev_same_sp_boss_ahl.csv
  Dialogue/Mid-Mission/ii_ev_shoot_darker_heli.csv
  Dialogue/Mid-Mission/ii_fsm_chase.csv
  Dialogue/Mid-Mission/ii_indi.csv
  Dialogue/Mid-Mission/ii_j_s_apc_alice.csv
  Dialogue/Mid-Mission/ii_j_s_apc_boss_revival.csv
  Dialogue/Mid-Mission/ii_j_s_apc_orakio.csv
  Dialogue/Mid-Mission/ii_joint_struggle_apc.csv
  Dialogue/Mid-Mission/ii_joint_struggle_apc_boss.csv
  Files/ii_session_apc_5629.csv
  Files/ii_session_apc_5630.csv
  Files/ii_session_apc_5631.csv
  Files/ii_session_apc_5632.csv
  Quests/Extreme Quests/co_011257.csv
  Quests/Extreme Quests/co_011258.csv
  Quests/Seasonal/White Day 2020/ii_session_apc_5629.csv
  Quests/Seasonal/White Day 2020/ii_session_apc_5630.csv
  Quests/Seasonal/White Day 2020/ii_session_apc_5631.csv
  Quests/Seasonal/White Day 2020/ii_session_apc_5632.csv
  Translated/Tutorial/Dialogue/co_011258.csv
Labels: size/XXL

#1003 EN: More e-trials
  Dialogue/Mid-Mission/ii_escape_from_darker_light.csv
  Dialogue/Mid-Mission/ii_escape_from_neo_burufu.csv
  Dialogue/Mid-Mission/ii_ev_boss_capture.csv
  Dialogue/Mid-Mission/ii_ev_boss_rematch.csv
  Dialogue/Mid-Mission/ii_ev_different_sp_boss_ahl.csv
  Dialogue/Mid-Mission/ii_ev_double_sp_ahl.csv
  Dialogue/Mid-Mission/ii_ev_js_apc_boss.csv
  Dialogue/Mid-Mission/ii_ev_partner_boss.csv
  Dialogue/Mid-Mission/ii_ev_same_sp_boss_ahl.csv
  Dialogue/Mid-Mission/ii_j_s_apc_asai.csv
  Dialogue/Mid-Mission/ii_j_s_apc_collabo1.csv
  Dialogue/Mid-Mission/ii_j_s_apc_nagisa.csv
  Dialogue/Mid-Mission/ii_js_apc_boss_5520.csv
  Dialogue/Mid-Mission/ii_pamper_jack_box.csv
  Dialogue/Mid-Mission/ii_pamper_umblla.csv
  Dialogue/Mid-Mission/ii_pit_ahl.csv
  Dialogue/Mid-Mission/ii_pse_defense.csv
  Dialogue/Mid-Mission/ii_rescue_darker_trap.csv
  Dialogue/Mid-Mission/ii_slime_vanish.csv
  Dialogue/Mid-Mission/ii_spene_ahl_rappyemp.csv
  Dialogue/Mid-Mission/ii_time_bomb.csv
  Dialogue/Mid-Mission/ii_umincyu_kiki1patu.csv
  Dialogue/Mid-Mission/ii_waker_ahl.csv
  Dialogue/Mid-Mission/ii_waker_bit_ahl_2ev_boss.csv
  Dialogue/Mid-Mission/ii_waker_bit_ahl_ev_boss.csv
  Dialogue/Mid-Mission/ii_waker_bit_ahl_ev_waker.csv
  Dialogue/Mid-Mission/quest_point_obj.csv
  Dialogue/Mid-Mission/umblla.csv
  Dialogue/Mid-Mission/umblla_santa.csv
  Quests/Descriptions/co_012601.csv
  Quests/Magatsu/ii_annihilation_mge.csv
  Quests/Magatsu/quest_00050390.csv
  Quests/Magatsu/quest_00050420.csv
  Quests/Magatsu/quest_00050440.csv
  Quests/Magatsu/quest_00170060.csv
  Quests/Seasonal/White Day 2016/ii_js_apc_boss_5520.csv
  Story/Episode 1/co_012601.csv
Labels: size/XL

#1008 EN: More message packs
  Files/mp_000461.csv
  Files/mp_000462.csv
  Files/mp_000468.csv
  Files/mp_000469.csv
  Files/mp_000470.csv
  Files/mp_000471.csv
  Files/mp_000472.csv
  Files/mp_000473.csv
  Files/mp_000474.csv
  Files/mp_000475.csv
  Files/mp_000476.csv
  Files/mp_000477.csv
  Files/mp_000478.csv
  Files/mp_000479.csv
  Files/mp_000480.csv
  Files/mp_000481.csv
  Files/mp_000482.csv
  Files/mp_000483.csv
  Tutorial/Message Pack/mp_000461.csv
  Tutorial/Message Pack/mp_000462.csv
  Tutorial/Message Pack/mp_000468.csv
  Tutorial/Message Pack/mp_000469.csv
  Tutorial/Message Pack/mp_000470.csv
  Tutorial/Message Pack/mp_000471.csv
  Tutorial/Message Pack/mp_000472.csv
  Tutorial/Message Pack/mp_000473.csv
  Tutorial/Message Pack/mp_000474.csv
  Tutorial/Message Pack/mp_000475.csv
  Tutorial/Message Pack/mp_000476.csv
  Tutorial/Message Pack/mp_000477.csv
  Tutorial/Message Pack/mp_000478.csv
  Tutorial/Message Pack/mp_000479.csv
  Tutorial/Message Pack/mp_000480.csv
  Tutorial/Message Pack/mp_000481.csv
  Tutorial/Message Pack/mp_000482.csv
  Tutorial/Message Pack/mp_000483.csv
Labels: size/M

#1009 EN: Spelling fixes
  Dialogue/Echo/np_011880.csv
  Dialogue/Fourier/np_010080.csv
  Dialogue/Io/np_010910.csv
  Dialogue/Io/np_012720.csv
  Dialogue/Kyokuya/od_060332061.csv
  Dialogue/Lucotte/od_060333067.csv
  Dialogue/Lucotte/od_060333117.csv
  Dialogue/Matoi/np_011850.csv
  Dialogue/Matoi/np_012130.csv
  Dialogue/Mid-Mission/ii_anh_fantasy_mob.csv
  Dialogue/Mid-Mission/ii_waker_ahl.csv
  Dialogue/Mid-Mission/ii_waker_bit_ahl_ev_waker.csv
  Dialogue/Pietro/np_012420.csv
  Dialogue/Stratos/np_014370.csv
  Misc/actor_name.csv
  Orders/Gene & co/2020 Anniversary/co06064903.csv
  Orders/Kyokuya/co06033206.csv
  Orders/_ARKS Missions/3 Event/ac06031221.csv
  Quests/Magatsu/ii_annihilation_mge.csv
  Story/Episode 6/Chapter 4/st_064040.csv
  Tutorial/Message Pack/mp_000387.csv
  UI/ui_bingo.csv
  UI/ui_item.csv
  UI/ui_shop.csv
  _aspell/PSO2.en_Chat.dict
  _aspell/PSO2.en_Enemies_Aberrations.dict
  _aspell/PSO2.en_Items.dict
  _aspell/PSO2.en_Misc.dict
  _aspell/PSO2.en_NPC.dict
  _aspell/PSO2.en_Names.dict
Labels: size/L

#1010 KO: additional UI translation
  Misc/actor_name.csv
  README.md
  UI/config.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1011 Es: little fix
  Dialogue/Popona/od_060645037.csv
  Misc/My Room/mikiri.csv
  Quests/Armada/pr_062010.csv
  Story/Episode 6/cap2/st_062045.csv
  Story/Episode 6/cap2/st_062060.csv
  Story/Episode 6/cap2/st_062070.csv
  Story/Episode 6/cap2/st_062080.csv
  Story/Episode 6/cap2/st_062087.csv
  Story/Episode 6/cap3/st_063010.csv
  Story/Episode 6/cap3/st_063110.csv
  Story/Episode 6/cap3/st_063120.csv
  Story/Episode 6/otros/un_063010.csv
Labels: size/L

#1016 KO: Additional Translation
  Files/cm_036210.csv
  Files/cm_036211.csv
  Files/cm_036212.csv
  Files/cm_036213.csv
  Files/cm_036214.csv
  Files/cm_036215.csv
  Files/cm_036216.csv
  Files/cm_036217.csv
  Files/pr_037010.csv
  Files/quest_00050480.csv
  Files/quest_00050570.csv
  Files/quest_00050640.csv
  Files/quest_00170090.csv
  Files/quest_00170150.csv
  Files/quest_00701700.csv
  Misc/actor_name.csv
  Quests/PD/cm_036210.csv
  Quests/PD/cm_036211.csv
  Quests/PD/cm_036212.csv
  Quests/PD/cm_036213.csv
  Quests/PD/cm_036214.csv
  Quests/PD/cm_036215.csv
  Quests/PD/cm_036216.csv
  Quests/PD/cm_036217.csv
  Quests/PD/pr_037010.csv
  Quests/PD/quest_00050480.csv
  Quests/PD/quest_00050570.csv
  Quests/PD/quest_00050640.csv
  Quests/PD/quest_00170090.csv
  Quests/PD/quest_00170150.csv
  Quests/quest_00701700.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1017 KO: Additional Translation
  Misc/actor_name.csv
  Quests/PD/cm_036213.csv
  Quests/PD/quest_00050480.csv
  Quests/PD/quest_00050570.csv
  Quests/PD/quest_00050640.csv
  Quests/PD/quest_00170090.csv
  Quests/PD/quest_00170150.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/XXL
