Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2020-09, with the labels that each got.

#1188 to begin our strategic operation. is no more
  UI/ui_challenge.csv
  UI/ui_directbuy_text.csv
  UI/ui_equipnote.csv
  UI/ui_esthetic_text.csv
  UI/ui_quest.csv
Labels: size/M

#1193 Fix some EP4 typos.
  Story/Episode 4/Chapter 5/st_045070.csv
  Story/Episode 4/Chapter 5/st_045090.csv
Labels: size/XS

#1184 EN: Lobby dialogue
  Dialogue/Amelin/np_010550.csv
  Dialogue/Azanami/np_010870.csv
  Dialogue/Barbara/np_010570.csv
  Dialogue/Claris Claes/np_012920.csv
  Dialogue/Girard/np_010530.csv
  Dialogue/Io/np_010910.csv
  Dialogue/Io/np_012720.csv
  Dialogue/Jozsef/np_010540.csv
  Dialogue/Keefus/np_011440.csv
  Dialogue/Kressida/np_010560.csv
  Dialogue/Lottie/np_010620.csv
  Dialogue/Lubert/np_010630.csv
  Dialogue/Lubert/np_012890.csv
  Dialogue/Pudding/np_010820.csv
  Dialogue/Revelle/np_010590.csv
  Dialogue/Rogio/np_013000.csv
  Dialogue/Zeno/np_010830.csv
  Files/np_011440.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/XL

#1196 yes
  UI/ui_item.csv
Labels: size/S

#1198 KO: fix typo
  Dialogue/E-Trial/ii_areaboss_db.csv
  Quests/Descriptions/quest_00050450.csv
  Quests/Primordial Darkness/co_069112.csv
  Quests/Primordial Darkness/co_069113.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
Labels: size/M

#1199 KO: EP3 Ch1 examine
  NPC/Ohza/Order/co03032010.csv
  Story/Episode 3/Chapter 1/ra_031010.csv
  Story/Episode 3/Chapter 1/ra_031030.csv
  Story/Episode 3/Chapter 1/ra_031050.csv
  Story/Episode 3/Chapter 1/st_030100.csv
  Story/Episode 3/Chapter 1/st_031010.csv
  Story/Episode 3/Chapter 1/st_031020.csv
  Story/Episode 3/Chapter 1/st_031030.csv
  Story/Episode 3/Chapter 1/st_031040.csv
  Story/Episode 3/Chapter 1/un_031010.csv
Labels: size/M

#1200 Es: Fixing
  Dialogue/Popona/od_060645037.csv
  Dialogue/Popona/od_060645041.csv
  Files/st_065090.csv
  Misc/np_012130.csv
  Orders/Kyokuya/co06033206.csv
  Story/Episode 1/st_010220.csv
  Story/Episode 2/st_020650.csv
  Story/Episode 2/st_020790.csv
  Story/Episode 3/ra_036020.csv
  Story/Episode 3/st_039050.csv
  Story/Episode 3/un_036010.csv
  Story/Episode 4/st_043120.csv
  Story/Episode 5/Cap 4/st_056220.csv
  Story/Episode 5/Cap 4/st_056225.csv
  Story/Episode 5/cap 6/st_058165.csv
  Story/Episode 6/Kyokuya/un_062010.csv
  Story/Episode 6/Kyokuya/un_062020.csv
  Story/Episode 6/Kyokuya/un_062080.csv
  Story/Episode 6/cap1/st_061100.csv
  Story/Episode 6/cap1/st_061110.csv
  Story/Episode 6/cap1/st_061120.csv
  Story/Episode 6/cap1/st_061130.csv
  Story/Episode 6/cap1/st_061136.csv
  Story/Episode 6/cap1/st_061140.csv
  Story/Episode 6/cap1/un_061030.csv
  Story/Episode 6/cap2/st_062060.csv
  Story/Episode 6/cap2/st_062085.csv
  Story/Episode 6/cap2/st_062087.csv
  Story/Episode 6/cap2/st_062090.csv
  Story/Episode 6/cap4/st_064030.csv
  Story/Episode 6/cap5/st_064070.csv
  Story/Episode 6/cap5/st_064075.csv
  Story/Episode 6/cap5/st_064078.csv
  Story/Episode 6/cap6/co_069111.csv
  Story/Episode 6/cap6/ii_session_apc_5661.csv
  Story/Episode 6/cap6/st_065090.csv
  Story/Episode 6/otros/un_065025.csv
  Story/Omnibus/st_010220_om.csv
  Story/Omnibus/st_020650_om.csv
Labels: size/L

#1201 EN: Final battle dialogue
  Dialogue/Final Battle/co_069101.csv
  Dialogue/Final Battle/co_069102.csv
  Dialogue/Final Battle/co_069103.csv
Labels: size/S

#1205 KO: Additional Translation
  Files/ui_mag.csv
  Files/un_020430.csv
  Files/un_020440.csv
  Files/un_020440_om.csv
  Files/un_032060.csv
  Misc/actor_name.csv
  Quests/Primordial Darkness/co_069104.csv
  Quests/Primordial Darkness/co_069105.csv
  README.md
  Story/Episode 3/Chapter 1/un_020430.csv
  Story/Episode 3/Chapter 1/un_020440.csv
  Story/Episode 3/Chapter 1/un_020440_om.csv
  Story/Episode 3/Chapter 1/un_031040.csv
  Story/Episode 3/Chapter 1/un_031070.csv
  Story/Episode 3/Chapter 1/un_031070_om.csv
  Story/Episode 3/Chapter 1/un_032060.csv
  Story/Episode 6/Chapter 6/st_065020.csv
  Story/Episode 6/Chapter 6/st_065030.csv
  UI/ui_craft.csv
  UI/ui_item.csv
  UI/ui_mag.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1206 Fix Zieg Takt exchanges.
  UI/ui_item.csv
Labels: size/XS

#1207 KO: Additional work
  Arks Mission/Event/Road To Luster/ac06031712.csv
  Arks Mission/Event/Road To Luster/ac06031713.csv
  Arks Mission/Event/Road To Luster/ac06031721.csv
  Arks Mission/Event/Road To Luster/ac06031722.csv
  Arks Mission/Event/Road To Luster/ac06031723.csv
  Arks Mission/Event/Road To Luster/ac06031732.csv
  Arks Mission/Event/Road To Luster/ac06031733.csv
  Dialogue/E-Trial/ii_areaboss_ab.csv
  Files/ac06031712.csv
  Files/ac06031713.csv
  Files/ac06031722.csv
  Files/ac06031723.csv
  Files/ac06031732.csv
  Files/ac06031733.csv
  Files/ls_010010.csv
  Files/ls_010020.csv
  Files/un_020460.csv
  Misc/Concert/ls_010010.csv
  Misc/Concert/ls_010020.csv
  Quests/Profound Darkness/quest_00050640.csv
  Quests/Profound Darkness/quest_00170150.csv
  Story/Episode 3/Chapter 1/un_020440.csv
  Story/Episode 3/Chapter 1/un_020440_om.csv
  Story/Episode 3/Chapter 1/un_020450.csv
  Story/Episode 3/Chapter 1/un_020460.csv
  Story/Episode 3/Chapter 1/un_031040.csv
  Story/Episode 3/Chapter 1/un_032060.csv
  Story/Episode 6/Kyokuya/un_061170.csv
Labels: size/L

#1209 Merge pull request #90 from Arks-Layer/ES
  Misc/np_012130.csv
  Story/Episode 5/np_014300.csv
  Story/Episode 6/cap5/st_064070.csv
  Story/Episode 6/cap5/st_064075.csv
Labels: size/M

#1212 Fix Melrondia's partner card.
  UI/ui_mainmode.csv
Labels: size/XS

#1213 Fix titled Profound Darkness mentions.
  Story/Episode 4/Chapter 5/un_046025.csv
  Story/Episode 5/st_051130.csv
Labels: size/XS

#1210 Fix returning player survey.
  UI/ui_title_text.csv
Labels: size/S

#1214 KO: Additional translation
  Arks Mission/Event/Road To Luster/ac06031743.csv
  Dialogue/E-Trial/ii_areaboss_df.csv
  Misc/Concert/ls_010020.csv
  Misc/actor_name.csv
  Quests/Story EP6 names/Chapter 6/quest_00302210.csv
  Quests/Story EP6 names/Chapter 6/quest_00302280.csv
  Quests/Time Attack/quest_00040110.csv
  Quests/quest_common.csv
  UI/config.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
Labels: size/L

#1216 Fix Silva/Rina/RINA voice salon choices.
  UI/ui_charamake_parts.csv
Labels: size/XS

#1221 Max7238 kyokuya patch 2
  Dialogue/_Partner chat/apc_chat_4.csv
  _aspell/PSO2.en_Chat.dict
Labels: size/L

#1215 Fix TPD Hitsugi's line.
  Quests/Primordial Darkness/ii_areaboss_db.csv
Labels: size/XS

#1224 Fix extra < in coding.
  Orders/Franka/co02040006.csv
  Tutorial/Tutorial List/wh_tl_co_060017.csv
  Tutorial/Window/co_060017.csv
Labels: size/S

#1217 EN: Couple of tutorials
  Dialogue/Azanami/od_020387007.csv
  Dialogue/Saga/od_030710001.csv
  Dialogue/Saga/od_030710007.csv
  Files/od_020387007.csv
  Files/od_030710007.csv
  Files/wh_tl_od_020387007.csv
  Files/wh_tl_od_030710007.csv
  Tutorial/Tutorial List/wh_tl_od_020387007.csv
  Tutorial/Tutorial List/wh_tl_od_030710007.csv
Labels: size/M

#1223 Translate TPD starting area Campship return.
  Files/ob_3250_0018.csv
  Quests/Primordial Darkness/ob_3250_0018.csv
Labels: size/XS

#1228 KO: Luster's translation
  Arks Mission/Event/Road To Luster/ac06031713.csv
  Arks Mission/Star Mission/ac06050101.csv
  Arks Mission/Star Mission/ac06050102.csv
  Arks Mission/Star Mission/ac06050103.csv
  Arks Mission/Star Mission/ac06050104.csv
  Arks Mission/Star Mission/ac06050105.csv
  Arks Mission/Star Mission/ac06050106.csv
  Arks Mission/Star Mission/ac06050107.csv
  Arks Mission/Star Mission/ac06050108.csv
  Arks Mission/Star Mission/ac06050109.csv
  Arks Mission/Star Mission/ac06050110.csv
  Arks Mission/Star Mission/ac06050111.csv
  Arks Mission/Star Mission/ac06050112.csv
  Arks Mission/Star Mission/ac06050205.csv
  Arks Mission/Star Mission/ac06050406.csv
  Arks Mission/Star Mission/ac06050504.csv
  Arks Mission/Star Mission/ac06050811.csv
  Arks Mission/Star Mission/ac06050812.csv
  Quests/quest_common.csv
  Story/Episode 6/Chapter 3/cm_064100.csv
  UI/ui_mainmode.csv
Labels: size/L

#1230 ES: Luster
  Misc/actor_name.csv
  UI/ui_mainmode.csv
Labels: size/L

#1229 KO: Star mission translation
  Arks Mission/Star Mission/ac06050313.csv
  Arks Mission/Star Mission/ac06050314.csv
  Arks Mission/Star Mission/ac06050315.csv
  Arks Mission/Star Mission/ac06050613.csv
  Arks Mission/Star Mission/ac06050614.csv
  Arks Mission/Star Mission/ac06050615.csv
  Arks Mission/Star Mission/ac06050616.csv
  Arks Mission/Star Mission/ac06050617.csv
  Arks Mission/Star Mission/ac06050713.csv
  Arks Mission/Star Mission/ac06050813.csv
  Arks Mission/Star Mission/ac06050814.csv
  Arks Mission/Star Mission/ac06050815.csv
  Arks Mission/Star Mission/ac06050816.csv
  Arks Mission/Star Mission/ac06051013.csv
  Arks Mission/Star Mission/ac06051014.csv
  Arks Mission/Star Mission/ac06051015.csv
  Files/ac06050313.csv
  Files/ac06050314.csv
  Files/ac06050315.csv
  Files/ac06050613.csv
  Files/ac06050614.csv
  Files/ac06050615.csv
  Files/ac06050616.csv
  Files/ac06050617.csv
  Files/ac06050713.csv
  Files/ac06050813.csv
  Files/ac06050814.csv
  Files/ac06050815.csv
  Files/ac06050816.csv
  Files/ac06051013.csv
  Files/ac06051014.csv
  Files/ac06051015.csv
  Files/co06010021.csv
  Files/co06010022.csv
  Files/co06010023.csv
  Files/co06010024.csv
  Misc/actor_name.csv
  NPC/Koffie/Order/co06010021.csv
  NPC/Koffie/Order/co06010022.csv
  NPC/Koffie/Order/co06010023.csv
  NPC/Koffie/Order/co06010024.csv
  Quests/quest_common.csv
  Quests/quest_counter.csv
  UI/common.csv
  UI/np_npc_00cmn.csv
  UI/ui_item.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
  UI/ui_title_text.csv
Labels: size/XL

#1232 EN: Vegas in viva
  Files/cm_060506.csv
  Files/cm_060508.csv
  Files/cm_060509.csv
  Files/cm_060510.csv
  Files/cm_060511.csv
  Files/cm_060512.csv
  Files/co_060043.csv
  Files/mp_000564.csv
  Files/quest_00051190.csv
  Files/quest_00170870.csv
  Quests/Seasonal/Vegas/cm_060506.csv
  Quests/Seasonal/Vegas/cm_060507.csv
  Quests/Seasonal/Vegas/cm_060508.csv
  Quests/Seasonal/Vegas/cm_060509.csv
  Quests/Seasonal/Vegas/cm_060510.csv
  Quests/Seasonal/Vegas/cm_060511.csv
  Quests/Seasonal/Vegas/cm_060512.csv
  Quests/Seasonal/Vegas/cm_060513.csv
  Quests/Seasonal/Vegas/co_060043.csv
  Quests/Seasonal/Vegas/mp_000564.csv
  Quests/Seasonal/Vegas/quest_00051190.csv
  Quests/Seasonal/Vegas/quest_00170870.csv
  Quests/Tutorial/cm_062170_01.csv
Labels: size/M

#1231 KO: Additional Translation
  Arks Mission/Event/Road To Luster/ac06031721.csv
  Arks Mission/Event/Road To Luster/ac06031722.csv
  Arks Mission/Event/Road To Luster/ac06031723.csv
  Arks Mission/Star Mission/ac06050101.csv
  Arks Mission/Star Mission/ac06050102.csv
  Arks Mission/Star Mission/ac06050103.csv
  Arks Mission/Star Mission/ac06050104.csv
  Arks Mission/Star Mission/ac06050105.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
Labels: size/L

#1234 KO: fix typo
  Misc/actor_name.csv
Labels: size/XS

#1235 Luccote's Autowords
  Dialogue/_Partner chat/apc_chat_4.csv
Labels: size/L

#1238 Various fixes.
  Dialogue/Koffie/np_010501.csv
  Dialogue/_Partner chat/apc_chat_4.csv
  Orders/_ARKS Missions/3 Event/ac06032032.csv
  UI/quest_counter.csv
  UI/ui_charamake_parts.csv
  UI/ui_equipnote.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
  _aspell/PSO2.en_Misc.dict
Labels: size/M

#1237 KO: Addditional Translation
  Arks Mission/Star Mission/ac06050816.csv
  Dialogue/E-Trial/heatup.csv
  Dialogue/E-Trial/ii_areaboss_bh.csv
  Dialogue/E-Trial/ii_areaboss_prism.csv
  Dialogue/E-Trial/ii_beach_naura_search.csv
  Dialogue/E-Trial/ii_boss_ahl_3boss.csv
  Dialogue/E-Trial/ii_boss_ahl_dk.csv
  Dialogue/E-Trial/ii_boss_ahl_m_oarfish.csv
  Dialogue/E-Trial/ii_boss_ahl_m_oarfish_ev.csv
  Dialogue/E-Trial/ii_boss_ahl_nyau.csv
  Dialogue/E-Trial/ii_boss_ahl_nyau_ev_boss.csv
  Dialogue/E-Trial/ii_boss_ahl_nyau_ev_rare.csv
  Dialogue/E-Trial/ii_boss_ahl_nyau_ev_two.csv
  Dialogue/E-Trial/ii_boss_ahl_remaining_buff.csv
  Dialogue/E-Trial/ii_boss_ahl_timelimit.csv
  Dialogue/E-Trial/ii_boss_ahl_volcano.csv
  Files/quest_00170690.csv
  Files/st_062040.csv
  Files/st_062045.csv
  Files/st_062050.csv
  Misc/actor_name.csv
  Quests/Armada/quest_00170690.csv
  Quests/Primordial Darkness/quest_00051160.csv
  Quests/Primordial Darkness/quest_00170830.csv
  Quests/Story EP6 names/Chapter 6/quest_00302295.csv
  Story/Episode 3/Chapter 1/un_020450.csv
  Story/Episode 6/Chapter 2/st_062040.csv
  Story/Episode 6/Chapter 2/st_062045.csv
  Story/Episode 6/Chapter 2/st_062050.csv
  Story/Episode 6/Chapter 6/st_065119.csv
  UI/ui_item.csv
  UI/ui_na_mainmode.csv
Labels: size/XXL

#1239 KO: Fix story
  Files/quest_00300010.csv
  Misc/Movies/mv_010010.csv
  Misc/Movies/mv_010011.csv
  Misc/Movies/mv_030010.csv
  Misc/actor_name.csv
  Quests/Tutorial/cm_062080_01.csv
  Quests/quest_common.csv
  Story/Episode 0/st_010005.csv
  Story/Episode 0/st_010010.csv
  Story/Episode 0/st_010020.csv
  Story/Episode 0/st_010030.csv
  Story/Episode 0/st_010030_fs.csv
  Story/Episode 0/st_010040.csv
  Story/Episode 0/st_010050.csv
  Story/Episode 0/st_010060.csv
  Story/Episode 0/st_010060_fs.csv
  Story/Episode 0/st_010070.csv
  Story/Episode 0/st_010080.csv
  Story/Episode 0/st_010080_fs.csv
  Story/Episode 0/st_010090.csv
  Story/Episode 0/st_010100.csv
  Story/Episode 0/st_010100_fs.csv
  Story/Episode 0/st_010110.csv
  Story/Episode 5/Chapter 1/가면을 되찾는 작전/quest_00300007.csv
  Story/Episode 5/Chapter 1/가면을 되찾는 작전/st_051020.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/quest_00300010.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/st_051030.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/st_051040.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/st_051050.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/st_051060.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/st_051070.csv
  Story/Episode 5/Chapter 1/구해낸 손끝에/st_051080.csv
  Story/Episode 5/Chapter 1/오메가/quest_00300016.csv
  Story/Episode 5/Chapter 1/오메가/st_051100.csv
  Tutorial/Quest/co_012030.csv
  UI/common.csv
  UI/ui_charamake_parts.csv
  UI/ui_gacha.csv
  UI/ui_na_mainmode.csv
  UI/ui_selectmenu_text.csv
Labels: size/XL

#1242 Various fixes
  UI/item_element_name.csv
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/S

#1244 KO: additional translation
  Dialogue/E-Trial/darker_trap.csv
  Dialogue/E-Trial/darker_trap_cage.csv
  Dialogue/E-Trial/ii_collect_goods_a.csv
  Dialogue/E-Trial/ii_collect_goods_b.csv
  Dialogue/E-Trial/ii_collect_goods_c.csv
  Dialogue/E-Trial/ii_collect_sample.csv
  Dialogue/E-Trial/ii_darkercore.csv
  Dialogue/E-Trial/ii_defense_from_mge.csv
  Dialogue/E-Trial/ii_destroy_neo_burufu.csv
  Dialogue/E-Trial/ii_destroy_phs_cannon.csv
  Dialogue/E-Trial/ii_destroy_pirate_ship.csv
  Dialogue/E-Trial/ii_dpp_chase.csv
  Dialogue/E-Trial/incident_common.csv
  Files/cm_060506.csv
  Files/cm_060507.csv
  Files/cm_060508.csv
  Files/cm_060509.csv
  Files/cm_060510.csv
  Files/cm_060511.csv
  Files/cm_060512.csv
  Files/cm_060513.csv
  Files/quest_00051190.csv
  Files/quest_00170870.csv
  Misc/Concert/ls_010020.csv
  NPC/Itsuki/E trial/ii_session_apc_5318.csv
  NPC/SORO/E trial/ii_session_apc_5315.csv
  Quests/Arks Quest/quest_00030220.csv
  Quests/Dark Falz/Persona/cm_0511114.csv
  Quests/Seasonal/Vegas/cm_060506.csv
  Quests/Seasonal/Vegas/cm_060507.csv
  Quests/Seasonal/Vegas/cm_060508.csv
  Quests/Seasonal/Vegas/cm_060509.csv
  Quests/Seasonal/Vegas/cm_060510.csv
  Quests/Seasonal/Vegas/cm_060511.csv
  Quests/Seasonal/Vegas/cm_060512.csv
  Quests/Seasonal/Vegas/cm_060513.csv
  Quests/Seasonal/Vegas/co_060043.csv
  Quests/Seasonal/Vegas/mp_000564.csv
  Quests/Seasonal/Vegas/quest_00051190.csv
  Quests/Seasonal/Vegas/quest_00170870.csv
  Quests/Ultimate Quests/Battleship/cm_064002.csv
  Quests/quest_common.csv
  UI/common.csv
  UI/ui_esthetic_text.csv
  UI/ui_gacha.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
Labels: size/XL

#1245 seasonal vegas EQ tutorial + message pack
  Files/co_060069.csv
  Files/mp_000570.csv
  Quests/Seasonal/Vegas/co_060069.csv
  Quests/Seasonal/Vegas/mp_000570.csv
Labels: size/S

#1247 typo fix in story subquest
  Story/Episode 6/Chapter 6/un_065180.csv
Labels: size/XS
