Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-03, with the labels that each got.

#1321 Es
  Dialogue/Koffie/co_060901.csv
  Dialogue/Xie (Anniversary)/np_010970.csv
  Files/ac06032211.csv
  Files/ac06032212.csv
  Files/ac06032213.csv
  Files/ac06032221.csv
  Files/ac06032222.csv
  Files/ac06032223.csv
  Files/ac06032231.csv
  Files/ac06032232.csv
  Files/ac06032233.csv
  Files/ac06032241.csv
  Files/ac06032242.csv
  Files/ac06032243.csv
  Files/ac06032251.csv
  Files/ac06032252.csv
  Files/ac06032253.csv
  Files/ac06032261.csv
  Files/ac06032262.csv
  Files/ac06032263.csv
  Files/ac06032282.csv
  Files/co_060901.csv
  Orders/_ARKS Missions/3 evento/ac06032211.csv
  Orders/_ARKS Missions/3 evento/ac06032212.csv
  Orders/_ARKS Missions/3 evento/ac06032213.csv
  Orders/_ARKS Missions/3 evento/ac06032221.csv
  Orders/_ARKS Missions/3 evento/ac06032222.csv
  Orders/_ARKS Missions/3 evento/ac06032223.csv
  Orders/_ARKS Missions/3 evento/ac06032231.csv
  Orders/_ARKS Missions/3 evento/ac06032232.csv
  Orders/_ARKS Missions/3 evento/ac06032233.csv
  Orders/_ARKS Missions/3 evento/ac06032241.csv
  Orders/_ARKS Missions/3 evento/ac06032242.csv
  Orders/_ARKS Missions/3 evento/ac06032243.csv
  Orders/_ARKS Missions/3 evento/ac06032251.csv
  Orders/_ARKS Missions/3 evento/ac06032252.csv
  Orders/_ARKS Missions/3 evento/ac06032253.csv
  Orders/_ARKS Missions/3 evento/ac06032261.csv
  Orders/_ARKS Missions/3 evento/ac06032262.csv
  Orders/_ARKS Missions/3 evento/ac06032263.csv
  Orders/_ARKS Missions/3 evento/ac06032271.csv
  Orders/_ARKS Missions/3 evento/ac06032282.csv
Labels: size/L

#1322 Pioneer II fixes.
  UI/ui_guild.csv
  UI/ui_mainmode.csv
Labels: size/XS

#1320 KO: Update new translation
  Files/ui_charamake_text_reb.csv
  Misc/actor_name.csv
  NPC/Magical Robo/Order/np_016440.csv
  NPC/Magical Robo/Order/od_060650047.csv
  NPC/Xie/Anniversary/8th/np_010970.csv
  Quests/Descriptions/quest_00050200.csv
  Quests/Descriptions/quest_00050310.csv
  Quests/quest_common.csv
  Quests/quest_counter.csv
  Tutorial/Window Help/wh_tl_co_011202.csv
  Tutorial/Window Help/wh_tl_co_021279.csv
  Tutorial/Window Help/wh_tl_co_021283.csv
  UI/apc_name.csv
  UI/common.csv
  UI/config.csv
  UI/item_element_expl.csv
  UI/item_element_name.csv
  UI/np_npc_00cmn.csv
  UI/ui_accessories_text.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_craft.csv
  UI/ui_esthetic_text.csv
  UI/ui_gacha.csv
  UI/ui_item.csv
  UI/ui_lobbymap.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1328 Es
  Files/ac06032272.csv
  Files/ac06032273.csv
  Files/ac06032281.csv
  Files/ac06032283.csv
  Files/ac06038011.csv
  Files/ac06038021.csv
  Files/ac06038031.csv
  Files/ac06038041.csv
  Files/ac06038042.csv
  Files/ac06038043.csv
  Files/ac06038044.csv
  Files/ac06038051.csv
  Files/ac06038052.csv
  Files/ac06038053.csv
  Files/ac06038111.csv
  Files/ac06038121.csv
  Files/ac06038131.csv
  Files/ac06038142.csv
  Files/ac06038143.csv
  Files/ac06038144.csv
  Files/ac06038151.csv
  Files/ac06038152.csv
  Files/ac06038153.csv
  Orders/_ARKS Missions/3 evento/ac06032271.csv
  Orders/_ARKS Missions/3 evento/ac06032272.csv
  Orders/_ARKS Missions/3 evento/ac06032273.csv
  Orders/_ARKS Missions/3 evento/ac06032281.csv
  Orders/_ARKS Missions/3 evento/ac06032283.csv
  Orders/_ARKS Missions/3 evento/ac06038011.csv
  Orders/_ARKS Missions/3 evento/ac06038021.csv
  Orders/_ARKS Missions/3 evento/ac06038031.csv
  Orders/_ARKS Missions/3 evento/ac06038041.csv
  Orders/_ARKS Missions/3 evento/ac06038042.csv
  Orders/_ARKS Missions/3 evento/ac06038043.csv
  Orders/_ARKS Missions/3 evento/ac06038044.csv
  Orders/_ARKS Missions/3 evento/ac06038051.csv
  Orders/_ARKS Missions/3 evento/ac06038052.csv
  Orders/_ARKS Missions/3 evento/ac06038053.csv
  Orders/_ARKS Missions/3 evento/ac06038111.csv
  Orders/_ARKS Missions/3 evento/ac06038121.csv
  Orders/_ARKS Missions/3 evento/ac06038131.csv
  Orders/_ARKS Missions/3 evento/ac06038142.csv
  Orders/_ARKS Missions/3 evento/ac06038143.csv
  Orders/_ARKS Missions/3 evento/ac06038144.csv
  Orders/_ARKS Missions/3 evento/ac06038151.csv
  Orders/_ARKS Missions/3 evento/ac06038152.csv
  Orders/_ARKS Missions/3 evento/ac06038153.csv
  UI/ui_charamake_text_reb.csv
Labels: size/XXL

#1326 Update co06065505.csv
  Orders/PSO 20th/co06065505.csv
Labels: size/XS

#1325 Update co06065504.csv
  Orders/PSO 20th/co06065504.csv
Labels: size/XS

#1324 Update co06065503.csv
  Orders/PSO 20th/co06065503.csv
Labels: size/XS

#1323 Update co06065502.csv
  Orders/PSO 20th/co06065502.csv
Labels: size/XS

#1327 Update co06065506.csv
  Orders/PSO 20th/co06065506.csv
Labels: size/XS

#1329 WIP update for new character creator stuff
  UI/config.csv
  UI/ui_charamake_text_reb.csv
Labels: size/L

#1330 Es: Here we go again
  Dialogue/Koffie/co_060901.csv
  Dialogue/Kyokuya/apc_chat_4.csv
  Orders/_ARKS Missions/3 evento/ac06032213.csv
  Orders/_ARKS Missions/3 evento/ac06032263.csv
  Orders/_ARKS Missions/3 evento/ac06038041.csv
  Orders/_ARKS Missions/3 evento/ac06038042.csv
  Orders/_ARKS Missions/3 evento/ac06038051.csv
  Orders/_ARKS Missions/3 evento/ac06038111.csv
  Orders/_ARKS Missions/3 evento/ac06038121.csv
  Orders/_ARKS Missions/3 evento/ac06038131.csv
  Orders/_ARKS Missions/3 evento/ac06038151.csv
  Orders/_ARKS Missions/3 evento/ac06038152.csv
  Orders/_ARKS Missions/3 evento/ac06038153.csv
  Story/Episode 6/cap5/st_064060.csv
  UI/ui_charamake_text_reb.csv
Labels: size/M

#1334 KO: fix typo
  Files/co_060529.csv
  NPC/NEED FIND LOCATION/co_060529.csv
  NPC/NEED FIND LOCATION/od_060655011.csv
  NPC/NEED FIND LOCATION/od_060655017.csv
  NPC/NEED FIND LOCATION/od_060655021.csv
  NPC/NEED FIND LOCATION/od_060655027.csv
  NPC/NEED FIND LOCATION/od_060655031.csv
  NPC/NEED FIND LOCATION/od_060655037.csv
  NPC/NEED FIND LOCATION/od_060655041.csv
  NPC/NEED FIND LOCATION/od_060655047.csv
  NPC/NEED FIND LOCATION/od_060655051.csv
  NPC/NEED FIND LOCATION/od_060655057.csv
  NPC/NEED FIND LOCATION/od_060655061.csv
  NPC/NEED FIND LOCATION/od_060655067.csv
  NPC/Rico/np_npc_298.csv
  Quests/Limited Quest/PSO1/quest_00170930.csv
  UI/apc_name.csv
  UI/ui_charamake_text_reb.csv
Labels: size/L

#1336 PT: Changed the image in the ReadMe file
  Readme.md
Labels: size/XS

#1337 PT: Minor UI adjustments
  Interface/ui_title_text.csv
Labels: size/S

#1338 PT: Minor Adjustments
  Interface/ui_title_text.csv
Labels: size/S

#1340 PT: Testing the " ã "
  Interface/ui_ship_name.csv
Labels: size/XS

#1348 Update item_element_expl.csv
  UI/item_element_expl.csv
Labels: size/XL

#1349 Es
  UI/item_element_expl.csv
Labels: size/L

#1351 KO: Dialogue's translation
  NPC/NEED FIND LOCATION/np_016710.csv
  NPC/NEED FIND LOCATION/np_016720.csv
  Quests/Arks Ship/quest_00050160.csv
Labels: size/M

#1352 KO: fix typo
  Misc/actor_name.csv
  NPC/NEED FIND LOCATION/np_016710.csv
Labels: size/XS

#1354 ES: Gacha
  UI/refer.csv
  UI/ui_gacha.csv
  UI/ui_tips.csv
Labels: size/L

#1359 KO: Fix typo
  Dialogue/apc_chat_4.csv
  NPC/Koffie/Order/co06010024.csv
  Quests/quest_counter.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/S

#1360 Some fixes.
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/XS

#1361 [RU] - A temporary move
  Files/item_element_name.csv
  translated files/Misc/actor_name.csv
  translated files/UI/item_element_expl.csv
  translated files/UI/item_element_name.csv
  translated files/UI/ui_item.csv
  translated files/UI/ui_mainmode.csv
Labels: size/XXL

#1367 Various fixes.
  Misc/My Room/sp_greeting.csv
  Orders/_ARKS Missions/1 Daily/ac06010408.csv
  Orders/_ARKS Missions/4 Main/ac06040705.csv
  Story/Episode 6/Lucotte/un_063050.csv
  Story/Episode 6/Lucotte/un_063070.csv
  Story/Episode 6/Lucotte/un_064060.csv
  Story/Episode 6/Lucotte/un_064070.csv
  Story/Episode 6/Lucotte/un_064080.csv
  UI/config.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_equip.csv
  UI/ui_mainmode.csv
  UI/ui_supportpartoner.csv
  UI/ui_title_text.csv
Labels: size/L

#1370 KO: fix typo
  Arks Mission/Daily/ac06010401.csv
  Dialogue/apc_chat_2.csv
  NPC/Magical Robo/Order/co06065001.csv
  NPC/NEED FIND LOCATION/np_012980.csv
  NPC/Nekonomiya/Order/co06065003.csv
  Quests/Divide Quest/quest_00220060.csv
  Quests/Divide Quest/quest_00220065.csv
  Quests/Divide Quest/quest_00220070.csv
  Quests/Divide Quest/quest_00220075.csv
  Quests/Divide Quest/quest_00220080.csv
  Quests/Divide Quest/quest_00220085.csv
  Quests/Divide Quest/quest_00220090.csv
  Quests/Divide Quest/quest_00220095.csv
  Quests/Divide Quest/quest_00220100.csv
  Quests/Divide Quest/quest_00220105.csv
  Quests/quest_counter.csv
  Tutorial/Quest/co_011215.csv
  Tutorial/Quest/co_012024.csv
  Tutorial/Window Help/wh_tl_co_011160.csv
  Tutorial/Window Help/wh_tl_co_021281.csv
  UI/common.csv
  UI/config.csv
  UI/forced_move.csv
  UI/ui_amusement.csv
  UI/ui_craft.csv
  UI/ui_gacha.csv
  UI/ui_guild.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_myroom.csv
  UI/ui_selectmenu_text.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1371 KO: fix typo
  Arks Mission/Daily/ac06010408.csv
  Arks Mission/Star Mission/ac06050712.csv
  Arks Mission/Weekly/ac06020103.csv
  Arks Mission/Weekly/ac06020105.csv
  Arks Mission/Weekly/ac06020109.csv
  Arks Mission/Weekly/ac06020306.csv
  Dialogue/E-Trial/cm_040002.csv
  Misc/actor_name.csv
  NPC/Magical Robo/Order/co06065001.csv
  NPC/Nekonomiya/Order/co06065003.csv
  Tutorial/Window Help/wh_tl_co_011160.csv
  Tutorial/Window Help/wh_tl_co_011201.csv
  Tutorial/Window Help/wh_tl_co_021279.csv
  Tutorial/Window Help/wh_tl_co_021280.csv
  Tutorial/Window Help/wh_tl_co_021285.csv
  Tutorial/Window Help/wh_tl_co_031391.csv
  UI/ui_craft.csv
  UI/ui_group_chat.csv
  UI/ui_lobbymap.csv
  UI/ui_myroom.csv
  UI/ui_selectmenu_text.csv
  UI/ui_title_text.csv
Labels: size/M

#1372 KO: CO Translation
  Files/co03071015.csv
  Files/co03071016.csv
  Files/co03071017.csv
  Files/co03071018.csv
  Files/co06033301.csv
  Files/co06033302.csv
  Files/co06033303.csv
  Files/co06033304.csv
  Files/co06033305.csv
  Files/co06033306.csv
  Files/co06033311.csv
  NPC/Kyokuya/co06033204.csv
  NPC/Lucotte/co06033301.csv
  NPC/Lucotte/co06033302.csv
  NPC/Lucotte/co06033303.csv
  NPC/Lucotte/co06033304.csv
  NPC/Lucotte/co06033305.csv
  NPC/Lucotte/co06033306.csv
  NPC/Lucotte/co06033311.csv
  NPC/NEED FIND LOCATION/od_060655057.csv
  NPC/Saga/co03071015.csv
  NPC/Saga/co03071016.csv
  NPC/Saga/co03071017.csv
  NPC/Saga/co03071018.csv
  Quests/Challenge Quests/3 Cataclysm/co_060072.csv
  Quests/Challenge Quests/3 Cataclysm/mp_000572.csv
  UI/ui_challenge.csv
Labels: size/M

#1375 KO: fix typo
  Files/co03072001.csv
  Files/co03072010.csv
  NPC/katori/co03072001.csv
  NPC/katori/co03072010.csv
  UI/ui_charamake_text.csv
  UI/ui_guild.csv
  UI/ui_quest.csv
  UI/ui_title_text.csv
Labels: size/M
