Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-01, with the labels that each got.

#1296 KO: Fix typo
  Quests/Challenge Quests/3 Cataclysm/mp_000572.csv
  UI/item_element_expl.csv
  UI/np_npc_00cmn.csv
Labels: size/XS

#1298 KO: Spaaaaaaaaaace MAGATSUUUUUU!!!!!
  Files/cm_060301.csv
  Files/cm_060302.csv
  Files/cm_060303.csv
  Files/cm_060304.csv
  Files/cm_060305.csv
  Files/cm_060306.csv
  Files/cm_060307.csv
  Files/cm_060309.csv
  Files/cm_060310.csv
  Files/cm_060311.csv
  Files/quest_00080410.csv
  Files/quest_00170670.csv
  NPC/Koffie/Dialogue/Talk/np_010500.csv
  Quests/Limited Quest/Space Magatsu/cm_060301.csv
  Quests/Limited Quest/Space Magatsu/cm_060302.csv
  Quests/Limited Quest/Space Magatsu/cm_060303.csv
  Quests/Limited Quest/Space Magatsu/cm_060304.csv
  Quests/Limited Quest/Space Magatsu/cm_060305.csv
  Quests/Limited Quest/Space Magatsu/cm_060306.csv
  Quests/Limited Quest/Space Magatsu/cm_060307.csv
  Quests/Limited Quest/Space Magatsu/cm_060309.csv
  Quests/Limited Quest/Space Magatsu/cm_060310.csv
  Quests/Limited Quest/Space Magatsu/cm_060311.csv
  Quests/Limited Quest/Space Magatsu/quest_00080410.csv
  Quests/Limited Quest/Space Magatsu/quest_00170670.csv
  Quests/quest_common.csv
  UI/ui_quest.csv
Labels: size/L

#1303 KO: Solo Sodam's translation
  Files/ii_areaboss_df_duel.csv
  Files/quest_00130050.csv
  Quests/Ultimate Quests/Sodam/co_060065.csv
  Quests/Ultimate Quests/Sodam/ii_areaboss_df_duel.csv
  Quests/Ultimate Quests/Sodam/quest_00130050.csv
Labels: size/M

#1304 KO: misc translation
  Quests/Ultimate Quests/Sodam/quest_00130050.csv
  UI/ui_shop.csv
Labels: size/M

#1305 KO: fix typo
  Quests/Ultimate Quests/Sodam/quest_00130050.csv
  UI/ui_item.csv
Labels: size/S
