Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-04, with the labels that each got.

#1378 RU: Delete item_element_name.csv
  Files/item_element_name.csv
Labels: size/XXL

#1377 KO: minor updates
  Dialogue/E-Trial/cm_048611.csv
  Dialogue/E-Trial/ii_ev_enemybomb_boss.csv
  Files/pr_045010.csv
  Files/ui_equip.csv
  NPC/Saga/co03071007.csv
  NPC/Saga/co03071009.csv
  Quests/Limited Quest/Anniversary/8th/1st/quest_00080440.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/L

#1368 Various fixes.
  Dialogue/np_npc_shoppoint3.csv
  Dialogue/np_npc_shoptrade2.csv
  Dialogue/np_npc_shoptrade3.csv
  Misc/actor_name.csv
  Misc/calor.csv
  Story/Episode 4/Chapter 1/cm_041100.csv
  Story/Episode 5/st_055020.csv
  Tutorial/Window Help/wh_myshop_sell.csv
  UI/config.csv
  UI/quest_common.csv
  UI/quest_counter.csv
  UI/ui_challenge.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_craft.csv
  UI/ui_equipnote.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_myroom.csv
  UI/ui_shop.csv
  UI/ui_tips.csv
Labels: size/L

#1379 KO: minor update
  Files/quest_00080240.csv
  Files/quest_00170280.csv
  NPC/Lucotte/co06033301.csv
  NPC/Lucotte/co06033302.csv
  Quests/Descriptions/quest_00170280.csv
  Quests/Limited Quest/Episode 1-4/quest_00080240.csv
  UI/np_npc_00cmn.csv
Labels: size/M

#1376 Story and various fixes.
  Misc/Movies/mv_020090.csv
  Orders/Koffie/co04010042.csv
  Orders/Koffie/co06010009.csv
  Orders/Xie/Easter/2020/co06050405.csv
  Orders/_ARKS Missions/3 Event/ac06031553.csv
  Quests/Training Quests/quest_00161000.csv
  Story/Episode 4/pr_045010.csv
  Tutorial/Training Quests/10 Hero/tr_100012.csv
  UI/common.csv
  UI/quest_counter.csv
  UI/ui_charamake_parts.csv
  UI/ui_equipnote.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/L

#1380 Bingo and various fixes
  Orders/_Bingo/bo00002133.csv
  UI/ui_bingo.csv
  UI/ui_mainmode.csv
Labels: size/S

#1382 RU: minor upd
  Files/co06010002.csv
  Files/co06010012.csv
  Files/co06010018.csv
  translated files/Orders/Koffie/co05010232.csv
  translated files/Orders/Koffie/co06010002.csv
  translated files/Orders/Koffie/co06010012.csv
  translated files/Orders/Koffie/co06010018.csv
  translated files/UI/ui_item.csv
  translated files/UI/ui_mainmode.csv
Labels: size/M

#1383 RU: asap fix
  translated files/Misc/actor_name.csv
  translated files/UI/ui_charamake_text_reb.csv
  translated files/UI/ui_esthetic_text.csv
  translated files/UI/ui_gacha.csv
  translated files/UI/ui_item.csv
  translated files/UI/ui_mainmode.csv
Labels: size/M

#1384 Fix Style Purge
  UI/ui_mainmode.csv
Labels: size/XS

#1385 Various fixes
  Orders/Lisa/co01011300.csv
  UI/common.csv
  UI/ui_quest.csv
Labels: size/XS

#1387 Some fixes
  UI/common.csv
  UI/quest_common.csv
  UI/ui_guild.csv
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/M

#1391 Translate Recovery Terminal
  Files/ob_9900_0472.csv
Labels: size/M

#1392 KO: fix typo
  Arks Mission/Event/ac06032221.csv
  Arks Mission/Event/ac06032222.csv
  Arks Mission/Event/ac06032223.csv
  Arks Mission/Main/ac06040502.csv
  Files/quest_00080260.csv
  NPC/Jean/co01020025.csv
  Quests/Base Defense/quest_00100040.csv
  Quests/Base Defense/quest_00170040.csv
  Quests/Limited Quest/Episode 1-4/quest_00080260.csv
  UI/ui_item.csv
Labels: size/M

#1394 Ult Lillipa, Block Move and line break fixes.
  Quests/Ultimate Quests/quest_00130010.csv
  Tutorial/Dialogue/pr_048010.csv
  UI/common.csv
  UI/quest_counter.csv
  UI/ui_mainmode.csv
Labels: size/S

#1396 KO: Episode 5 Story stuff
  Files/st_058130.csv
  Files/st_058140.csv
  Files/st_058145.csv
  Files/st_058150.csv
  Files/st_058155.csv
  Files/st_058160.csv
  Files/st_058165.csv
  Files/st_058170.csv
  Quests/Story EP5 names/quest_00301350.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058130.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058140.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058145.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058150.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058155.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058160.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058165.csv
  Story/Episode 5/Chapter 6/전승을 새기는 구세의 영웅/st_058170.csv
  Story/Episode 6/Chapter 6/st_065086.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1395 Various fixes.
  Dialogue/Pietro/np_012422.csv
  Misc/actor_name.csv
  Orders/_Team/go03001002.csv
  Orders/_Team/go03001007.csv
  Orders/_Team/go03001057.csv
  Orders/_Team/go03001068.csv
  Orders/_Team/go03001093.csv
  Orders/_Team/go03001109.csv
  Orders/_Team/go04000010.csv
  Orders/_Team/go05005112.csv
  Orders/_Team/go05005113.csv
  Orders/_Team/go05005114.csv
  Quests/Base Defense/co_021282.csv
  Quests/Base Defense/quest_00100030.csv
  Quests/Base Defense/quest_00100040.csv
  Quests/Base Defense/quest_00100060.csv
  Quests/Base Defense/quest_00170030.csv
  Quests/Base Defense/quest_00170040.csv
  Quests/Base Defense/quest_00170190.csv
  Quests/Base Defense/ui_qu_defence.csv
  Quests/Descriptions/quest_00050450.csv
  Quests/Descriptions/quest_00170000.csv
  Quests/Loser/quest_00050270.csv
  Quests/Seasonal/Rain 02/quest_00050300.csv
  Quests/Story EP2 names/Chapter 4/quest_00702010.csv
  Story/Episode 2/st_020350.csv
  Tutorial/Message Pack/mp_000505.csv
  Tutorial/Quest/co_040116.csv
  Tutorial/Tutorial List/wh_tl_co_021281.csv
  Tutorial/Tutorial List/wh_tl_co_021282.csv
  Tutorial/Window/co_021281.csv
  UI/quest_common.csv
  UI/quest_counter.csv
  UI/ui_apc.csv
  UI/ui_charamake_parts.csv
  UI/ui_craft.csv
  UI/ui_gacha.csv
  UI/ui_group_chat.csv
  UI/ui_guild.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_quest.csv
  UI/ui_selectmenu_text.csv
  UI/ui_supportpartoner.csv
  UI/ui_title_text.csv
Labels: size/L

#1397 Fix CM3 line
  Quests/Challenge Quests/3 Cataclysm/quest_00120020.csv
Labels: size/XS

#1398 Fix Episode 5 LQ quest name
  Quests/Limited Quests/Episode 5 LQ/quest_00170660.csv
  UI/quest_counter.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/M

#1399 Various fixes
  Orders/Katori/co03072007.csv
  Orders/Saga/co03071007.csv
  Orders/Seraphy/co04063101.csv
  Orders/_Daily/do04921201.csv
  Orders/_Daily/do04921251.csv
  Orders/_Team/go03100001.csv
  Quests/Buster Quests/quest_00300210.csv
  Quests/Level-up Quests/Engulfed in Shadows/quest_00080230.csv
  Quests/Limited Quests/Episode 1-4 LQ/quest_00080240.csv
  Quests/Limited Quests/Episode 1-4 LQ/quest_00080250.csv
  Quests/Limited Quests/Episode 1-4 LQ/quest_00080260.csv
  Quests/Limited Quests/Episode 1-4 LQ/quest_00080270.csv
  Quests/Limited Quests/Episode 1-4 LQ/quest_00080280.csv
  Quests/Loser/quest_00050800.csv
  Quests/Loser/quest_00170370.csv
  Quests/Omega Apprentice/quest_00170460.csv
  Quests/Story EP4 names/Chapter 1/quest_00703400.csv
  Story/Episode 1/Chapter 5/st_010380.csv
  Story/Episode 1/Chapter 5/st_010380_om.csv
  Story/Episode 1/Chapter 6/un_011180.csv
  Story/Matterboard/mb00000021.csv
  Story/Matterboard/mb00000047.csv
  Story/Matterboard/mb00000056.csv
  Story/Matterboard/mb00000071.csv
  Story/Matterboard/mb00000108.csv
  Story/Matterboard/mb00000360.csv
  Story/Matterboard/mb00000363.csv
  Story/Matterboard/mb00000365.csv
  Story/Matterboard/mb00000373.csv
  Story/Matterboard/mb00000376.csv
  Story/Matterboard/mb00000388.csv
  Story/Matterboard/mb00000405.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_gat.csv
  UI/ui_mainmode.csv
Labels: size/M

#1400 Fix back sell to attendant window title
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_play_achievement.csv
Labels: size/S

#1401 Fix max damage cap and title category
  Quests/Destroyers of Light/quest_00050970.csv
  Quests/Destroyers of Light/quest_00170540.csv
  Quests/Endless Quest/2 Eternal Rondo/quest_00121001.csv
  Quests/Evil Dragon/quest_00050760.csv
  Quests/Evil Dragon/quest_00050770.csv
  Quests/Evil Dragon/quest_00170270.csv
  Quests/Evil Dragon/quest_00170320.csv
  Quests/Guides of Creation/quest_00050820.csv
  Quests/Guides of Creation/quest_00170390.csv
  Quests/Limited Quests/Episode 1-4 LQ/quest_00080280.csv
  Quests/Limited Quests/Revelry of Darkness/quest_00080350.csv
  Quests/Limited Quests/Revelry of Darkness/quest_00170510.csv
  Quests/Loser/quest_00050810.csv
  Quests/Loser/quest_00170380.csv
  Quests/Omega Persona/quest_00050900.csv
  Quests/Omega Persona/quest_00050910.csv
  Quests/Phantom God/quest_00050660.csv
  Quests/Phantom God/quest_00050690.csv
  Quests/Phantom God/quest_00170200.csv
  Quests/Ultimate Quests/Masquerade/quest_00130030.csv
  Quests/Yamato/quest_00050670.csv
  Quests/Yamato/quest_00170220.csv
  UI/ui_mainmode.csv
Labels: size/M

#1402 Various fixes
  Misc/actor_name.csv
  Orders/Jean/co01020038.csv
  Orders/Jean/co01020045.csv
  UI/ui_amusement.csv
  UI/ui_mainmode.csv
  UI/ui_pollute.csv
Labels: size/XXL

#1404 Some fixes
  Dialogue/Pietro/np_012422.csv
  Quests/Evil Dragon/ii_anh_rd.csv
  Quests/Tutorial/cm_062056_01.csv
  Tutorial/Quest/co_011024.csv
  Tutorial/Tutorial List/wh_tl_co_011024.csv
  UI/config.csv
Labels: size/M
