Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-09, with the labels that each got.

#1638 EN: Minor fixes
  UI/common.csv
  UI/ui_gacha.csv
Labels: size/XS

#1637 EN_Reboot: Minor fixes
  Translated/UI/common.csv
  Translated/UI/ui_item_reb.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_rebops.csv
  Translated/UI/ui_shop_reb.csv
Labels: size/S

#1639 KO_Reboot: Fix Typo
  Misc/apc_chat_1.csv
  Misc/apc_name.csv
  NPC Dialogue/np_npc_7206_001.csv
  Quest/Base Defense/qst_1120020024.csv
  Quest/Base Defense/qst_1120020202.csv
  Quest/Base Defense/qst_1120020203.csv
  Quest/Base Defense/qst_1120020204.csv
  Quest/Base Defense/qst_1120020205.csv
  Quest/Base Defense/qst_1120020206.csv
  UI/common.csv
  UI/config.csv
  UI/refer.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1640 KO_Reboot: Fix typo
  UI/ui_mainmode.csv
Labels: size/XS

#1641 KO: FIx Typo
  UI/ui_charamake_text_reb.csv
Labels: size/XS

#1642 EN_Reboot: Minor fix
  Translated/Dialog/trial_defence.csv
Labels: size/XS

#1645 KO_Reboot: update just one file
  NPC Dialogue/np_npc_7206_001.csv
Labels: size/XS

#1646 KO_Reboot: update filelist.txt
  filelist.txt
Labels: size/S

#1647 EN_Reboot: Sept 20th Hotfixes
  Translated/Dialog/trial_comet.csv
  Translated/Dialog/trial_cometrare.csv
  Translated/Tasks/Limited/2021-05-14 Beta/ls0060050102.csv
  Translated/Tasks/Limited/2021-05-14 Beta/ls0060060101.csv
  Translated/Tutorials/tut_006371.csv
  Translated/UI/common.csv
  Translated/UI/quest_common_reboot.csv
  Translated/UI/ui_item_reb.csv
  Translated/UI/ui_mainmode_reb.csv
  Translated/UI/ui_selectmenu_text.csv
Labels: size/M

#1648 Ru reboot: Just for test
  Files/apc_chat_1.csv
  Files/apc_name.csv
  Files/msn_011063_006.csv
  Files/np_npc_7009_001.csv
  Files/npc_760501.csv
  Files/ssn_011110.csv
  Files/ui_achievements.csv
  Files/ui_directbuy_text.csv
  Reboot/Story/02 The Mysterious Colossus/msc_010140.csv
  Reboot/UI/actor_name.csv
  Reboot/UI/actor_name_npc.csv
  Reboot/UI/common.csv
  Reboot/UI/config.csv
  Reboot/UI/object_common.csv
  Reboot/UI/quest_common_reboot.csv
  Reboot/UI/rebops_common.csv
  Reboot/UI/refer.csv
  Reboot/UI/region_mag_common.csv
  Reboot/UI/ui_achievements.csv
  Reboot/UI/ui_item.csv
  Reboot/UI/ui_item_reb.csv
  Reboot/UI/ui_mainmode.csv
  Reboot/UI/ui_mainmode_reb.csv
  Reboot/UI/ui_quest_reb.csv
  Reboot/UI/ui_rebops.csv
Labels: size/XXL

#1649 KO: homework
  UI/ui_accessories_text.csv
  UI/ui_charamake_parts.csv
Labels: size/XXL

#1650 KO: FIx typo
  UI/ui_charamake_parts.csv
Labels: size/L
