Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-08, with the labels that each got.

#1554 EN_Reboot: Fix Regional Mag Boost.
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#1555 EN: Fix Offline Character Creation.
  UI/ui_title_text.csv
Labels: size/XS

#1557 KO_Reboot: Update file list
  filelist.txt
Labels: size/XS

#1558 EN_Reboot: Various fixes.
  Translated/UI/region_mag_common.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_mainmode_reb.csv
Labels: size/S

#1559 EN: Various fixes.
  UI/ui_mainmode.csv
Labels: size/XS

#1563 KO: update more quest
  Files/tr_060000.csv
  Files/tr_060010.csv
  Files/tr_060020.csv
  Files/tr_060030.csv
  Files/tr_060040.csv
  Files/tr_060050.csv
  Files/tr_060060.csv
  Files/tr_060070.csv
  Files/tr_060080.csv
  Files/tr_060090.csv
  Quests/Training Quest/tr_060000.csv
  Quests/Training Quest/tr_060010.csv
  Quests/Training Quest/tr_060020.csv
  Quests/Training Quest/tr_060030.csv
  Quests/Training Quest/tr_060040.csv
  Quests/Training Quest/tr_060050.csv
  Quests/Training Quest/tr_060060.csv
  Quests/Training Quest/tr_060070.csv
  Quests/Training Quest/tr_060080.csv
  Quests/Training Quest/tr_060090.csv
  UI/ui_challenge.csv
Labels: size/L

#1561 EN_Reboot: Various fixes.
  Translated/Tutorials/tut_006331.csv
  Translated/UI/ui_item.csv
  Translated/UI/ui_item_reb.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_tutorial_reb.csv
Labels: size/M

#1565 es_volviendo
  Translated/Interfaz/ui_item.csv
  Translated/Interfaz/ui_mainmode.csv
Labels: size/S

#1567 EN: Aug 4th hotfix
  Tutorial/Window Help/wh_fashioncat.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1568 KO: update new files
  Quests/Challenge Quests/1 Start/cm_038101_5.csv
  Quests/Challenge Quests/1 Start/cm_038102_0.csv
  Quests/Challenge Quests/1 Start/cm_038103_6.csv
  Quests/Challenge Quests/1 Start/cm_038103_7.csv
  Quests/Challenge Quests/1 Start/cm_038104_0.csv
  Quests/Challenge Quests/1 Start/cm_038104_1.csv
  Quests/Challenge Quests/1 Start/cm_038104_2.csv
  Quests/Challenge Quests/1 Start/cm_038104_3.csv
  Quests/Challenge Quests/1 Start/cm_038105_0.csv
  Quests/Challenge Quests/1 Start/cm_038105_2.csv
  Quests/Challenge Quests/1 Start/cm_038105_3.csv
  Quests/Challenge Quests/1 Start/cm_038105_4.csv
  Quests/Challenge Quests/1 Start/cm_038105_5.csv
  Quests/Challenge Quests/1 Start/cm_038120_0.csv
  Quests/Challenge Quests/2 Decision/cm_038204_9.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_item.csv
  UI/ui_title_text.csv
Labels: size/L

#1570 KO: fix typo
  UI/item_element_expl.csv
  UI/ui_item.csv
Labels: size/S

#1572 KO_Reboot: update filelist.txt
  filelist.txt
Labels: size/L

#1573 KO_Reboot: Update files
  Quest but need check/qst_1100050120.csv
  Quest but need check/qst_1100050150.csv
  Quest/ui_quest_counter_reb.csv
  Task/Limited/ls0061020101.csv
  Task/Limited/ls0061020102.csv
  Task/Limited/ls0061020103.csv
  Task/Limited/ls0061020104.csv
  Task/Limited/ls0061020105.csv
  Task/Limited/ls0064010101.csv
  Task/Limited/ls0064010102.csv
  Task/Limited/ls0064010103.csv
  Task/Limited/ls0064010104.csv
  Task/Limited/ls0064010105.csv
  Task/Limited/ls0064020101.csv
  Task/Limited/ls0064020102.csv
  Task/Limited/ls0064020103.csv
  Task/Limited/ls0064020104.csv
  Task/Limited/ls0064020105.csv
  Task/Limited/ls0064020106.csv
  Task/Limited/ls0064020108.csv
  Task/Limited/ls0064020109.csv
  Task/Limited/ls0064020111.csv
  Tutorial/tut_006259.csv
  Tutorial/tut_006277.csv
  Tutorial/tut_006300.csv
  Tutorial/tut_006315.csv
  Tutorial/tut_006353.csv
  Tutorial/tut_006380.csv
  Tutorial/tut_006402.csv
  Tutorial/tut_006418.csv
  UI/ui_item.csv
  UI/ui_item_reb.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
  UI/ui_tutorial_guide.csv
Labels: size/L

#1577 EN_Reboot: Braver Trainer Quest Translated
  Files/ss0030766501.csv
  Translated/Tasks/Side/Deirdre/ss0030766501.csv
Labels: size/S

#1576 aina story subplot
  Files/msq_011500.csv
  Files/msq_011501.csv
  Files/msq_011502.csv
  Files/msq_011503.csv
  Files/msq_011510.csv
  Files/msq_011511.csv
  Files/msq_011512.csv
  Files/msq_011520.csv
  Files/msq_011530.csv
  Files/msq_011531.csv
  Files/msq_011532.csv
  Files/msq_011540.csv
  Files/msq_011550.csv
  Files/msq_011551.csv
  Files/ssc_011010.csv
  Files/ssc_011020.csv
  Files/ssc_011030.csv
  Files/ssc_011040.csv
  Files/ssc_011050.csv
  Files/ssc_011060.csv
  Files/ssn_011015.csv
  Files/ssn_011015_001.csv
  Translated/Story/08-09 Finding Bruder/msq_011500.csv
  Translated/Story/08-09 Finding Bruder/msq_011501.csv
  Translated/Story/08-09 Finding Bruder/msq_011502.csv
  Translated/Story/08-09 Finding Bruder/msq_011503.csv
  Translated/Story/08-09 Finding Bruder/msq_011510.csv
  Translated/Story/08-09 Finding Bruder/msq_011511.csv
  Translated/Story/08-09 Finding Bruder/msq_011512.csv
  Translated/Story/08-09 Finding Bruder/msq_011520.csv
  Translated/Story/08-09 Finding Bruder/msq_011530.csv
  Translated/Story/08-09 Finding Bruder/msq_011531.csv
  Translated/Story/08-09 Finding Bruder/msq_011532.csv
  Translated/Story/08-09 Finding Bruder/msq_011540.csv
  Translated/Story/08-09 Finding Bruder/msq_011550.csv
  Translated/Story/08-09 Finding Bruder/msq_011551.csv
  Translated/Story/08-09 Finding Bruder/ssc_011010.csv
  Translated/Story/08-09 Finding Bruder/ssc_011020.csv
  Translated/Story/08-09 Finding Bruder/ssc_011030.csv
  Translated/Story/08-09 Finding Bruder/ssc_011040.csv
  Translated/Story/08-09 Finding Bruder/ssc_011050.csv
  Translated/Story/08-09 Finding Bruder/ssc_011060.csv
  Translated/Story/08-09 Finding Bruder/ssn_011015.csv
  Translated/Story/08-09 Finding Bruder/ssn_011015_001.csv
Labels: size/L

#1579 KO_Reboot: Fix Typo
  Misc/actor_name_npc.csv
  Quest/Base Defense/qst_1120020001.csv
  Quest/Base Defense/qst_1120020024.csv
  Quest/Base Defense/qst_1120020104.csv
  Quest/Base Defense/qst_1120020105.csv
  Tutorial/tut_006413.csv
Labels: size/S

#1580 KO: fix error
  UI/common.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_title_text.csv
Labels: size/M

#1581 KO_Reboot: Update filelist.txt
  filelist.txt
Labels: size/M

#1582 KO_Reboot: Update filelist.txt
  filelist.txt
Labels: size/L

#1566 EN: Fix terms.
  UI/ui_craft.csv
  UI/ui_item.csv
Labels: size/XS

#1578 Deirdre braver dialogue
  Files/np_npc_7400_001.csv
  Files/ssn_014270.csv
  Files/ssn_014271.csv
  Files/ssn_019010_001.csv
  Files/ssn_019010_002.csv
  Files/ssn_019010_003.csv
  Files/ssn_019010_004.csv
  Files/ssn_019010_005.csv
  Files/ssn_019010_006.csv
  Files/ssn_019010_007.csv
  Files/ssn_019010_008.csv
  Files/ssq_014273.csv
  Files/ssq_019010_003.csv
  Files/ssq_019010_004.csv
  Files/ssq_019010_005.csv
  Translated/Dialog/Deirdre/np_npc_7400_001.csv
  Translated/Dialog/Deirdre/ssn_014270.csv
  Translated/Dialog/Deirdre/ssn_014271.csv
  Translated/Dialog/Deirdre/ssq_014273.csv
  Translated/Dialog/Xiandy/2021-07-07 Anniversary/ssn_019001.csv
  Translated/Dialog/Xiandy/ssn_019010_001.csv
  Translated/Dialog/Xiandy/ssn_019010_002.csv
  Translated/Dialog/Xiandy/ssn_019010_003.csv
  Translated/Dialog/Xiandy/ssn_019010_004.csv
  Translated/Dialog/Xiandy/ssn_019010_005.csv
  Translated/Dialog/Xiandy/ssn_019010_006.csv
  Translated/Dialog/Xiandy/ssn_019010_007.csv
  Translated/Dialog/Xiandy/ssn_019010_008.csv
  Translated/Dialog/Xiandy/ssq_019010_003.csv
  Translated/Dialog/Xiandy/ssq_019010_004.csv
  Translated/Dialog/Xiandy/ssq_019010_005.csv
Labels: size/L

#1584 Es reboot
  Files/actor_name.csv
  Files/actor_name_npc.csv
  Files/ssn_011110.csv
  Translated/Dialogos/Dozer/ssn_011110.csv
  Translated/Interfaz/actor_name.csv
  Translated/Interfaz/actor_name_npc.csv
  Translated/Interfaz/common.csv
  Translated/Interfaz/ui_item.csv
  Translated/Interfaz/ui_mainmode.csv
  Translated/Interfaz/ui_quest_reb.csv
  Translated/Tareas/Secundarias/Bono/ss0030741903.csv
  Translated/Tareas/Secundarias/Dantre/ss0030766202.csv
Labels: size/XXL

#1583 ES_Unos Cambios
  Translated/Interfaz/ui_item.csv
  Translated/Interfaz/ui_item_reb.csv
  Translated/Interfaz/ui_mainmode.csv
  Translated/Interfaz/ui_mainmode_reb.csv
Labels: size/L

#1585 Es_Reboot
  Translated/Interfaz/ui_mainmode_reb.csv
Labels: size/M

#1586 Update ui_quest_counter_reb.csv
  Translated/Interfaz/ui_quest_counter_reb.csv
Labels: size/L

#1588 KO_Reboot: Fix typo
  Misc/apc_chat_1.csv
  Misc/apc_name.csv
  Task/Side Story/ssc_011050.csv
Labels: size/L

#1590 Bono, segreto, Taoyuan dialog
  Files/ssn_013030.csv
  Files/ssn_013031.csv
  Files/ssn_013110.csv
  Files/ssn_013110_001.csv
  Files/ssn_013220.csv
  Files/ssn_013221.csv
  Files/ssq_013040.csv
  Files/ssq_013111.csv
  Files/ssq_013230.csv
  Translated/Dialog/Bono/ssn_013110.csv
  Translated/Dialog/Bono/ssn_013110_001.csv
  Translated/Dialog/Bono/ssq_013111.csv
  Translated/Dialog/Segreto/ssn_013030.csv
  Translated/Dialog/Segreto/ssn_013031.csv
  Translated/Dialog/Segreto/ssq_013040.csv
  Translated/Dialog/Taoyuan/ssn_013220.csv
  Translated/Dialog/Taoyuan/ssn_013221.csv
  Translated/Dialog/Taoyuan/ssq_013230.csv
Labels: size/L

#1591 KO_Reboot: 머지?? 암튼 옮겻음
  Files/quest_01200000.csv
  Story/Prologue/quest_01200000.csv
Labels: size/S

#1592 task dialogue for somua, bergmann, liu lin, nandel, oranje, hoxie
  Files/ssn_014020.csv
  Files/ssn_014021.csv
  Files/ssn_014050.csv
  Files/ssn_014051.csv
  Files/ssn_014100.csv
  Files/ssn_014101.csv
  Files/ssn_014160.csv
  Files/ssn_014160_001.csv
  Files/ssn_014230.csv
  Files/ssn_014231.csv
  Files/ssn_014250.csv
  Files/ssn_014251.csv
  Files/ssq_014030.csv
  Files/ssq_014031.csv
  Files/ssq_014060.csv
  Files/ssq_014070.csv
  Files/ssq_014110.csv
  Files/ssq_014161.csv
  Files/ssq_014240.csv
  Files/ssq_014260.csv
  Translated/Dialog/Bergmann/ssn_014160.csv
  Translated/Dialog/Bergmann/ssn_014160_001.csv
  Translated/Dialog/Bergmann/ssq_014161.csv
  Translated/Dialog/Dighal/ssn_012220.csv
  Translated/Dialog/Dighal/ssn_012221.csv
  Translated/Dialog/Hoxie/ssn_014230.csv
  Translated/Dialog/Hoxie/ssn_014231.csv
  Translated/Dialog/Hoxie/ssq_014240.csv
  Translated/Dialog/Liu Lin/ssn_014100.csv
  Translated/Dialog/Liu Lin/ssn_014101.csv
  Translated/Dialog/Liu Lin/ssq_014110.csv
  Translated/Dialog/Nandel/ssn_014250.csv
  Translated/Dialog/Nandel/ssn_014251.csv
  Translated/Dialog/Nandel/ssq_014260.csv
  Translated/Dialog/Oranje/ssn_014050.csv
  Translated/Dialog/Oranje/ssn_014051.csv
  Translated/Dialog/Oranje/ssq_014060.csv
  Translated/Dialog/Oranje/ssq_014070.csv
  Translated/Dialog/Rossa/ssn_014120.csv
  Translated/Dialog/Rossa/ssn_014120_001.csv
  Translated/Dialog/Rossa/ssq_014121.csv
  Translated/Dialog/Segreto/ssn_013030.csv
  Translated/Dialog/Segreto/ssq_013040.csv
  Translated/Dialog/Somua/ssn_014020.csv
  Translated/Dialog/Somua/ssn_014021.csv
  Translated/Dialog/Somua/ssq_014030.csv
  Translated/Dialog/Somua/ssq_014031.csv
  Translated/Story/04-05 DOLLS on Mt. Magnus/msn_011063_006.csv
  Translated/Story/08-09 Finding Bruder/msc_011450.csv
Labels: size/L

#1593 Es
  Files/ui_charamake_parts.csv
Labels: size/XL

#1596 ES_ interfas
  UI/ui_mainmode.csv
  UI/ui_selectmenu_text.csv
Labels: size/L

#1597 Update ui_mainmode.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1600 Update ui_mainmode.csv
  Files/ui_accessories_text.csv
  UI/config.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1602 Update apc_name.csv
  UI/apc_name.csv
Labels: size/L

#1601 EN: Minor fixes
  UI/ui_charamake_parts.csv
  UI/ui_title_text.csv
Labels: size/S

#1603 ES
  UI/quest_common.csv
  UI/ui_bingo.csv
  UI/ui_charamake_text.csv
  UI/ui_craft_name.csv
  UI/ui_esthetic_text.csv
  UI/ui_eventchronicle.csv
  UI/ui_fashion_catalog.csv
  UI/ui_fashion_manager_text.csv
  UI/ui_gacha.csv
  UI/ui_tips.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1606 EN_Reboot: Fix party settings.
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_mainmode_reb.csv
Labels: size/XS

#1607 KO: text for tests
  Dialogue/Should find it/np_npc_counterquest2.csv
  Story/Episode 6/Chapter 3/cm_064205.csv
  Story/Episode 6/Chapter 3/cm_064206.csv
  Story/Episode 6/Chapter 3/cm_064207.csv
  Story/Episode 6/Chapter 3/cm_064208.csv
  Story/Episode 6/Chapter 3/cm_064209.csv
  Story/Episode 6/Chapter 3/cm_064210.csv
  Story/Episode 6/Chapter 3/cm_064211.csv
Labels: size/M

#1595 Es_reboot
  Files/mt0199905000.csv
  Files/mt0199907000.csv
  Files/mt0199908000.csv
  Files/mt0199909000.csv
  Files/mt0199910000.csv
  Files/mt0199911000.csv
  Files/mt0199913000.csv
  Files/mt0199914000.csv
  Files/mt0199915000.csv
  Files/mt0199916000.csv
  Files/mt0199917000.csv
  Files/mt0299901000.csv
  Files/mt0299902000.csv
  Files/mt0299903000.csv
  Files/mt0299904000.csv
  Files/mt0299906000.csv
  Files/mt0299907000.csv
  Translated/Interfaz/np_npc_00cmn_reboot.csv
  Translated/Interfaz/quest_common_reboot.csv
  Translated/Interfaz/rebops_common.csv
  Translated/Interfaz/region_mag_common.csv
  Translated/Interfaz/ui_equip.csv
  Translated/Interfaz/ui_group_chat.csv
  Translated/Interfaz/ui_item.csv
  Translated/Interfaz/ui_scratch_reb.csv
  Translated/Misiones/titulos/mt0199905000.csv
  Translated/Misiones/titulos/mt0199907000.csv
  Translated/Misiones/titulos/mt0199908000.csv
  Translated/Misiones/titulos/mt0199909000.csv
  Translated/Misiones/titulos/mt0199910000.csv
  Translated/Misiones/titulos/mt0199911000.csv
  Translated/Misiones/titulos/mt0199913000.csv
  Translated/Misiones/titulos/mt0199914000.csv
  Translated/Misiones/titulos/mt0199915000.csv
  Translated/Misiones/titulos/mt0199916000.csv
  Translated/Misiones/titulos/mt0199917000.csv
  Translated/Misiones/titulos/mt0299901000.csv
  Translated/Misiones/titulos/mt0299902000.csv
  Translated/Misiones/titulos/mt0299903000.csv
  Translated/Misiones/titulos/mt0299904000.csv
  Translated/Misiones/titulos/mt0299906000.csv
  Translated/Misiones/titulos/mt0299907000.csv
Labels: size/XL

#1604 apc_chat completed
  Files/apc_chat_1.csv
  Translated/Dialog/apc_chat_1.csv
Labels: size/XXL

#1608 EN: Hotfixes.
  UI/common.csv
  UI/item_element_expl_reb.csv
  UI/quest_common.csv
  UI/quest_counter.csv
  UI/ui_craft.csv
  UI/ui_fashion_catalog.csv
  UI/ui_guild.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
  UI/ui_pet.csv
  UI/ui_petlabo.csv
  UI/ui_poka_text.csv
  UI/ui_quest.csv
  UI/ui_ship_battle.csv
Labels: size/L

#1609 EN_Reboot: Hotfixes.
  Translated/UI/ui_item.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_na_mainmode.csv
Labels: size/L

#1605 Update ui_gat.csv
  Misc/actor_name.csv
  UI/quest_counter.csv
  UI/ui_gat.csv
  UI/ui_lobbymap.csv
Labels: size/XXL

#1611 ES correcciones en nombres
  Dialogue/np_npc_00cmn.csv
  Misc/actor_name.csv
  UI/ui_title_text.csv
Labels: size/L

#1612 KO_Reboot: Fix typo
  Misc/apc_chat_1.csv
  Misc/apc_name.csv
  Quest/ui_quest_reb.csv
  UI/common.csv
  UI/config.csv
  UI/refer.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/XXL

#1614 ES: Casino
  Misc/actor_name.csv
  Tutorial/Dialogue/co_031373.csv
  Tutorial/Tutorial List/wh_tl_co_031373.csv
  UI/date.csv
  UI/forced_move.csv
  UI/item_element_name.csv
  UI/oa_emplacement_common.csv
  UI/refer.csv
  UI/terminal_object.csv
  UI/ui_amusement.csv
  UI/ui_apc.csv
  UI/ui_basnet_text.csv
  UI/ui_beginner_guide.csv
  UI/ui_billing_direct.csv
Labels: size/XXL

#1615 ES: detalles
  UI/ui_briefing.csv
  UI/ui_challenge.csv
Labels: size/L

#1616 ES Ui
  UI/ui_charamake_text_reb.csv
  UI/ui_charamake_text_sp.csv
  UI/ui_craft.csv
Labels: size/XXL

#1617 ES: Update ui_directbuy_text.csv
  UI/ui_directbuy_text.csv
  UI/ui_equip.csv
Labels: size/L

#1618 ES: Update ui_equipnote.csv
  UI/ui_equipnote.csv
  UI/ui_gat_mat2item.csv
  UI/ui_group_chat.csv
  UI/ui_guild.csv
  UI/ui_help.csv
Labels: size/XL

#1619 ES: Update ui_item.csv
  UI/ui_item.csv
  UI/ui_mag.csv
  UI/ui_matterboard.csv
  UI/ui_missionboard.csv
  UI/ui_myroom.csv
  UI/ui_newly.csv
  UI/ui_pet.csv
  UI/ui_petlabo.csv
  UI/ui_play_achievement.csv
Labels: size/XXL

#1622 Es reboot Sera asi?
  Translated/Interfaz/config.csv
  Translated/Interfaz/ui_mainmode_reb.csv
Labels: size/M

#1630 ES: interfaz
  UI/No aplica en NA/ui_portrait.csv
  UI/apc_name.csv
  UI/common.csv
  UI/ui_poka_text.csv
  UI/ui_pollute.csv
  UI/ui_qu_eternal.csv
  UI/ui_qu_extra.csv
  UI/ui_quest.csv
  UI/ui_selectmenu_text.csv
  UI/ui_ship_battle.csv
  UI/ui_ship_name.csv
  UI/ui_shop.csv
  UI/ui_storyboard.csv
  UI/ui_supportpartoner.csv
  UI/ui_symbol.csv
  UI/ui_tutorial.csv
Labels: size/XXL

#1631 context fixed
  Translated/Dialog/Rossa/ssq_014121.csv
Labels: size/XS

#1634 EN_Reboot: Minor fixes
  Translated/UI/ui_item.csv
Labels: size/XS

#1629 EN: Various fixes
  UI/ui_accessories_text.csv
  UI/ui_charamake_parts.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/XL

#1636 EN: Minor fix
  UI/ui_charamake_parts.csv
Labels: size/S

#1635 EN_Reboot: Minor fix
  Translated/UI/common.csv
Labels: size/XS
