Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-06, with the labels that each got.

#1421 Various fixes Part 2
  Dialogue/np_npc_00cmn.csv
  UI/common.csv
  UI/quest_counter.csv
  UI/refer.csv
  UI/ui_esthetic_text.csv
  UI/ui_guild.csv
  UI/ui_title_text.csv
Labels: size/L

#1429 EN_Reboot: NPC hello/goodbyes
  Files/np_npc_7004_001.csv
  Files/np_npc_7006_001.csv
  Files/np_npc_7007_001.csv
  Files/np_npc_7008_001.csv
  Translated/Dialog/Crawford/np_npc_7004_001.csv
  Translated/Dialog/Liu Lin/np_npc_7007_001.csv
  Translated/Dialog/Ran/np_npc_7006_001.csv
  Translated/Dialog/Rossa/np_npc_7008_001.csv
Labels: size/M

#1436 EN_Reboot: Translations for files: tut_006222. tut_006254, and tut_006256
  Files/tut_006254.csv
  Files/tut_006256.csv
  Translated/Tutorials/tut_006222.csv
  Translated/Tutorials/tut_006254.csv
  Translated/Tutorials/tut_006256.csv
  Translated/tut_006222.csv
Labels: size/S

#1437 EN_REboot: Restoring translated ui_mainmode.csv
  Translated/UI/ui_mainmode.csv
Labels: size/L

#1440 EN_Reboot : Translate main story quest
  Files/ms0010100101.csv
  Files/ms0010100103.csv
  Files/ms0010100104.csv
  Files/ms0010100105.csv
  Files/ms0010100108.csv
  Files/ms0010100121.csv
  Files/ms0010100123.csv
  Files/ms0010100126.csv
  Translated/Quests/Main Story/ms0010100101.csv
  Translated/Quests/Main Story/ms0010100102.csv
  Translated/Quests/Main Story/ms0010100103.csv
  Translated/Quests/Main Story/ms0010100104.csv
  Translated/Quests/Main Story/ms0010100105.csv
  Translated/Quests/Main Story/ms0010100106.csv
  Translated/Quests/Main Story/ms0010100107.csv
  Translated/Quests/Main Story/ms0010100108.csv
  Translated/Quests/Main Story/ms0010100109.csv
  Translated/Quests/Main Story/ms0010100110.csv
  Translated/Quests/Main Story/ms0010100120.csv
  Translated/Quests/Main Story/ms0010100121.csv
  Translated/Quests/Main Story/ms0010100122.csv
  Translated/Quests/Main Story/ms0010100123.csv
  Translated/Quests/Main Story/ms0010100124.csv
  Translated/Quests/Main Story/ms0010100125.csv
  Translated/Quests/Main Story/ms0010100126.csv
  Translated/Quests/Main Story/ms0010100127.csv
  Translated/Tasks/Side/ss0030766051.csv
Labels: size/L

#1434 EN_REboot: Some capitalization improvements and obvious word translations
  Translated/Dialog/trial_defence.csv
  Translated/Tasks/Daily/ed0610010320.csv
  Translated/Tasks/Side/ss0030766051.csv
  Translated/UI/access_info.csv
Labels: size/XS

#1441 EN_Reboot: translatos before breakkie
  Files/np_npc_7009_001.csv
  Files/np_npc_7195_001.csv
  Files/np_npc_7196_001.csv
  Files/np_npc_7199_001.csv
  Files/np_npc_7200_001.csv
  Files/np_npc_7201_001.csv
  Files/np_npc_7202_001.csv
  Files/np_npc_7203_001.csv
  Files/np_npc_7206_001.csv
  Files/np_npc_7207_001.csv
  Files/np_npc_7208_001.csv
  Files/np_npc_7209_001.csv
  Files/np_npc_7210_001.csv
  Files/np_npc_7211_001.csv
  Files/np_npc_7417_001.csv
  Files/np_npc_7418_001.csv
  Translated/Dialog/Bergmann/np_npc_7418_001.csv
  Translated/Dialog/Crochet/np_npc_7208_001.csv
  Translated/Dialog/Dachua/np_npc_7196_001.csv
  Translated/Dialog/Dighal/np_npc_7417_001.csv
  Translated/Dialog/Eterna/np_npc_7209_001.csv
  Translated/Dialog/Eutroy/np_npc_7207_001.csv
  Translated/Dialog/Frankie/np_npc_7202_001.csv
  Translated/Dialog/Franme/np_npc_7203_001.csv
  Translated/Dialog/Guiden/np_npc_7199_001.csv
  Translated/Dialog/Kartevie/np_npc_7200_001.csv
  Translated/Dialog/Koharu/np_npc_7211_001.csv
  Translated/Dialog/Misha/np_npc_7206_001.csv
  Translated/Dialog/Oranje/np_npc_7009_001.csv
  Translated/Dialog/Slona/np_npc_7195_001.csv
  Translated/Dialog/Somua/np_npc_7201_001.csv
  Translated/Dialog/Travis/np_npc_7210_001.csv
Labels: size/M

#1445 Graphics Settings edit, cleanup
  Translated/UI/config.csv
Labels: size/S

#1446 EN: post cleanup of manually merge of PSO2:NGS changes
  UI/config.csv
  UI/oa_emplacement_common.csv
  UI/quest_common.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_newly.csv
  UI/ui_title_text.csv
Labels: size/M

#1444 EN_Reboot: Translated Weekly tasks
  Files/ew0620000104.csv
  Files/ew0620000201.csv
  Files/ew0620000202.csv
  Files/ew0620000203.csv
  Files/ew0620000204.csv
  Files/ew0620000299.csv
  Files/ew0620000301.csv
  Files/ew0620000302.csv
  Files/ew0620000303.csv
  Files/ew0620000304.csv
  Files/ew0620000399.csv
  Files/ew0621010101.csv
  Files/ew0621010102.csv
  Files/ew0621010201.csv
  Translated/Tasks/Weekly/2021 Anniversary/ew0621010101.csv
  Translated/Tasks/Weekly/2021 Anniversary/ew0621010102.csv
  Translated/Tasks/Weekly/2021 Anniversary/ew0621010201.csv
  Translated/Tasks/Weekly/ew0620000104.csv
  Translated/Tasks/Weekly/ew0620000201.csv
  Translated/Tasks/Weekly/ew0620000202.csv
  Translated/Tasks/Weekly/ew0620000203.csv
  Translated/Tasks/Weekly/ew0620000204.csv
  Translated/Tasks/Weekly/ew0620000299.csv
  Translated/Tasks/Weekly/ew0620000301.csv
  Translated/Tasks/Weekly/ew0620000302.csv
  Translated/Tasks/Weekly/ew0620000303.csv
  Translated/Tasks/Weekly/ew0620000304.csv
  Translated/Tasks/Weekly/ew0620000399.csv
Labels: size/M

#1449 Ko_Reboot: still translating side task stuff
  E-Trial/trial_common.csv
  Files/access_info.csv
  Files/object_common.csv
  Files/object_individual.csv
  Files/open_field.csv
  Files/pse.csv
  Files/rebops_common.csv
  Files/ui_item.csv
  Misc/object_common.csv
  Misc/open_field.csv
  Quest/ui_quest_reb.csv
  Task/Daily/ed0610020201.csv
  Task/Daily/ed0610020303.csv
  Task/Side Story/ssn_005080.csv
  Task/Side Story/ssn_005090.csv
  Task/Side Story/ssn_005111.csv
  Task/Side Story/ssn_005121.csv
  Task/Side Story/ssn_011100.csv
  Task/Side Story/ssn_011100_001.csv
  Task/Side Story/ssn_011110.csv
  Task/Side Story/ssn_011111.csv
  Task/Side Story/ssn_011120.csv
  Task/Side Story/ssn_011121.csv
  Task/Side Story/ssn_011131.csv
  Task/Side Story/ssn_012100.csv
  Task/Side Story/ssn_012100_001.csv
  Task/Side Story/ssn_012220.csv
  Task/Side Story/ssn_013090.csv
  Task/Side Story/ssn_013090_001.csv
  Task/Side Story/ssn_013200.csv
  Task/Side Story/ssn_014160.csv
  Task/Side Story/ssn_014160_001.csv
  Task/Side Story/ssn_014210.csv
  Task/Side Story/ssq_013091.csv
  Task/Side Story/ssq_014161.csv
  Task/Side Story/ssq_014201.csv
  Task/Side Story/ssq_014203.csv
  UI/access_info.csv
  UI/common.csv
  UI/object_individual.csv
  UI/pse.csv
  UI/rebops_common.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
Labels: size/XL

#1453 EN_Reboot: fixups
  Translated/UI/ui_item.csv
Labels: size/XS

#1450 EN_Reboot: Translations for most of Side Quests
  Files/ss0030700601.csv
  Files/ss0030700701.csv
  Files/ss0030700801.csv
  Files/ss0030700901.csv
  Files/ss0030719501.csv
  Files/ss0030720001.csv
  Files/ss0030720101.csv
  Files/ss0030741701.csv
  Files/ss0030741702.csv
  Files/ss0030741703.csv
  Files/ss0030741704.csv
  Files/ss0030741801.csv
  Files/ss0030741802.csv
  Files/ss0030741803.csv
  Files/ss0030741804.csv
  Files/ss0030741901.csv
  Files/ss0030741902.csv
  Files/ss0030761101.csv
  Files/ss0030761201.csv
  Files/ss0030761301.csv
  Files/ss0030761801.csv
  Translated/Tasks/Side/Bergmann/ss0030741801.csv
  Translated/Tasks/Side/Bergmann/ss0030741802.csv
  Translated/Tasks/Side/Bergmann/ss0030741803.csv
  Translated/Tasks/Side/Bergmann/ss0030741804.csv
  Translated/Tasks/Side/Bono/ss0030741901.csv
  Translated/Tasks/Side/Bono/ss0030741902.csv
  Translated/Tasks/Side/Dughal/ss0030741701.csv
  Translated/Tasks/Side/Dughal/ss0030741702.csv
  Translated/Tasks/Side/Dughal/ss0030741703.csv
  Translated/Tasks/Side/Dughal/ss0030741704.csv
  Translated/Tasks/Side/Hoxie/ss0030761201.csv
  Translated/Tasks/Side/Kartevie/ss0030720001.csv
  Translated/Tasks/Side/Liu Lin/ss0030700701.csv
  Translated/Tasks/Side/Nandel/ss0030761101.csv
  Translated/Tasks/Side/Oranje/ss0030700901.csv
  Translated/Tasks/Side/Ran/ss0030700601.csv
  Translated/Tasks/Side/Rossa/ss0030700801.csv
  Translated/Tasks/Side/Seymour/ss0030761801.csv
  Translated/Tasks/Side/Slona/ss0030719501.csv
  Translated/Tasks/Side/Somua/ss0030720101.csv
  Translated/Tasks/Side/Taoyuan/ss0030761301.csv
Labels: size/L

#1455 EN: reset URL strings
  UI/refer.csv
Labels: size/XS

#1456 Ru: small update
  Files/item_element_expl_reb.csv
  translated files/UI/item_element_expl_reb.csv
  translated files/UI/ui_mag.csv
Labels: size/XL

#1457 KO_Reboot: Fix typo
  Files/ui_item_reb.csv
  Quest/ui_quest_reb.csv
  UI/config.csv
  UI/ui_item_reb.csv
  story stuff/msc_010010.csv
Labels: size/XXL

#1458 KO_Reboot: Update potential name
  UI/ui_item_reb.csv
Labels: size/L

#1459 KO_Reboot: update refer
  Files/tut_006205.csv
  Files/tut_006207.csv
  Files/tut_006208.csv
  Files/tut_006212.csv
  Files/tut_006213.csv
  Files/tut_006219.csv
  Tutorial/tut_006205.csv
  Tutorial/tut_006207.csv
  Tutorial/tut_006208.csv
  Tutorial/tut_006212.csv
  Tutorial/tut_006213.csv
  Tutorial/tut_006219.csv
  UI/config.csv
  UI/refer.csv
  UI/ui_scratch_reb.csv
Labels: size/M

#1461 EN_Reboot: fix quotes
  Translated/UI/ui_scratch_reb.csv
Labels: size/XS

#1462 KO: fix error
  NPC/NEED FIND LOCATION/od_060656011.csv
  NPC/NEED FIND LOCATION/od_060656017.csv
  NPC/NEED FIND LOCATION/od_060656021.csv
  NPC/NEED FIND LOCATION/od_060656027.csv
  NPC/NEED FIND LOCATION/od_060656031.csv
  NPC/NEED FIND LOCATION/od_060656037.csv
  NPC/NEED FIND LOCATION/od_060656041.csv
  NPC/NEED FIND LOCATION/od_060656051.csv
  NPC/NEED FIND LOCATION/od_060656057.csv
  Quests/Mother/quest_00050600.csv
Labels: size/S

#1464 KO_Reboot: fix typo and new translation
  E-Trial/trial_defence.csv
  Files/msp_0004.csv
  Files/quest_01120000.csv
  Files/quest_01120010.csv
  Files/tut_006247.csv
  Files/tut_006248.csv
  Files/tut_006249.csv
  Files/tut_006250.csv
  Files/tut_006251.csv
  Message Pack/msp_0004.csv
  Quest/EQ Prepare/qst_1120000000.csv
  Quest/Fedas Vera/quest_01120000.csv
  Quest/Nex Vera/quest_01120010.csv
  Quest/ui_quest_counter_reb.csv
  Tutorial/tut_006247.csv
  Tutorial/tut_006248.csv
  Tutorial/tut_006249.csv
  Tutorial/tut_006250.csv
  Tutorial/tut_006251.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_item_reb.csv
  UI/ui_mainmode.csv
Labels: size/L

#1465 KO_Reboot: fix typo
  Misc/actor_name_npc.csv
  UI/ui_item_reb.csv
Labels: size/S

#1476 KO_Reboot: update files
  Files/region_mag_common.csv
  Files/ui_directbuy_text.csv
  Files/ui_tutorial_guide.csv
  Misc/region_mag_common.csv
  UI/ui_directbuy_text.csv
  UI/ui_tutorial_guide.csv
Labels: size/L

#1478 can't fetch upstream for some reason but here's Aerio translated at least
  Translated/Quests/Story/00 First Meeting/qst_1200000000.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000010.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000015.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000016.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000017.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000018.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000020.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000030.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000045.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000050.csv
  Translated/Quests/Story/00 First Meeting/qst_1200000055.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010000.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010005.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010006.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010010.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010011.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010012.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010015.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010020.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010030.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010040.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010050.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010060.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010070.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010071.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010080.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010085.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010090.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010100.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010110.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010120.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010130.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010140.csv
  Translated/Story/00 Introduction/msn_010130_012.csv
  Translated/Story/00 Introduction/msn_010130_022.csv
  Translated/Story/00 Introduction/msq_010021.csv
  Translated/Story/00 Introduction/msq_010022.csv
  Translated/UI/actor_name_npc.csv
Labels: size/L

#1479 KO_Reboot: update more translation
  Files/npc_760401.csv
  Files/npc_765301.csv
  Files/npc_765401.csv
  Files/ui_shop_reb.csv
  Message Pack/msp_0004.csv
  NPC Dialogue/npc_760401.csv
  NPC Dialogue/npc_765301.csv
  NPC Dialogue/npc_765401.csv
  Quest but need check/qst_1200010072.csv
  Quest but need check/qst_1200010073.csv
  Task/Side Story/ss0030761101.csv
  Task/Side Story/ssn_005080.csv
  Task/Side Story/ssn_005090.csv
  Task/Side Story/ssn_005151.csv
  Task/Side Story/ssn_011131.csv
  Task/Side Story/ssn_011160.csv
  Task/Side Story/ssn_011161.csv
  Task/Side Story/ssn_011171.csv
  Task/Side Story/ssn_012010.csv
  Task/Side Story/ssn_012011.csv
  Task/Side Story/ssn_012030.csv
  Task/Side Story/ssn_012031.csv
  Task/Side Story/ssn_012050.csv
  Task/Side Story/ssn_012051.csv
  Task/Side Story/ssn_012070.csv
  Task/Side Story/ssn_012090.csv
  Task/Side Story/ssn_012100.csv
  Task/Side Story/ssn_012100_001.csv
  Task/Side Story/ssn_012220.csv
  Task/Side Story/ssn_012221.csv
  Task/Side Story/ssn_012230.csv
  Task/Side Story/ssn_012231.csv
  Task/Side Story/ssn_013010.csv
  Task/Side Story/ssn_013011.csv
  Task/Side Story/ssn_013031.csv
  Task/Side Story/ssn_013090.csv
  Task/Side Story/ssn_013090_001.csv
  Task/Side Story/ssn_013110.csv
  Task/Side Story/ssn_013110_001.csv
  Task/Side Story/ssn_013200.csv
  Task/Side Story/ssn_013201.csv
  Task/Side Story/ssn_013220.csv
  Task/Side Story/ssn_013221.csv
  Task/Side Story/ssn_014020.csv
  Task/Side Story/ssn_014021.csv
  Task/Side Story/ssn_014050.csv
  Task/Side Story/ssn_014051.csv
  Task/Side Story/ssn_014100.csv
  Task/Side Story/ssn_014101.csv
  Task/Side Story/ssn_014210.csv
  Task/Side Story/ssn_014211.csv
  Tutorial/tut_006219.csv
  UI/ui_directbuy_text.csv
  UI/ui_shop_reb.csv
  should find category/0010100061.csv
Labels: size/XL

#1474 Update ui_item_reb.csv
  Translated/UI/ui_item_reb.csv
Labels: size/XS

#1483 First translation- generic tips
  Translated/UI/ui_tips_reb.csv
Labels: size/S

#1489 KO_Reboot: Update UI things and fix typo
  Files/ui_equip.csv
  Files/ui_group_chat.csv
  Files/ui_na_mainmode.csv
  Files/wh_messagepack.csv
  Quest but need check/qst_1100050030.csv
  Quest but need check/qst_1100050110.csv
  Quest but need check/qst_1100050120.csv
  Quest but need check/qst_1100050130.csv
  Quest but need check/qst_1100050150.csv
  Quest but need check/qst_1100050160.csv
  Quest/quest_common_reboot.csv
  Tutorial/tut_006219.csv
  Tutorial/tut_006289.csv
  Tutorial/tut_006290.csv
  Tutorial/tut_006291.csv
  Tutorial/tut_006294.csv
  Tutorial/tut_006296.csv
  Tutorial/tut_006297.csv
  Tutorial/tut_006304.csv
  Tutorial/tut_006305.csv
  Tutorial/tut_006306.csv
  Tutorial/tut_006308.csv
  Tutorial/tut_006309.csv
  Tutorial/tut_006310.csv
  Tutorial/tut_006311.csv
  Tutorial/tut_006312.csv
  Tutorial/tut_006313.csv
  Tutorial/tut_006314.csv
  Tutorial/tut_006315.csv
  Tutorial/tut_006316.csv
  Tutorial/tut_006318.csv
  Tutorial/tut_006319.csv
  Tutorial/tut_006321.csv
  Tutorial/tut_006322.csv
  Tutorial/tut_006324.csv
  Tutorial/tut_006326.csv
  Tutorial/tut_006329.csv
  Tutorial/tut_006330.csv
  Tutorial/tut_006331.csv
  Tutorial/tut_006336.csv
  Tutorial/tut_006337.csv
  Tutorial/tut_006338.csv
  Tutorial/tut_006360.csv
  Tutorial/tut_006364.csv
  Tutorial/tut_006368.csv
  Tutorial/tut_006374.csv
  Tutorial/tut_006375.csv
  Tutorial/tut_006376.csv
  Tutorial/tut_006378.csv
  Tutorial/tut_006380.csv
  Tutorial/tut_006381.csv
  Tutorial/wh_messagepack.csv
  UI/config.csv
  UI/rebops_common.csv
  UI/ui_equip.csv
  UI/ui_group_chat.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
  UI/ui_na_mainmode.csv
  story stuff/msc_011280.csv
Labels: size/XXL

#1492 EN Classic File fixes
  Misc/actor_name.csv
  Quests/Training Quests/quest_00160000.csv
  Quests/Training Quests/quest_00160001.csv
  Quests/Training Quests/quest_00160100.csv
  Quests/Training Quests/quest_00160200.csv
  Quests/Training Quests/quest_00160300.csv
  Quests/Training Quests/quest_00160400.csv
  Quests/Training Quests/quest_00160500.csv
  Quests/Training Quests/quest_00160600.csv
  Quests/Training Quests/quest_00160700.csv
  Quests/Training Quests/quest_00160800.csv
  Quests/Training Quests/quest_00160900.csv
  Quests/Training Quests/quest_00161000.csv
  Quests/Training Quests/quest_00161100.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_sp.csv
Labels: size/M

#1498 KO_Reboot: fix typo
  Task/Limited/ls0064010101.csv
  UI/common.csv
  UI/config.csv
  UI/ui_mainmode_reb.csv
  UI/ui_scratch_reb.csv
Labels: size/L

#1500 ES_Reboot apc chat 1
  Files/apc_chat_1.csv
  Files/qst_1200000030.csv
  Translated/Dialogos/apc_chat_1.csv
  Translated/Story/00 Introduction/qst_1200000030.csv
Labels: size/XXL

#1501 Fix missing L.
  UI/common.csv
Labels: size/XS

#1496 EN: Misc fixes for June 9th patch.
  Dialogue/Koffie/co_060901.csv
  Misc/actor_name.csv
  UI/common.csv
  UI/config.csv
  UI/ui_fashion_catalog.csv
  UI/ui_gacha.csv
  UI/ui_guild.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_portrait.csv
  UI/ui_selectmenu_text.csv
  UI/ui_title_text.csv
Labels: size/L

#1504 KO_Reboot: Fix typo
  Misc/actor_name.csv
  Task/Daily/ed0610010105.csv
  Task/Daily/ed0610010110.csv
  Task/Daily/ed0610010205.csv
  Task/Daily/ed0610010210.csv
  Task/Daily/ed0610010215.csv
  Task/Daily/ed0610010220.csv
  Task/Daily/ed0610010305.csv
  Task/Daily/ed0610010310.csv
  Task/Daily/ed0610010315.csv
  Task/Side Story/ss0030766202.csv
  UI/common.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
  story stuff/msc_010130.csv
Labels: size/M
