Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-12, with the labels that each got.

#1701 KO: Update for test
  UI/item_element_name_reb.csv
Labels: size/M

#1702 KO_Reboot: idiot sandwitch
  Misc/actor_name.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_moralskeeper.csv
  filelist.txt
Labels: size/L

#1704 Ru: new content + fix
  translated files/UI/common.csv
  translated files/UI/config.csv
  translated files/UI/item_element_expl_reb.csv
  translated files/UI/ui_charamake_text.csv
  translated files/UI/ui_charamake_text_reb.csv
  translated files/UI/ui_fashion_catalog.csv
  translated files/UI/ui_gacha.csv
  translated files/UI/ui_guild.csv
  translated files/UI/ui_item.csv
  translated files/UI/ui_mainmode.csv
  translated files/UI/ui_tips.csv
  translated files/UI/ui_title_text.csv
Labels: size/L

#1706 KO_Reboot: Fix typo
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  UI/ui_item.csv
Labels: size/L

#1707 Update item_element_expl_reb.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
Labels: size/L

#1709 ES:reboot secundarias
  Files/ss0030702001.csv
  Files/ss0030702101.csv
  Files/ss0030719901.csv
  Files/ss0030742001.csv
  Files/ss0030742002.csv
  Files/ss0030742101.csv
  Files/ss0030742201.csv
  Files/ss0030742301.csv
  Files/ss0030769001.csv
  Files/ss0030769501.csv
  Files/ss0030769502.csv
  Files/ss0030769503.csv
  Files/ss0030769601.csv
  Files/ss0030769602.csv
  Files/ss0030769603.csv
  Files/ss0030770001.csv
  Files/ss0030770501.csv
  Files/ss0030770502.csv
  Files/ss0030771001.csv
  Files/ss0030771301.csv
  Files/ss0030771302.csv
  Files/ss0030771401.csv
  Files/ss0030771402.csv
  Files/ss0030771403.csv
  Files/ss0030771801.csv
  Files/ss0030771802.csv
  Files/ss0030771803.csv
  Translated/Tareas/Secundarias/ss0030702001.csv
  Translated/Tareas/Secundarias/ss0030702101.csv
  Translated/Tareas/Secundarias/ss0030719901.csv
  Translated/Tareas/Secundarias/ss0030742001.csv
  Translated/Tareas/Secundarias/ss0030742002.csv
  Translated/Tareas/Secundarias/ss0030742101.csv
  Translated/Tareas/Secundarias/ss0030742201.csv
  Translated/Tareas/Secundarias/ss0030742301.csv
  Translated/Tareas/Secundarias/ss0030769001.csv
  Translated/Tareas/Secundarias/ss0030769501.csv
  Translated/Tareas/Secundarias/ss0030769502.csv
  Translated/Tareas/Secundarias/ss0030769503.csv
  Translated/Tareas/Secundarias/ss0030769601.csv
  Translated/Tareas/Secundarias/ss0030769602.csv
  Translated/Tareas/Secundarias/ss0030769603.csv
  Translated/Tareas/Secundarias/ss0030770001.csv
  Translated/Tareas/Secundarias/ss0030770501.csv
  Translated/Tareas/Secundarias/ss0030770502.csv
  Translated/Tareas/Secundarias/ss0030771001.csv
  Translated/Tareas/Secundarias/ss0030771301.csv
  Translated/Tareas/Secundarias/ss0030771302.csv
  Translated/Tareas/Secundarias/ss0030771401.csv
  Translated/Tareas/Secundarias/ss0030771402.csv
  Translated/Tareas/Secundarias/ss0030771403.csv
  Translated/Tareas/Secundarias/ss0030771801.csv
  Translated/Tareas/Secundarias/ss0030771802.csv
  Translated/Tareas/Secundarias/ss0030771803.csv
Labels: size/L

#1710 ES:reboot UI mainmode
  Translated/Interfaz/ui_mainmode.csv
Labels: size/XL

#1711 KO_Reboot: fix typo
  Files/msc_012020.csv
  Quest/quest_common_reboot.csv
  Story/Retem/1/msc_012020.csv
  UI/ui_mainmode.csv
Labels: size/M

#1714 KO_Reboot: fix typo
  Misc/actor_name.csv
  UI/ui_item.csv
  UI/ui_tips_reb.csv
Labels: size/L

#1717 Xiandy xmas dialogue
  Files/ssn_019050_001.csv
  Files/ssn_019050_002.csv
  Files/ssq_019050_003.csv
  Files/ssq_019050_004.csv
  Files/ssq_019050_005.csv
  Files/ssq_019050_006.csv
  Translated/Dialog/Xiandy/2021-12-22 Christmas/ssn_019050_001.csv
  Translated/Dialog/Xiandy/2021-12-22 Christmas/ssn_019050_002.csv
  Translated/Dialog/Xiandy/2021-12-22 Christmas/ssq_019050_003.csv
  Translated/Dialog/Xiandy/2021-12-22 Christmas/ssq_019050_004.csv
  Translated/Dialog/Xiandy/2021-12-22 Christmas/ssq_019050_005.csv
  Translated/Dialog/Xiandy/2021-12-22 Christmas/ssq_019050_006.csv
Labels: size/L

#1720 KO_Reboot: update files
  Files/ssn_014275.csv
  Files/ssn_014300.csv
  Files/ssn_014301.csv
  Files/ssn_014310.csv
  Files/ssn_014311.csv
  Files/ssn_014320.csv
  Files/ssn_014321.csv
  Files/ssn_014330.csv
  Files/ssn_014331.csv
  Files/ssn_014334.csv
  Files/ssn_014340.csv
  Files/ssn_014341.csv
  Files/ssn_014350.csv
  Files/ssn_014351.csv
  Files/ssn_014355.csv
  Files/ssn_014360.csv
  Files/ssn_014361.csv
  Files/ssn_014370.csv
  Files/ssn_014371.csv
  Files/ssn_014560.csv
  Files/ssn_014561.csv
  Files/ssn_014580.csv
  Files/ssn_014590.csv
  Task/Side Story/ssn_014275.csv
  Task/Side Story/ssn_014300.csv
  Task/Side Story/ssn_014301.csv
  Task/Side Story/ssn_014310.csv
  Task/Side Story/ssn_014311.csv
  Task/Side Story/ssn_014320.csv
  Task/Side Story/ssn_014321.csv
  Task/Side Story/ssn_014330.csv
  Task/Side Story/ssn_014331.csv
  Task/Side Story/ssn_014334.csv
  Task/Side Story/ssn_014340.csv
  Task/Side Story/ssn_014341.csv
  Task/Side Story/ssn_014350.csv
  Task/Side Story/ssn_014351.csv
  Task/Side Story/ssn_014355.csv
  Task/Side Story/ssn_014360.csv
  Task/Side Story/ssn_014361.csv
  Task/Side Story/ssn_014370.csv
  Task/Side Story/ssn_014371.csv
  Task/Side Story/ssn_014560.csv
  Task/Side Story/ssn_014561.csv
  Task/Side Story/ssn_014580.csv
  Task/Side Story/ssn_014590.csv
Labels: size/L

#1726 KO_Reboot: FIx typo
  NPC Dialogue/np_npc_7213_001.csv
  Quest/quest_common_reboot.csv
Labels: size/XS

#1728 KO_Reboot: Fix Typo
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Quest/Main/Retem/quest_01200260.csv
  Quest/Main/Retem/quest_01200280.csv
  Story/Retem/msc_012120.csv
  Story/Retem/msc_012170.csv
  Story/Retem/msc_012200.csv
  Story/Retem/msc_012220.csv
  Story/Retem/msc_012240.csv
  Story/Retem/msc_012250.csv
  Story/Retem/msc_012280.csv
  Story/Retem/msc_012292.csv
  Story/Retem/msc_012300.csv
  Story/Retem/msc_012305.csv
  Story/Retem/msn_012241.csv
  Story/Retem/msn_012243.csv
  Story/Retem/msn_012265.csv
  Story/Retem/msq_012252.csv
  Story/Retem/msq_012271.csv
  Story/Retem/msq_012272.csv
  Story/Retem/msq_012273.csv
  Story/Retem/msq_012274.csv
  Story/Retem/msq_012275.csv
  Story/Retem/msq_012279.csv
  Story/Retem/msq_012281.csv
  Story/Retem/msq_012282.csv
  Story/Retem/msq_012283.csv
  Story/Retem/msq_012284.csv
  Story/Retem/msq_012287.csv
  Story/Retem/msq_012293.csv
  Story/Retem/qst_1200270000.csv
  Story/Retem/qst_1200270010.csv
  Story/Retem/qst_1200280000.csv
  Story/Retem/qst_1200280010.csv
  Story/Retem/qst_1200280020.csv
  Story/Retem/qst_1200280050.csv
  Task/Main/ms0010100280.csv
  Task/Main/ms0010100290.csv
  Task/Side Story/ss0030702001.csv
  Task/Side Story/ss0030702101.csv
  Task/Side Story/ssn_014540.csv
  Task/Side Story/ssn_014550.csv
  Task/Side Story/ssn_014560.csv
Labels: size/L

#1729 EQ stuff
  Translated/Quests/Emergency Quests/Lenus Vera/qst_1120030000.csv
  Translated/Quests/Emergency Quests/Lenus Vera/qst_1120030010.csv
  Translated/Quests/Emergency Quests/Snidael Vera/qst_1120040000.csv
  Translated/Quests/Emergency Quests/Snidael Vera/qst_1120040001.csv
Labels: size/S

#1730 KO_Reboot: Fix typo
  Story/Retem/msc_012250.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_scratch_reb.csv
Labels: size/M

#1731 KO_Reboot: Fix typo
  UI/config.csv
  UI/ui_item.csv
  UI/ui_tutorial_reb.csv
Labels: size/S

#1732 KO: Update ui_fashion_catalog.csv
  UI/ui_fashion_catalog.csv
Labels: size/XS
