Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-05, with the labels that each got.

#1406 KO: minor changes
  Dialogue/E-Trial/incident_common.csv
  NPC/Marlu/Order/co05031901.csv
  NPC/katori/co03072000.csv
  Quests/Arks Quest/quest_00030300.csv
  Quests/quest_common.csv
  Story/Episode 6/Chapter 6/ii_session_apc_5666.csv
  UI/config.csv
  UI/item_element_expl.csv
  UI/item_element_name.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/L

#1407 KO: fix typo
  UI/ui_craft.csv
Labels: size/XS

#1408 KO: fix typo
  UI/ui_charamake_text_reb.csv
Labels: size/XS

#1409 Various fixes
  Dialogue/Inanna/np_011650.csv
  Quests/Challenge Quests/2 Decision/quest_00120010.csv
  Quests/Challenge Quests/3 Cataclysm/co_060072.csv
  Quests/Challenge Quests/3 Cataclysm/mp_000572.csv
  Quests/Challenge Quests/3 Cataclysm/quest_00120020.csv
  Quests/Story EP1 names/Chapter 8/quest_00701130.csv
  Story/Episode 3/cm_032830.csv
  Story/Episode 3/cm_032930.csv
  Tutorial/Dialogue/co_031407.csv
  Tutorial/Tutorial List/wh_tl_co_031407.csv
  UI/quest_common.csv
  UI/quest_counter.csv
  UI/ui_amusement.csv
  UI/ui_equip.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_tips.csv
Labels: size/M

#1410 Various fixes
  Dialogue/Matoi/np_010040.csv
  Dialogue/Matoi/np_011850.csv
  Dialogue/Matoi/np_012130.csv
  Misc/actor_name.csv
  Orders/_Bingo/bo00001446.csv
  Story/Episode 4/Chapter 2/ra_043020.csv
  UI/ui_charamake_parts.csv
  UI/ui_lobbymap.csv
  UI/ui_mag.csv
  UI/ui_mainmode.csv
Labels: size/L

#1416 EN: Rename Techer to Techter
  Dialogue/Barbara/np_010570.csv
  Dialogue/Barbara/od_060424071.csv
  Dialogue/Barbara/od_060424081.csv
  Dialogue/Barbara/od_060424097.csv
  Dialogue/Marlu/np_010190.csv
  Orders/Barbara/co06042407.csv
  Orders/Barbara/co06042408.csv
  Orders/Barbara/co06042409.csv
  Orders/Koffie/Retired/co04010526.csv
  Orders/Koffie/Retired/co05010546.csv
  Orders/Marlu/Retired/co01012021.csv
  Orders/Marlu/co01011500.csv
  Orders/Marlu/co01011501.csv
  Orders/Marlu/co03031904.csv
  Orders/Marlu/co03031905.csv
  Orders/Marlu/co03031908.csv
  Orders/Marlu/co03031909.csv
  Quests/Training Quests/quest_00160600.csv
  Translated/Dialogue/Marlu/od_010115001.csv
  Translated/Dialogue/Marlu/od_010115007.csv
  Translated/Dialogue/Marlu/od_010115011.csv
  Translated/Dialogue/Marlu/od_010120201.csv
  Translated/Dialogue/Marlu/od_010120207.csv
  Translated/Dialogue/Marlu/od_010120211.csv
  Translated/Dialogue/Marlu/od_010120217.csv
  Translated/Dialogue/Marlu/od_010200182.csv
  Translated/Tutorial/Dialogue/od_010200181.csv
  Tutorial/Arks Road/Card Details/ar_ca0108.csv
  Tutorial/Client Order notices/co_010008.csv
  Tutorial/Training Quests/06 Techer/tr_060000.csv
  Tutorial/Training Quests/06 Techer/tr_060010.csv
  Tutorial/Training Quests/06 Techer/tr_060090.csv
  Tutorial/Window/co_011037.csv
  UI/common.csv
  UI/quest_counter.csv
  UI/ui_charamake_parts.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  _aspell/PSO2.en_Class.dict
Labels: size/L

#1418 Various fixes
  Dialogue/np_npc_00cmn.csv
  UI/common.csv
  UI/ui_challenge.csv
  UI/ui_gat_mat2item.csv
  UI/ui_help.csv
  UI/ui_information.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_poka_text.csv
  UI/ui_title_text.csv
Labels: size/L
