Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-10, with the labels that each got.

#1666 EN_Reboot: fix quotes
  Translated/Tutorials/tut_006437.csv
Labels: size/XS

#1675 Update ssq_019020_006.csv
  Translated/Dialog/Xiandy/2021-10-27 Halloween/ssq_019020_006.csv
Labels: size/XS

#1674 Update ssq_019020_005.csv
  Translated/Dialog/Xiandy/2021-10-27 Halloween/ssq_019020_005.csv
Labels: size/XS

#1667 KO_Reboot: Fix typo
  Files/tut_006284.csv
  Files/tut_006340.csv
  Files/tut_006351.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  Tutorial/tut_006284.csv
  Tutorial/tut_006340.csv
  Tutorial/tut_006351.csv
  UI/common.csv
  UI/config.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
  UI/ui_na_mainmode.csv
  UI/ui_rebops.csv
  UI/ui_scratch_reb.csv
  UI/ui_tutorial_reb.csv
Labels: size/L

#1684 RU_Reboot: Update filelist.txt
  filelist.txt
Labels: size/L

#1693 KO_Reboot: Test
  filelist.txt
Labels: size/XL

#1694 KO_Reboot: update filelist
  filelist.txt
Labels: size/XL

#1695 RU_Reboot: Update filelist.txt
  filelist.txt
Labels: size/S
