Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2021-07, with the labels that each got.

#1506 translated some useful tips/prompts etc
  UI/ui_charamake_text.csv
Labels: size/S

#1508 Character Creator hotfix.
  UI/ui_charamake_text.csv
Labels: size/XS

#1507 Basinia's world dialogue + extras
  Files/npc_764501.csv
  Files/npc_764701.csv
  Files/ssn_013010.csv
  Translated/Dialog/Basinia/ssn_013010.csv
  Translated/Dialog/Nesca/npc_764701.csv
  Translated/Dialog/Rudy/npc_764501.csv
  Translated/Quests/Story/01 Aerio Town/qst_1200010071.csv
Labels: size/M

#1510 KO_Reboot: fix typo
  Task/Daily/ed0610010320.csv
  UI/ui_mainmode_reb.csv
Labels: size/XS

#1505 EN_Reboot: Finished translations of Translated/Dialogue
  Translated/Dialog/Raskina/np_npc_7617_001.csv
  Translated/Dialog/trial_boss_ahl.csv
  Translated/Dialog/trial_enemy_ahl.csv
  Translated/Dialog/trial_fort.csv
Labels: size/S

#1495 EN: salon mess
  UI/ui_accessories_text.csv
  UI/ui_charamake_parts.csv
Labels: size/M

#1514 KO: symbol art
  Files/ui_symbol.csv
  UI/config.csv
  UI/ui_symbol.csv
Labels: size/L

#1515 KO_Reboot: fix typo
  Misc/apc_chat_1.csv
  Quest but need check/qst_1200010080.csv
  Quest but need check/qst_1200010100.csv
  Quest but need check/qst_1200020000.csv
  Quest but need check/qst_1200030020.csv
  filelist.txt
  story stuff/msc_010130.csv
  story stuff/msc_010230.csv
  story stuff/msn_010130_022.csv
  story stuff/msq_010207.csv
Labels: size/M

#1516 KO_Reboot: fix typo
  UI/ui_item.csv
  UI/ui_mainmode.csv
Labels: size/M

#1511 Kensing, Norisimo, Dighal world dialogue
  Files/npc_762201.csv
  Files/npc_762301.csv
  Files/ssn_011110.csv
  Translated/Dialog/Dighal/ssn_011110.csv
  Translated/Dialog/Kensing/npc_762201.csv
  Translated/Dialog/Norisimo/npc_762301.csv
Labels: size/M

#1519 KO_Reboot: Fix typo
  UI/common.csv
  UI/config.csv
Labels: size/S

#1518 EN: Salon File Import and fix translations.
  UI/ui_accessories_text.csv
  UI/ui_charamake_parts.csv
Labels: size/XXL

#1521 KO_Reboot: Fix typo
  NPC Dialogue/np_npc_7208_001.csv
  NPC Dialogue/np_npc_7211_001.csv
  Task/Limited/ls0061010102.csv
  Task/Limited/ls0061010103.csv
  Task/Side Story/ssn_012220.csv
  Task/Side Story/ssn_012221.csv
  Task/Side Story/ssn_014210.csv
  Task/Side Story/ssn_019004.csv
  Task/Side Story/ssn_019006.csv
  Tutorial/tut_006424.csv
Labels: size/S

#1522 KO_Reboot: Fix typo
  Task/Side Story/ss0030719851.csv
  Task/Side Story/ss0030766402.csv
  Task/Side Story/ssn_005020.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
Labels: size/M

#1523 KO: Update files
  Files/tr_100006_01.csv
  Files/tr_140100.csv
  Files/ui_newly.csv
  UI/common.csv
  UI/ui_amusement.csv
  UI/ui_charamake_parts.csv
Labels: size/L

#1524 NPC Trial Dialog
  Files/trial_apc_7903001.csv
  Files/trial_apc_7904001.csv
  Files/trial_apc_7905001.csv
  Files/trial_apc_7906001.csv
  Files/trial_apc_7907001.csv
  Files/trial_apc_7908001.csv
  Translated/Dialog/Aina/trial_apc_7002001.csv
  Translated/Dialog/Dachua/trial_apc_7904001.csv
  Translated/Dialog/Dalghe/trial_apc_7903001.csv
  Translated/Dialog/Holoman/trial_apc_7908001.csv
  Translated/Dialog/Hosannia/trial_apc_7907001.csv
  Translated/Dialog/Manon/trial_apc_7001001.csv
  Translated/Dialog/Shamal/trial_apc_7905001.csv
  Translated/Dialog/Shanrae/trial_apc_7906001.csv
  _misc/jp_dup.json
Labels: size/XL

#1525 KO_Reboot: Fix typo
  Story/Prologue/msc_011430.csv
Labels: size/XS

#1526 EN_Reboot: Various fixes
  Translated/Dialog/Dalghe/trial_apc_7903001.csv
  Translated/Dialog/Manon/trial_apc_7001001.csv
  Translated/Dialog/Somua/np_npc_7201_001.csv
  Translated/Dialog/Xiandy/2021-07-07 Anniversary/ssn_019003.csv
  Translated/Dialog/trial_boss_ahl.csv
  Translated/Quests/Story/04 DOLLS on Mt. Magnus/qst_1200040090.csv
  Translated/Story/04-05 DOLLS on Mt. Magnus/msq_011136.csv
  Translated/Tasks/Limited/2021-06-09 Launch/ls0060010101.csv
  Translated/Tasks/Limited/2021-06-09 Launch/ls0060010102.csv
  Translated/Tasks/Side/Segreto/ss0030765601.csv
  Translated/Tasks/Weekly/ew0620000102.csv
  Translated/Tutorials/tut_006280.csv
  Translated/Tutorials/tut_006408.csv
  Translated/Tutorials/tut_006409.csv
  Translated/UI/common.csv
  Translated/UI/ui_directbuy_text.csv
  Translated/UI/ui_group_chat.csv
  Translated/UI/ui_help.csv
  Translated/UI/ui_item.csv
  Translated/UI/ui_item_reb.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_mainmode_reb.csv
  Translated/UI/ui_quest_counter_reb.csv
  Translated/UI/ui_selectmenu_text.csv
Labels: size/XL

#1527 EN: Various fixes
  Dialogue/Koffie/np_010501.csv
  Orders/Zieg/co03074132.csv
  Orders/Zieg/co03074133.csv
  Quests/Burning Rangers/quest_00050160.csv
  Tutorial/Dialogue/np_014371.csv
  Tutorial/Dialogue/np_015661.csv
  Tutorial/Dialogue/np_015701.csv
  Tutorial/Training Quests/10 Hero/tr_100002.csv
  Tutorial/Tutorial List/wh_tl_co_031403.csv
  Tutorial/Window Help/wh_container.csv
  Tutorial/Window Help/wh_rabo.csv
  Tutorial/Window/co_031403.csv
  Tutorial/Window/co_050014.csv
  Tutorial/Window/co_050015.csv
  Tutorial/Window/co_050016.csv
  Tutorial/Window/co_060004.csv
  Tutorial/Window/co_060025.csv
  UI/common.csv
  UI/item_element_expl.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/quest_counter.csv
  UI/ui_charamake_text.csv
  UI/ui_craft.csv
  UI/ui_directbuy_text.csv
  UI/ui_equipnote.csv
  UI/ui_group_chat.csv
  UI/ui_guild.csv
  UI/ui_help.csv
  UI/ui_item.csv
  UI/ui_mag.csv
  UI/ui_mainmode.csv
  UI/ui_selectmenu_text.csv
  UI/ui_tips.csv
Labels: size/XL

#1529 KO_Reboot: Fix Typo
  E-Trial/trial_defence.csv
  Task/Side Story/ssn_019002.csv
Labels: size/XS

#1528 i broke all red containers to translate this
  Files/ssn_014120.csv
  Files/ssn_014120_001.csv
  Files/ssn_014200.csv
  Files/ssn_014200_001.csv
  Files/ssn_014202.csv
  Files/ssq_014121.csv
  Files/ssq_014201.csv
  Files/ssq_014203.csv
  Files/ssq_014212.csv
  Translated/Dialog/Bono/ssn_014200.csv
  Translated/Dialog/Bono/ssn_014200_001.csv
  Translated/Dialog/Bono/ssn_014202.csv
  Translated/Dialog/Bono/ssq_014201.csv
  Translated/Dialog/Bono/ssq_014203.csv
  Translated/Dialog/Dighal/ssq_014212.csv
  Translated/Dialog/Rossa/ssn_014120.csv
  Translated/Dialog/Rossa/ssn_014120_001.csv
  Translated/Dialog/Rossa/ssq_014121.csv
Labels: size/L

#1531 dighal task dialogue
  Files/ssn_012220.csv
  Files/ssn_012221.csv
  Files/ssq_012222.csv
  Translated/Dialog/Dighal/ssn_012220.csv
  Translated/Dialog/Dighal/ssn_012221.csv
  Translated/Dialog/Dighal/ssq_012222.csv
Labels: size/M

#1530 EN_Reboot: Translate dialogue.
  Files/ssn_005113.csv
  Files/ssn_005114.csv
  Files/ssn_005123.csv
  Files/ssn_005124.csv
  Files/ssn_005133.csv
  Files/ssn_005134.csv
  Files/ssn_005143.csv
  Files/ssn_005144.csv
  Files/ssn_005153.csv
  Files/ssn_005154.csv
  Files/ssn_005163.csv
  Files/ssn_005164.csv
  Translated/Dialog/Bergmann/ssn_012100.csv
  Translated/Dialog/Dantre/ssn_005113.csv
  Translated/Dialog/Dantre/ssn_005114.csv
  Translated/Dialog/Dantre/ssn_005123.csv
  Translated/Dialog/Dantre/ssn_005124.csv
  Translated/Dialog/Dantre/ssn_011120.csv
  Translated/Dialog/Hornyan/ssn_005153.csv
  Translated/Dialog/Hornyan/ssn_005154.csv
  Translated/Dialog/Hornyan/ssn_005163.csv
  Translated/Dialog/Hornyan/ssn_005164.csv
  Translated/Dialog/Hornyan/ssn_011160.csv
  Translated/Dialog/Hornyan/ssq_011163.csv
  Translated/Dialog/Hornyan/ssq_011173.csv
  Translated/Dialog/Sharkey/ssn_005133.csv
  Translated/Dialog/Sharkey/ssn_005134.csv
  Translated/Dialog/Sharkey/ssn_005143.csv
  Translated/Dialog/Sharkey/ssn_005144.csv
  Translated/Dialog/Sharkey/ssn_011140.csv
  Translated/Dialog/Sharkey/ssq_011143.csv
  Translated/Dialog/Sharkey/ssq_011153.csv
Labels: size/M

#1542 Es_Reboot
  Files/ui_item_reb.csv
  Files/ui_na_mainmode.csv
  Translated/UI/ui_item_reb.csv
  Translated/UI/ui_mainmode_reb.csv
  Translated/UI/ui_na_mainmode.csv
Labels: size/XXL

#1545 Update config.csv
  Translated/Interfaz/config.csv
Labels: size/XL

#1546 Es
  UI/ui_newly.csv
  UI/ui_title_text.csv
Labels: size/M

#1538 EN_Reboot: Various fixes.
  Translated/Dialog/Bergmann/ssn_011100.csv
  Translated/Dialog/Bergmann/ssn_011100_001.csv
  Translated/Dialog/Dalghe/trial_apc_7903001.csv
  Translated/Dialog/Dighal/ssn_011110.csv
  Translated/Dialog/Dighal/ssn_012220.csv
  Translated/Dialog/Dighal/ssn_013200.csv
  Translated/Dialog/Dighal/ssn_014210.csv
  Translated/Dialog/Kartevie/ssn_012050.csv
  Translated/Dialog/Kartevie/ssn_012051.csv
  Translated/Dialog/Raddmagg/npc_765801.csv
  Translated/Dialog/Sharkey/ssn_011140.csv
  Translated/Dialog/Sharkey/ssn_011151.csv
  Translated/Quests/Cocoons/mt0199912000.csv
  Translated/Quests/Emergency Quests/Nex Vera/qst_1120010010.csv
  Translated/Quests/Emergency Quests/Pedas Vera/qst_1120000020.csv
  Translated/Story/02 The Mysterious Colossus/msc_010140.csv
  Translated/Story/03 To Central City/msc_010220.csv
  Translated/Story/03 To Central City/msn_011080_002.csv
  Translated/Story/04-05 DOLLS on Mt. Magnus/msc_011140.csv
  Translated/Story/04-05 DOLLS on Mt. Magnus/msc_011190.csv
  Translated/Story/04-05 DOLLS on Mt. Magnus/msn_011063_006.csv
  Translated/Story/06-07 Three Stand Alone/msn_011350_010.csv
  Translated/Tasks/Daily/2021-07-07 Anniversary/ed0611010203.csv
  Translated/Tasks/Side/Slona/ss0030719551.csv
  Translated/Tasks/Side/Slona/ss0030721051.csv
  Translated/Tutorials/tut_006261.csv
  Translated/Tutorials/tut_006262.csv
  Translated/Tutorials/tut_006267.csv
  Translated/Tutorials/tut_006297.csv
  Translated/Tutorials/tut_006302.csv
  Translated/Tutorials/tut_006363.csv
  Translated/Tutorials/tut_006378.csv
  Translated/Tutorials/tut_006379.csv
  Translated/Tutorials/tut_006400.csv
  Translated/UI/common.csv
  Translated/UI/config.csv
  Translated/UI/ui_directbuy_text.csv
  Translated/UI/ui_group_chat.csv
  Translated/UI/ui_item.csv
  Translated/UI/ui_item_reb.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_mainmode_reb.csv
  Translated/UI/ui_na_mainmode.csv
  Translated/UI/ui_selectmenu_text.csv
  Translated/UI/ui_shop_reb.csv
  Translated/UI/ui_symbol.csv
  Translated/UI/ui_tips_reb.csv
  Translated/UI/ui_tutorial_reb.csv
Labels: size/XL

#1547 ES_Interfas
  Files/ui_directbuy_text.csv
  Files/ui_item.csv
  Files/ui_moralskeeper.csv
  Files/ui_movieviewer.csv
  Files/ui_play_achievement.csv
  Files/ui_shop.csv
  Files/ui_shop_reb.csv
  Files/ui_symbol.csv
  Files/ui_tips_reb.csv
  Files/ui_tutorial_guide.csv
  Translated/Interfaz/ui_directbuy_text.csv
  Translated/Interfaz/ui_item.csv
  Translated/Interfaz/ui_moralskeeper.csv
  Translated/Interfaz/ui_movieviewer.csv
  Translated/Interfaz/ui_play_achievement.csv
  Translated/Interfaz/ui_shop.csv
  Translated/Interfaz/ui_shop_reb.csv
  Translated/Interfaz/ui_symbol.csv
  Translated/Interfaz/ui_tips_reb.csv
  Translated/Interfaz/ui_tutorial_guide.csv
  Translated/Interfaz/ui_tutorial_reb.csv
Labels: size/XXL

#1549 KO: Update files
  Dialogue/Should find it/np_npc_59.csv
  Dialogue/Should find it/np_npc_82.csv
  Dialogue/Should find it/np_npc_counterquest2.csv
  Files/np_npc_59.csv
  Files/np_npc_82.csv
  Files/np_npc_counterquest2.csv
  Quests/Bonus Quest/Tokyo Gold/quest_00150000.csv
  Quests/Bonus Quest/Tokyo Rainbow/quest_00150080.csv
  Quests/Bonus Quest/Tokyo Silver/quest_00150010.csv
  Quests/Ultimate Quests/Masquerade/quest_00130030.csv
  Quests/Ultimate Quests/quest_00130000.csv
  Quests/Ultimate Quests/quest_00130010.csv
  Quests/Ultimate Quests/quest_00130020.csv
Labels: size/L

#1550 EN_Reboot: Various fixes
  Translated/Tasks/Limited/2021-07-07 Anniversary/ls0061010102.csv
  Translated/Tasks/Limited/2021-07-07 Anniversary/ls0061010103.csv
  Translated/Tasks/Limited/2021-07-07 Anniversary/ls0061010104.csv
  Translated/Tasks/Side/Bergmann/ss0030741803.csv
  Translated/Tasks/Side/Bono/ss0030741901.csv
  Translated/Tasks/Side/Bono/ss0030741951.csv
  Translated/Tasks/Side/Dachua/ss0030719651.csv
  Translated/Tasks/Side/Dantre/ss0030766201.csv
  Translated/Tasks/Side/Dantre/ss0030766202.csv
  Translated/Tasks/Side/Holoman/ss0030719851.csv
  Translated/Tasks/Side/Hornyan/ss0030766401.csv
  Translated/Tasks/Side/Hornyan/ss0030766402.csv
  Translated/Tasks/Side/Hoxie/ss0030761201.csv
  Translated/Tasks/Side/Oranje/ss0030700901.csv
  Translated/Tasks/Side/Segreto/ss0030765651.csv
  Translated/Tasks/Side/Shanrae/ss0030719751.csv
  Translated/Tasks/Side/Sharkey/ss0030766301.csv
  Translated/Tasks/Side/Sharkey/ss0030766302.csv
  Translated/Tasks/Side/Staggy/ss0030766051.csv
  Translated/Tasks/Weekly/2021-07-07 Anniversary/ew0621010101.csv
  Translated/Tasks/Weekly/2021-07-07 Anniversary/ew0621010102.csv
  Translated/UI/config.csv
  Translated/UI/ui_directbuy_text.csv
  Translated/UI/ui_item.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_mainmode_reb.csv
  Translated/UI/ui_rebops.csv
  Translated/UI/ui_shop_reb.csv
Labels: size/L

#1551 EN: Various fixes
  Misc/My Room/poster_board.csv
  Quests/Limited Quests/Excluder/quest_00080370.csv
  Quests/Training Quests/quest_00160000.csv
  Quests/Training Quests/quest_00160001.csv
  Tutorial/Message Pack/mp_000516.csv
  Tutorial/Window/co_050098.csv
  UI/config.csv
  UI/quest_counter.csv
  UI/ui_basnet_text.csv
  UI/ui_directbuy_text.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_pollute.csv
Labels: size/L

#1552 dighal and basinia for dabir
  Files/ssq_013021.csv
  Files/ssq_013202.csv
  Translated/Dialog/Basinia/ssq_013021.csv
  Translated/Dialog/Dighal/ssq_013202.csv
Labels: size/M

#1553 Fix Trainia.
  Translated/Quests/Cocoons/First Step/quest_01100050.csv
  Translated/Quests/Cocoons/Lone Way/quest_01100040.csv
  Translated/Quests/Cocoons/Swift Jump/quest_01100060.csv
  Translated/Quests/Towers/quest_01110020.csv
  Translated/UI/quest_common_reboot.csv
  Translated/UI/ui_quest_reb.csv
Labels: size/S
