Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-06, with the labels that each got.

#1827 KO_Reboot: Update files
  E-Trial/Captan/ti_1019916000_unk_tan_ba.csv
  Files/ti_1019916000_unk_tan_ba.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_reb.csv
  Story/Aelio/msn_011065_001.csv
  Story/Prologue/msc_010144.csv
  Task/Limited/ls0064020111.csv
  Task/Side Story/ssc_012010.csv
  Task/Side Story/ssq_011101.csv
  Tutorial/tut_006348.csv
Labels: size/M

#1828 KO_Update: UI Update
  E-Trial/trial_common.csv
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Misc/object_common.csv
  Misc/open_field.csv
  Misc/region_mag_common.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  Story/Aelio/msn_011063_006.csv
  Story/Aelio/msn_011063_007.csv
  UI/access_info.csv
  UI/common.csv
  UI/config.csv
  UI/object_individual.csv
  UI/ui_achievements.csv
  UI/ui_battle_trigger.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_shop_reb.csv
Labels: size/XXL

#1834 Communa, speeder, +missing guiden dialogues
  Files/ssq_014812.csv
  Files/ssq_014813.csv
  Translated/Dialog/Communa/ssn_015140.csv
  Translated/Dialog/Communa/ssn_015141.csv
  Translated/Dialog/Guiden/ssq_014812.csv
  Translated/Dialog/Guiden/ssq_014813.csv
  Translated/Dialog/Speeder/ssn_015160_001.csv
  Translated/Dialog/Speeder/ssn_015160_003.csv
  Translated/Dialog/trial_common.csv
  Translated/Quests/Story/17 To the Kvaris Region/qst_1200300000.csv
  Translated/Story/15b Dark Falz/ssc_012030.csv
  Translated/Story/15b Dark Falz/ssc_012035.csv
  Translated/Story/15b Dark Falz/ssc_012070.csv
  Translated/Story/15b Dark Falz/ssc_012080.csv
  Translated/Tasks/Side/Speeder/ss0030740101.csv
  Translated/UI/ui_tutorial_reb.csv
Labels: size/L

#1837 KO: Update ui_charamake_text.csv
  UI/ui_charamake_text.csv
Labels: size/XS

#1841 KO_Reboot: Update files
  Files/qt1200300000.csv
  Files/qt1200320000.csv
  Files/qt1200340000.csv
  Files/qt1200360000.csv
  Files/qt1200370000.csv
  Misc/actor_name.csv
  Misc/object_common.csv
  Misc/region_mag_common.csv
  Quest/Undefined/quest_01100180.csv
  Quest/Undefined/quest_01200360.csv
  Task/Daily/ed0610000902.csv
  Task/Daily/ed0610011007.csv
  Task/Main/Kvaris/ms0010100330.csv
  Task/Main/Kvaris/ms0010100360.csv
  Task/Main/Kvaris/ms0010100370.csv
  Task/Main/Kvaris/qt1200300000.csv
  Task/Main/Kvaris/qt1200320000.csv
  Task/Main/Kvaris/qt1200340000.csv
  Task/Main/Kvaris/qt1200360000.csv
  Task/Main/Kvaris/qt1200370000.csv
  Task/Side Story/Kvaris/ss0030743004.csv
  Task/Side Story/Kvaris/ss0030774001.csv
  Task/Side Story/ss0030719501.csv
  Task/Side Story/ss0030719551.csv
  Task/Side Story/ss0030721051.csv
  Task/Side Story/ssn_012010.csv
  Task/Side Story/ssn_012011.csv
  Task/Side Story/ssn_019020_002.csv
  Task/Side Story/ssq_019020_004.csv
  Task/Weekly/gs0040103003.csv
  Tutorial/tut_006331.csv
  Tutorial/tut_006498.csv
  Tutorial/tut_006512.csv
  Tutorial/tut_006513.csv
  Tutorial/tut_006514.csv
  Tutorial/tut_006515.csv
  UI/common.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_selectmenu_text.csv
  UI/ui_shop_reb.csv
  UI/ui_tutorial_reb.csv
Labels: size/L

#1842 KO_Reboot: Fix error and fix typo
  UI/ui_item.csv
  UI/ui_tips_reb.csv
Labels: size/S

#1843 KO_Reboot: Update ui_mainmode.csv
  UI/ui_mainmode.csv
Labels: size/XS

#1845 KO_Reboot: Update files
  Files/ssn_014660.csv
  Files/ssn_014661.csv
  Files/ssn_014670.csv
  Files/ssn_014671.csv
  Files/ssn_014680.csv
  Files/ssn_014681.csv
  Files/ssn_014690.csv
  Files/ssn_014691.csv
  Files/ssn_014700.csv
  Files/ssn_014701.csv
  Files/ssn_014703.csv
  Files/ssn_014710.csv
  Files/ssn_014711.csv
  Files/ssn_014714.csv
  Task/Side Story/Kvaris/ssn_014660.csv
  Task/Side Story/Kvaris/ssn_014661.csv
  Task/Side Story/Kvaris/ssn_014670.csv
  Task/Side Story/Kvaris/ssn_014671.csv
  Task/Side Story/Kvaris/ssn_014680.csv
  Task/Side Story/Kvaris/ssn_014681.csv
  Task/Side Story/Kvaris/ssn_014690.csv
  Task/Side Story/Kvaris/ssn_014691.csv
  Task/Side Story/Kvaris/ssn_014700.csv
  Task/Side Story/Kvaris/ssn_014701.csv
  Task/Side Story/Kvaris/ssn_014703.csv
  Task/Side Story/Kvaris/ssn_014710.csv
  Task/Side Story/Kvaris/ssn_014711.csv
  Task/Side Story/Kvaris/ssn_014714.csv
Labels: size/L

#1846 KO_Reboot: Update actor_name_npc.csv
  Misc/actor_name_npc.csv
Labels: size/XS

#1848 Ko:캐릭터 이름 한국어로 하지말라고
  UI/ui_charamake_text.csv
Labels: size/XS

#1849 KO_Reboot: Update files
  Files/ssn_014720.csv
  Files/ssn_014721.csv
  Files/ssn_014724.csv
  Files/ssn_014727.csv
  Files/ssn_014730.csv
  Files/ssn_014731.csv
  Files/ssn_014733.csv
  Files/ssn_014736.csv
  Files/ssn_014750.csv
  Files/ssn_014751.csv
  Files/ssn_014760.csv
  Files/ssn_014761.csv
  Files/ssn_014770.csv
  Files/ssn_014771.csv
  Files/ssn_014780.csv
  Files/ssn_014783.csv
  Files/ssn_014790.csv
  Files/ssn_014791.csv
  Files/ssn_014792.csv
  Misc/actor_name_npc.csv
  Quest/Undefined/quest_01180030.csv
  Task/Side Story/Kvaris/ss0030762501.csv
  Task/Side Story/Kvaris/ssn_014720.csv
  Task/Side Story/Kvaris/ssn_014721.csv
  Task/Side Story/Kvaris/ssn_014724.csv
  Task/Side Story/Kvaris/ssn_014727.csv
  Task/Side Story/Kvaris/ssn_014730.csv
  Task/Side Story/Kvaris/ssn_014731.csv
  Task/Side Story/Kvaris/ssn_014733.csv
  Task/Side Story/Kvaris/ssn_014736.csv
  Task/Side Story/Kvaris/ssn_014750.csv
  Task/Side Story/Kvaris/ssn_014751.csv
  Task/Side Story/Kvaris/ssn_014760.csv
  Task/Side Story/Kvaris/ssn_014761.csv
  Task/Side Story/Kvaris/ssn_014770.csv
  Task/Side Story/Kvaris/ssn_014771.csv
  Task/Side Story/Kvaris/ssn_014780.csv
  Task/Side Story/Kvaris/ssn_014783.csv
  Task/Side Story/Kvaris/ssn_014790.csv
  Task/Side Story/Kvaris/ssn_014791.csv
  Task/Side Story/Kvaris/ssn_014792.csv
  Tutorial/tut_006516.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1847 Alvaro, Leso, Yuri sidetask dialogue
  Files/ssn_014770.csv
  Files/ssn_014771.csv
  Files/ssn_014920.csv
  Files/ssn_014921.csv
  Files/ssn_014950.csv
  Files/ssn_014951.csv
  Files/ssn_014960.csv
  Files/ssn_014961.csv
  Files/ssq_014772.csv
  Files/ssq_014922.csv
  Files/ssq_014952.csv
  Files/ssq_014962.csv
  Files/ssq_015072.csv
  Translated/Dialog/Alvaro/ssn_014960.csv
  Translated/Dialog/Alvaro/ssn_014961.csv
  Translated/Dialog/Alvaro/ssq_014962.csv
  Translated/Dialog/Leso/ssn_014950.csv
  Translated/Dialog/Leso/ssn_014951.csv
  Translated/Dialog/Leso/ssq_014952.csv
  Translated/Dialog/Leso/ssq_015072.csv
  Translated/Dialog/Truxtun/ssq_015061_005.csv
  Translated/Dialog/Yuri/ssn_014770.csv
  Translated/Dialog/Yuri/ssn_014771.csv
  Translated/Dialog/Yuri/ssn_014920.csv
  Translated/Dialog/Yuri/ssn_014921.csv
  Translated/Dialog/Yuri/ssq_014772.csv
  Translated/Dialog/Yuri/ssq_014922.csv
Labels: size/L

#1851 Cristobal & Vienne sidetask dialogue
  Files/ssn_014800.csv
  Files/ssn_014801.csv
  Files/ssn_014970.csv
  Files/ssn_014971.csv
  Files/ssn_014973.csv
  Files/ssq_014802.csv
  Files/ssq_014972.csv
  Files/ssq_014974.csv
  Translated/Dialog/Cristobal/ssn_015030.csv
  Translated/Dialog/Cristobal/ssn_015031.csv
  Translated/Dialog/Cristobal/ssn_015033.csv
  Translated/Dialog/Cristobal/ssn_015035.csv
  Translated/Dialog/Cristobal/ssn_015037.csv
  Translated/Dialog/Cristobal/ssq_015032.csv
  Translated/Dialog/Cristobal/ssq_015034.csv
  Translated/Dialog/Cristobal/ssq_015036.csv
  Translated/Dialog/Cristobal/ssq_015038.csv
  Translated/Dialog/Vienne/ssn_014800.csv
  Translated/Dialog/Vienne/ssn_014801.csv
  Translated/Dialog/Vienne/ssn_014970.csv
  Translated/Dialog/Vienne/ssn_014971.csv
  Translated/Dialog/Vienne/ssn_014973.csv
  Translated/Dialog/Vienne/ssq_014802.csv
  Translated/Dialog/Vienne/ssq_014972.csv
  Translated/Dialog/Vienne/ssq_014974.csv
  Translated/Tasks/Side/Leso/ss0030723701.csv
  Translated/Tasks/Side/Leso/ss0030723702.csv
Labels: size/L

#1852 KO: fix it soon
  UI/ui_charamake_parts.csv
Labels: size/XXL

#1853 the patch gave Leso an extra line of dialogue
  Translated/Dialog/Leso/ssn_014950.csv
  Translated/Dialog/Leso/ssn_015071.csv
Labels: size/XS
