Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-10, with the labels that each got.

#1906 EN: Snaedal change
  Translated/Quests/Emergency Quests/Snidael Vera/qst_1120040000.csv
  Translated/Quests/Emergency Quests/Snidael Vera/qst_1120040001.csv
  Translated/Quests/Emergency Quests/Snidael Vera/quest_01120040.csv
  Translated/Tasks/Limited/2022-03-23 Spring/ls0060130104.csv
  Translated/Tasks/Limited/2022-08-03 Waker release/ls0060090605.csv
  Translated/Tasks/Limited/2022-08-03 Waker release/ls0060090606.csv
  Translated/Tasks/Limited/Successive Training/Retem/ls0064060113.csv
  Translated/Tasks/Limited/Successive Training/Retem/ls0064060119.csv
  Translated/Tasks/Limited/Successive Training/Retem/ls0064060121.csv
  Translated/Tasks/Limited/Successive Training/Retem/retem rank 3/cp0410010110.csv
  Translated/Tasks/Limited/Successive Training/Retem/retem rank 3/cp0410010129.csv
  Translated/UI/actor_name.csv
  Translated/UI/ui_tips_reb.csv
Labels: size/M

#1909 Update msp_0119.csv
  Translated/Message Packs/msp_0119.csv
Labels: size/XS

#1910 Update ui_mainmode.csv
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#1911 Update ssc_502050.csv
  Translated/Dialog/Manon/ssc_502050.csv
Labels: size/XS

#1907 Update README.md
  README.md
Labels: size/S

#1912 Update quest_01200703.csv
  Translated/Quests/Story/Side Ch. 1/quest_01200703.csv
Labels: size/XS

#1914 KO_Reboot: Update files
  E-Trial/trial_common.csv
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Misc/object_common.csv
  Misc/open_field.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  UI/common.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
  UI/ui_playnavi.csv
  UI/ui_ranking_reb.csv
  UI/ui_selectmenu_text.csv
  UI/ui_tips_reb.csv
Labels: size/XL

#1915 Ko: Update files
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_gacha.csv
  UI/ui_guild.csv
  UI/ui_quest_es.csv
  UI/ui_selectmenu_text.csv
  UI/ui_title_text.csv
Labels: size/XL

#1917 KO_Reboot: Update files
  E-Trial/trial_apc_7001001.csv
  E-Trial/trial_apc_7002001.csv
  E-Trial/trial_comet.csv
  Task/Side Story/ssn_015150.csv
  WIP/Trigger Quest/quest_01180060.csv
  WIP/Trigger Quest/quest_01180070.csv
  WIP/Trigger Quest/quest_01180080.csv
  WIP/Trigger Quest/quest_01180090.csv
  WIP/Trigger Quest/quest_01180100.csv
  WIP/Trigger Quest/quest_01180110.csv
  WIP/Trigger Quest/quest_01180120.csv
  WIP/Trigger Quest/quest_01180130.csv
  WIP/Trigger Quest/quest_01180180.csv
Labels: size/M

#1918 KO: Update MANY STUFF
  Files/reb_gacha_banner_15032.csv
  Files/reb_gacha_banner_15061.csv
  Files/reb_gacha_banner_15062.csv
  Files/reb_gacha_banner_20005.csv
  Files/reb_gacha_banner_20006.csv
  Files/reb_gacha_banner_20007.csv
  Files/reb_gacha_banner_20010.csv
  Files/reb_gacha_banner_20011.csv
  Files/reb_gacha_banner_20012.csv
  Files/reb_gacha_banner_s_15061.csv
  Files/reb_gacha_banner_s_15062.csv
  Files/reb_gacha_banner_s_20005.csv
  Files/reb_gacha_banner_s_20006.csv
  Files/reb_gacha_banner_s_20007.csv
  Files/reb_gacha_banner_s_20010.csv
  Files/reb_gacha_banner_s_20011.csv
  Files/reb_gacha_banner_s_20012.csv
  Files/reb_gacha_banner_small_15032.csv
  Files/ui_gacha_101_00.csv
  UI/common.csv
  UI/item_element_expl_reb.csv
  UI/ui_amusement.csv
  UI/ui_billing_direct.csv
  UI/ui_challenge.csv
  UI/ui_fashion_catalog.csv
  UI/ui_gacha.csv
  UI/ui_guild.csv
  UI/ui_na_mainmode.csv
  UI/ui_symbol.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1921 Update ui_mainmode.csv
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#1919 KO_Reboot: Update files
  E-Trial/trial_common.csv
  Files/cl0421110101.csv
  Files/cl0421110102.csv
  Files/cl0421110103.csv
  Files/cl0421110104.csv
  Files/ls0060100517.csv
  Files/ls0060100519.csv
  Files/quest_01190000.csv
  Files/ss0030740503.csv
  Files/ssn_015220.csv
  Files/tut_006298.csv
  Quest/Ordinal Tower/quest_01190000.csv
  Quest/ui_quest_counter_reb.csv
  Task/Limited/2022/October/Limited/cl0421110101.csv
  Task/Limited/2022/October/Limited/cl0421110102.csv
  Task/Limited/2022/October/Limited/cl0421110103.csv
  Task/Limited/2022/October/Limited/cl0421110104.csv
  Task/Limited/Ordinal Tower/ls0060100517.csv
  Task/Limited/Ordinal Tower/ls0060100519.csv
  Task/Side Story/Aelio/Schraft/ss0030740503.csv
  Task/Side Story/Aelio/Schraft/ssn_015220.csv
  Task/Side Story/Kvaris/ssn_014711.csv
  Tutorial/tut_006298.csv
  UI/ui_selectmenu_text.csv
  UI/ui_tutorial_reb.csv
  WIP/ssn_015185.csv
Labels: size/M

#1923 Update ui_shop_reb.csv
  Translated/UI/ui_shop_reb.csv
Labels: size/XS
