Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-05, with the labels that each got.

#1811 KO_Reboot: Update files
  .circleci/config.yml
  UI/ui_mainmode.csv
  UI/ui_scratch_reb.csv
Labels: size/S

#1812 KO: Fix typo
  .circleci/config.yml
  .gitignore
  Files/smut_filter.csv
  UI/ui_title_text.csv
Labels: size/XXL

#1813 Change wording in Ruslan's Tower Task
  Translated/Tasks/Side/Ruslan/ss0030771001.csv
Labels: size/XS

#1815 RU_Reboot: asap upd
  Reboot/UI/ui_mainmode.csv
Labels: size/S

#1817 Remove and replace circle
  .circleci/config.yml
  .github/workflow/build.yml
Labels: size/M

#1818 RU: trigger event
  .github/workflow/build.yml
Labels: size/S

#1819 RU: fix file
  .github/workflows/build.yml
Labels: size/XS

#1820 specify events
  .github/workflows/build.yml
Labels: size/S

#1822 ....
  .github/workflows/build.yml
Labels: size/XS

#1823 fix2
  .github/workflows/build.yml
Labels: size/XS

#1825 test
  .github/workflows/build.yml
Labels: size/XS

#1826 RU: ignore branch from circle
  .circleci/config.yml
  .github/workflows/build.yml
Labels: size/XS
