Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-01, with the labels that each got.

#1733 KO: FIx typo
  Quests/Challenge Quests/1 Start/cm_038105_12.csv
  UI/item_element_expl_reb.csv
Labels: size/S

#1734 KO_Reboot: fix typo
  UI/config.csv
  UI/ui_mainmode.csv
Labels: size/S

#1735 KO: fix typo
  UI/item_element_name_reb.csv
  UI/ui_charamake_text.csv
Labels: size/M

#1737 KO: Update ob_9900_0471.csv
  Files/ob_9900_0471.csv
  Quests/Screenshot Quest/ob_9900_0471.csv
Labels: size/M

#1738 KO_Reboot: Fix typo
  Files/msc_011200.csv
  Story/Aelio/msc_011200.csv
  Story/Prologue/msc_010230.csv
  Task/Side Story/ssn_014320.csv
  Task/Side Story/ssn_014321.csv
  Task/Side Story/ssn_014410.csv
  Task/Side Story/ssn_014411.csv
  Task/Side Story/ssn_014500.csv
  Task/Side Story/ssn_014501.csv
  Task/Side Story/ssq_014323.csv
  Task/Side Story/ssq_014413.csv
  Task/Side Story/ssq_014414.csv
  Task/Side Story/ssq_014503.csv
  Task/Side Story/ssq_014504.csv
  UI/config.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
Labels: size/L

#1739 KO_Reboot: Fix typo
  Tutorial/tut_006358.csv
  UI/config.csv
  UI/ui_equip.csv
  UI/ui_mainmode.csv
  UI/ui_tutorial_guide.csv
  UI/ui_tutorial_reb.csv
Labels: size/S

#1740 small grammar changes
  Translated/Dialog/world_trial_gold.csv
Labels: size/XS

#1741 KO_Reboot: fix typo
  Task/Side Story/ssq_019050_004.csv
  UI/ui_mainmode.csv
Labels: size/S
