Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-04, with the labels that each got.

#1771 KO: update filelist
  UI/ui_esthetic_text.csv
  UI/ui_shop.csv
  filelist.txt
Labels: size/XXL

#1775 KO: Update ui_gacha.csv
  UI/ui_gacha.csv
Labels: size/XS

#1776 Update msq_012011.csv
  Translated/Story/15a Song of Restoration/msq_012011.csv
Labels: size/S

#1777 Update msq_012013.csv
  Translated/Story/15a Song of Restoration/msq_012013.csv
Labels: size/XS

#1778 Update msq_012014.csv
  Translated/Story/15a Song of Restoration/msq_012014.csv
Labels: size/XS

#1779 Update msq_012015.csv
  Translated/Story/15a Song of Restoration/msq_012015.csv
Labels: size/XS

#1780 Update msq_012016.csv
  Translated/Story/15a Song of Restoration/msq_012016.csv
Labels: size/XS

#1781 Update msq_012017.csv
  Translated/Story/15a Song of Restoration/msq_012017.csv
Labels: size/XS

#1782 Update msq_012018.csv
  Translated/Story/15a Song of Restoration/msq_012018.csv
Labels: size/XS

#1783 Update msq_012019.csv
  Translated/Story/15a Song of Restoration/msq_012019.csv
Labels: size/XS

#1784 Update ssc_012010.csv
  Translated/Story/15a Song of Restoration/ssc_012010.csv
Labels: size/M

#1785 Update ssc_012020.csv
  Translated/Story/15a Song of Restoration/ssc_012020.csv
Labels: size/S

#1786 Ru: New content
  Files/item_series_name.csv
  translated files/UI/common.csv
  translated files/UI/config.csv
  translated files/UI/item_element_expl_reb.csv
  translated files/UI/item_element_name_reb.csv
  translated files/UI/item_series_name.csv
  translated files/UI/ui_charamake_text.csv
  translated files/UI/ui_charamake_text_reb.csv
  translated files/UI/ui_mainmode.csv
Labels: size/L

#1788 KO: Update files
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_mainmode.csv
Labels: size/L

#1787 KO_Reboot: 2022-04-06 Retem update
  .gitignore
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Misc/object_common.csv
  Misc/open_field.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  Task/Side Story/ssq_019060_002.csv
  Tutorial/tut_006436.csv
  Tutorial/tut_006437.csv
  Tutorial/tut_006439.csv
  Tutorial/tut_006442.csv
  Tutorial/tut_006443.csv
  Tutorial/tut_006445.csv
  Tutorial/tut_006447.csv
  Tutorial/tut_006462.csv
  Tutorial/tut_006480.csv
  UI/common.csv
  UI/config.csv
  UI/ui_battle_trigger.csv
  UI/ui_directbuy_text.csv
  UI/ui_equip.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_qu_extra.csv
  UI/ui_rebops.csv
  UI/ui_selectmenu_text.csv
  UI/ui_shop_reb.csv
  UI/ui_tips_reb.csv
  UI/ui_tutorial_reb.csv
Labels: size/XXL

#1795 Change High Rank Equalizing Enemy tutorial description
  Translated/Tutorials/tut_006482.csv
Labels: size/XS

#1797 Apostrophe fix
  Translated/Lobby/Concert/lvs_070010.csv
Labels: size/XS

#1801 Ru_Reboot: Some ui upd, Nadereh & DF
  Files/msq_012011.csv
  Files/msq_012013.csv
  Files/msq_012014.csv
  Files/msq_012015.csv
  Files/msq_012016.csv
  Files/msq_012017.csv
  Files/msq_012018.csv
  Files/msq_012019.csv
  Files/ssn_012005.csv
  Files/ssn_012006.csv
  Reboot/Dialog/Retem/Nadereh/ssn_012005.csv
  Reboot/Dialog/Retem/Nadereh/ssn_012006.csv
  Reboot/Dialog/ti_1019916000_unk_tan_ba.csv
  Reboot/Quests/Emergency Quests/Retem/Rig Defense/qst_1120080000.csv
  Reboot/Quests/Emergency Quests/Retem/Rig Defense/qst_1120080010.csv
  Reboot/Quests/Emergency Quests/Retem/Rig Defense/qst_1120080020.csv
  Reboot/Quests/Emergency Quests/Retem/Rig Defense/quest_01120050.csv
  Reboot/Quests/Story/Ch2/15a Song of Restoration/qst_1200290000.csv
  Reboot/Quests/Story/Ch2/15a Song of Restoration/qt1200290000.csv
  Reboot/Quests/Story/Ch2/15a Song of Restoration/quest_01200290.csv
  Reboot/Quests/Trinitas/quest_01170000.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012011.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012013.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012014.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012015.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012016.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012017.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012018.csv
  Reboot/Story/Ch2/15a Song of Restoration/msq_012019.csv
  Reboot/Story/Ch2/15a Song of Restoration/ssc_012010.csv
  Reboot/Story/Ch2/15a Song of Restoration/ssc_012020.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012010.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012020.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012030.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012035.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012070.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012080.csv
  Reboot/UI/common.csv
  Reboot/UI/config.csv
  Reboot/UI/ui_item.csv
  Reboot/UI/ui_tips_reb.csv
Labels: size/XXL

#1803 Guiden task dialogue
  Translated/Dialog/Guiden/ssn_014380.csv
  Translated/Dialog/Guiden/ssn_014381.csv
  Translated/Dialog/Guiden/ssq_014382.csv
  Translated/Dialog/Guiden/ssq_014382_001.csv
Labels: size/M

#1805 Ru reboot: Some fixes
  Files/msq_011220_005.csv
  Reboot/Dialog/Aelio/Somua/ssn_014020.csv
  Reboot/Dialog/Aelio/Somua/ssn_014021.csv
  Reboot/Message Packs/msp_0013.csv
  Reboot/Message Packs/msp_0033.csv
  Reboot/Message Packs/msp_0034.csv
  Reboot/Message Packs/msp_0035.csv
  Reboot/Message Packs/msp_0038.csv
  Reboot/Message Packs/msp_0042.csv
  Reboot/Message Packs/msp_0053.csv
  Reboot/Message Packs/msp_0057.csv
  Reboot/Message Packs/msp_0069.csv
  Reboot/Message Packs/msp_0070.csv
  Reboot/Message Packs/msp_0071.csv
  Reboot/Message Packs/msp_0072.csv
  Reboot/Message Packs/msp_0080.csv
  Reboot/Message Packs/msp_0085.csv
  Reboot/Message Packs/msp_0086.csv
  Reboot/Message Packs/msp_0087.csv
  Reboot/Quests/Battledia/Aelio/quest_01140000.csv
  Reboot/Quests/Battledia/Aelio/quest_01150000.csv
  Reboot/Quests/Battledia/Retem/quest_01140010.csv
  Reboot/Quests/Battledia/Retem/quest_01150010.csv
  Reboot/Quests/Cocoons/Aelio/Enhanced Enemy/quest_01100010.csv
  Reboot/Quests/Cocoons/Aelio/First Step/quest_01100050.csv
  Reboot/Quests/Cocoons/Aelio/Lone Way/quest_01100040.csv
  Reboot/Quests/Cocoons/Aelio/Test Flight/quest_01100020.csv
  Reboot/Quests/Cocoons/Retem/Lone Way II/quest_01100130.csv
  Reboot/Quests/Cocoons/Retem/Parkour Master/quest_01100140.csv
  Reboot/Quests/Emergency Quests/Seasonal/Spring 2022/qst_1120070000.csv
  Reboot/Quests/Emergency Quests/Seasonal/Spring 2022/qst_1120070010.csv
  Reboot/Story/Ch1/04-05 DOLLS on Mt. Magnus/msq_011220_005.csv
  Reboot/Story/Ch1/06-07 Three Stand Alone/msc_011330.csv
  Reboot/Story/Ch1/06-07 Three Stand Alone/msn_011350_020.csv
  Reboot/Tasks/Daily/2022-01-12 Winter/ed0611041103.csv
  Reboot/Tasks/Daily/2022-01-12 Winter/ed0611041203.csv
  Reboot/Tasks/Limited/2022-01-12 Winter/ls0061040102.csv
  Reboot/Tasks/Limited/2022-01-12 Winter/ls0061040103.csv
  Reboot/Tasks/Main Story/Ch1/ms0010100121.csv
  Reboot/Tasks/Repeating/rs0317424013.csv
  Reboot/Tasks/Side/Retem/Ariete/ss0030742101.csv
  Reboot/Tutorial/tut_006405.csv
  Reboot/UI/common.csv
  Reboot/UI/config.csv
  Reboot/UI/open_field.csv
  Reboot/UI/quest_common_reboot.csv
  Reboot/UI/ui_item.csv
  Reboot/UI/ui_mainmode.csv
  Reboot/UI/ui_quest_reb.csv
  Reboot/UI/ui_rebops.csv
  Reboot/UI/ui_scratch_reb.csv
  Reboot/UI/ui_selectmenu_text.csv
  Reboot/UI/ui_shop_reb.csv
  filelist.txt
Labels: size/L

#1806 RU: Some additional & copy-paste ticket item names
  translated files/UI/item_series_name.csv
  translated files/UI/ui_charamake_parts.csv
  translated files/UI/ui_charamake_text.csv
  translated files/UI/ui_charamake_text_reb.csv
Labels: size/XXL

#1809 JP_Reboot: remove file
  Files/mt0010100210.csv
Labels: size/XS
