Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-07, with the labels that each got.

#1854 over, but also over
  Translated/Dialog/Leso/ssn_014950.csv
Labels: size/XS

#1856 fix linebreak
  Translated/Tutorials/tut_006506.csv
Labels: size/XS

#1857 KO:Update files
  Files/smut_filter.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
Labels: size/XXL

#1858 Peppy Rappy dialogue
  Files/ssn_019080_001.csv
  Files/ssn_019080_002.csv
  Files/ssq_019080_003.csv
  Files/ssq_019080_004.csv
  Files/ssq_019080_005.csv
  Files/ssq_019080_006.csv
  Files/ssq_019080_007.csv
  Files/ssq_019080_008.csv
  Files/ssq_019080_009.csv
  Files/ssq_019080_010.csv
  Translated/Dialog/Peppy Rappy/ssn_019080_001.csv
  Translated/Dialog/Peppy Rappy/ssn_019080_002.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_003.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_004.csv.
  Translated/Dialog/Peppy Rappy/ssq_019080_005.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_006.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_007.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_008.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_009.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_010.csv
  Translated/Dialog/trial_rappy_room.csv
  Translated/Tutorials/tut_006517.csv
Labels: size/L

#1859 10th Anniversary Seasonal Tasks
  Files/ls0060140401.csv
  Files/ls0060140402.csv
  Files/ls0061090101.csv
  Files/ls0061090103.csv
  Files/ls0061090104.csv
  Files/ls0061090105.csv
  Files/ls0061090106.csv
  Files/ls0061090107.csv
  Files/ls0061090108.csv
  Files/ls0061090110.csv
  Files/ls0061090111.csv
  Files/ls0061090112.csv
  Files/ls0061090113.csv
  Files/ls0061090201.csv
  Files/ls0061090202.csv
  Files/ls0061090203.csv
  Files/ls0061090204.csv
  Files/ls0061090205.csv
  Files/ls0061090206.csv
  Files/ls0061090207.csv
  Files/ls0061090208.csv
  Files/ls0061090209.csv
  Files/ls0061090210.csv
  Files/ls0061090211.csv
  Files/ls0061090212.csv
  Translated/Dialog/Peppy Rappy/ssq_019080_004.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0060140401.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0060140402.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090101.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090102.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090103.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090104.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090105.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090106.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090107.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090108.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090109.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090110.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090111.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090112.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090113.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090201.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090202.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090203.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090204.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090205.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090206.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090207.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090208.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090209.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090210.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090211.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061090212.csv
Labels: size/L

#1861 KO_Reboot: Fix typo
  Task/Side Story/Kvaris/ss0030742901.csv
  Task/Side Story/Kvaris/ss0030742902.csv
  Task/Side Story/Kvaris/ss0030742903.csv
  Task/Side Story/Kvaris/ss0030742904.csv
  Task/Side Story/Kvaris/ss0030742905.csv
  Task/Side Story/Kvaris/ss0030742906.csv
  Task/Side Story/Kvaris/ss0030742907.csv
  Task/Side Story/Kvaris/ss0030742908.csv
  Task/Side Story/Kvaris/ss0030742909.csv
  UI/ui_item.csv
Labels: size/M

#1860 KO: Update files
  Files/smut_filter.csv
  UI/ui_accessories_text.csv
  UI/ui_charamake_parts.csv
Labels: size/XXL

#1863 KO_Reboot: Update files
  Quest/Undefined/quest_01180020.csv
  WIP/ssn_019080_002.csv
Labels: size/S

#1864 forgot some seasonal tasks
  Files/ls0061091101.csv
  Files/ls0061091102.csv
  Files/ls0061091103.csv
  Files/ls0061091104.csv
  Files/ls0061091105.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061091101.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061091102.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061091103.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061091104.csv
  Translated/Tasks/Limited/2022-07-06 10th Anniversary/ls0061091105.csv
Labels: size/M

#1865 untranslated lobby actions
  Translated/UI/common.csv
Labels: size/L

#1866 ellipse spacing
  Translated/Dialog/Cristobal/ssn_014870.csv
  Translated/Dialog/Lize/ssn_014550.csv
  Translated/Quests/Story/17 The Ancient Snow-Covered Ruins/qst_1200320050.csv
  Translated/Quests/Story/18 The Forest Searchers/qst_1200340001.csv
  Translated/Quests/Story/18 The Forest Searchers/qst_1200340020.csv
  Translated/Story/16 To the Kvaris Region/msc_013100.csv
  Translated/Story/16 To the Kvaris Region/msq_013041.csv
  Translated/Story/17 The Ancient Snow-Covered Ruins/msc_013160.csv
  Translated/Story/17 The Ancient Snow-Covered Ruins/msc_013170.csv
  Translated/Story/18 The Forest Searchers/msc_013220.csv
  Translated/Story/18 The Forest Searchers/msq_013201.csv
  Translated/Story/19-20 The Forbidding City/msc_013230.csv
  Translated/Story/19-20 The Forbidding City/msc_013300.csv
Labels: size/S

#1867 forgot some
  Translated/Story/16 To the Kvaris Region/msc_013020.csv
  Translated/Story/16 To the Kvaris Region/msc_013025.csv
  Translated/Story/16 To the Kvaris Region/msc_013090.csv
  Translated/Story/17 The Ancient Snow-Covered Ruins/msq_013151.csv
Labels: size/XS

#1869 linebreak testing for tips
  Translated/UI/ui_tips_reb.csv
Labels: size/M

#1870 loading screen and death tips translated
  Translated/UI/ui_tips_reb.csv
Labels: size/L

#1871 EN: fixup EN build
  Files/gacha_banner_large_14.csv
  Files/gacha_banner_large_18.csv
  Files/load_banner_large_08.csv
  Files/load_banner_large_20.csv
  Files/mainmenu_banner_06.csv
  Files/mainmenu_banner_07.csv
  Files/mainmenu_banner_08.csv
  Files/mainmenu_banner_10.csv
Labels: size/XS

#1872 EN: fixes to pass the "verifing CSVs for PSO2 format" test
  Files/mainmenu_banner_04.csv
  Files/reb_gacha_banner_15032.csv
  Files/reb_gacha_banner_15061.csv
  Files/reb_gacha_banner_15062.csv
  Files/reb_gacha_banner_20005.csv
  Files/reb_gacha_banner_20006.csv
  Files/reb_gacha_banner_20007.csv
  Files/reb_gacha_banner_20010.csv
  Files/reb_gacha_banner_20011.csv
  Files/reb_gacha_banner_20012.csv
  Files/reb_gacha_banner_s_15061.csv
  Files/reb_gacha_banner_s_15062.csv
  Files/reb_gacha_banner_s_20005.csv
  Files/reb_gacha_banner_s_20006.csv
  Files/reb_gacha_banner_s_20007.csv
  Files/reb_gacha_banner_s_20010.csv
  Files/reb_gacha_banner_s_20011.csv
  Files/reb_gacha_banner_s_20012.csv
  Files/reb_gacha_banner_small_15032.csv
  Files/smut_filter.csv
  Misc/smut_filter.csv
Labels: size/XXL
