Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-12, with the labels that each got.

#1935 KO_Reboot: Fix typo
  E-Trial/trial_machine_discover.csv
  Files/trial_machine_discover.csv
  Misc/actor_name_npc.csv
  Quest/ui_quest_reb.csv
  UI/common.csv
  UI/config.csv
  UI/ui_na_mainmode.csv
  UI/ui_playnavi.csv
  UI/ui_ranking_reb.csv
  UI/ui_shop_reb.csv
Labels: size/M

#1933 Reworded join party message
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#1936 KO_Reboot: Update files
  E-Trial/trial_machine_discover.csv
  Files/ssn_014823.csv
  Files/ssn_014824.csv
  Files/ssn_015190_007.csv
  Files/ssn_015190_009.csv
  Files/ssn_015190_011.csv
  Files/ssn_015190_013.csv
  Files/ssn_015190_015.csv
  Task/Side Story/ssn_014823.csv
  Task/Side Story/ssn_014824.csv
  Task/Side Story/ssn_015190_007.csv
  Task/Side Story/ssn_015190_009.csv
  Task/Side Story/ssn_015190_011.csv
  Task/Side Story/ssn_015190_013.csv
  Task/Side Story/ssn_015190_015.csv
  UI/ui_mainmode.csv
Labels: size/L

#1938 Update ed0610011808.csv
  Translated/Tasks/Daily/Stia/ed0610011808.csv
Labels: size/XS

#1939 KO_Reboot: Update ui_mainmode.csv
  UI/ui_mainmode.csv
Labels: size/XS

#1941 KO_Reboot: Update files
  Files/ssn_015300.csv
  Files/ssn_015301.csv
  Files/ssn_015303.csv
  Files/ssn_015306.csv
  Files/ssn_015310.csv
  Files/ssn_015311.csv
  Files/ssn_015320.csv
  Files/ssn_015321.csv
  Files/ssq_015190_008.csv
  Files/ssq_015190_010.csv
  Files/ssq_015190_012.csv
  Files/ssq_015190_014.csv
  Files/ssq_015190_016.csv
  Files/ssq_015302.csv
  Files/ssq_015304.csv
  Files/ssq_015305.csv
  Files/ssq_015307.csv
  Files/ssq_015308.csv
  Files/ssq_015312.csv
  Files/ssq_015313.csv
  Files/ssq_015322.csv
  Task/Side Story/Stia/ssn_015300.csv
  Task/Side Story/Stia/ssn_015301.csv
  Task/Side Story/Stia/ssn_015303.csv
  Task/Side Story/Stia/ssn_015306.csv
  Task/Side Story/Stia/ssn_015310.csv
  Task/Side Story/Stia/ssn_015311.csv
  Task/Side Story/Stia/ssn_015320.csv
  Task/Side Story/Stia/ssn_015321.csv
  Task/Side Story/Stia/ssq_015302.csv
  Task/Side Story/Stia/ssq_015304.csv
  Task/Side Story/Stia/ssq_015305.csv
  Task/Side Story/Stia/ssq_015307.csv
  Task/Side Story/Stia/ssq_015308.csv
  Task/Side Story/Stia/ssq_015312.csv
  Task/Side Story/Stia/ssq_015313.csv
  Task/Side Story/Stia/ssq_015322.csv
  Task/Side Story/ssq_015190_008.csv
  Task/Side Story/ssq_015190_010.csv
  Task/Side Story/ssq_015190_012.csv
  Task/Side Story/ssq_015190_014.csv
  Task/Side Story/ssq_015190_016.csv
Labels: size/L

#1944 Correct Fom Souls IV/V values
  UI/item_element_expl_reb.csv
Labels: size/S

#1949 Typos and suggested improvements
  Translated/Story/23 The Battle For Dreisen Plant/msc_014110.csv
  Translated/Story/24 The Battle For Altera Base/msn_014141.csv
  Translated/Story/24 The Battle For Altera Base/msq_014155.csv
  Translated/Story/26 The Heart of Stia/msc_014320.csv
  Translated/Story/26 The Heart of Stia/msc_014355.csv
Labels: size/S

#1952 KO_Reboot: Update files
  Files/ssn_015330.csv
  Files/ssn_015331.csv
  Files/ssn_015334.csv
  Files/ssn_015340.csv
  Files/ssn_015341.csv
  Files/ssn_015350.csv
  Files/ssn_015351.csv
  Files/ssn_015354.csv
  Files/ssn_015357.csv
  Files/ssn_015450.csv
  Files/ssn_015451.csv
  Files/ssn_015460.csv
  Files/ssn_015461.csv
  Files/ssn_015463.csv
  Files/ssq_015332.csv
  Files/ssq_015335.csv
  Files/ssq_015342.csv
  Files/ssq_015352.csv
  Files/ssq_015353.csv
  Files/ssq_015355.csv
  Files/ssq_015356.csv
  Files/ssq_015358.csv
  Files/ssq_015359.csv
  Files/ssq_015452.csv
  Files/ssq_015462.csv
  Files/ssq_015464.csv
  Task/Side Story/Stia/ssn_015330.csv
  Task/Side Story/Stia/ssn_015331.csv
  Task/Side Story/Stia/ssn_015334.csv
  Task/Side Story/Stia/ssn_015340.csv
  Task/Side Story/Stia/ssn_015341.csv
  Task/Side Story/Stia/ssn_015350.csv
  Task/Side Story/Stia/ssn_015351.csv
  Task/Side Story/Stia/ssn_015354.csv
  Task/Side Story/Stia/ssn_015357.csv
  Task/Side Story/Stia/ssn_015450.csv
  Task/Side Story/Stia/ssn_015451.csv
  Task/Side Story/Stia/ssn_015460.csv
  Task/Side Story/Stia/ssn_015461.csv
  Task/Side Story/Stia/ssn_015463.csv
  Task/Side Story/Stia/ssq_015332.csv
  Task/Side Story/Stia/ssq_015335.csv
  Task/Side Story/Stia/ssq_015342.csv
  Task/Side Story/Stia/ssq_015352.csv
  Task/Side Story/Stia/ssq_015353.csv
  Task/Side Story/Stia/ssq_015355.csv
  Task/Side Story/Stia/ssq_015356.csv
  Task/Side Story/Stia/ssq_015358.csv
  Task/Side Story/Stia/ssq_015359.csv
  Task/Side Story/Stia/ssq_015452.csv
  Task/Side Story/Stia/ssq_015462.csv
  Task/Side Story/Stia/ssq_015464.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1953 Update msc_014040.csv
  Translated/Story/22 To the Stia Region/msc_014040.csv
Labels: size/XS

#1954 KO_Reboot: Fix typo
  Story/Stia/msc_014040.csv
  Story/Stia/msc_014290.csv
  Story/Stia/msc_014380.csv
  Story/Stia/msq_014322.csv
  Task/Main/Stia/ms0010100420.csv
  Task/Side Story/Stia/ss0030745002.csv
  UI/access_info.csv
  UI/ui_mainmode.csv
Labels: size/M

#1955 doldoris vera dialogue + dummy files that are no longer dummies
  Dummy/qst_1200480020.csv
  Dummy/qst_1200480030.csv
  Dummy/qst_1200480050.csv
  Dummy/qst_1200480060.csv
  Translated/Quests/Emergency Quests/Doldoris Vera/qst_1120140000.csv
  Translated/Quests/Emergency Quests/Doldoris Vera/qst_1120140010.csv
  Translated/Story/26 The Heart of Stia/qst_1200480020.csv
  Translated/Story/26 The Heart of Stia/qst_1200480030.csv
  Translated/Story/26 The Heart of Stia/qst_1200480050.csv
  Translated/Story/26 The Heart of Stia/qst_1200480060.csv
Labels: size/M

#1956 KO_Reboot: Update files
  Files/ssn_015470.csv
  Files/ssn_015471.csv
  Files/ssn_015480.csv
  Files/ssn_015481.csv
  Files/ssn_015483.csv
  Files/ssq_015472.csv
  Files/ssq_015482.csv
  Files/ssq_015484.csv
  Task/Side Story/Stia/ssn_015470.csv
  Task/Side Story/Stia/ssn_015471.csv
  Task/Side Story/Stia/ssn_015480.csv
  Task/Side Story/Stia/ssn_015481.csv
  Task/Side Story/Stia/ssn_015483.csv
  Task/Side Story/Stia/ssq_015472.csv
  Task/Side Story/Stia/ssq_015482.csv
  Task/Side Story/Stia/ssq_015484.csv
  UI/ui_mainmode.csv
Labels: size/L

#1961 KO_Reboot: Update files
  Files/ssn_015490.csv
  Files/ssn_015491.csv
  Files/ssn_015500.csv
  Files/ssn_015501.csv
  Files/ssn_015502.csv
  Files/ssq_015492.csv
  Task/Side Story/Stia/ssn_015490.csv
  Task/Side Story/Stia/ssn_015491.csv
  Task/Side Story/Stia/ssn_015500.csv
  Task/Side Story/Stia/ssn_015501.csv
  Task/Side Story/Stia/ssn_015502.csv
  Task/Side Story/Stia/ssq_015492.csv
  UI/ui_mainmode.csv
Labels: size/L
