Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-02, with the labels that each got.

#1744 KO_Reboot: Fix typo
  Files/msc_011200.csv
  Quest/quest_common_reboot.csv
  Story/Aelio/msc_011200.csv
  Task/Daily/ed0611042205.csv
  UI/ui_mainmode.csv
  UI/ui_tips_reb.csv
Labels: size/S

#1746 Retem NPC dialogue
  Files/npc_769301.csv
  Files/npc_769401.csv
  Files/npc_769601.csv
  Files/npc_770201.csv
  Files/npc_770202.csv
  Files/npc_771101.csv
  Files/npc_771201.csv
  Files/npc_771701.csv
  Files/npc_771901.csv
  Files/npc_772001.csv
  Translated/Dialog/Beverly/npc_771701.csv
  Translated/Dialog/Cicogna/npc_770201.csv
  Translated/Dialog/Cicogna/npc_770202.csv
  Translated/Dialog/Gepallt/npc_771201.csv
  Translated/Dialog/Irida/npc_769301.csv
  Translated/Dialog/Lysandre/npc_769401.csv
  Translated/Dialog/Murriah/npc_769601.csv
  Translated/Dialog/Ratel/npc_771901.csv
  Translated/Dialog/Roara/npc_771101.csv
  Translated/Dialog/Rooikat/npc_772001.csv
Labels: size/M

#1743 uhhhhh, is this right?
  Files/ssn_005001.csv
  Translated/Dialog/Varme/ssn_005001.csv
Labels: size/M

#1749 KO_Reboot: Update files
  Misc/actor_name.csv
  NPC Dialogue/np_npc_7207_001.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_tutorial_reb.csv
Labels: size/M

#1753 KO_Reboot: derp
  Files/ssc_012030.csv
  Files/ssc_012035.csv
  Task/Side Story/ssc_012030.csv
  Task/Side Story/ssc_012035.csv
Labels: size/M

#1754 KO_Reboot: DF After Cutscene
  Files/ssc_012070.csv
  Files/ssc_012080.csv
  Task/Side Story/ssc_012070.csv
  Task/Side Story/ssc_012080.csv
Labels: size/M

#1755 KO_Reboot: Update files
  Files/qt1200290000.csv
  Files/quest_01180000.csv
  Files/quest_01200290.csv
  Files/ssn_019060_001.csv
  Files/ssn_019060_002.csv
  Files/ssq_014571.csv
  Files/ssq_019060_002.csv
  Files/ssq_019060_003.csv
  Files/ssq_019060_004.csv
  Files/ssq_019060_005.csv
  Files/ssq_019060_006.csv
  Files/ssq_019060_007.csv
  Files/ssq_019060_008.csv
  Files/ssq_019060_009.csv
  Files/ssq_019060_010.csv
  Files/ssq_019060_011.csv
  Files/ssq_019060_012.csv
  Files/ssq_019060_013.csv
  Quest/Main/Retem/quest_01200290.csv
  Quest/quest_01180000.csv
  Task/Main/qt1200290000.csv
  Task/Side Story/ssc_012030.csv
  Task/Side Story/ssc_012035.csv
  Task/Side Story/ssc_012070.csv
  Task/Side Story/ssn_019060_001.csv
  Task/Side Story/ssn_019060_002.csv
  Task/Side Story/ssq_014571.csv
  Task/Side Story/ssq_019060_002.csv
  Task/Side Story/ssq_019060_003.csv
  Task/Side Story/ssq_019060_004.csv
  Task/Side Story/ssq_019060_005.csv
  Task/Side Story/ssq_019060_006.csv
  Task/Side Story/ssq_019060_007.csv
  Task/Side Story/ssq_019060_008.csv
  Task/Side Story/ssq_019060_009.csv
  Task/Side Story/ssq_019060_010.csv
  Task/Side Story/ssq_019060_011.csv
  Task/Side Story/ssq_019060_012.csv
  Task/Side Story/ssq_019060_013.csv
Labels: size/L

#1756 KO_Reboot : 아 맞다 파일리스트 까먹엇네
  filelist.txt
Labels: size/L

#1757 KO_Reboot: Delete unused files
  Quest but need check/qst_1100050150.csv
  Quest but need check/qst_1100050160.csv
Labels: size/S

#1760 KO: Update ui_charamake_text_reb.csv
  UI/ui_charamake_text_reb.csv
Labels: size/XS

#1763 RU Reboot: filelist fix
  filelist.txt
Labels: size/L
