Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-08, with the labels that each got.

#1878 pushing to debug
  Translated/Dialog/Bruder/ssc_503020.csv
  Translated/Dialog/Bruder/ssc_503030.csv
  Translated/Dialog/Bruder/ssc_503040.csv
  Translated/Dialog/Manon/ssc_502040.csv
  Translated/Dialog/Manon/ssc_502050.csv
  Translated/Dialog/Waker Release/ssc_502040.csv
  Translated/Dialog/Waker Release/ssc_502050.csv
  Translated/Dialog/Waker Release/ssc_503020.csv
  Translated/Dialog/Waker Release/ssc_503030.csv
Labels: size/L

#1874 KO_Reboot: Update files
  Misc/actor_name.csv
  Quest/ui_quest_reb.csv
  Story/Prologue/msc_010130.csv
  Task/Main/ms0010100220.csv
  Task/Side Story/Kvaris/ssn_014950.csv
  Task/Side Story/Kvaris/ssn_014951.csv
  Task/Side Story/Kvaris/ssn_014960.csv
  Task/Side Story/Kvaris/ssn_014961.csv
  Task/Side Story/Kvaris/ssn_014970.csv
  Task/Side Story/Kvaris/ssn_014971.csv
  Task/Side Story/Kvaris/ssn_014973.csv
  Task/Side Story/Kvaris/ssn_015030.csv
  Task/Weekly/cp0410010208.csv
  UI/common.csv
  UI/config.csv
  UI/date.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_scratch_reb.csv
  UI/ui_selectmenu_text.csv
  UI/ui_shop_reb.csv
  WIP/ssn_014951.csv
  WIP/ssn_014960.csv
  WIP/ssn_014961.csv
  WIP/ssn_014970.csv
  WIP/ssn_014971.csv
  WIP/ssn_014973.csv
  WIP/ssn_015030.csv
  WIP/ssn_015031.csv
  WIP/ssn_015033.csv
  WIP/ssn_015035.csv
  WIP/ssn_015037.csv
  should find category/ssn_014950.csv
Labels: size/XXL

#1879 KO_Reboot: Fix typo
  Message Pack/msp_0127.csv
  UI/ui_mainmode.csv
  WIP/ssn_014880.csv
Labels: size/M

#1880 more updates
  Translated/Dialog/Bruder/ssc_503010.csv
  Translated/Dialog/Crawford/ssc_503050.csv
  Translated/Dialog/Crawford/ssc_504010.csv
  Translated/Dialog/Crawford/ssc_504020.csv
  Translated/Dialog/Crawford/ssc_504030.csv
  Translated/Dialog/Waker Release/ssc_503010.csv
  Translated/Dialog/Waker Release/ssc_503050.csv
  Translated/Dialog/Waker Release/ssc_504010.csv
  Translated/Dialog/Waker Release/ssc_504020.csv
  Translated/Dialog/Waker Release/ssc_504030.csv
  Translated/Dialog/Waker Release/ssc_505010.csv
Labels: size/L

#1881 KO_Reboot: guess what is it
  UI/ui_mainmode.csv
  WIP/ssn_015140.csv
  WIP/ssn_015150.csv
  WIP/ssn_015160_001.csv
  WIP/ssn_015160_003.csv
  WIP/ssn_019080_001.csv
  WIP/ssn_019080_002.csv
Labels: size/L

#1882 linebreaks and a missed cutscene
  Translated/Dialog/Aina/ssc_501020.csv
  Translated/Dialog/Aina/ssc_501030.csv
  Translated/Dialog/Aina/ssc_501040.csv
  Translated/Dialog/Aina/ssc_501050.csv
  Translated/Dialog/Bruder/ssc_503020.csv
  Translated/Dialog/Bruder/ssc_503040.csv
  Translated/Dialog/Crawford/ssc_504010.csv
  Translated/Dialog/Crawford/ssc_504020.csv
  Translated/Dialog/Crawford/ssc_504030.csv
  Translated/Dialog/Manon/ssc_502010.csv
  Translated/Dialog/Manon/ssc_502020.csv
  Translated/Dialog/Manon/ssc_502030.csv
  Translated/Dialog/Manon/ssc_502040.csv
  Translated/Dialog/Manon/ssc_502050.csv
  Translated/Dialog/Meri/ssn_013000.csv
  Translated/Dialog/Meri/ssn_013001.csv
  Translated/Dialog/Meri/ssn_013002.csv
  Translated/Dialog/Meri/ssn_013004.csv
  Translated/Dialog/Ran/ssc_505010.csv
  Translated/Dialog/Taivas/ssn_013004.csv
  Translated/Dialog/Waker Release/ssc_505010.csv
Labels: size/XL

#1883 KO_Reboot: Update files
  Files/ui_playnavi.csv
  Files/ui_ranking_reb.csv
  Quest/ui_quest_counter_reb.csv
  Story/Aelio/msq_011360_010.csv
  Task/Limited/ls0060030309.csv
  Task/Limited/ls0060080203.csv
  Task/Limited/ls0060080204.csv
  Task/Limited/ls0060100105.csv
  Task/Limited/ls0060100206.csv
  Task/Limited/ls0064020102.csv
  Task/Limited/ls0064020103.csv
  Task/Limited/ls0064020104.csv
  Task/Limited/ls0064030104.csv
  Task/Limited/ls0064030105.csv
  Task/Limited/ls0064030106.csv
  Task/Side Story/Kvaris/ssn_014970.csv
  Task/Side Story/ss0030719901.csv
  Task/Side Story/ssn_014381.csv
  Tutorial/tut_006280.csv
  Tutorial/tut_006329.csv
  Tutorial/tut_006409.csv
  Tutorial/tut_006453.csv
  Tutorial/tut_006476.csv
  Tutorial/tut_006477.csv
  Tutorial/tut_006478.csv
  Tutorial/tut_006507.csv
  UI/common.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_playnavi.csv
  UI/ui_ranking_reb.csv
  UI/ui_shop_reb.csv
  UI/ui_tutorial_reb.csv
  WIP/ssn_015040.csv
  WIP/ssn_015041.csv
  WIP/ssn_015050.csv
  WIP/ssn_015051.csv
  WIP/ssn_015060.csv
  WIP/ssn_015061.csv
  WIP/ssn_015062.csv
  WIP/ssn_015062_001.csv
  WIP/ssn_015062_002.csv
  WIP/ssn_015063.csv
  WIP/ssn_015160_001.csv
Labels: size/XL

#1884 KO_Reboot: update files
  Files/gs0040106001.csv
  Files/gs0040107001.csv
  Files/gs0040108001.csv
  Files/gs0040108002.csv
  Files/gs0040108003.csv
  Files/gs0040109001.csv
  Misc/actor_name_npc.csv
  Task/Team/gs0040101001.csv
  Task/Team/gs0040101002.csv
  Task/Team/gs0040102001.csv
  Task/Team/gs0040103001.csv
  Task/Team/gs0040103002.csv
  Task/Team/gs0040103003.csv
  Task/Team/gs0040104001.csv
  Task/Team/gs0040104002.csv
  Task/Team/gs0040104003.csv
  Task/Team/gs0040104004.csv
  Task/Team/gs0040104005.csv
  Task/Team/gs0040104006.csv
  Task/Team/gs0040104007.csv
  Task/Team/gs0040104008.csv
  Task/Team/gs0040104009.csv
  Task/Team/gs0040104010.csv
  Task/Team/gs0040104011.csv
  Task/Team/gs0040104012.csv
  Task/Team/gs0040105001.csv
  Task/Team/gs0040105002.csv
  Task/Team/gs0040105003.csv
  Task/Team/gs0040106001.csv
  Task/Team/gs0040107001.csv
  Task/Team/gs0040108001.csv
  Task/Team/gs0040108002.csv
  Task/Team/gs0040108003.csv
  Task/Team/gs0040109001.csv
  UI/ui_ranking_reb.csv
  WIP/ssn_015160_001.csv
Labels: size/M

#1885 dialogue, tasks + upcoming quiz event?
  Files/np_npc_7403_001.csv
  Files/np_npc_7746_001.csv
  Files/qst_1900108000.csv
  Files/qst_1900108010.csv
  Files/qst_1900108020.csv
  Files/qst_1900108021.csv
  Files/qst_1900108022.csv
  Files/qst_1900108023.csv
  Files/qst_1900108024.csv
  Files/qst_1900108025.csv
  Files/ss0030701501.csv
  Files/ss0030740102.csv
  Files/ss0030740201.csv
  Files/ss0030740301.csv
  Files/ss0030740501.csv
  Files/ss0030740502.csv
  Files/ss0030774601.csv
  Files/ss0030774602.csv
  Files/ssn_015191.csv
  Files/ssq_015192.csv
  Translated/Dialog/Artie/np_npc_7746_001.csv
  Translated/Dialog/Rediah/np_npc_7403_001.csv
  Translated/Dialog/Rediah/ssn_015190.csv
  Translated/Dialog/Rediah/ssn_015191.csv
  Translated/Dialog/Rediah/ssq_015192.csv
  Translated/Quest/Quiz/qst_1900108020.csv
  Translated/Quests/Quiz/qst_1900108000.csv
  Translated/Quests/Quiz/qst_1900108010.csv
  Translated/Quests/Quiz/qst_1900108021.csv
  Translated/Quests/Quiz/qst_1900108022.csv
  Translated/Quests/Quiz/qst_1900108023.csv
  Translated/Quests/Quiz/qst_1900108024.csv
  Translated/Quests/Quiz/qst_1900108025.csv
  Translated/Tasks/Side/Artie/ss0030774601.csv
  Translated/Tasks/Side/Artie/ss0030774602.csv
  Translated/Tasks/Side/Meri/ss0030701501.csv
  Translated/Tasks/Side/Rediah/ss0030740301.csv
  Translated/Tasks/Side/Schraft/ss0030740501.csv
  Translated/Tasks/Side/Schraft/ss0030740502.csv
  Translated/Tasks/Side/Speeder/ss0030740102.csv
  Translated/Tasks/Side/Welmina/ss0030740201.csv
Labels: size/L

#1886 tutorials
  Dummy/ssq_014883.csv
  Dummy/ssq_014884.csv
  Dummy/ssq_014887.csv
  Files/np_npc_7404_001.csv
  Files/npc_740401.csv
  Files/tut_006523.csv
  Files/tut_006531.csv
  Files/tut_006532.csv
  Files/tut_006533.csv
  Translated/Dialog/Vulgans/np_npc_7404_001.csv
  Translated/Dialog/Vulgans/npc_740401.csv
  Translated/Tutorials/tut_006523.csv
  Translated/Tutorials/tut_006531.csv
  Translated/Tutorials/tut_006532.csv
  Translated/Tutorials/tut_006533.csv
Labels: size/M

#1890 Upcoming Xitrae dialogue
  Files/ssn_019090_001.csv
  Files/ssn_019090_002.csv
  Files/ssn_019090_003.csv
  Files/ssn_019090_004.csv
  Files/ssn_019090_005.csv
  Files/ssq_019090_006.csv
  Files/ssq_019090_007.csv
  Files/ssq_019090_008.csv
  Files/ssq_019090_009.csv
  Files/ssq_019090_010.csv
  Translated/Dialog/Xitrae/ssn_019090_001.csv
  Translated/Dialog/Xitrae/ssn_019090_002.csv
  Translated/Dialog/Xitrae/ssn_019090_003.csv
  Translated/Dialog/Xitrae/ssn_019090_004.csv
  Translated/Dialog/Xitrae/ssn_019090_005.csv
  Translated/Dialog/Xitrae/ssq_019090_006.csv
  Translated/Dialog/Xitrae/ssq_019090_007.csv
  Translated/Dialog/Xitrae/ssq_019090_008.csv
  Translated/Dialog/Xitrae/ssq_019090_009.csv
  Translated/Dialog/Xitrae/ssq_019090_010.csv
  Translated/Quests/Quiz/qst_1900108020.csv
Labels: size/L

#1894 KO_Reboot: Update files
  UI/ui_achievements.csv
  UI/ui_item.csv
  UI/ui_shop_reb.csv
  UI/ui_tutorial_reb.csv
Labels: size/L
