Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-03, with the labels that each got.

#1764 Ru Reboot: Concert test not finished yet
  Files/lvs_070010.csv
  Reboot/Concerts/lvs_070010.csv
  Reboot/Concerts/lvs_070020.csv
Labels: size/M

#1765 KO_Reboot: Update concert
  Files/lvs_070010.csv
  Files/lvs_070020.csv
  Live Lyrics/lvs_070010.csv
  Live Lyrics/lvs_070020.csv
  Message Pack/msp_0020.csv
Labels: size/L

#1766 Ru reboot: fast translate
  Files/np_npc_7224_001.csv
  Files/quest_01120070.csv
  Files/quest_01160000.csv
  Files/quest_01180000.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssn_019060_001.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssn_019060_002.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_002.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_003.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_004.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_005.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_006.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_007.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_008.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_009.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_010.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_011.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_012.csv
  Reboot/Dialog/Aelio/Xitre/Spring/ssq_019060_013.csv
  Reboot/Dialog/Aelio/Xitre/np_npc_7224_001.csv
  Reboot/Quests/Emergency Quests/Aelio/Dark Falz/quest_01160000.csv
  Reboot/Quests/Emergency Quests/Aelio/Dark Falz/trial_god2.csv
  Reboot/Quests/Emergency Quests/Seasonal/Spring 2022/quest_01120070.csv
  Reboot/Quests/Emergency Quests/Seasonal/Spring 2022/quest_01180000.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012010.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012020.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012030.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012035.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012070.csv
  Reboot/Story/Ch2/15b Dark Falz/ssc_012080.csv
  Reboot/UI/actor_name.csv
  Reboot/UI/actor_name_npc.csv
  Reboot/UI/region_mag_common.csv
  Reboot/UI/ui_mainmode.csv
  Reboot/UI/ui_quest_reb.csv
Labels: size/L

#1768 KO_Reboot: Fix typo
  Live Lyrics/lvs_070010.csv
Labels: size/XS

#1769 KO_Reboot: fix typo
  Live Lyrics/lvs_070010.csv
  Task/Limited/ls0061070106.csv
Labels: size/XS

#1773 KO_Reboot: Update files
  Live Lyrics/lvs_070020.csv
  Misc/actor_name.csv
  Misc/apc_chat_1.csv
  UI/ui_mainmode.csv
Labels: size/XL

#1774 KO_Reboot: Fix typo
  E-Trial/trial_dropship.csv
  Live Lyrics/lvs_070010.csv
  Live Lyrics/lvs_070020.csv
Labels: size/M
