Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2022-11, with the labels that each got.

#1926 KO_Reboot: 우애옹
  Task/Side Story/Kvaris/ssq_014650.csv
  WIP/gpro/cp0410010306.csv
  WIP/gpro/cp0410010309.csv
  WIP/gpro/cp0410010316.csv
  WIP/gpro/cp0410010319.csv
  WIP/gpro/cp0410010326.csv
  WIP/gpro/cp0410010329.csv
  WIP/gpro/msn_005002.csv
  WIP/gpro/npc_773301.csv
  WIP/gpro/npc_773801.csv
  WIP/gpro/qst_1200049000.csv
  WIP/gpro/quest_01180040.csv
  WIP/gpro/ssn_015190_002.csv
  WIP/gpro/ssn_019100_001.csv
  WIP/gpro/ssn_019100_002.csv
  WIP/gpro/ssq_005142.csv
  WIP/gpro/ssq_005152.csv
  WIP/gpro/ssq_005162.csv
  WIP/gpro/ssq_015190_003.csv
  WIP/gpro/ssq_015221.csv
  WIP/gpro/ssq_015250.csv
  WIP/gpro/trial_apc_7001004.csv
  WIP/gpro/trial_apc_7002012.csv
  WIP/gpro/trial_apc_7005001.csv
  WIP/gpro/trial_apc_7010001.csv
  WIP/gpro/trial_apc_7014001.csv
  WIP/gpro/tut_006536.csv
  WIP/gpro/tut_006539.csv
  WIP/gpro/tut_006541.csv
Labels: size/L

#1927 Update ssn_019100_002.csv
  Translated/Dialog/Xiemmy/2022-11-02 Autumn 22/ssn_019100_002.csv
Labels: size/XS

#1928 KO_Reboot: Fix typo
  WIP/gpro/quest_01201005.csv
  WIP/gpro/ssc_501060.csv
  WIP/gpro/ssc_501070.csv
  WIP/gpro/ssc_501080.csv
  WIP/gpro/ssc_501090.csv
  WIP/gpro/ssc_502060.csv
  WIP/gpro/ssc_504040.csv
  WIP/gpro/ssc_505020.csv
  WIP/gpro/ssc_507010.csv
  WIP/gpro/ssc_507030.csv
  WIP/gpro/ssc_508010.csv
  WIP/gpro/ssc_508020.csv
  WIP/gpro/ssc_509010.csv
  WIP/gpro/ssc_509020.csv
  WIP/gpro/ssn_019100_001.csv
  WIP/gpro/ssn_019100_002.csv
  WIP/gpro/tut_006537.csv
Labels: size/M

#1929 KO_Reboot: bruh
  WIP/gpro/npc_773901.csv
Labels: size/XS

#1930 Update common.csv
  Translated/UI/common.csv
Labels: size/M
