Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-08, with the labels that each got.

#2122 KO_Reboot: Update files
  Files/qst_1180330012.csv
  Files/qst_1180330013.csv
  Files/qst_1180330014.csv
  Files/qst_1180330015.csv
  Files/qst_1180330016.csv
  Task/Side Story/ssn_011120.csv
  UI/ui_item.csv
  WIP/gpro/msc_020220.csv
  WIP/gpro/msc_020225.csv
  WIP/halgeo jonna manne/qst_1180320000.csv
  WIP/halgeo jonna manne/qst_1180320020.csv
  WIP/qst_1180330011.csv
  WIP/qst_1180330012.csv
  WIP/qst_1180330013.csv
  WIP/qst_1180330014.csv
  WIP/qst_1180330015.csv
  WIP/qst_1180330016.csv
Labels: size/L

#2124 KO_Reboot: Update files
  E-Trial/trial_common.csv
  E-Trial/trial_continuous_battle.csv
  E-Trial/trial_fixed_format_raidboss.csv
  E-Trial/trial_growup_final.csv
  E-Trial/trial_lightning.csv
  E-Trial/trial_machine_discover.csv
  Files/trial_continuous_battle.csv
  Files/trial_fixed_format_raidboss.csv
  Files/trial_growup_final.csv
  Files/trial_lightning.csv
  Misc/actor_name.csv
  Misc/object_common.csv
  Misc/open_field.csv
  Quest/quest_common_reboot.csv
  UI/common.csv
  UI/config.csv
  UI/date.csv
  UI/myspace_text.csv
  UI/object_individual.csv
  UI/ui_item.csv
Labels: size/XXL

#2126 first bunch of stuff
  Files/msc_022010.csv
  Files/msc_022020.csv
  Files/msn_022011.csv
  Files/ssn_015900.csv
  Files/ssq_016050.csv
  Translated/Dialog/Arche/ssq_016050.csv
  Translated/Dialog/Ran/ssn_015900.csv
  Translated/Story/34 Manon's Return/msc_022010.csv
  Translated/Story/34 Manon's Return/msn_022011.csv
  Translated/Story/35 Manon's Guilt/msc_022020.csv
Labels: size/L

#2127 side story cutscenes
  Files/ssc_501130.csv
  Files/ssc_503090.csv
  Files/ssc_504050.csv
  Files/ssc_504060.csv
  Files/ssc_506050.csv
  Files/ssc_508060.csv
  Translated/Story/Side Bruder/ssc_503090.csv
  Translated/Story/Side Crawford/ssc_501130.csv
  Translated/Story/Side Crawford/ssc_504050.csv
  Translated/Story/Side Crawford/ssc_504060.csv
  Translated/Story/Side Ilma/ssc_508060.csv
  Translated/Story/Side Nadereh/ssc_506050.csv
Labels: size/L

#2125 KO_Reboot: Update files
  Files/ed0610002150.csv
  Files/quest_01330000.csv
  Files/tut_006626.csv
  Files/tut_006639.csv
  Files/tut_006640.csv
  Files/tut_006646.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  UI/myspace_text.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_moralskeeper.csv
  UI/ui_ranking_reb.csv
  UI/ui_rebops.csv
  UI/ui_tutorial_reb.csv
  WIP/230802/ed0610002150.csv
  WIP/230802/quest_01330000.csv
  WIP/230802/tut_006626.csv
  WIP/230802/tut_006639.csv
  WIP/230802/tut_006640.csv
  WIP/230802/tut_006646.csv
Labels: size/L

#2129 Corrections/Improvements
  Translated/Dialog/Arche/ssq_016050.csv
  Translated/UI/quest_common_reboot.csv
Labels: size/L

#2130 No gold or rainbow. Just tree.
  Translated/Story/Side Aina/ssc_501130.csv
  Translated/Story/Side Nadereh/ssc_506050.csv
  Translated/Tasks/Limited/2023-08-02 Leciel & T Space/ls0060151406.csv
Labels: size/XS

#2133 upcoming limited quests + dialogue
  Files/qst_1340020000.csv
  Files/qst_1340020010.csv
  Files/qst_1340020020.csv
  Files/qst_1340020030.csv
  Files/qst_1340050000.csv
  Files/qst_1340050010.csv
  Files/qst_1340050020.csv
  Files/qst_1340050030.csv
  Files/qst_1340050040.csv
  Files/qst_1340050050.csv
  Files/qst_1340050060.csv
  Files/qst_1340050070.csv
  Files/quest_01180340.csv
  Files/quest_01340010.csv
  Files/quest_01340020.csv
  Files/quest_01340050.csv
  Files/quest_01340070.csv
  Files/quest_01340080.csv
  Translated/Quests/Limited Quests/Autumn 2023/quest_01340010.csv
  Translated/Quests/Limited Quests/Autumn 2023/quest_01340070.csv
  Translated/Quests/Limited Quests/Autumn 2023/quest_01340080.csv
  Translated/Quests/Limited Quests/Interception at the Ruins/qst_1340020000.csv
  Translated/Quests/Limited Quests/Interception at the Ruins/qst_1340020010.csv
  Translated/Quests/Limited Quests/Interception at the Ruins/qst_1340020020.csv
  Translated/Quests/Limited Quests/Interception at the Ruins/qst_1340020030.csv
  Translated/Quests/Limited Quests/Interception at the Ruins/quest_01340020.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050000.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050010.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050020.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050030.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050040.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050050.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050060.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1340050070.csv
  Translated/Quests/Limited Quests/Truck Breakdown/quest_01340050.csv
  Translated/Quests/Limited Quests/Unknown Area/quest_01180340.csv
Labels: size/L

#2135 KO_Reboot: Update files
  WIP/test/msc_022010.csv
  WIP/test/msc_022020.csv
  WIP/test/qst_1120170000.csv
  WIP/test/qst_1120170010.csv
  WIP/test/qst_1120170020.csv
  WIP/test/qst_1120170030.csv
  WIP/test/qst_1120170040.csv
  WIP/test/qst_1120170050.csv
  WIP/test/qst_1120170060.csv
  WIP/test/qst_1120170070.csv
  WIP/test/qst_1340020000.csv
  WIP/test/qst_1340020010.csv
  WIP/test/quest_01180360.csv
  WIP/test/quest_01180380.csv
  WIP/test/quest_01200001.csv
  WIP/test/quest_01200002.csv
  WIP/test/quest_01200003.csv
  WIP/test/quest_01200004.csv
  WIP/test/quest_01200005.csv
  WIP/test/quest_01200006.csv
  WIP/test/quest_01200007.csv
  WIP/test/quest_01200615.csv
  WIP/test/quest_01200835.csv
  WIP/test/quest_01200836.csv
  WIP/test/quest_01200837.csv
  WIP/test/quest_01200905.csv
  WIP/test/quest_01201010.csv
  WIP/test/quest_01202006.csv
  WIP/test/quest_01202007.csv
  WIP/test/quest_01202090.csv
  WIP/test/quest_01340010.csv
  WIP/test/quest_01340050.csv
  WIP/test/quest_01340070.csv
  WIP/test/ssc_020010.csv
  WIP/test/ssc_501130.csv
  WIP/test/ssc_503090.csv
  WIP/test/ssc_504050.csv
  WIP/test/ssc_506050.csv
  WIP/test/ssc_508060.csv
  WIP/test/ssn_015900.csv
  WIP/test/ssn_019170_002.csv
  WIP/test/tut_006630.csv
  WIP/test/tut_006631.csv
  WIP/test/tut_006632.csv
Labels: size/L
