Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-12, with the labels that each got.

#2155 KO_Reboot: System text update
  Misc/object_common.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  UI/myspace_text.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_scratch_reb.csv
  UI/ui_shop_reb.csv
  UI/ui_tips_reb.csv
  UI/ui_tutorial_reb.csv
Labels: size/XL

#2156 New story dialogue
  Files/msc_022090.csv
  Files/msc_022120.csv
  Files/msc_022160.csv
  Files/msc_022170.csv
  Files/msc_022190.csv
  Files/msc_023060.csv
  Files/msc_023070.csv
  Files/msc_023080.csv
  Files/msn_022080.csv
  Files/msn_022091.csv
  Files/msn_022092.csv
  Files/msn_022093.csv
  Files/msn_022094.csv
  Files/msn_022096.csv
  Files/msn_022097.csv
  Files/msn_022098.csv
  Files/msn_022110.csv
  Files/msn_022112.csv
  Files/msn_022131.csv
  Files/msn_022132.csv
  Files/msn_022150.csv
  Files/msn_022180.csv
  Files/msn_023061.csv
  Files/msn_023062.csv
  Files/msn_023071.csv
  Files/msn_023072.csv
  Files/msq_023071.csv
  Files/msq_023072.csv
  Translated/Story/41 Aina's Worries/msc_022090.csv
  Translated/Story/41 Aina's Worries/msn_022080.csv
  Translated/Story/41 Aina's Worries/msn_023061.csv
  Translated/Story/41 Aina's Worries/msn_023062.csv
  Translated/Story/41 Aina's Worries/msn_023071.csv
  Translated/Story/41 Aina's Worries/msn_023072.csv
  Translated/Story/41 Aina's Worries/msq_023072.csv
  Translated/Story/42 Liminal Sign/msn_022091.csv
  Translated/Story/42 Liminal Sign/msn_022092.csv
  Translated/Story/42 Liminal Sign/msn_022093.csv
  Translated/Story/42 Liminal Sign/msn_022094.csv
  Translated/Story/42 Liminal Sign/msn_022096.csv
  Translated/Story/42 Liminal Sign/msn_022097.csv
  Translated/Story/42 Liminal Sign/msn_022098.csv
  Translated/Story/43 Liminal Sign Found!/msc_022120.csv
  Translated/Story/43 Liminal Sign Found!/msn_022110.csv
  Translated/Story/43 Liminal Sign Found!/msn_022112.csv
  Translated/Story/44 Large-scale Search Effort/msn_022131.csv
  Translated/Story/44 Large-scale Search Effort/msn_022132.csv
  Translated/Story/44 Large-scale Search Effort/msn_022150.csv
  Translated/Story/45 Manon's Feelings/msc_022160.csv
  Translated/Story/45 Manon's Feelings/msc_022170.csv
  Translated/Story/46 Manon's Request/msc_022190.csv
  Translated/Story/46 Manon's Request/msn_022180.csv
  Translated/Story/47 Growing As An Instructor/msc_023060.csv
  Translated/Story/47 Growing As An Instructor/msc_023070.csv
  Translated/Story/47 Growing As An Instructor/msc_023080.csv
  Translated/Story/47 Growing As An Instructor/msq_023071.csv
Labels: size/XL

#2157 En reboot
  Translated/Story/43 Liminal Sign Found/msc_022120.csv
  Translated/Story/43 Liminal Sign Found/msn_022110.csv
  Translated/Story/43 Liminal Sign Found/msn_022112.csv
  Translated/Story/47 Growing As An Instructor/msc_023080.csv
Labels: size/XS

#2160 KO: Update files
  Story/Episode 1/Chapter 9/co_0121101.csv
  Story/Episode 1/Chapter 9/co_0121102.csv
  Story/Episode 1/Chapter 9/co_0121106.csv
  Story/Episode 1/Chapter 9/co_0121107.csv
  Story/Episode 1/Chapter 9/co_0121109.csv
  Story/Episode 1/Chapter 9/co_0121110.csv
  Story/Episode 1/Chapter 9/co_0121111.csv
  Story/Episode 1/Chapter 9/co_0121114.csv
  Story/Episode 1/Chapter 9/co_022501.csv
  Story/Episode 1/Chapter 9/co_022502.csv
  Story/Episode 1/Chapter 9/co_022507.csv
  Story/Episode 1/Chapter 9/co_022513.csv
  Story/Episode 1/Chapter 9/co_022514.csv
  Story/Episode 1/Chapter 9/ra_012020_om.csv
  Story/Episode 1/Chapter 9/st_013000_om.csv
  Story/Episode 1/Chapter 9/st_013010.csv
  Story/Episode 1/Chapter 9/st_013400.csv
  Story/Episode 1/Chapter 9/st_013420.csv
  Story/Episode 1/Chapter 9/st_013430.csv
  Story/Episode 1/Chapter 9/st_013440_om.csv
  Story/Episode 1/Chapter 9/st_020248_om.csv
  Story/Episode 1/Chapter 9/un_012620.csv
  Story/Episode 1/Chapter 9/un_012630.csv
  Story/Episode 1/Chapter 9/un_013000.csv
  Story/Episode 1/Chapter 9/un_020660.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/item_series_name.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_title_text.csv
Labels: size/XL

#2163 KO_Reboot: fix typo
  UI/date.csv
  UI/ui_item.csv
  WIP/20231206/tut_006654.csv
  WIP/20231206/tut_006655.csv
  WIP/20231206/tut_006656.csv
  WIP/20231206/tut_006657.csv
  WIP/20231206/tut_006659.csv
Labels: size/S

#2164 Update ui_charamake_parts.csv
  UI/ui_charamake_parts.csv
Labels: size/L

#2162 Corrections
  Translated/Story/41 Aina's Worries/msc_023070.csv
  Translated/Story/43 News About Manon/msc_022090.csv
  Translated/UI/quest_common_reboot.csv
Labels: size/S

#2165 KO_Reboot: Update quest_01330000.csv
  Quest/Leciel/quest_01330000.csv
Labels: size/S

#2166 dialogue for christmas 2023, new years 2024, and one other season event?
  Files/ssn_019190_001.csv
  Files/ssn_019190_002.csv
  Files/ssn_019200_001.csv
  Files/ssn_019200_002.csv
  Files/ssn_019210_001.csv
  Files/ssn_019210_002.csv
  Files/ssq_019190_002.csv
  Files/ssq_019190_003.csv
  Files/ssq_019200_002.csv
  Files/ssq_019200_003.csv
  Files/ssq_019210_002.csv
  Files/ssq_019210_003.csv
  Translated/Dialog/Xiandy/ssn_019200_001.csv
  Translated/Dialog/Xiandy/ssn_019200_002.csv
  Translated/Dialog/Xiandy/ssq_019200_002.csv
  Translated/Dialog/Xiandy/ssq_019200_003.csv
  Translated/Dialog/Xiemmy/ssn_019210_001.csv
  Translated/Dialog/Xiemmy/ssn_019210_002.csv
  Translated/Dialog/Xiemmy/ssq_019210_002.csv
  Translated/Dialog/Xiemmy/ssq_019210_003.csv
  Translated/Dialog/Xitrae/Christmas 2023/ssn_019190_001.csv
  Translated/Dialog/Xitrae/Christmas 2023/ssn_019190_002.csv
  Translated/Dialog/Xitrae/Christmas 2023/ssq_019190_002.csv
  Translated/Dialog/Xitrae/Christmas 2023/ssq_019190_003.csv
Labels: size/L

#2167 not santa dialogue
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100000.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100010.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100020.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100030.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100040.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100050.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100060.csv
  Translated/Quests/Limited Quests/Xmas 2023/qst_1340100070.csv
Labels: size/S

#2168 KO_Reboot: update files
  Files/quest_01340100.csv
  WIP/20231206/quest_01340100.csv
  WIP/20231206/ssn_019200_002.csv
  WIP/gpro/quest_01120170.csv
Labels: size/S
