Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-05, with the labels that each got.

#2073 KO_Reboot: Update files
  Quest/quest_common_reboot.csv
  WIP/gpro/ssn_019150_002.csv
Labels: size/XS

#2074 ui stuff
  Translated/UI/ui_mainmode.csv
Labels: size/S

#2075 KO_Reboot: Update files
  Story/Aelio/msq_011260_001.csv
  Story/Retem/msn_012243_001.csv
  Story/Retem/msn_012243_002.csv
  Story/Retem/msq_012241_001.csv
  Task/Limited/ls0060030310.csv
  Task/Limited/ls0060080205.csv
  Task/Limited/ls0060100207.csv
  Task/Side Story/Kvaris/ssn_014810.csv
  Task/Side Story/Kvaris/ssn_014811.csv
  Task/Side Story/Kvaris/ssn_014812.csv
  Task/Side Story/Kvaris/ssn_014813.csv
  Task/Side Story/ss0030765701.csv
  Task/Side Story/ss0030765751.csv
  Task/Side Story/ssn_012030.csv
  Task/Side Story/ssn_012031.csv
  Task/Side Story/ssq_012040.csv
  Task/Team/gs0040104001.csv
  Task/Team/gs0040104002.csv
  Task/Team/gs0040104003.csv
  Task/Team/gs0040104004.csv
  Task/Team/gs0040104005.csv
  Task/Team/gs0040104006.csv
  Task/Team/gs0040104007.csv
  Task/Team/gs0040104008.csv
  Task/Team/gs0040104009.csv
  Task/Team/gs0040104010.csv
  Task/Team/gs0040104011.csv
  Task/Team/gs0040104012.csv
  Task/Team/gs0040104013.csv
  Task/Team/gs0040104014.csv
  Task/Team/gs0040104015.csv
  Task/Team/gs0040104016.csv
  Tutorial/tut_006280.csv
  Tutorial/tut_006294.csv
  Tutorial/tut_006316.csv
  Tutorial/tut_006326.csv
  Tutorial/tut_006408.csv
  Tutorial/tut_006409.csv
  Tutorial/tut_006476.csv
  Tutorial/tut_006477.csv
  Tutorial/tut_006478.csv
  Tutorial/tut_006484.csv
  Tutorial/tut_006498.csv
  Tutorial/tut_006514.csv
  Tutorial/tut_006515.csv
  UI/ui_item.csv
  UI/ui_item_reb.csv
  UI/ui_mainmode.csv
  UI/ui_shop_reb.csv
  UI/ui_tutorial_reb.csv
Labels: size/L

#2076 Last bit of Limited Tasks
  Files/ls0060030401.csv
  Files/ls0060030402.csv
  Files/ls0060030403.csv
  Files/ls0060030404.csv
  Files/ls0060030405.csv
  Files/ls0060030406.csv
  Files/ls0060030407.csv
  Files/ls0060030408.csv
  Files/ls0060030409.csv
  Files/ls0060030410.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030401.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030402.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030403.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030404.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030405.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030406.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030407.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030408.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030409.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030410.csv
Labels: size/M

#2077 quest -> task
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030401.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030402.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030403.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030404.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030405.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030406.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030407.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030408.csv
  Translated/Tasks/Limited/2023-04-19 2nd Anniversary/ls0060030409.csv
Labels: size/S

#2078 KO_Reboot: Update files
  NPC Dialogue/np_npc_7195_001.csv
  NPC Dialogue/np_npc_7655_001.csv
  NPC Dialogue/np_npc_7656_001.csv
  NPC Dialogue/np_npc_7657_001.csv
  NPC Dialogue/npc_740401.csv
  Story/Side/ssc_503060.csv
  Task/Main/qt1200000000.csv
  Task/Side Story/ss0030719901.csv
  Tutorial/tut_006347.csv
  UI/common.csv
  UI/ui_item.csv
  WIP/gpro/msc_020310.csv
  WIP/gpro/quest_01180300.csv
  filelist.txt
Labels: size/M

#2079 KO: Update files
  Story/Episode 1/Chapter 8/quest_00701130.csv
  Story/Episode 1/Chapter 9/un_013040.csv
  Story/Episode 1/Chapter 9/un_013180.csv
  Story/Episode 1/Chapter 9/un_013210.csv
  UI/ui_charamake_text.csv
Labels: size/M

#2085 KO_Reboot: fix typo
  Task/Side Story/ssc_501070.csv
  Task/Side Story/ssc_502060.csv
  Task/Side Story/ssc_507010.csv
Labels: size/XS

#2088 KO: Fix typo
  Quests/Ultimate Quests/Masquerade/co_058010.csv
  UI/ui_guild.csv
Labels: size/XS

#2087 KO_Reboot: Update files
  Task/Side Story/Stia/ss0030744102.csv
  Task/Side Story/Stia/ssn_015480.csv
  Task/Side Story/Stia/ssn_015483.csv
  Task/Side Story/ssc_502060.csv
Labels: size/S
