Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-06, with the labels that each got.

#2082 Correct Extension Storage 6 icon
  UI/ui_item.csv
Labels: size/XS

#2086 Concert Lyrics & LQ Name Updates
  Translated/Lobby/Concert/lvs_070010.csv
  Translated/Lobby/Concert/lvs_070020.csv
  Translated/Quests/Limited Quests/Spring 2023/quest_01180280.csv
  Translated/Tasks/Daily/2023-04-19 2nd Anniversary/ed0611161105.csv
Labels: size/M

#2089 Ko: fix typo
  Arks Mission/Main/ac06040504.csv
  UI/ui_charamake_text_reb.csv
Labels: size/S

#2090 KO: Update files
  UI/common.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/item_series_name.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_item.csv
  UI/ui_title_text.csv
Labels: size/L

#2095 KO_Reboot: Update files
  Misc/object_common.csv
  UI/myspace_text.csv
  UI/ui_mainmode.csv
  WIP/230607/quest_01202002.csv
  WIP/230607/quest_01202003.csv
  WIP/230607/quest_01202004.csv
  WIP/230607/quest_01202005.csv
  WIP/230607/quest_01340000.csv
  WIP/230607/ss0030725801.csv
  WIP/230607/ss0030725802.csv
  WIP/230607/ss0030725803.csv
  WIP/230607/ss0030725804.csv
  WIP/230607/ss0030740308.csv
  WIP/230607/ss0030740309.csv
  WIP/230607/ss0030740505.csv
  WIP/230607/ss0030740506.csv
  WIP/230607/ssc_501120.csv
  WIP/230607/ssc_503080.csv
  WIP/230607/ssc_508040.csv
  WIP/230607/ssc_508050.csv
Labels: size/L

#2096 KO_Reboot: Update files
  Story/Aelio/ssc_501040.csv
  UI/common.csv
  UI/myspace_text.csv
  UI/ui_equip.csv
  UI/ui_item.csv
  UI/ui_moralskeeper.csv
  UI/ui_rebops.csv
  UI/ui_scratch_reb.csv
  UI/ui_selectmenu_text.csv
  UI/ui_shop_reb.csv
  WIP/230607/msc_021020.csv
  WIP/230607/msc_021030.csv
  WIP/230607/msc_021090.csv
  WIP/230607/msc_021100.csv
  WIP/230607/msn_021050.csv
  WIP/230607/ssc_501120.csv
  WIP/230607/ssc_508050.csv
Labels: size/L

#2097 new skill descriptions
  Translated/UI/ui_mainmode.csv
Labels: size/M

#2098 Corrections
  Translated/Dialog/Arche/msn_016000_001.csv
  Translated/Dialog/Arche/ssq_016025.csv
  Translated/Story/34 Fabricated World/msc_021030.csv
  Translated/Tutorials/tut_006588.csv
  Translated/Tutorials/tut_006593.csv
  Translated/Tutorials/tut_006628.csv
  Translated/UI/config.csv
  Translated/UI/ui_mainmode.csv
Labels: size/S

#2099 renaming folder for consistency with mainmode
  Translated/Story/36 The New Enemy/msc_021070.csv
  Translated/Story/36 The New Enemy/msc_021090.csv
  Translated/Story/36 The New Enemy/msc_021100.csv
  Translated/Story/36 The New Enemy/msn_021050.csv
  Translated/Story/36 The New Enemy/msn_021101.csv
  Translated/Story/36 The New Enemy/msq_021042.csv
  Translated/Story/36 The New Enemy/msq_021061.csv
  Translated/Story/36 The New Enemy/msq_021063.csv
  Translated/Story/36 The New Enemy/msq_021081.csv
  Translated/Story/36 The New Enemy/msq_021085.csv
  Translated/Story/36 The New Enemy/msq_021088.csv
Labels: size/XS

#2101 line breaks
  Translated/Lobby/Concert/lvs_070020.csv
Labels: size/XS

#2100 Paibt > Paint
  Translated/UI/ui_item.csv
Labels: size/XS

#2103 KO_Reboot: Fix typo
  UI/common.csv
  WIP/230607/ss0030725802.csv
  WIP/230607/ssn_015190_019.csv
Labels: size/S

#2104 KO_Reboot: Part 2
  E-Trial/trial_apc_7005001.csv
  Misc/actor_name_npc.csv
  Misc/object_common.csv
  Task/Side Story/ss0030766401.csv
  Task/Side Story/ss0030766402.csv
  Task/Side Story/ss0030766403.csv
  Task/Side Story/ssn_011160.csv
  Task/Side Story/ssn_011161.csv
  Task/Side Story/ssn_011165.csv
  Task/Side Story/ssn_011171.csv
  Task/Side Story/ssq_011163.csv
  Task/Side Story/ssq_011164.csv
  Task/Side Story/ssq_011166.csv
  Task/Side Story/ssq_011173.csv
  UI/config.csv
  UI/date.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_rebops.csv
  WIP/230607/cp0410010501.csv
  WIP/230607/cp0410010502.csv
  WIP/230607/cp0410010503.csv
  WIP/230607/cp0410010504.csv
  WIP/230607/cp0410010505.csv
  WIP/230607/ew0621171101.csv
  WIP/230607/ss0030740505.csv
  WIP/230607/ss0030740506.csv
  WIP/230607/ssn_015190_017.csv
  WIP/230607/ssn_015190_019.csv
  WIP/230607/ssn_015200_002.csv
  WIP/230607/ssn_015200_004.csv
  WIP/230607/ssn_016010.csv
  WIP/230607/ssn_016011.csv
  WIP/230607/ssn_016033.csv
  WIP/230607/tut_006602.csv
  WIP/230607/tut_006613.csv
  WIP/230607/tut_006614.csv
  WIP/230607/tut_006616.csv
  WIP/230607/tut_006617.csv
  WIP/230607/tut_006618.csv
  WIP/230607/tut_006619.csv
  WIP/230607/tut_006620.csv
  WIP/230607/tut_006621.csv
  WIP/230607/tut_006623.csv
  WIP/230607/tut_006625.csv
  WIP/230607/tut_006628.csv
  WIP/230607/tut_006629.csv
  should find category/0010100091.csv
Labels: size/L

#2107 KO_Reboot: Update files
  UI/ui_tutorial_reb.csv
  WIP/230607/ssn_016014.csv
  WIP/230607/ssn_016021.csv
  WIP/230607/ssn_016026.csv
  WIP/230607/ssn_016031.csv
  WIP/230607/ssn_016041.csv
  WIP/230607/ssn_019160_002.csv
  WIP/230607/ssq_015190_018.csv
  WIP/230607/ssq_015190_020.csv
  WIP/230607/ssq_016013.csv
  WIP/230607/ssq_016024.csv
  WIP/230607/ssq_016027.csv
  WIP/230607/ssq_016034.csv
  WIP/230607/ssq_016043.csv
  WIP/230607/tut_006584.csv
  WIP/230607/tut_006589.csv
  WIP/230607/tut_006598.csv
Labels: size/M

#2108 Update ui_charamake_parts.csv
  UI/ui_charamake_parts.csv
Labels: size/L

#2105 Boo-urns
  Translated/Tasks/Limited/2023-06-21 Sonic/ls0064133102.csv
  Translated/UI/myspace_text.csv
  Translated/UI/ui_mainmode.csv
Labels: size/S

#2102 capitalization
  Translated/Lobby/Concert/lvs_070020.csv
Labels: size/XS

#2111 KO_Reboot: Update files
  Quest/Ordinal Tower/quest_01190000.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_tutorial_reb.csv
  WIP/230607/msn_021010.csv
  WIP/230607/ssn_016041.csv
  WIP/230607/ssn_019160_001.csv
  WIP/230607/ssn_019160_002.csv
  WIP/230607/ssq_015190_018.csv
  WIP/230607/ssq_015200_005.csv
  WIP/230607/ssq_015251.csv
  WIP/230607/ssq_016012.csv
  WIP/230607/ssq_016013.csv
  WIP/230607/ssq_016015.csv
  WIP/230607/ssq_016022.csv
  WIP/230607/ssq_016024.csv
  WIP/230607/ssq_016025.csv
  WIP/230607/ssq_016032.csv
  WIP/230607/ssq_016034.csv
  WIP/230607/ssq_016035.csv
  WIP/230607/ssq_016043.csv
  WIP/230607/ssq_019160_003.csv
  WIP/230607/tut_006583.csv
  WIP/230607/tut_006584.csv
  WIP/230607/tut_006585.csv
  WIP/230607/tut_006586.csv
  WIP/230607/tut_006587.csv
  WIP/230607/tut_006588.csv
  WIP/230607/tut_006589.csv
  WIP/230607/tut_006590.csv
  WIP/230607/tut_006591.csv
  WIP/230607/tut_006592.csv
  WIP/230607/tut_006593.csv
  WIP/230607/tut_006594.csv
  WIP/230607/tut_006595.csv
  WIP/230607/tut_006596.csv
  WIP/230607/tut_006597.csv
  WIP/230607/tut_006598.csv
  WIP/230607/tut_006599.csv
  WIP/230607/tut_006600.csv
  WIP/230607/tut_006601.csv
  WIP/230607/tut_006610.csv
  WIP/230607/tut_006611.csv
  WIP/230607/tut_006619.csv
  WIP/gpro/quest_01320040.csv
Labels: size/L

#2112 KO_Reboot: Fix typo
  Tutorial/tut_006261.csv
  Tutorial/tut_006301.csv
  Tutorial/tut_006519.csv
  UI/config.csv
  UI/ui_directbuy_text.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_rebops.csv
  WIP/230607/ssn_015190_017.csv
  WIP/230607/ssn_016041.csv
  WIP/230607/ssq_015190_018.csv
  WIP/230607/ssq_016012.csv
  WIP/230607/ssq_016013.csv
  WIP/230607/tut_006611.csv
Labels: size/M

#2113 Update ui_accessories_text.csv
  UI/ui_accessories_text.csv
  UI/ui_charamake_text_reb.csv
Labels: size/L
