Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-04, with the labels that each got.

#2044 Ko: update files
  Files/co_012701.csv
  Story/Episode 1/Chapter 7/co_012701.csv
  Story/Episode 1/Chapter 7/co_012702.csv
  Story/Episode 1/Chapter 7/co_012709.csv
  Story/Episode 1/Chapter 7/ra_010160.csv
  Story/Episode 1/Chapter 7/st_010646.csv
  Story/Episode 1/Chapter 7/st_010648.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_item.csv
Labels: size/L

#2046 KO_Reboot: Update files
  Files/np_npc_7258_001.csv
  Files/np_npc_7406_001.csv
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Misc/object_common.csv
  Misc/open_field.csv
  NPC Dialogue/np_npc_7258_001.csv
  NPC Dialogue/np_npc_7406_001.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Tutorial/tut_006294.csv
  UI/access_info.csv
  UI/common.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
  UI/ui_ranking_reb.csv
  UI/ui_scratch_reb.csv
  UI/ui_shop_reb.csv
  UI/ui_tips_reb.csv
  should find category/DF Ages/tut_006579.csv
Labels: size/XXL

#2049 KO_Reboot: Update story stuff
  WIP/gpro/msc_020130.csv
  WIP/gpro/msc_020170.csv
  WIP/gpro/msc_020180.csv
  WIP/gpro/msc_020200.csv
  WIP/gpro/msc_020210.csv
  WIP/gpro/msc_020220.csv
  WIP/gpro/msc_020225.csv
  WIP/gpro/msc_020250.csv
  WIP/gpro/msc_020280.csv
  WIP/gpro/msc_020310.csv
  WIP/gpro/msc_020330.csv
  WIP/gpro/msc_020340.csv
  WIP/gpro/msq_020073.csv
  WIP/gpro/msq_020161.csv
  WIP/gpro/msq_020163.csv
  WIP/gpro/msq_020235.csv
  WIP/gpro/msq_020249.csv
  WIP/gpro/msq_020264.csv
  WIP/gpro/msq_020269.csv
  WIP/gpro/msq_020274.csv
  WIP/gpro/msq_020326.csv
  WIP/gpro/msq_020341.csv
  WIP/gpro/qst_1200540020.csv
  WIP/gpro/qst_1200560020.csv
  WIP/gpro/quest_01200523.csv
  WIP/gpro/quest_01200524.csv
  WIP/gpro/quest_01200525.csv
  WIP/gpro/quest_01200581.csv
Labels: size/L

#2050 KO_Reboot: Update files
  Quest/ui_quest_counter_reb.csv
  UI/ui_item.csv
  WIP/gpro/qst_1200500040.csv
  WIP/gpro/quest_01320000.csv
  WIP/gpro/quest_01320010.csv
  WIP/gpro/quest_01320020.csv
  WIP/gpro/quest_01320030.csv
  WIP/gpro/ss0030740601.csv
  WIP/gpro/ssn_015810.csv
  WIP/gpro/ssn_015811.csv
  WIP/gpro/ssn_019150_001.csv
  WIP/gpro/ssq_015812.csv
  should find category/DF Ages/msc_020020.csv
Labels: size/L

#2051 Corrections
  Translated/Story/29 A Visitor in the Desert/msc_020225.csv
  Translated/Story/30 Storming Leciel/msc_020250.csv
  Translated/UI/actor_name.csv
  Translated/UI/ui_item.csv
Labels: size/S

#2052 AMERICA
  Translated/Dialog/Bergmann/ssq_013091.csv
  Translated/Dialog/Chitose/ssn_015470.csv
  Translated/Dialog/Dino/ssn_014670.csv
  Translated/Dialog/Ingstad/ssn_014710.csv
  Translated/Dialog/Kirishima/ssn_015300.csv
  Translated/Dialog/Rediah/ssq_015190_004.csv
  Translated/Dialog/Souya/ssn_015450.csv
  Translated/Dialog/Tokiwa/npc_777101.csv
  Translated/Dialog/Xiandy/2021-09-01 Moon Viewing/ssn_019010_006.csv
  Translated/Dialog/Xiandy/2021-10-27 Halloween/ssq_019020_005.csv
  Translated/Dialog/Xiandy/2023-01-01 New Year/ssn_019120_002.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssn_019140_002.csv
  Translated/Dialog/trial_common.csv
  Translated/Story/04-05 DOLLS on Mt. Magnus/msq_011220_005.csv
  Translated/Story/10 To Retem City/msc_012130.csv
  Translated/Story/29 A Visitor in the Desert/msc_020220.csv
  Translated/Story/29 A Visitor in the Desert/msc_020225.csv
  Translated/Story/32 Zephetto/msc_020330.csv
  Translated/Tutorials/tut_006356.csv
  Translated/Tutorials/tut_006423.csv
  Translated/Tutorials/tut_006452.csv
  Translated/Tutorials/tut_006467.csv
  Translated/Tutorials/tut_006551.csv
  Translated/Tutorials/tut_006609.csv
  Translated/UI/common.csv
  Translated/UI/object_individual.csv
  Translated/UI/quest_common_reboot.csv
  Translated/UI/ui_group_chat.csv
  Translated/UI/ui_item.csv
  Translated/UI/ui_mainmode.csv
  Translated/UI/ui_na_mainmode.csv
  Translated/UI/ui_quest_reb.csv
  Translated/UI/ui_selectmenu_text.csv
Labels: size/L

#2053 KO_Reboot: Update files
  UI/ui_mainmode.csv
  WIP/gpro/msn_016000_000.csv
  WIP/gpro/quest_01180300.csv
  WIP/gpro/ssn_019150_002.csv
  WIP/gpro/ssq_019150_002.csv
  WIP/gpro/ssq_019150_003.csv
  WIP/gpro/ssq_019150_004.csv
  WIP/gpro/ssq_019150_005.csv
  WIP/gpro/trial_apc_7016001.csv
  WIP/gpro/trial_apc_7022001.csv
  WIP/gpro/trial_apc_7224005.csv
  WIP/gpro/trial_apc_7234002.csv
  WIP/gpro/trial_apc_7761001.csv
  WIP/gpro/trial_apc_7762001.csv
  WIP/gpro/trial_apc_7763001.csv
  WIP/gpro/tut_006551.csv
  WIP/gpro/tut_006552.csv
  WIP/gpro/tut_006555.csv
  WIP/gpro/tut_006603.csv
  WIP/gpro/tut_006607.csv
  WIP/gpro/tut_006608.csv
  WIP/gpro/tut_006609.csv
Labels: size/L

#2054 Line break on Venogia death hint
  Translated/UI/ui_tips_reb.csv
Labels: size/XS

#2055 you've yee'd your last haw
  Translated/Dialog/Anan/ssn_015500.csv
  Translated/Dialog/Shioji/ssn_015514.csv
  Translated/Story/Side Bruder/ssc_503030.csv
  Translated/Story/Side Bruder/ssc_503050.csv
  Translated/UI/actor_name.csv
Labels: size/S

#2057 Remove lingering double quotes
  Translated/UI/actor_name.csv
Labels: size/XS

#2058 Spacing after Slayer PA names
  Translated/UI/actor_name.csv
Labels: size/XS

#2059 upcoming seasonal event dialogue
  Files/ssn_019150_001.csv
  Files/ssn_019150_002.csv
  Files/ssq_019150_001.csv
  Files/ssq_019150_002.csv
  Files/ssq_019150_003.csv
  Files/ssq_019150_004.csv
  Files/ssq_019150_005.csv
  Translated/Dialog/Xiemmy/2023-01-11 Winter/ssn_019130_001.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssn_019150_001.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssn_019150_002.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssq_019150_001.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssq_019150_002.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssq_019150_003.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssq_019150_004.csv
  Translated/Dialog/Xiemmy/Spring 2023/ssq_019150_005.csv
Labels: size/L

#2060 KO_Reboot: Fix typo
  Quest/ui_quest_reb.csv
  UI/common.csv
  UI/ui_mainmode.csv
  UI/ui_mainmode_reb.csv
  UI/ui_tips_reb.csv
Labels: size/S

#2062 KO_Reboot: Update ui_mainmode.csv
  UI/ui_mainmode.csv
Labels: size/XS

#2063 KO: Update story stuff
  Story/Episode 1/Chapter 8/co_012801.csv
  Story/Episode 1/Chapter 8/ra_010630.csv
  Story/Episode 1/Chapter 8/ra_010640.csv
  Story/Episode 1/Chapter 8/ra_010650_om.csv
  Story/Episode 1/Chapter 8/ra_012000.csv
  Story/Episode 1/Chapter 8/st_010660.csv
  Story/Episode 1/Chapter 8/st_010690.csv
  Story/Episode 1/Chapter 8/st_010700_om.csv
  Story/Episode 1/Chapter 8/st_010710_om.csv
  Story/Episode 1/Chapter 8/st_010720.csv
  Story/Episode 1/Chapter 8/st_010730.csv
  Story/Episode 1/Chapter 8/st_010740.csv
  Story/Episode 1/Chapter 8/st_010750.csv
  Story/Episode 1/Chapter 8/st_010760.csv
Labels: size/L

#2064 KO: Episode1-8
  Story/Episode 1/Chapter 4/quest_00700510.csv
  Story/Episode 1/Chapter 8/ra_012000.csv
  Story/Episode 1/Chapter 8/ra_012010_om.csv
  Story/Episode 1/Chapter 8/ra_013030.csv
  Story/Episode 1/Chapter 8/st_010710_om.csv
  Story/Episode 1/Chapter 8/st_010730.csv
  Story/Episode 1/Chapter 8/st_010740.csv
  Story/Episode 1/Chapter 8/st_010750.csv
  Story/Episode 1/Chapter 8/st_010760.csv
  Story/Episode 1/Chapter 8/un_010660.csv
  Story/Episode 1/Chapter 8/un_012470.csv
  Story/Episode 1/Chapter 8/un_012490.csv
  Story/Episode 1/Chapter 9/un_011550.csv
  UI/ui_eventchronicle.csv
  UI/ui_mainmode.csv
Labels: size/L

#2065 KO_Reboot: Fix typo
  Task/Team/gs0040104013.csv
  UI/common.csv
  WIP/gpro/msc_020280.csv
Labels: size/XS

#2069 small change
  Translated/Tutorials/tut_006608.csv
Labels: size/XS

#2067 KO_Reboot: Update files
  E-Trial/trial_enemy_ahl.csv
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Task/Weekly/ew0620011521.csv
Labels: size/S

#2070 KO_Reboot: Update files
  WIP/gpro/ls0061160105.csv
  WIP/gpro/ssn_019150_002.csv
Labels: size/XS

#2071 Happy Rappy Operation EQ dialogue
  Files/qst_1120150000.csv
  Files/qst_1120150010.csv
  Files/qst_1120150020.csv
  Files/qst_1120150021.csv
  Files/qst_1120150030.csv
  Files/qst_1120150040.csv
  Files/qst_1120150041.csv
  Files/qst_1120150050.csv
  Files/qst_1120150060.csv
  Files/qst_1120150061.csv
  Files/qst_1120150070.csv
  Files/qst_1120150080.csv
  Files/qst_1120150090.csv
  Files/qst_1120150100.csv
  Files/qst_1120150110.csv
  Files/qst_1120150120.csv
  Files/qst_1120150130.csv
  Files/qst_1120150131.csv
  Files/qst_1120150132.csv
  Files/qst_1120150140.csv
  Files/qst_1120150141.csv
  Files/qst_1120150142.csv
  Files/qst_1120160010.csv
  Files/qst_1120160015.csv
  Files/qst_1120160020.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150000.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150010.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150020.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150021.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150030.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150040.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150041.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150050.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150060.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150061.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150070.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150080.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150090.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150100.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150110.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150120.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150130.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150131.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150132.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150140.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150141.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120150142.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120160010.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120160015.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1120160020.csv
Labels: size/L

#2072 Duel Quest descriptions + some Ran dialogue
  Files/qst_1180220000.csv
  Files/qst_1180300010.csv
  Files/qst_1180300015.csv
  Files/qst_1180300020.csv
  Files/quest_01320000.csv
  Files/quest_01320010.csv
  Files/quest_01320020.csv
  Files/quest_01320030.csv
  Files/quest_01320040.csv
  Translated/Dialog/Ran/qst_1120160010.csv
  Translated/Dialog/Ran/qst_1120160015.csv
  Translated/Dialog/Ran/qst_1120160020.csv
  Translated/Dialog/Ran/qst_1180300010.csv
  Translated/Dialog/Ran/qst_1180300015.csv
  Translated/Dialog/Ran/qst_1180300020.csv
  Translated/Quests/Duel Quests/quest_01320000.csv
  Translated/Quests/Duel Quests/quest_01320010.csv
  Translated/Quests/Duel Quests/quest_01320020.csv
  Translated/Quests/Duel Quests/quest_01320030.csv
  Translated/Quests/Duel Quests/quest_01320040.csv
  Translated/Quests/Emergency Quests/Happy Rappy Operation/qst_1180220000.csv
Labels: size/M
