Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-10, with the labels that each got.

#2142 new story quick push
  Files/msc_023020.csv
  Files/msn_022021.csv
  Files/msn_022022.csv
  Files/msn_023010.csv
  Files/msn_023021.csv
  Files/msn_023022.csv
  Files/msn_023023.csv
  Translated/Story/Unorganized/msc_023020.csv
  Translated/Story/Unorganized/msn_022021.csv
  Translated/Story/Unorganized/msn_022022.csv
  Translated/Story/Unorganized/msn_023010.csv
  Translated/Story/Unorganized/msn_023021.csv
  Translated/Story/Unorganized/msn_023022.csv
  Translated/Story/Unorganized/msn_023023.csv
Labels: size/L

#2143 New story. unorganized, no linebreaks
  Files/msc_022030.csv
  Files/msc_022040.csv
  Files/msc_022050.csv
  Files/msc_022060.csv
  Files/msc_022070.csv
  Files/msc_023030.csv
  Files/msc_023040.csv
  Files/msc_023050.csv
  Files/msn_022041.csv
  Files/msn_022042.csv
  Files/msn_022051.csv
  Files/msn_022061.csv
  Files/msn_022062.csv
  Files/msn_022071.csv
  Files/msn_023024.csv
  Files/msn_023025.csv
  Files/msn_023026.csv
  Files/msn_023041.csv
  Files/msn_023042.csv
  Translated/Story/Unorganized/msc_022030.csv
  Translated/Story/Unorganized/msc_022040.csv
  Translated/Story/Unorganized/msc_022050.csv
  Translated/Story/Unorganized/msc_022060.csv
  Translated/Story/Unorganized/msc_022070.csv
  Translated/Story/Unorganized/msc_023030.csv
  Translated/Story/Unorganized/msc_023040.csv
  Translated/Story/Unorganized/msc_023050.csv
  Translated/Story/Unorganized/msn_022041.csv
  Translated/Story/Unorganized/msn_022042.csv
  Translated/Story/Unorganized/msn_022051.csv
  Translated/Story/Unorganized/msn_022061.csv
  Translated/Story/Unorganized/msn_022062.csv
  Translated/Story/Unorganized/msn_022071.csv
  Translated/Story/Unorganized/msn_023024.csv
  Translated/Story/Unorganized/msn_023025.csv
  Translated/Story/Unorganized/msn_023026.csv
  Translated/Story/Unorganized/msn_023041.csv
  Translated/Story/Unorganized/msn_023042.csv
Labels: size/XL

#2146 New ARKS records ranking titles
  Translated/UI/ui_ranking_reb.csv
Labels: size/XS

#2147 KO_Reboot: Update files
  Files/quest_01330000.csv
  Quest/Leciel/quest_01330000.csv
  Quest/ui_quest_reb.csv
  UI/config.csv
  WIP/20231017/ls0061190103.csv
  WIP/20231017/msc_022040.csv
  WIP/20231017/msc_022050.csv
  WIP/20231017/msc_022060.csv
  WIP/20231017/msc_022070.csv
  WIP/20231017/msc_023020.csv
  WIP/20231017/msc_023030.csv
  WIP/20231017/msc_023040.csv
  WIP/20231017/msc_023050.csv
  WIP/20231017/msn_022022.csv
  WIP/20231017/msn_022062.csv
  WIP/20231017/msn_023021.csv
  WIP/20231017/msn_023024.csv
  WIP/20231017/msn_023026.csv
  WIP/20231017/qst_1120190010.csv
  WIP/gpro/quest_01200540.csv
  WIP/gpro/quest_01200550.csv
  WIP/gpro/quest_01200560.csv
  WIP/gpro/quest_01200570.csv
Labels: size/M

#2148 KO_Reboot: ONE MORE THING
  UI/config.csv
Labels: size/XS

#2150 KO_Reboot: Fix typo
  UI/config.csv
  UI/ui_selectmenu_text.csv
Labels: size/XS

#2149 Ko
  UI/item_element_name_reb.csv
  UI/ui_charamake_text_reb.csv
Labels: size/S
