Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-01, with the labels that each got.

#1962 retem and kvaris side stories
  Files/ssc_501060.csv
  Files/ssc_501070.csv
  Files/ssc_501080.csv
  Files/ssc_501090.csv
  Files/ssc_502060.csv
  Files/ssc_502070.csv
  Files/ssc_502080.csv
  Files/ssc_503060.csv
  Files/ssc_504040.csv
  Files/ssc_505020.csv
  Files/ssc_505030.csv
  Files/ssc_506010.csv
  Files/ssc_506020.csv
  Files/ssc_506030.csv
  Files/ssc_507010.csv
  Files/ssc_507020.csv
  Files/ssc_507030.csv
  Files/ssc_508010.csv
  Files/ssc_508020.csv
  Files/ssc_509020.csv
  Files/ssc_509030.csv
  Translated/Story/Side Aina/ssc_501060.csv
  Translated/Story/Side Aina/ssc_501070.csv
  Translated/Story/Side Aina/ssc_501080.csv
  Translated/Story/Side Aina/ssc_501090.csv
  Translated/Story/Side Bruder/ssc_503060.csv
  Translated/Story/Side Crawford/ssc_504040.csv
  Translated/Story/Side Hadi/ssc_507010.csv
  Translated/Story/Side Hadi/ssc_507020.csv
  Translated/Story/Side Hadi/ssc_507030.csv
  Translated/Story/Side Ilma/ssc_508010.csv
  Translated/Story/Side Ilma/ssc_508020.csv
  Translated/Story/Side Manon/ssc_502060.csv
  Translated/Story/Side Manon/ssc_502070.csv
  Translated/Story/Side Manon/ssc_502080.csv
  Translated/Story/Side Meri/ssc_509020.csv
  Translated/Story/Side Meri/ssc_509030.csv
  Translated/Story/Side Nadereh/ssc_506010.csv
  Translated/Story/Side Nadereh/ssc_506020.csv
  Translated/Story/Side Nadereh/ssc_506030.csv
  Translated/Story/Side Ran/ssc_505020.csv
  Translated/Story/Side Ran/ssc_505030.csv
Labels: size/XXL

#1967 KO_Reboot: Update files
  Task/Side Story/Limited Event/2022-2023/ssn_019110_002.csv
  Task/Side Story/Limited Event/2022-2023/ssn_019120_002.csv
  Task/Side Story/Limited Event/2022-2023/ssn_019130_002.csv
Labels: size/S

#1966 xiandy new year dialogue
  Translated/Dialog/Xiandy/2023-01-01 New Year/ssn_019120_001.csv
  Translated/Dialog/Xiandy/2023-01-01 New Year/ssn_019120_002.csv
  Translated/Dialog/Xiandy/2023-01-01 New Year/ssq_019120_001.csv
  Translated/Dialog/Xiandy/2023-01-01 New Year/ssq_019120_002.csv
Labels: size/M

#1968 upcoming xiemmy event dialogue
  Translated/Dialog/Xiemmy/2023-01-11 Winter/ssn_019130_001.csv
  Translated/Dialog/Xiemmy/2023-01-11 Winter/ssn_019130_002.csv
  Translated/Dialog/Xiemmy/2023-01-11 Winter/ssq_019130_001.csv
  Translated/Dialog/Xiemmy/2023-01-11 Winter/ssq_019130_002.csv
Labels: size/L

#1972 KO: Update files
  UI/ui_accessories_text.csv
  UI/ui_charamake_parts.csv
Labels: size/XXL

#1973 KO_Reboot: Click
  Task/Side Story/ssq_015190_004.csv
Labels: size/XS

#1970 EN_Reboot: Add leading space to Open Chat strings
  Translated/UI/common.csv
Labels: size/S

#1971 Corrections and suggested improvements
  Translated/Story/Side Bruder/ssc_503060.csv
  Translated/Story/Side Crawford/ssc_504040.csv
  Translated/Story/Side Meri/ssc_509020.csv
  Translated/Story/Side Meri/ssc_509030.csv
  Translated/Tasks/Limited/2023-01-01 New Year/ls0061130103.csv
  Translated/Tasks/Limited/2023-01-11 Winter/ls0061140102.csv
  Translated/Tasks/Limited/2023-01-11 Winter/ls0061140103.csv
  Translated/Tasks/Limited/2023-01-11 Winter/ls0061143102.csv
  Translated/Tutorials/tut_006566.csv
  Translated/UI/object_common.csv
Labels: size/S

#1975 KO_Reboot: Update files
  Task/Side Story/Limited Event/2022-2023/ssn_019110_002.csv
  Task/Side Story/Limited Event/2022-2023/ssn_019130_002.csv
  WIP/gpro/20230106/ssn_015510.csv
  WIP/ssn_015190.csv
Labels: size/M

#1976 Double space fix
  Translated/Tasks/Daily/Stia/ed0610011908.csv
Labels: size/XS

#1980 xiemmy says this line
  Translated/Dialog/Xiemmy/2023-01-11 Winter/ssn_019130_002.csv
Labels: size/XS

#1983 KO: Update item_element_expl_reb.csv
  Files/reb_gacha_banner_15032.csv
  Files/reb_gacha_banner_15061.csv
  Files/reb_gacha_banner_15062.csv
  Files/reb_gacha_banner_20005.csv
  Files/reb_gacha_banner_20006.csv
  Files/reb_gacha_banner_20007.csv
  Files/reb_gacha_banner_20010.csv
  Files/reb_gacha_banner_20011.csv
  Files/reb_gacha_banner_20012.csv
  Files/reb_gacha_banner_s_15061.csv
  Files/reb_gacha_banner_s_15062.csv
  Files/reb_gacha_banner_s_20005.csv
  Files/reb_gacha_banner_s_20006.csv
  Files/reb_gacha_banner_s_20007.csv
  Files/reb_gacha_banner_s_20010.csv
  Files/reb_gacha_banner_s_20011.csv
  Files/reb_gacha_banner_s_20012.csv
  Files/reb_gacha_banner_small_15032.csv
  Files/ui_gacha_101_00.csv
  UI/item_element_expl_reb.csv
Labels: size/XL

#1984 "Leave Party" to "Remove from Party"
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#1985 Character creation stuff
  UI/ui_charamake_text.csv
Labels: size/L

#1987 Fitting text into box
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#1982 KO_Reboot: Update files
  Files/msq_014112.csv
  Files/np_npc_7447_001.csv
  Files/np_npc_7761_001.csv
  Files/np_npc_7764_001.csv
  Files/np_npc_7765_001.csv
  Files/ssn_005134.csv
  Files/ssn_005144.csv
  Files/tut_006556.csv
  WIP/gpro/qwerty/msn_014020.csv
  WIP/gpro/qwerty/msq_014112.csv
  WIP/gpro/qwerty/msq_014158.csv
  WIP/gpro/qwerty/msq_014201.csv
  WIP/gpro/qwerty/msq_014291.csv
  WIP/gpro/qwerty/np_npc_7447_001.csv
  WIP/gpro/qwerty/np_npc_7761_001.csv
  WIP/gpro/qwerty/np_npc_7764_001.csv
  WIP/gpro/qwerty/np_npc_7765_001.csv
  WIP/gpro/qwerty/qst_1200420001.csv
  WIP/gpro/qwerty/ssn_005134.csv
  WIP/gpro/qwerty/ssn_005144.csv
  WIP/gpro/qwerty/ssn_005160.csv
  WIP/gpro/qwerty/ssq_015602.csv
  WIP/gpro/qwerty/ssq_019110_002.csv
  WIP/gpro/qwerty/tut_006556.csv
  WIP/ssn_015190.csv
Labels: size/M

#1988 KO: 자꾸 아찔한 이 느낌
  Files/item_series_name.csv
  Files/reb_gacha_banner_15032.csv
  Files/reb_gacha_banner_15061.csv
  Files/reb_gacha_banner_15062.csv
  Files/reb_gacha_banner_20005.csv
  Files/reb_gacha_banner_20006.csv
  Files/reb_gacha_banner_20007.csv
  Files/reb_gacha_banner_20010.csv
  Files/reb_gacha_banner_20011.csv
  Files/reb_gacha_banner_20012.csv
  Files/reb_gacha_banner_s_15061.csv
  Files/reb_gacha_banner_s_15062.csv
  Files/reb_gacha_banner_s_20005.csv
  Files/reb_gacha_banner_s_20006.csv
  Files/reb_gacha_banner_s_20007.csv
  Files/reb_gacha_banner_s_20010.csv
  Files/reb_gacha_banner_s_20011.csv
  Files/reb_gacha_banner_s_20012.csv
  Files/reb_gacha_banner_small_15032.csv
  Files/ui_gacha_101_00.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/item_series_name.csv
  UI/ui_charamake_text_reb.csv
Labels: size/L

#1990 KO_Reboot: Update files
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  UI/ui_directbuy_text.csv
  UI/ui_equip.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_ranking_reb.csv
  UI/ui_scratch_reb.csv
  UI/ui_shop_reb.csv
Labels: size/XL

#1992 Typo fix
  Translated/UI/ui_quest_counter_reb.csv
Labels: size/XS

#1994 main story + side story dialogue
  Files/msc_020020.csv
  Files/msc_020030.csv
  Files/msc_020080.csv
  Files/msc_020090.csv
  Files/msc_020100.csv
  Files/ssc_501100.csv
  Files/ssc_501110.csv
  Files/ssc_502090.csv
  Files/ssc_502100.csv
  Files/ssc_503070.csv
  Files/ssc_506040.csv
  Files/ssc_508030.csv
  Files/ssc_509040.csv
  Files/ssc_510010.csv
  Files/ssc_510020.csv
  Files/ssc_510030.csv
  Files/ssc_511010.csv
  Files/ssc_511020.csv
  Files/ssc_511030.csv
  Translated/Dialog/apc_chat_1.csv
  Translated/Story/26b Dark Falz Aegis/msc_020020.csv
  Translated/Story/26b Dark Falz Aegis/msc_020030.csv
  Translated/Story/26b Dark Falz Aegis/msc_020080.csv
  Translated/Story/26b Dark Falz Aegis/msc_020090.csv
  Translated/Story/26b Dark Falz Aegis/msc_020100.csv
  Translated/Story/Side Aina/ssc_501100.csv
  Translated/Story/Side Aina/ssc_501110.csv
  Translated/Story/Side Bruder/ssc_503070.csv
  Translated/Story/Side Guren/ssc_510010.csv
  Translated/Story/Side Guren/ssc_510020.csv
  Translated/Story/Side Guren/ssc_510030.csv
  Translated/Story/Side Ilma/ssc_508030.csv
  Translated/Story/Side Kanui/ssc_511010.csv
  Translated/Story/Side Kanui/ssc_511020.csv
  Translated/Story/Side Kanui/ssc_511030.csv
  Translated/Story/Side Manon/ssc_502090.csv
  Translated/Story/Side Manon/ssc_502100.csv
  Translated/Story/Side Meri/ssc_509040.csv
  Translated/Story/Side Nadereh/ssc_506040.csv
Labels: size/XXL

#1995 bits and bobs
  Files/ssn_015222.csv
  Files/ssn_015751.csv
  Files/ssn_015800.csv
  Files/ssn_015801.csv
  Files/ssn_015802.csv
  Files/ssn_019140_001.csv
  Files/ssn_019140_002.csv
  Files/ssq_015223.csv
  Files/ssq_015752.csv
  Files/ssq_019140_001.csv
  Files/ssq_019140_002.csv
  Files/ssq_019140_003.csv
  Files/ssq_019140_004.csv
  Translated/Dialog/Hatsukari/ssn_015751.csv
  Translated/Dialog/Hatsukari/ssq_015752.csv
  Translated/Dialog/Ran/ssn_015800.csv
  Translated/Dialog/Ran/ssn_015801.csv
  Translated/Dialog/Ran/ssn_015802.csv
  Translated/Dialog/Schraft/ssn_015222.csv
  Translated/Dialog/Schraft/ssq_015223.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssn_019140_001.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssn_019140_002.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssq_019140_001.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssq_019140_002.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssq_019140_003.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssq_019140_004.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110000.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110010.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110020.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110030.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110040.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110050.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110060.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110070.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110080.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110090.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110100.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110110.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110120.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250000.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250001.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250010.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250020.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250021.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250022.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250023.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180250024.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260000.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260011.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260012.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260013.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260014.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260015.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260016.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260017.csv
  Translated/Quests/Limited Quests/Truck Breakdown/qst_1180260018.csv
Labels: size/L

#1997 Corrections
  Translated/Dialog/Ran/ssn_015800.csv
  Translated/Dialog/Ran/ssn_015801.csv
  Translated/Dialog/Xiandy/2023-03-22 Spring/ssn_019140_002.csv
  Translated/Quests/Emergency Quests/Dark Falz Aegis/qst_1120110000.csv
  Translated/Quests/Story/Side Manon/quest_01200709.csv
  Translated/Quests/Story/Side Manon/quest_01200710.csv
  Translated/Story/Side Aina/ssc_501100.csv
  Translated/Story/Side Kanui/ssc_511010.csv
  Translated/Story/Side Kanui/ssc_511030.csv
Labels: size/S

#1999 sory -> sorry
  Translated/Story/Side Ilma/ssc_508030.csv
Labels: size/XS

#2000 KO_Reboot: 자꾸 아찔한 이 느낌
  E-Trial/trial_apc_7735001.csv
  E-Trial/trial_apc_7736001.csv
  Files/ssc_510010.csv
  NPC Dialogue/npc_772901.csv
  NPC Dialogue/npc_773501.csv
  NPC Dialogue/npc_773601.csv
  Quest/Seasonal/2023/quest_01180190.csv
  Quest/Seasonal/2023/quest_01180200.csv
  Quest/Trainia/quest_01110060.csv
  Story/Side/ssc_501060.csv
  Story/Side/ssc_504040.csv
  Story/Side/ssc_505020.csv
  Story/Side/ssc_510010.csv
  Task/Limited/ls0060080102.csv
  Task/Limited/ls0060080103.csv
  Task/Limited/ls0060080104.csv
  Task/Limited/ls0060080105.csv
  Task/Limited/ls0060100103.csv
  Task/Limited/ls0060100104.csv
  Task/Side Story/ssn_015070.csv
  Task/Side Story/ssn_015180.csv
  Task/Side Story/ssn_015181.csv
  Task/Side Story/ssn_015185.csv
  Task/Side Story/ssn_015186.csv
  Task/Side Story/ssn_015190.csv
  Task/Side Story/ssn_015191.csv
  Task/Side Story/ssn_015200.csv
  Task/Side Story/ssn_015201.csv
  Task/Side Story/ssn_015211.csv
  Task/Side Story/ssn_015212.csv
  Task/Side Story/ssq_015160_006.csv
  Task/Side Story/ssq_015184.csv
  Task/Side Story/ssq_015190_004.csv
  Task/Side Story/ssq_015192.csv
  Task/Side Story/ssq_015202.csv
  UI/ui_directbuy_text.csv
  UI/ui_item.csv
  WIP/gpro/ssc_501060.csv
  WIP/gpro/ssc_503060.csv
  WIP/gpro/ssc_504040.csv
  WIP/gpro/ssc_505020.csv
  WIP/gpro/ssc_506010.csv
  WIP/gpro/ssc_506020.csv
  WIP/gpro/ssc_506030.csv
  WIP/npc_772901.csv
  WIP/npc_773501.csv
  WIP/npc_773601.csv
  WIP/quest_01110060.csv
  WIP/quest_01180190.csv
  WIP/quest_01180200.csv
  WIP/ssn_015180.csv
  WIP/ssn_015181.csv
  WIP/ssn_015185.csv
  WIP/ssn_015186.csv
  WIP/ssn_015200.csv
  WIP/ssn_015201.csv
  WIP/ssn_015211.csv
Labels: size/XL
