Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-02, with the labels that each got.

#2002 KO_Reboot: Update files
  Files/msc_020020.csv
  Files/msc_020030.csv
  Files/msc_020080.csv
  Files/msc_020090.csv
  Files/msc_020100.csv
  Files/qst_1120110000.csv
  Files/qst_1120110010.csv
  Files/qst_1120110020.csv
  Files/qst_1120110030.csv
  Files/qst_1120110040.csv
  Files/qst_1120110050.csv
  Files/qst_1120110060.csv
  Files/qst_1120110070.csv
  Files/qst_1120110080.csv
  Files/qst_1120110090.csv
  Files/qst_1120110100.csv
  Files/qst_1120110110.csv
  Files/qst_1120110120.csv
  Files/qst_1180220000.csv
  Files/quest_01120110.csv
  Files/quest_01180240.csv
  Files/ssc_503070.csv
  Files/ssc_506040.csv
  Files/tut_006578.csv
  Files/tut_006579.csv
  Story/Side/ssc_503070.csv
  Story/Side/ssc_506040.csv
  UI/object_individual.csv
  UI/ui_scratch_reb.csv
  WIP/gpro/ssc_503060.csv
  WIP/gpro/ssc_506030.csv
  WIP/gpro/ssc_507020.csv
  WIP/gpro/ssc_507030.csv
  should find category/DF Ages/msc_020020.csv
  should find category/DF Ages/msc_020030.csv
  should find category/DF Ages/msc_020080.csv
  should find category/DF Ages/msc_020090.csv
  should find category/DF Ages/msc_020100.csv
  should find category/DF Ages/qst_1120110000.csv
  should find category/DF Ages/qst_1120110010.csv
  should find category/DF Ages/qst_1120110020.csv
  should find category/DF Ages/qst_1120110030.csv
  should find category/DF Ages/qst_1120110040.csv
  should find category/DF Ages/qst_1120110050.csv
  should find category/DF Ages/qst_1120110060.csv
  should find category/DF Ages/qst_1120110070.csv
  should find category/DF Ages/qst_1120110080.csv
  should find category/DF Ages/qst_1120110090.csv
  should find category/DF Ages/qst_1120110100.csv
  should find category/DF Ages/qst_1120110110.csv
  should find category/DF Ages/qst_1120110120.csv
  should find category/DF Ages/qst_1180220000.csv
  should find category/DF Ages/quest_01120110.csv
  should find category/DF Ages/quest_01180240.csv
  should find category/DF Ages/tut_006578.csv
  should find category/DF Ages/tut_006579.csv
Labels: size/XL

#2003 KO_Reboot: Update files
  E-Trial/trial_god3.csv
  Files/trial_god3.csv
  UI/ui_item.csv
  should find category/DF Ages/msc_020020.csv
  should find category/DF Ages/msc_020080.csv
Labels: size/M

#2001 Add line break to item description message
  Translated/UI/ui_item.csv
Labels: size/XS

#2005 Stia Successive Training task name reword
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010401.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010402.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010403.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010404.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010405.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010406.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010407.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010408.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010409.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010410.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010411.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010412.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010413.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010414.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010415.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010416.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010417.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010418.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010419.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010420.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010421.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010422.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010423.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010424.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010425.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010426.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010427.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010428.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010429.csv
  Translated/Tasks/Limited/Successive Training/Stia/cp0410010430.csv
Labels: size/M

#1996 Trim Outer Mediola daily title to fit text box
  Translated/Tasks/Daily/Stia/ed0610011806.csv
  Translated/Tasks/Daily/Stia/ed0610011807.csv
  Translated/Tasks/Daily/Stia/ed0610011808.csv
  Translated/Tasks/Daily/Stia/ed0610011809.csv
  Translated/Tasks/Daily/Stia/ed0610011810.csv
  Translated/Tasks/Daily/Stia/ed0610011906.csv
  Translated/Tasks/Daily/Stia/ed0610011907.csv
  Translated/Tasks/Daily/Stia/ed0610011908.csv
  Translated/Tasks/Daily/Stia/ed0610011909.csv
  Translated/Tasks/Daily/Stia/ed0610011910.csv
  Translated/Tasks/Daily/Stia/ed0610011911.csv
  Translated/Tasks/Daily/Stia/ed0610011912.csv
  Translated/Tasks/Daily/Stia/ed0610011913.csv
Labels: size/S

#2008 KO_Reboot: Update files
  Files/qst_1180250000.csv
  Files/qst_1180250001.csv
  Files/qst_1180250010.csv
  Files/qst_1180250020.csv
  Files/qst_1180250021.csv
  Files/qst_1180250022.csv
  Files/qst_1180250023.csv
  Files/qst_1180250024.csv
  Files/qst_1180260000.csv
  Files/qst_1180260011.csv
  Files/qst_1180260012.csv
  Files/qst_1180260013.csv
  Files/qst_1180260014.csv
  Files/qst_1180260015.csv
  Files/qst_1180260016.csv
  Files/qst_1180260017.csv
  Files/qst_1180260018.csv
  Files/quest_01180250.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250000.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250001.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250010.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250020.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250021.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250022.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250023.csv
  Quest/Seasonal/2023/Truck 1/qst_1180250024.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260000.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260011.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260012.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260013.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260014.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260015.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260016.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260017.csv
  Quest/Seasonal/2023/Truck 1/qst_1180260018.csv
  Quest/Seasonal/2023/Truck 1/quest_01180250.csv
  UI/ui_mainmode.csv
  filelist.txt
  should find category/DF Ages/quest_01180240.csv
Labels: size/L

#2009 KO_Reboot: DRUNK TRANSLATION
  Files/ssc_508030.csv
  Files/ssc_510020.csv
  Files/ssc_511010.csv
  Quest/Seasonal/2023/Truck 1/quest_01180250.csv
  Story/Side/ssc_501090.csv
  Story/Side/ssc_508030.csv
  Story/Side/ssc_510020.csv
  Story/Side/ssc_511010.csv
  WIP/gpro/Check/quest_01200610.csv
  WIP/gpro/Check/quest_01200611.csv
  WIP/gpro/ssc_501090.csv
  WIP/gpro/ssc_502070.csv
Labels: size/L

#2011 ARKs → ARKS
  Translated/Story/03 To Central City/msc_010230.csv
  Translated/Story/Side Hadi/ssc_507010.csv
Labels: size/XS

#2012 Filling in untranslated new strings introduced in the past few weeks
  Translated/UI/ui_ranking_reb.csv
Labels: size/S

#2014 KO_Reboot: Update files
  NPC Dialogue/npc_740401.csv
  NPC Dialogue/npc_772901.csv
  Story/Aelio/msq_011152.csv
  Story/Aelio/msq_011437.csv
  Tutorial/tut_006472.csv
  Tutorial/tut_006492.csv
  UI/ui_mainmode.csv
  UI/ui_shop.csv
  UI/ui_tips_reb.csv
  UI/ui_tutorial_reb.csv
  WIP/gpro/Side Story/ssc_501070.csv
  WIP/gpro/Side Story/ssc_501100.csv
  WIP/gpro/Side Story/ssc_501110.csv
  WIP/gpro/Side Story/ssc_502060.csv
  WIP/gpro/Side Story/ssc_502090.csv
  WIP/gpro/Side Story/ssc_502100.csv
  WIP/gpro/Side Story/ssc_505030.csv
  WIP/gpro/Side Story/ssc_507010.csv
  WIP/gpro/Side Story/ssc_508010.csv
  WIP/gpro/Side Story/ssc_508020.csv
  WIP/gpro/Side Story/ssc_510030.csv
  WIP/gpro/Side Story/ssc_511020.csv
  WIP/gpro/Side Story/ssc_511030.csv
  WIP/gpro/msq_014072.csv
  WIP/gpro/quest_01200492.csv
  WIP/gpro/quest_01200612.csv
  WIP/gpro/quest_01200709.csv
  WIP/gpro/quest_01200807.csv
  WIP/gpro/quest_01200904.csv
  WIP/gpro/quest_01201006.csv
  WIP/gpro/quest_01201007.csv
  WIP/gpro/quest_01201102.csv
  WIP/gpro/quest_01201105.csv
  WIP/gpro/quest_01201106.csv
  WIP/gpro/ss0030744003.csv
  WIP/gpro/ssn_015514.csv
  WIP/gpro/ssn_015600.csv
  WIP/gpro/ssn_015601.csv
  WIP/gpro/ssn_015610.csv
  WIP/gpro/ssn_015611.csv
  WIP/gpro/ssn_015620.csv
  WIP/gpro/ssn_015630.csv
  WIP/gpro/ssn_015631.csv
  WIP/gpro/ssn_015640.csv
  WIP/gpro/ssn_015650.csv
  WIP/gpro/ssn_015750.csv
  WIP/gpro/ssn_019120_001.csv
  WIP/gpro/ssq_015622.csv
Labels: size/XL

#2015 KO_Reboot: Update files
  Task/Side Story/ssn_015211.csv
  WIP/gpro/Side Story/ssc_508020.csv
  WIP/gpro/Side Story/ssc_510030.csv
  WIP/gpro/Side Story/ssc_511020.csv
  WIP/gpro/Side Story/ssc_511030.csv
  WIP/gpro/quest_01180220.csv
  WIP/gpro/quest_01180230.csv
  WIP/gpro/quest_01200710.csv
  WIP/gpro/ssn_015222.csv
  WIP/gpro/ssn_015511.csv
  WIP/gpro/ssn_015514.csv
  WIP/gpro/ssn_015600.csv
  WIP/gpro/ssn_015601.csv
  WIP/gpro/ssn_015610.csv
  WIP/gpro/ssn_015620.csv
  WIP/gpro/ssn_015621.csv
  WIP/gpro/ssn_015630.csv
  WIP/gpro/ssn_015640.csv
  WIP/gpro/ssn_015650.csv
  WIP/gpro/ssn_015651.csv
  WIP/gpro/ssn_015750.csv
  WIP/gpro/ssn_015800.csv
  WIP/gpro/ssn_015801.csv
  WIP/gpro/ssn_015802.csv
  WIP/gpro/ssn_019120_001.csv
  WIP/gpro/ssn_019130_001.csv
  WIP/gpro/ssn_019140_001.csv
  WIP/gpro/tut_006557.csv
  should find category/DF Ages/quest_01120110.csv
Labels: size/XL

#2017 KO: Fix typo
  UI/item_element_name_reb.csv
Labels: size/L

#2018 KO_Reboot: Update files
  Quest/ui_quest_reb.csv
  Story/Side/ssc_501060.csv
  Story/Side/ssc_503060.csv
  Story/Side/ssc_507030.csv
  Story/Side/ssc_508030.csv
  Task/Daily/ed0610010102.csv
  Task/Daily/ed0610010103.csv
  Task/Daily/ed0610010104.csv
  Task/Daily/ed0610010106.csv
  Task/Daily/ed0610010107.csv
  Task/Daily/ed0610010108.csv
  Task/Daily/ed0610010201.csv
  Task/Daily/ed0610010202.csv
  Task/Daily/ed0610010203.csv
  Task/Daily/ed0610010204.csv
  Task/Daily/ed0610010206.csv
  Task/Daily/ed0610010207.csv
  Task/Daily/ed0610010208.csv
  Task/Daily/ed0610010211.csv
  Task/Side Story/ss0030740501.csv
  Task/Side Story/ss0030769101.csv
  Task/Side Story/ssn_015200.csv
  Task/Team/gs0040103002.csv
  Tutorial/tut_006340.csv
  Tutorial/tut_006536.csv
  UI/ui_battle_trigger.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_tutorial_reb.csv
  WIP/gpro/Check/quest_01180040.csv
  WIP/gpro/Check/quest_01200608.csv
  WIP/gpro/Check/quest_01200833.csv
  WIP/gpro/quest_01180220.csv
  WIP/gpro/quest_01180230.csv
  WIP/gpro/quest_01180260.csv
  WIP/gpro/ssn_019140_001.csv
  WIP/gpro/tut_006576.csv
Labels: size/L

#2019 Typo
  Translated/UI/ui_tips_reb.csv
Labels: size/XS

#2023 KO: update files
  Story/Episode 1/Chapter 1/st_010160.csv
  UI/ui_charamake_text.csv
  UI/ui_charamake_text_reb.csv
  UI/ui_esthetic_text.csv
Labels: size/L

#2021 KO_Reboot: Update files
  E-Trial/trial_rappy_room.csv
  should find category/DF Ages/quest_01180240.csv
Labels: size/XS
