Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2023-03, with the labels that each got.

#2027 KO: Episode 1-2
  Files/ra_010250.csv
  Files/ra_010470.csv
  Files/ra_010480.csv
  Files/st_010230_om.csv
  Files/st_010380.csv
  Files/st_010380_om.csv
  Files/st_010400.csv
  Files/st_010440.csv
  Files/st_010450.csv
  Files/st_010450_om.csv
  Files/st_010460.csv
  Files/st_010460_om.csv
  Files/un_010220.csv
  Files/un_010720.csv
  Files/un_011260.csv
  Files/un_012030.csv
  Story/Episode 1/Chapter 1/quest_00700000.csv
  Story/Episode 1/Chapter 1/quest_00700020.csv
  Story/Episode 1/Chapter 1/quest_00700030.csv
  Story/Episode 1/Chapter 1/quest_00700035.csv
  Story/Episode 1/Chapter 1/quest_00700040.csv
  Story/Episode 1/Chapter 1/quest_00700050.csv
  Story/Episode 1/Chapter 1/quest_00700060.csv
  Story/Episode 1/Chapter 1/quest_00700070.csv
  Story/Episode 1/Chapter 1/quest_00700080.csv
  Story/Episode 1/Chapter 1/quest_00700090.csv
  Story/Episode 1/Chapter 1/quest_00700100.csv
  Story/Episode 1/Chapter 1/quest_00700110.csv
  Story/Episode 1/Chapter 1/quest_00700120.csv
  Story/Episode 1/Chapter 2/ra_010250.csv
  Story/Episode 1/Chapter 2/ra_010470.csv
  Story/Episode 1/Chapter 2/ra_010480.csv
  Story/Episode 1/Chapter 2/st_010230_om.csv
  Story/Episode 1/Chapter 2/st_010380.csv
  Story/Episode 1/Chapter 2/st_010380_om.csv
  Story/Episode 1/Chapter 2/st_010400.csv
  Story/Episode 1/Chapter 2/st_010440.csv
  Story/Episode 1/Chapter 2/st_010450.csv
  Story/Episode 1/Chapter 2/st_010450_om.csv
  Story/Episode 1/Chapter 2/st_010460.csv
  Story/Episode 1/Chapter 2/st_010460_om.csv
  Story/Episode 1/Chapter 2/un_010220.csv
  Story/Episode 1/Chapter 2/un_010550.csv
  Story/Episode 1/Chapter 2/un_010720.csv
  Story/Episode 1/Chapter 2/un_011260.csv
  Story/Episode 1/Chapter 2/un_012030.csv
  UI/ui_eventchronicle.csv
  UI/ui_storyboard.csv
Labels: size/XL

#2032 KO: Marking
  Story/Episode 1/Chapter 10/un_012090.csv
  Story/Episode 1/Chapter 10/un_012100.csv
  Story/Episode 1/Chapter 10/un_012110.csv
  Story/Episode 1/Chapter 10/un_012160.csv
  Story/Episode 1/Chapter 10/un_012170.csv
  Story/Episode 1/Chapter 10/un_012220.csv
  Story/Episode 1/Chapter 10/un_012230.csv
  Story/Episode 1/Chapter 10/un_012240.csv
  Story/Episode 1/Chapter 10/un_012380.csv
  Story/Episode 1/Chapter 10/un_012510.csv
  Story/Episode 1/Chapter 10/un_012590.csv
  Story/Episode 1/Chapter 10/un_012700.csv
  Story/Episode 1/Chapter 6/un_010260.csv
  Story/Episode 1/Chapter 6/un_010370.csv
  Story/Episode 1/Chapter 6/un_011100.csv
  Story/Episode 1/Chapter 6/un_011300.csv
  Story/Episode 1/Chapter 6/un_012070.csv
  Story/Episode 1/Chapter 7/un_010600.csv
  Story/Episode 1/Chapter 7/un_011110.csv
  Story/Episode 1/Chapter 7/un_011170.csv
  Story/Episode 1/Chapter 7/un_011370.csv
  Story/Episode 1/Chapter 7/un_012330.csv
  Story/Episode 1/Chapter 7/un_013020_om.csv
  Story/Episode 1/Chapter 8/un_012080.csv
  Story/Episode 1/Chapter 8/un_012470.csv
  Story/Episode 1/Chapter 8/un_012490.csv
  Story/Episode 1/Chapter 9/un_012620.csv
  Story/Episode 1/Chapter 9/un_012630.csv
  Story/Episode 1/Chapter 9/un_013000.csv
  Story/Episode 1/Chapter 9/un_013040.csv
  Story/Episode 1/Chapter 9/un_013180.csv
  Story/Episode 1/Chapter 9/un_013210.csv
  Story/Episode 1/Chapter 9/un_020660.csv
Labels: size/M

#2034 Line break on free Salon use message
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#2037 Line break plus past/present tense tweak
  Translated/UI/ui_quest_counter_reb.csv
Labels: size/XS

#2038 Ko: Update files
  Files/gacha_banner_large_07.csv
  Files/gacha_banner_large_08.csv
  Files/gacha_banner_large_09.csv
  Files/load_banner_large_07.csv
  Files/load_banner_large_08.csv
  Files/load_banner_large_12.csv
  Files/quest_00700180.csv
  Quests/quest_counter.csv
  Story/Episode 1/Chapter 2/quest_00700180.csv
  Story/Episode 1/Chapter 3/ra_010280.csv
  Story/Episode 1/Chapter 6/ra_010220.csv
  Story/Episode 1/Chapter 6/ra_010560.csv
  Story/Episode 1/Chapter 6/un_011100.csv
  Story/Episode 4/Chapter 8/un_049040.csv
Labels: size/L

#2041 KO: Episode 1-6
  Story/Episode 1/Chapter 1/st_010225_om.csv
  Story/Episode 1/Chapter 2/un_010220.csv
  Story/Episode 1/Chapter 3/ra_010280.csv
  Story/Episode 1/Chapter 3/st_010370.csv
  Story/Episode 1/Chapter 5/ra_010290.csv
  Story/Episode 1/Chapter 5/ra_010290_om.csv
  Story/Episode 1/Chapter 6/ra_010150.csv
  Story/Episode 1/Chapter 6/ra_010540.csv
  Story/Episode 1/Chapter 6/ra_010800.csv
  Story/Episode 1/Chapter 6/st_010555_om.csv
  Story/Episode 1/Chapter 6/un_010260.csv
  Story/Episode 1/Chapter 6/un_010370.csv
  Story/Episode 1/Chapter 6/un_011100.csv
  Story/Episode 1/Chapter 6/un_011300.csv
  Story/Episode 1/Chapter 6/un_012070.csv
  UI/item_element_name_reb.csv
Labels: size/L

#2042 Ko: Episode 1-6 complete
  Story/Episode 1/Chapter 6/ra_010150.csv
  Story/Episode 1/Chapter 6/ra_010800.csv
  Story/Episode 1/Chapter 6/st_010520.csv
  Story/Episode 1/Chapter 6/st_010520_om.csv
  Story/Episode 1/Chapter 6/st_010555_om.csv
  Story/Episode 1/Chapter 6/st_010620.csv
  Story/Episode 1/Chapter 6/st_010630.csv
  Story/Episode 1/Chapter 6/st_010635.csv
  Story/Episode 1/Chapter 6/st_010640.csv
  Story/Episode 1/Chapter 6/un_010260.csv
  Story/Episode 1/Chapter 6/un_011300.csv
  Story/Episode 1/Chapter 6/un_012070.csv
Labels: size/L

#2043 KO: Update files
  Dialogue/E-Trial/ob_9900_0318.csv
  Files/ob_9900_0318.csv
  Story/Episode 1/Chapter 6/ra_010530.csv
  Story/Episode 1/Chapter 6/ra_010560.csv
  Story/Episode 1/Chapter 6/st_010520.csv
  Story/Episode 1/Chapter 6/st_010520_om.csv
  Story/Episode 1/Chapter 6/st_010630.csv
  Story/Episode 1/Chapter 6/st_010635.csv
  Story/Episode 1/Chapter 6/st_010640.csv
  Story/Episode 1/Chapter 6/un_011100.csv
  Story/Episode 1/Chapter 7/co_012702.csv
  Story/Episode 1/Chapter 7/co_012703.csv
  Story/Episode 1/Chapter 7/co_012704.csv
  Story/Episode 1/Chapter 7/co_012705.csv
  Story/Episode 1/Chapter 7/co_012706.csv
  Story/Episode 1/Chapter 7/co_012709.csv
  Story/Episode 1/Chapter 7/ra_010160.csv
  Story/Episode 1/Chapter 7/ra_010530.csv
  Story/Episode 1/Chapter 7/st_010560_om.csv
  Story/Episode 1/Chapter 7/st_010642.csv
  Story/Episode 1/Chapter 7/st_010643.csv
  Story/Episode 1/Chapter 7/st_010644.csv
  Story/Episode 1/Chapter 7/st_010646.csv
  Story/Episode 1/Chapter 7/st_010648.csv
  Story/Episode 1/Chapter 7/st_010649.csv
  Story/Episode 1/Chapter 7/un_010600.csv
  Story/Episode 1/Chapter 7/un_010650.csv
  Story/Episode 1/Chapter 7/un_011110.csv
  Story/Episode 1/Chapter 7/un_011170.csv
  Story/Episode 1/Chapter 7/un_011370.csv
  Story/Episode 1/Chapter 7/un_012330.csv
  Story/Episode 1/Chapter 7/un_013020_om.csv
  UI/config.csv
Labels: size/XL
