Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-01, with the labels that each got.

#2170 KO_Reboot: Fix typo
  Story/Aelio/msc_011170.csv
  Story/Aelio/msq_011260_000.csv
  Task/Main/mt0010100101_010.csv
  Task/Side Story/ss0030740304.csv
  Task/Side Story/ss0030740305.csv
  Task/Side Story/ss0030740306.csv
  Task/Side Story/ss0030740307.csv
  Tutorial/tut_006282.csv
  Tutorial/tut_006304.csv
  Tutorial/tut_006320.csv
  Tutorial/tut_006366.csv
  Tutorial/tut_006386.csv
  Tutorial/tut_006455.csv
  UI/config.csv
  UI/ui_directbuy_text.csv
Labels: size/M

#2171 KO_Reboot: update files
  Quest/Leciel/quest_01330000.csv
  UI/ui_mainmode.csv
  WIP/20231017/trial_sheepdog.csv
  WIP/20231206/msn_023071.csv
Labels: size/S

#2172 KO_Reboot: Update files
  filelist.txt
  pruned-dupes.txt
  pruneempties.py
Labels: size/L

#2174 KO_Reboot: Fix typo
  E-Trial/trial_common.csv
  Story/Kvaris/msc_013280.csv
Labels: size/XS

#2173 KO:Update files
  Dialogue/ShopArea/np_npc_shopdisc.csv
  Dialogue/ShopArea/np_npc_shopitem.csv
  Files/np_npc_shopdisc.csv
  Files/np_npc_shopitem.csv
  Story/Episode 1/Chapter 10/co_0121001.csv
  Story/Episode 1/Chapter 10/co_0121002.csv
  Story/Episode 1/Chapter 10/st_012010.csv
  Story/Episode 1/Chapter 10/st_012020_om.csv
  Story/Episode 1/Chapter 10/st_012030_om.csv
  Story/Episode 1/Chapter 10/st_012045.csv
  Story/Episode 1/Chapter 10/st_012055.csv
  Story/Episode 1/Chapter 10/st_012090.csv
  Story/Episode 1/Chapter 10/st_012100.csv
  Story/Episode 1/Chapter 10/st_012110.csv
  Story/Episode 1/Chapter 10/st_012120.csv
  Story/Episode 1/Chapter 10/un_012090.csv
  Story/Episode 1/Chapter 10/un_012100.csv
  Story/Episode 1/Chapter 10/un_012110.csv
  Story/Episode 1/Chapter 10/un_012160.csv
  Story/Episode 1/Chapter 10/un_012170.csv
  Story/Episode 1/Chapter 10/un_012220.csv
  Story/Episode 1/Chapter 10/un_012230.csv
  Story/Episode 1/Chapter 10/un_012240.csv
  Story/Episode 1/Chapter 10/un_012380.csv
  Story/Episode 1/Chapter 10/un_012510.csv
  Story/Episode 1/Chapter 10/un_012590.csv
  Story/Episode 1/Chapter 10/un_012700.csv
  Story/Episode 1/Chapter 9/co_0121103.csv
  Story/Episode 1/Chapter 9/co_0121104.csv
  Story/Episode 1/Chapter 9/co_0121105.csv
  Story/Episode 1/Chapter 9/st_013420.csv
  Story/Episode 1/Chapter 9/st_013440_om.csv
  Story/Episode 1/Chapter 9/st_020250.csv
  Story/Episode 1/Chapter 9/st_020260.csv
  Story/Episode 1/Chapter 9/st_020270.csv
  Story/Episode 1/Chapter 9/st_020280.csv
  Story/Episode 1/Chapter 9/st_020290.csv
  Story/Episode 1/Chapter 9/st_020293.csv
  Story/Episode 1/Chapter 9/st_020296.csv
  UI/config.csv
Labels: size/XXL

#2175 KO: Episode 1-10
  Story/Episode 1/Chapter 10/un_012230.csv
  Story/Episode 1/Chapter 10/un_012240.csv
  Story/Episode 1/Chapter 10/un_012380.csv
  Story/Episode 1/Chapter 10/un_012510.csv
Labels: size/L

#2176 KO: Update file list
  Story/Episode 2/Chapter 4/un_020740.csv
  filelist.txt
Labels: size/XXL

#2177 KO: Update filelist.txt
  filelist.txt
Labels: size/M

#2179 KO: TEST
  win32_main_filelist.txt
Labels: size/XXL

#2180 KO: Update files
  Files/np_npc_25.csv
  Files/np_npc_344.csv
  Files/np_npc_49.csv
  Files/quest_00080250.csv
  Files/quest_00080270.csv
  Quests/Limited Quest/Anniversary/8th/1st/quest_00080440.csv
  Quests/Limited Quest/Anniversary/8th/1st/quest_00170800.csv
  Quests/Limited Quest/Episode 1-4/quest_00080240.csv
  Quests/Limited Quest/Episode 1-4/quest_00080260.csv
  Should move files/np_npc_25.csv
  Should move files/np_npc_344.csv
  Should move files/np_npc_49.csv
  Should move files/quest_00080250.csv
  Should move files/quest_00080270.csv
Labels: size/L

#2181 KO: story test
  filelist.txt
Labels: size/XXL

#2182 RU: Preparing to return RU patch
  Reboot/UI/actor_name.csv
  Reboot/UI/actor_name_npc.csv
  Reboot/UI/ui_mainmode.csv
Labels: size/XXL

#2184 KO: Update files
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/item_series_name.csv
Labels: size/L

#2183 KO_Reboot: Update files part 1
  .circleci/config.yml
  E-Trial/trial_common.csv
  E-Trial/trial_continuous_battle.csv
  E-Trial/trial_evolution_enemy_ahl.csv
  Files/trial_evolution_enemy_ahl.csv
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  Quest/Leciel/quest_01330000.csv
  Quest/ui_quest_counter_reb.csv
  Quest/ui_quest_reb.csv
  Story/Aelio/ssc_503020.csv
  Task/Main/Kvaris/ms0010100340.csv
  Task/Side Story/Kvaris/ssn_014811.csv
  UI/access_info.csv
  UI/common.csv
  UI/config.csv
  UI/myspace_text.csv
  UI/object_individual.csv
  UI/pse.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_na_mainmode.csv
  UI/ui_ranking_reb.csv
  UI/ui_selectmenu_text.csv
  UI/ui_shop.csv
  UI/ui_tips_reb.csv
  UI/ui_tutorial_reb.csv
  WIP/20231206/quest_01320060.csv
  WIP/230607/ss0030725801.csv
  WIP/230607/ssn_016014.csv
  WIP/230607/ssq_016013.csv
Labels: size/XL

#2185 PSO2 Day/Creative Space Tasks & Leciel Description Restore
  Files/ls0060115201.csv
  Files/ls0060115202.csv
  Files/ls0060115203.csv
  Files/ls0060115204.csv
  Files/ls0060115205.csv
  Files/ls0060115206.csv
  Files/ls0060115207.csv
  Files/ls0060115208.csv
  Files/ls0060115209.csv
  Files/ls0060152001.csv
  Files/ls0060152002.csv
  Files/ls0060152003.csv
  Files/ls0060152004.csv
  Files/ls0060152005.csv
  Files/ls0060152006.csv
  Files/ls0060152007.csv
  Files/ls0060152008.csv
  Files/ls0060152009.csv
  Files/ls0060152010.csv
  Files/ls0060152101.csv
  Files/ls0060152102.csv
  Files/ls0060152103.csv
  Files/ls0060152104.csv
  Files/ls0060152105.csv
  Files/ls0060152106.csv
  Files/ls0060152107.csv
  Files/ls0060152108.csv
  Files/ls0060152109.csv
  Files/ls0060152110.csv
  Translated/Quests/Leciel/quest_01330000.csv
  Translated/Tasks/Limited/Creative Space/ls0060152001.csv
  Translated/Tasks/Limited/Creative Space/ls0060152002.csv
  Translated/Tasks/Limited/Creative Space/ls0060152003.csv
  Translated/Tasks/Limited/Creative Space/ls0060152004.csv
  Translated/Tasks/Limited/Creative Space/ls0060152005.csv
  Translated/Tasks/Limited/Creative Space/ls0060152006.csv
  Translated/Tasks/Limited/Creative Space/ls0060152007.csv
  Translated/Tasks/Limited/Creative Space/ls0060152008.csv
  Translated/Tasks/Limited/Creative Space/ls0060152009.csv
  Translated/Tasks/Limited/Creative Space/ls0060152010.csv
  Translated/Tasks/Limited/Creative Space/ls0060152101.csv
  Translated/Tasks/Limited/Creative Space/ls0060152102.csv
  Translated/Tasks/Limited/Creative Space/ls0060152103.csv
  Translated/Tasks/Limited/Creative Space/ls0060152104.csv
  Translated/Tasks/Limited/Creative Space/ls0060152105.csv
  Translated/Tasks/Limited/Creative Space/ls0060152106.csv
  Translated/Tasks/Limited/Creative Space/ls0060152107.csv
  Translated/Tasks/Limited/Creative Space/ls0060152108.csv
  Translated/Tasks/Limited/Creative Space/ls0060152109.csv
  Translated/Tasks/Limited/Creative Space/ls0060152110.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115201.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115202.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115203.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115204.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115205.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115206.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115207.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115208.csv
  Translated/Tasks/Limited/PSO2 Day/ls0060115209.csv
Labels: size/L
