Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-02, with the labels that each got.

#2187 RU: Just CircleCI test
  .github/workflows/build.yml
  Reboot/UI/access_info.csv
  Reboot/UI/actor_name.csv
  Reboot/UI/actor_name_npc.csv
  Reboot/UI/common.csv
  Reboot/UI/config.csv
  Reboot/UI/date.csv
  Reboot/UI/ui_mainmode.csv
Labels: size/XXL

#2189 KO: Update filelist.txt
  filelist.txt
Labels: size/XXL

#2190 RU: Preparing to return RU patch #2
  Reboot/UI/actor_name.csv
  Reboot/UI/common.csv
  Reboot/UI/object_common.csv
  Reboot/UI/object_individual.csv
  Reboot/UI/open_field.csv
  Reboot/UI/pse.csv
  Reboot/UI/quest_common_reboot.csv
  Reboot/UI/region_mag_common.csv
  Reboot/UI/ui_battle_trigger.csv
  Reboot/UI/ui_equip.csv
  Reboot/UI/ui_mainmode.csv
  Reboot/UI/ui_moralskeeper.csv
  Reboot/UI/ui_quest_counter_reb.csv
  Reboot/UI/ui_quest_reb.csv
  Reboot/UI/ui_scratch_reb.csv
  Reboot/UI/ui_selectmenu_text.csv
  Reboot/UI/ui_shop_reb.csv
  Reboot/UI/ui_symbol.csv
  Reboot/UI/ui_tips_reb.csv
Labels: size/XXL

#2192 RU: Preparing to return RU patch #3.1
  Files/ui_box_gacha.csv
  Files/ui_playnavi.csv
  Files/ui_ranking_reb.csv
  Reboot/UI/myspace_text.csv
  Reboot/UI/ui_box_gacha.csv
  Reboot/UI/ui_na_mainmode.csv
  Reboot/UI/ui_playnavi.csv
  Reboot/UI/ui_quest_reb.csv
  Reboot/UI/ui_ranking_reb.csv
  Reboot/UI/ui_rebops.csv
  Reboot/UI/ui_scratch_reb.csv
  Reboot/UI/ui_shop.csv
  Reboot/UI/ui_tutorial_reb.csv
Labels: size/XL

#2193 RU: Preparing to return RU patch #3.2
  Files/ls0061170102.csv
  Files/ls0061170103.csv
  Files/ms0010100150.csv
  Files/ms0010100160.csv
  Files/ms0010100380.csv
  Files/ms0010100450.csv
  Files/ms0010100570.csv
  Files/msc_014070.csv
  Files/msc_014090.csv
  Files/msc_014130.csv
  Files/msc_014190.csv
  Files/msc_014280.csv
  Files/msc_014290.csv
  Files/msc_014355.csv
  Files/msc_020130.csv
  Files/msc_020170.csv
  Files/msc_020220.csv
  Files/msc_020310.csv
  Files/msn_011063_010.csv
  Files/msn_020211.csv
  Files/qst_1180150000.csv
  Files/quest_01180140.csv
  Files/quest_01330000.csv
  Files/ssn_019160_002.csv
  Files/ssq_019160_002.csv
  Files/ssq_019160_005.csv
  Files/tut_006335.csv
  Files/tut_006502.csv
  Files/tut_006536.csv
  Files/tut_006544.csv
  Files/tut_006545.csv
  Files/tut_006548.csv
  Files/tut_006549.csv
  Files/tut_006558.csv
  Files/tut_006561.csv
  Files/tut_006565.csv
  Files/tut_006607.csv
Labels: size/L

#2194 RU: Preparing to return RU patch #3.3
  Reboot/Quests/Emergency Quests/Kvaris/quest_01120090.csv
  Reboot/Story/Ch1/04-05 DOLLS on Mt. Magnus/msn_011063_006.csv
  Reboot/UI/myspace_text.csv
  Reboot/UI/object_common.csv
  Reboot/UI/ui_mainmode.csv
  Reboot/UI/ui_quest_reb.csv
  Reboot/UI/ui_tips_reb.csv
Labels: size/L

#2195 RU: Preparing to return RU patch #3.35
  Reboot/UI/myspace_text.csv
  Reboot/UI/quest_common_reboot.csv
  Reboot/UI/ui_mainmode.csv
Labels: size/M

#2196 Preparing to return RU patch #3.36
  Reboot/UI/myspace_text.csv
Labels: size/L

#2197 RU: Preparing to return RU patch #3.4
  Reboot/UI/myspace_text.csv
  Reboot/UI/ui_item.csv
Labels: size/XXL

#2198 RU: Preparing to return RU patch #3.41
  Reboot/UI/ui_item.csv
Labels: size/XS

#2199 RU: Preparing to return RU patch #3.42
  Reboot/UI/myspace_text.csv
Labels: size/XS

#2200 Update ui_shop_reb.csv
  Translated/UI/ui_shop_reb.csv
Labels: size/XS

#2201 Update ms0010100660.csv
  Translated/Story/Unorganized/msc_023090.csv
  Translated/Story/Unorganized/msc_023180.csv
  Translated/Story/Unorganized/msc_023190.csv
  Translated/Story/Unorganized/msc_023200.csv
  Translated/Tasks/Main Story/Chapter 6/ms0010100660.csv
  Translated/Tasks/Main Story/Chapter 6/ms0010100661.csv
Labels: size/S

#2202 RU: Preparing to return RU patch #3.5
  translated files/UI/config.csv
  translated files/UI/date.csv
  translated files/UI/item_element_expl_reb.csv
  translated files/UI/item_element_name_reb.csv
  translated files/UI/item_series_name.csv
  translated files/UI/ui_charamake_text.csv
  translated files/UI/ui_charamake_text_reb.csv
  translated files/UI/ui_charamake_text_sp.csv
  translated files/UI/ui_item.csv
  translated files/UI/ui_title_text.csv
Labels: size/XXL

#2203 RU: Preparing to return RU patch #3.51
  translated files/UI/item_element_expl_reb.csv
  translated files/UI/ui_charamake_text_reb.csv
Labels: size/XS

#2204 RU: Update filelist.txt
  filelist.txt
Labels: size/XXL

#2206 RU: Preparing to return RU patch #3.91
  Files/cp0410010401.csv
  Files/cp0410010402.csv
  Files/cp0410010403.csv
  Files/cp0410010404.csv
  Files/cp0410010405.csv
  Files/cp0410010406.csv
  Files/cp0410010407.csv
  Files/cp0410010408.csv
  Files/cp0410010409.csv
  Files/cp0410010410.csv
  Files/cp0410010411.csv
  Files/cp0410010412.csv
  Files/cp0410010413.csv
  Files/cp0410010414.csv
  Files/cp0410010415.csv
  Files/cp0410010416.csv
  Files/cp0410010417.csv
  Files/cp0410010418.csv
  Files/cp0410010419.csv
  Files/cp0410010420.csv
  Files/cp0410010421.csv
  Files/cp0410010422.csv
  Files/cp0410010423.csv
  Files/cp0410010424.csv
  Files/cp0410010425.csv
  Files/cp0410010426.csv
  Files/cp0410010427.csv
  Files/cp0410010428.csv
  Files/cp0410010429.csv
  Files/cp0410010430.csv
Labels: size/L

#2208 RU: Preparing to return RU patch #3.92
  Reboot/Tasks/Team/gs0040101001.csv
  Reboot/Tasks/Team/gs0040101002.csv
Labels: size/XS

#2209 RU: Preparing to return RU patch #3.92
  Reboot/Tasks/Team/gs0040101001.csv
  Reboot/Tasks/Team/gs0040101002.csv
Labels: size/XS

#2211 RU: some fixes
  Reboot/UI/myspace_text.csv
  Reboot/UI/ui_achievements.csv
  Reboot/UI/ui_item.csv
  Reboot/UI/ui_rebops.csv
  Reboot/UI/ui_shop.csv
  Reboot/UI/ui_tips_reb.csv
Labels: size/M

#2212 KO_Reboot: Update files
  .circleci/config.yml
  Files/quest_01340140.csv
  Quest/Leciel/quest_01330000.csv
  Quest/Limited Quest/quest_01340140.csv
  WIP/20240131/msc_023190.csv
  WIP/230607/ssq_016013.csv
Labels: size/M

#2213 KO: Update ui_charamake_parts.csv
  UI/ui_charamake_parts.csv
  filelist.txt
  win32_main_filelist.txt
  win32_story_filelist.txt
Labels: size/XXL

#2214 lends > lend
  Translated/Story/48 Nadereh's Subjugation Request/msn_023101.csv
Labels: size/XS

#2215 KO_Reboot: Update files
  .circleci/config.yml
  Quest/Leciel/quest_01330000.csv
  Story/Side/ssc_506010.csv
  UI/common.csv
  UI/config.csv
  UI/ui_item.csv
  UI/ui_tutorial_reb.csv
  WIP/20240131/ms0010100663.csv
  WIP/20240131/msc_023110.csv
  WIP/20240131/msc_023140.csv
  WIP/20240131/tut_006663.csv
  WIP/gpro/ms0010100580.csv
Labels: size/M
