Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-06, with the labels that each got.

#2233 KO_Reboot: fix typo
  E-Trial/trial_common.csv
  Quest/quest_common_reboot.csv
  UI/common.csv
  UI/myspace_text.csv
  UI/object_individual.csv
  WIP/20231017/tut_006644.csv
  WIP/20240410/gs0040104020.csv
  WIP/20240606/msc_027020.csv
  WIP/20240606/msc_027050.csv
  WIP/20240606/msc_027070.csv
  WIP/20240606/msc_027110.csv
  WIP/20240606/msc_027120.csv
  WIP/20240606/msc_027140.csv
  WIP/20240606/msc_027160.csv
  WIP/20240606/msc_027170.csv
  WIP/20240606/msc_027180.csv
  WIP/20240606/msq_027061.csv
  WIP/20240606/qst_1202300010.csv
  WIP/230607/tut_006612.csv
  WIP/230607/tut_006621.csv
  WIP/test/quest_01180380.csv
Labels: size/L

#2235 KO_Reboot: fix typo
  E-Trial/trial_city_field_race.csv
  Files/trial_city_field_race.csv
  Task/Side Story/ssc_508020.csv
  Task/Side Story/ssn_015611.csv
  UI/myspace_text.csv
  UI/ui_item.csv
  UI/ui_item_reb.csv
  UI/ui_mainmode.csv
  WIP/20240606/msc_027040.csv
  WIP/20240606/msc_027110.csv
  WIP/20240606/msc_027120.csv
  WIP/20240606/msc_027140.csv
  WIP/20240606/msc_027170.csv
  WIP/20240606/msq_027063.csv
  WIP/20240606/qst_1202330050.csv
  WIP/20240606/quest_01202302.csv
  WIP/20240606/quest_01202331.csv
Labels: size/M

#2237 Settings and Client orders JP>EN translation
  UI/quest_counter.csv
Labels: size/XS
