Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-10, with the labels that each got.

#2258 Missed daily file
  Files/ed0614050118.csv
  Translated/Tasks/Daily/2024-10-09 Halloween 24/ed0614050118.csv
  pruned-dupes.txt
Labels: size/XS

#2260 KO_Reboot: Update files
  UI/common.csv
Labels: size/S

#2259 KO: Update files
  Files/quest_00010020.csv
  Files/quest_00010040.csv
  Files/quest_00050520.csv
  Files/ra_010400.csv
  Quests/quest_00010020.csv
  Quests/quest_00010040.csv
  Quests/quest_00050520.csv
  Story/Episode 1/Chapter 10/st_012100.csv
  Story/Episode 1/Chapter 10/st_012120.csv
  Story/Episode 1/Chapter 10/un_012090.csv
  Story/Episode 1/Chapter 10/un_012380.csv
  Story/Episode 1/Chapter 3/ra_010330.csv
  Story/Episode 1/Chapter 8/st_010750.csv
  Story/Episode 1/Chapter 8/un_012470.csv
  Story/Episode 2/Chapter 4/st_020450.csv
  Story/Episode 2/Chapter 4/un_020720.csv
  Story/Episode 2/Chapter 4/un_020730.csv
  UI/item_element_expl_reb.csv
  UI/ui_item.csv
  UI/ui_outline.csv
  UI/ui_shop.csv
  WhatIsIt/quest_00010140.csv
  WhatIsIt/ra_010400.csv
  WhatIsIt/skit_common.csv
  WhatIsIt/st_013120.csv
  WhatIsIt/st_013220.csv
  WhatIsIt/st_013320.csv
  WhatIsIt/st_013520.csv
  WhatIsIt/st_013620.csv
Labels: size/L

#2261 Begin from Chapter 7 text
  UI/ui_charamake_text_reb.csv
Labels: size/XS

#2262 Trim line break
  Translated/UI/ui_item.csv
Labels: size/XS

#2263 KO: item_element_name_reb.csv 업데이트
  UI/item_element_name_reb.csv
Labels: size/XS
