Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-04, with the labels that each got.

#2217 Removed double space
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#2218 KO: Update files
  NPC/Azanami/np_010870.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_parts.csv
  UI/ui_gacha.csv
  UI/ui_mainmode.csv
Labels: size/XL

#2220 KO_Reboot: Update files
  E-Trial/trial_lightning.csv
  Misc/object_common.csv
  Misc/open_field.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_reb.csv
  UI/ui_battle_trigger.csv
  UI/ui_directbuy_text.csv
  UI/ui_help.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_ranking_reb.csv
  UI/ui_scratch_reb.csv
  UI/ui_selectmenu_text.csv
  UI/ui_shop_reb.csv
  WIP/20240410/cl0421240102.csv
  WIP/20240410/cl0421240103.csv
  WIP/20240410/cl0421240104.csv
  WIP/20240410/ed0610030102.csv
  WIP/20240410/ed0610030103.csv
  WIP/20240410/ed0610030104.csv
  WIP/20240410/ed0614010108.csv
  WIP/20240410/ed0614020107.csv
  WIP/20240410/ed0614020108.csv
  WIP/20240410/ed0614020109.csv
  WIP/20240410/ed0614050111.csv
  WIP/20240410/ew0621240101.csv
Labels: size/L
