Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-07, with the labels that each got.

#2238 KO_Reboot: Fix typo
  E-Trial/trial_rappy_room.csv
  NPC Dialogue/np_npc_7649_001.csv
  Quest/Leciel/quest_01330000.csv
  Quest/ui_quest_counter_reb.csv
  UI/common.csv
  UI/ui_mainmode.csv
  UI/ui_shop.csv
  WIP/20240606/np_npc_7015_001.csv
  WIP/halgeo jonna manne/qst_1180320020.csv
Labels: size/M

#2239 KO_Reboot: fix typo
  UI/ui_tutorial_reb.csv
  WIP/20240606/qst_1340270030.csv
Labels: size/XS

#2240 KO_Reboot: DUEL
  Files/np_npc_7010_001.csv
  Files/quest_01180420.csv
  Files/ss0030745101.csv
  Files/ss0030745102.csv
  Files/ui_lineduel_text.csv
  NPC Dialogue/np_npc_7010_001.csv
  UI/ui_tutorial_reb.csv
  WIP/20240606/lineduel_text.csv
  WIP/20240606/ls0064190101.csv
  WIP/20240606/ls0064190102.csv
  WIP/20240606/ssn_016100_000.csv
  WIP/20240606/ssn_016100_001.csv
  WIP/20240606/ssn_016100_003.csv
  WIP/20240606/ssq_016100_002.csv
  WIP/20240606/ssq_016100_004.csv
  WIP/20240606/tut_006667.csv
  WIP/20240606/tut_006668.csv
  WIP/20240606/tut_006669.csv
  WIP/20240606/tut_006670.csv
  WIP/20240606/tut_006671.csv
  WIP/quest_01180420.csv
  WIP/ss0030745101.csv
  WIP/ss0030745102.csv
  WIP/ui_lineduel_text.csv
Labels: size/XL

#2241 KO_REeboot: fix typo
  WIP/20240606/lineduel_text.csv
  WIP/20240606/tut_006668.csv
  WIP/20240606/tut_006669.csv
  WIP/20240606/tut_006670.csv
Labels: size/L

#2242 KO_Reboot: 이걸안했네
  WIP/20240606/lineduel_text.csv
Labels: size/S

#2243 KO_Reboot: fix typo
  WIP/20240606/ls0061301141.csv
  WIP/ui_lineduel_text.csv
Labels: size/XS

#2244 KO_Reboot: Fix typo
  Quest/ui_quest_reb.csv
  WIP/230607/tut_006621.csv
Labels: size/XS

#2245 KO: Update quest files
  Files/quest_00080420.csv
  Files/quest_00080430.csv
  Quests/Limited Quest/Episode 1-4/quest_00080250.csv
  Quests/Limited Quest/Episode 1-4/quest_00080270.csv
  Quests/Limited Quest/Level-up Quests/quest_00080230.csv
  Quests/Limited Quest/Level-up Quests/quest_00080420.csv
  Quests/Limited Quest/Level-up Quests/quest_00080430.csv
Labels: size/M

#2247 KO: Update files
  UI/common.csv
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
  UI/ui_charamake_parts.csv
  UI/ui_mainmode.csv
  UI/ui_title_text.csv
Labels: size/L

#2246 KO_Reboot: Update files
  E-Trial/trial_enemy_ahl.csv
  Files/ui_arsenal_module.csv
  Linestrike/lineduel_common_text.csv
  Linestrike/lineduel_text.csv
  Linestrike/ui_lineduel_text.csv
  Misc/actor_name.csv
  Misc/actor_name_npc.csv
  NPC Dialogue/np_npc_7649_001.csv
  Quest/Leciel/quest_01330000.csv
  Quest/Ordinal Tower/quest_01190000.csv
  Quest/Trainia/quest_01140030.csv
  Quest/Undefined/quest_01140020.csv
  Quest/quest_common_reboot.csv
  Tutorial/tut_006316.csv
  UI/access_info.csv
  UI/common.csv
  UI/myspace_text.csv
  UI/object_individual.csv
  UI/ui_arsenal_module.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  WIP/20240410/quest_01180390.csv
  WIP/20240606/np_npc_7015_001.csv
Labels: size/XXL

#2248 KO_Reboot: MARS
  Tutorial/tut_006418.csv
  UI/ui_arsenal_module.csv
  UI/ui_mainmode.csv
  WIP/20231206/ui_box_gacha.csv
  WIP/fix error temp/qt1200000002.csv
Labels: size/L

#2250 Correct damage values + add in details for other new descriptions
  UI/item_element_expl_reb.csv
Labels: size/S
