Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2024-12, with the labels that each got.

#2265 KO_Reboot: so many things to merge it
  Misc/actor_name.csv
  NPC Dialogue/np_npc_7649_001.csv
  WIP/20240606/np_npc_7015_001.csv
Labels: size/L

#2266 KO_Reboot: missed files
  E-Trial/trial_common.csv
  E-Trial/trial_mutual_resurrect.csv
  Files/quest_01340410.csv
  Misc/actor_name.csv
  Quest/Limited Quest/quest_01340410.csv
  Quest/quest_common_reboot.csv
  Quest/ui_quest_counter_reb.csv
  UI/common.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  UI/ui_ranking_reb.csv
  UI/ui_shop_reb.csv
Labels: size/XXL

#2267 Incapacitation
  Translated/UI/quest_common_reboot.csv
Labels: size/S

#2268 no u
  Translated/Quests/Dimension Fault/DF Solus/qst_1120170040.csv
Labels: size/XS

#2269 no u 2
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#2271 KO_Reboot: Fix typo
  Quest but need check/quest_01180270.csv
  Quest/Limited Quest/quest_01340410.csv
  Quest/Seasonal/2023/quest_01180190.csv
  Quest/Seasonal/2023/quest_01180200.csv
  WIP/20231206/quest_01340120.csv
  WIP/20240410/quest_01340180.csv
  WIP/20241204/ed0611321102.csv
  WIP/20241204/ed0611331101.csv
  WIP/20241204/ed0614040901.csv
  WIP/20241204/ls0060010129.csv
  WIP/20241204/quest_01340420.csv
  WIP/20241204/quest_01340430.csv
  should find category/quest_01340370.csv
  should find category/quest_01340380.csv
Labels: size/M

#2272 KO_Reboot: Update quest_01120260.csv
  should find category/quest_01120260.csv
Labels: size/XS
