Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2025-06, with the labels that each got.

#2303 New Fixa values + fixes
  Files/ls0064340101.csv
  Files/ls0064380103.csv
  Files/quest_01120290.csv
  Translated/Dialog/Bosey/np_npc_7649_001.csv
  Translated/Dialog/Meri/np_npc_7015_001.csv
  Translated/UI/ui_item.csv
Labels: size/M

#2304 Fix outstanding text
  UI/item_element_expl_reb.csv
  UI/item_element_name_reb.csv
Labels: size/M

#2286 Misc. Changes
  Translated/Story/55 Dark Falz Vael/msc_031070.csv
  Translated/UI/ui_mainmode.csv
Labels: size/XS

#2307 Quest names
  Translated/Quests/Alter Realm/quest_01011233.csv
  Translated/Quests/Dimension Fault/DF Vael/quest_01180430.csv
  Translated/Quests/Emergency Quests/Shadow of the Fallen Star/quest_01120290.csv
  Translated/Quests/Limited Quests/Sinister Sylvan Citadel/quest_01340630.csv
  Translated/Quests/Limited Quests/Sinister Sylvan Citadel/quest_01340640.csv
  Translated/Quests/Limited Quests/Sonic 2025/quest_01340680.csv
  Translated/Quests/Limited Quests/Sonic 2025/quest_01340690.csv
  Translated/Quests/Limited Quests/Winged Border-Beyonder/quest_01340650.csv
  Translated/Quests/Limited Quests/Winged Border-Beyonder/quest_01340660.csv
  Translated/Quests/Limited Quests/Winged Border-Beyonder/quest_01340670.csv
Labels: size/S

#2310 Reduction > Duration
  Translated/UI/quest_common_reboot.csv
Labels: size/XS
