Repository Arks-Layer/PSO2ENPatchCSV, pull requests merged in 2025-02, with the labels that each got.

#2275 Restore Bosey/Meri's greeting lines
  Translated/Dialog/Bosey/np_npc_7649_001.csv
  Translated/Dialog/Meri/np_npc_7015_001.csv
Labels: size/XS

#2277 KO_Reboot: Update files
  Files/ls0061340101.csv
  Files/msc_031040.csv
  Files/msc_031041.csv
  UI/ui_item.csv
  UI/ui_mainmode.csv
  WIP/20250205/msc_031040.csv
  WIP/20250205/msc_031041.csv
  WIP/20250205/qst_1120240050.csv
  WIP/a/quest_01202401.csv
  WIP/a/quest_01202406.csv
  WIP/a/quest_01340470.csv
  WIP/a/quest_01340530.csv
  WIP/a/quest_01340540.csv
  WIP/a/quest_01340550.csv
Labels: size/M

#2283 Restore deleted changes
  Translated/Dialog/Bosey/np_npc_7649_001.csv
  Translated/Dialog/Meri/np_npc_7015_001.csv
Labels: size/XS

#2280 Update qst_1120240240.csv
  Translated/Quests/Emergency Quests/Dark Falz Vael/qst_1120240240.csv
  Translated/Quests/Leciel/quest_01330000.csv
  Translated/Story/55 Dark Falz Vael/msc_031070.csv
  Translated/Story/55 Dark Falz Vael/msn_031010.csv
  Translated/UI/common.csv
  Translated/UI/quest_common_reboot.csv
Labels: size/M

#2282 Revert file changes + escape double quotes
  UI/ui_charamake_parts.csv
Labels: size/XXL
